getsentry/sentry-cocoa

SentrySwiftTests/SentrySwiftTests.swift, Sources/EventProperties.swift
The current behaviour when merging properties from `SentryClient` into an event is to override any values present in both with the clients value. This means that there is no way to sent a special value for a specific event when there is a value set on the client. I think it makes more sense to treat the clients values as "defaults" that are overridable by events.
So this pr changes the behaviour so that in conflicts, the events value wins.
=> change merging behaviour in EventProperties

Examples/ObjCExample/ObjCExample/Base.lproj/LaunchScreen.storyboard, Examples/ObjCExample/ObjCExample/Base.lproj/Main.storyboard, Examples/ObjCExample/ObjCExample/ViewController.m, Examples/ObjCExample/Podfile.lock, Examples/SwiftExample/Podfile.lock, Examples/SwiftTVOSExample/Podfile.lock, Examples/SwiftTVOSExample/SwiftTVOSExample.xcodeproj/project.pbxproj, SentrySwift.xcodeproj/project.pbxproj, SentrySwiftTests/SentrySwiftBreadcrumbTests.swift, SentrySwiftTests/SentrySwiftObjCTests.m, SentrySwiftTests/SentrySwiftTests.swift, Sources/AppleCrashReport.swift, Sources/Breadcrumb.swift, Sources/BreadcrumbStore.swift, Sources/CrashHandler.swift, Sources/DSN.swift, Sources/Dictionary+Extras.swift, Sources/Event.swift, Sources/EventOffline.swift, Sources/EventProperties.swift, Sources/EventSerializable.swift, Sources/KSCrashHandler.swift, Sources/NSDate+Extras.swift, Sources/Request.swift, Sources/Sentry.swift, Sources/User.swift
Hey guys,
As a big user of Sentry, I was patiently waiting for the new SDK to be out and now it is! 🎉 However, in my project I had some issues. Mostly around namespacing, I went in to fix the issues and in there thought some things could be improved:
- There's now better namespacing! Almost all classes/structs will fall under the `Sentry` namespace.  It works really well with Swift though somethings couldn't be moved because of the required interoperability with objc.
- I've now explicitly set access-control. There was many things that were public that probably shouldn't have been. There was also a divergence in code style (probably because of different people working on it).
- 47c463ba6b10df46da752eeac7ec41a7bd79e483 broke compatibility with `Breadcrumbs` in objc; however, it wasn't …
=> Refactor Project, Add Tests, Namespacing!

SentrySwiftTests/SentrySwiftTests.swift
I broke merging an empty event in #11. This adds a (currently failing) test for that and is supposed to act as a reminder for me to fix this.
@joshdholtz do you still agree with making `tags` and `extra` non-optional and default to `[:]`?
=> [WIP] merging empty events

SentrySwiftTests/SentrySwiftTests.swift, Sources/Event.swift, Sources/EventOffline.swift, Sources/EventProperties.swift, Sources/KSCrashHandler.swift, Sources/Request.swift, Sources/Sentry.swift
Fixes #33 
This fixes the immediate problem of the app crashing.. however, this should not be the long term fix. We don't convey in any way to the user that the dictionaries they use for extras/tags are supposed to be JSON mappable... it's also bad if users are setting some weird things in their tags and now their events are not being reported because the serialization is failing.
so we should either convey this through a custom type/documentation or we should find a way to sanitize the values. I prefer latter because I find it weird for the user to have to sanitize their own dictionaries. we could also possibly just drop the failing part but still send the event (probably best option as the user would be missing info, but not the whole event)
however, I'd say let's merge this to fix the …
=> Fix crash when setting non-JSON conforming attributes

SentrySwift.xcodeproj/project.pbxproj, SentrySwiftTests/SentryClientTests.swift, Sources/EventProperties.swift, Sources/KSCrashHandler.swift, Sources/Sentry.swift
The `Event` class had support for a ReleaseVersion string, but there was no way to set it outside of calling `SentryClient.captureEvent(_:)`.
I have added it as an ivar to `SentryClient`, so that it will be sent automatically in case of crashes.
=> Pass release on to the sentry-server

Sources/Sentry.swift
`releaseVersion` was already supported just not defaulting to version in main bundle 😊  - fixes #40 
cc: @dcramer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-swift/41)
=> Defaulting release version

SentrySwift.xcodeproj/project.pbxproj, SentrySwiftTests/SentrySwiftErrorTests.swift, SentrySwiftTests/SentrySwiftSourceLocationTests.swift, Sources/Event.swift, Sources/Exception.swift, Sources/Sentry+Error.swift, Sources/Sentry+NSError.swift, Sources/Sentry.swift
This PR introduces a method to capture NSErrors. It's a WIP and I'd appreciate any feedback. It also doesn't include any tests yet.
`raven-swift` and `raven-objc` have similar methods. This implementation, unlike theirs, does not send the errors description as message, as I find that to have bad readability and it may exceed the limit of 1000 characters for the message.
Instead, it sends messages similar to this:
NSURLErrorDomain.-1004 in SomeFile.swift:99 someFunc(_:params:)
I'd like to send a more readable error name, but the only thing available at runtime is `localizedDescription`, which can be in any number of languages.
A possibility to do this would be to ship a dictionary that maps error domains and codes to their respective names, but generating such a dictionary automatically is …
=> add method to capture NSError

SentrySwiftTests/SentrySwiftTests.swift, Sources/Event.swift, Sources/Sentry.swift
- Release was not getting sent up on crashes
- Contexts was getting sent up on wrong key
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-swift/52)
=> Fixes for release and contexts

Cartfile, Cartfile.resolved, Examples/MacExample/Podfile.lock, Examples/ObjCExample/Podfile.lock, Examples/SwiftExample/Podfile.lock, Examples/SwiftTVOSExample/Podfile.lock, SentrySwift.podspec
- Bump to version `0.4.0`
- Now using `KSCrash` version `1.8.3`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-swift/62)
=> Version bump and kscrash dependency update

SentrySwift.xcodeproj/project.pbxproj, SentrySwiftTests/SentrySwiftBreadcrumbTests.swift, SentrySwiftTests/SentrySwiftTests.swift, Sources/Breadcrumb.swift, Sources/CrashReportConverter.swift, Sources/Dictionary+Extras.swift, Sources/Event.swift, Sources/Functions.swift, Sources/KSCrashHandler.swift, Sources/NSNumber+Extras.swift, Sources/Sentry+Error.swift, Sources/Sentry.swift, Sources/User.swift
This will stop crashes that occur when you pass in keys that cannot be serializable into JSON. The current approach that I implemented a while back discarded the whole dictionary if it wasn't serializable. This approach will always serialize one way or another but will mostly try to do it correctly and gives us control on serializing particular types like `NSError`.
=> Sanitize Dictionary Entries

.travis/run.sh, Sources/Sentry/SentryKSCrashReportConverter.m, Tests/Resources/fatalError.json, Tests/SentryTests/SentryKSCrashReportConverterTests.m
=> Enhance value of exception with crash reason

Sources/Sentry/SentryClient.m
=> Fix initialization of last context

.travis.yml, .travis/run.sh, KSCrash/Sentry-KSCrash.xcodeproj/project.pbxproj, KSCrash/Sentry-KSCrash.xcodeproj/xcshareddata/xcschemes/SentryTests.xcscheme, KSCrash/SentryTests/Info.plist, KSCrash/SentryTests/SentryTests.m, Sources/Sentry/SentryKSCrashReportSink.m, fastlane/Fastfile
Also adds tests for KSCrash specific tests
Fixes #206
=> fix: Use thread from exception instead of threads for snapshot

Sources/Sentry/SentryFileManager.m, Tests/SentryTests/SentryBreadcrumbTests.m
Send breadcrumbs in the order in which they got created.
See files:
```
"1508754960.460319-0-4DAA9212-4FF6-4064-8A7D-7FF7ABE37807.json",
"1508754960.461277-1-4A0ACA73-207F-4D16-BB79-E9E8C89BAC0D.json",
"1508754960.462301-2-12BC2A42-D67E-4C2D-ADE5-5439AEFB039C.json",
"1508754960.463050-3-B17304D1-45D8-4C2F-B47D-DD6817450874.json",
"1508754969.272279-0-EEF0BCEE-1E1D-4435-A54A-50700F10B181.json",
"1508754969.278541-1-69F4BAB7-8BB2-4664-B617-3D6A8E47FF5A.json",
"1508754969.281323-2-46566918-0A3A-44A6-AE86-BC8F39AA1FD3.json",
"1508754969.282348-3-797B166F-C983-4794-8095-DAC01D9D37C5.json"
```
So that's how filename get generated:
https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryFileManager.m#L70-L75
`Timestamp-counter-UUID` so it should be sortable.
=> fix: Return breadcrumbs in order in which they where created

.travis.yml, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryDsn.m, Sources/Sentry/SentryFileManager.m, Sources/Sentry/include/SentryDsn.h, Sources/Sentry/include/SentryFileManager.h, Tests/SentryTests/SentryBreadcrumbTests.m, Tests/SentryTests/SentryFileManagerTests.m, Tests/SentryTests/SentryInterfacesTests.m, Tests/SentryTests/SentryJavaScriptBridgeHelperTests.m, Tests/SentryTests/SentryRequestTests.m, Tests/SentryTests/SentrySwiftTests.swift, Tests/SentryTests/SentryTests.m
Fixes #216 
This will create a subfolder for each instance of SentryClient so multiple clients do not interfere.
=> fix: SentryFilemanager will create folder depending on dsn

Sources/Sentry/SentryBreadcrumbStore.m, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryFileManager.m, Sources/Sentry/SentryQueueableRequestManager.m, Sources/Sentry/SentryRequestOperation.m, Sources/Sentry/include/SentryClient.h, Sources/Sentry/include/SentryDefines.h, Sources/Sentry/include/SentryFileManager.h, Sources/Sentry/include/SentryQueueableRequestManager.h, Sources/Sentry/include/SentryRequestOperation.h, Tests/SentryTests/SentryBreadcrumbTests.m, Tests/SentryTests/SentryFileManagerTests.m, Tests/SentryTests/SentryInterfacesTests.m, Tests/SentryTests/SentryRequestTests.m, fastlane/Fastfile
This PR should greatly improve the handling we do when hitting rate limits and general "extreme" situations when dealing with many events.
- Introduced a max local queue for events of 10
- Introduced a max local queue for breadcrumbs of 200
- By default events will be stored locally and send again later if:
- There is no internet connection
- Or they hit a 429 in which case it will be only retired once, ever.
- Provide a callback block for people to implement their own logic of local caching
(The hard cap of local 10 events applies to all of it)
Example of the the block: see default implementation in the PRs code
```objc
self.client.shouldQueueEvent = ^BOOL(SentryEvent * _Nonnull event, NSHTTPURLResponse * _Nullable response, NSError * _Nullable error) {
return NO; // Always discard the …
```
=> feat: Improve rate limiting and local file cache

KSCrash/Sentry-KSCrash.xcodeproj/project.pbxproj
The SKIP_INSTALL setting for frameworks is normally set to YES.
This PR removes the KSCrash project level NO setting, allowing the Sentry.xcconfig setting of YES to be used.
With the setting set to NO the resulting framework is copied to any generated archive, creating a Generic Archive which cannot be uploaded to the app store.
This breaks automated builds managed with Carthage/Fastlane without hacks to toggle the setting to NO.
See: https://developer.apple.com/library/archive/technotes/tn2215/_index.html#//apple_ref/doc/uid/DTS40011221-CH1-PROJ
(Under the image ... "You must set "Skip Install" to YES to prevent your
static libraries or framework from being added to your archive.")
Also in the bordered note: "Note: If your archive contains unexpected items such as header files, static …
=> Remove SKIP_INSTALL settings from Sentry-KSCrash project settings.

Sources/Sentry/SentryJavaScriptBridgeHelper.m
We needed to set a custom fingerprint on captureException in react-native-sentry. The fingerprint was not part of the event sent to Sentry. We added the ability to set a custom fingerprint for iOS (and Android within the react-native-sentry package). The feature was requested over a year ago, so we thought it would be nice to share our implementation.
If there are questions or problems please contact me, so I can resolve them.
=> added fingerprint option on createSentryEventFromJavaScriptEvent

Sources/Sentry/SentryBreadcrumbStore.m
This fixes https://github.com/getsentry/react-native-sentry/issues/515.
=> Fix NSInvalidArgumentException in SentryBreadcrumbStore

Sources/SentryCrash/Recording/SentryCrash.m
An array of length 0 is not ideal and Xcode is stopping there if sanitizer flags are on while running in debug mode.
=> Fix empty array creation

Sources/Sentry/SentryJavaScriptBridgeHelper.m
Hey all!
I believe I've discovered the fix to an issue that turned up over in [getsentry/react-native-sentry](https://github.com/getsentry/react-native-sentry/) regarding fingerprints not being set (issue https://github.com/getsentry/react-native-sentry/issues/407). Looks like it was a simple copy-paste mistake from PR #269 — all `fingerprint` event data was being assigned to the `logger` field. I've tested this fork myself against @edenhealth's on-prem Sentry instance, and verified that fingerprints are now passed through properly. 👌
Running via the JS bridge in a react-native application, something like:
```typescript
Sentry.config(SENTRY_DSN, {
// ...
dataCallback: (data: any) => {
data.fingerprint = ['Custom', 'Fingerprint']
return data
},
}).install()
Sentry.captureException(new …
```
=> fix(react-native): Correctly label fingerprints for JS bridge.

.travis.yml, Sources/Sentry/SentryContext.m, Sources/Sentry/SentryEvent.m, Sources/Sentry/include/SentryContext.h, Sources/Sentry/include/SentryEvent.h
A lot of code, but with this, you can send transactions to Sentry.
```swift
let event = Event(level: .info)
event.transaction = "test.transaction.1"
event.type = "transaction"
let context = Context()
context.otherContexts = ["trace": [
"trace_id": NSUUID().uuidString.replacingOccurrences(of: "-", with: "").lowercased(),
"span_id": NSUUID().uuidString.replacingOccurrences(of: "-", with: "").lowercased().prefix(16),
"op": "manual",
"description": "Test operation"
]
]
event.context = context
Client.shared?.send(event: event) { (error) in
// Optional callback after event has been send
}
```
=> feat: Add support for event type and custom contexts

Tests/SentryTests/SentryCrash/RFC3339UTFString_Tests.m, Tests/SentryTests/SentryCrash/SentryCrashObjC_Tests.m
no more crashes when executing unit tests.
Possible next Steps:
* Evaluate if those tests can be fixed. if not, remove.
* Some tests in `SentryCrashObjC_Tests.m` fail. Check if they can be fixed, remove if not.
=> fix: remove broken SentryCrash unit tests

Sources/Sentry/SentryHub.m, Tests/SentryTests/SentryTests.m
code coverage of SentryCrashReportSink.m is still low.
@HazAT Looks like there are 2 tests covering this, but the constraint `nil != SentryClient.sharedClient` is always false. Maybe the related tests aren't properly setup or the cleanup of another test is sloppy? Anyways, should I fix or ignore this?
=> added more tests for `SentrySDK` and `SentryHub`

Package.swift, Sources/Sentry/include/module.modulemap
This PR implements [Swift Package Manager](https://swift.org/package-manager/) support with the existing `SentryCrash` directory structure. I’ve tested this lightly within an existing iOS app, and it seems to operate in line with the CocoaPods build.
It builds on the command line via `swift build` on macOS Catalina, and I haven’t tested it on tvOS, watchOS, or iOS earlier than 13.3.
This fixes #312 and was inspired by #321.
=> Swift Package Manager support

Sources/Sentry/include/SentryClient.h
Tiny change to fix a little spelling mistake in doc comments.
`notifcation` => `notification`
=> Fix spelling in doc comments

Sources/Sentry/SentryClient.m, Sources/Sentry/SentryContext.m, Sources/Sentry/SentryScope.m, Sources/Sentry/include/SentryClient.h, Sources/Sentry/include/SentryScope.h, Tests/SentryTests/SentryBreadcrumbTests.m, Tests/SentryTests/SentryDsnTests.m, Tests/SentryTests/SentryFileManagerTests.m, Tests/SentryTests/SentryLogTests.m, Tests/SentryTests/SentryOptionsTest.m, Tests/SentryTests/SentrySwiftTests.swift, Tests/SentryTests/SentryTests.m
`[SentryScope applyToEvent]` adds `scope.context` to `event.context.otherContexts` (both dicts).
(`otherContexts` is merged into context when it's serialized)
@HazAT Fixed broken the tests in this PR/branch as well. Sorry for the mix.
=> 5.x-scope-setcontext

Sources/Sentry/SentryContext.m
Manually created SentryEvents have `os.name=iOS` set, but should be `os.name=tvOS`.
This PR fixes this for tvOS (`os.name=tvOS`) and mac catalyst apps (`os.name=macOS`).
Original Issue: https://github.com/getsentry/sentry-cocoa/issues/361
=> Fix SentryContext OS name detection for tvOS and macCatalyst

Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_Signal.c, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m, Sources/SentryCrash/Recording/SentryCrashReport.c, Sources/SentryCrash/Recording/SentryCrashReportFixer.c, Sources/SentryCrash/Recording/Tools/SentryCrashFileUtils.c, Sources/SentryCrash/Recording/Tools/SentryCrashLogger.c, Sources/SentryCrash/Reporting/Tools/SentryCrashCString.m
We ran version 4.4.3 of the Sentry SDK through a code scanner, and it identified several unchecked error conditions, mostly related to memory allocation. This branch has my patches to address those items.
=> Add more error checking to crash recording and reporting

README.md
* fixed link to travis from .org to .com (build batch)
* added twitter batch
* rearranged them (build, tests, releases, platforms, languages, twitter)
"old": https://github.com/getsentry/sentry-cocoa/blob/master/README.md
new: https://github.com/getsentry/sentry-cocoa/blob/updates-readme-batches/README.md
=> updates readme batches

Sources/Sentry/SentryClient.m, Sources/Sentry/SentryCrashIntegration.m, Sources/Sentry/SentryGlobalEventProcessor.m, Sources/Sentry/SentryHub.m, Sources/Sentry/SentryOptions.m, Sources/Sentry/SentryTransport.m, Sources/Sentry/include/SentryGlobalEventProcessor.h, Sources/Sentry/include/SentryTransport.h
The response is checked for HTTP 429 and the corresponding event setup for queuing[sic!]. No actual radio silence implemented.
If a response is HTTP 429, the "Retry-After" header is parsed. Resulting `radioSilenceDeadline` is set. No event is sent as long as this NSDate is after now.
This date isn't saved on disk. Thus requests will be triggered again after app restart. To fix this `NSUserDefaults` could be used (iOS 2.0+, macOS 10.0+, Mac Catalyst 13.0+, tvOS 9.0+, watchOS 2.0+). Can add this if wanted.
The batch upload `sendAllStoredEvents` should stop uploading as soon as a 429 occurs (AFAIK sentry-android is doing this `getQueue().clear();`). But `sendAllStoredEvents` is not a queue - it's a for loop with a `dispatchGroup` to get a callback when all responses have been processed. …
=> 5.x improve behaviour if response is http 429 aka. retry after

Sources/Sentry/SentryClient.m, Sources/Sentry/SentryScope.m, Sources/Sentry/include/SentryScope.h, Tests/SentryTests/SentryScopeTests.m
Adds:
* release
* dist
* environment
To the scope, as properties with copy semantics.
Made sure values from the scope are applied before the values from `SentryOptions` since they are more "specific".
=> feat: Scope extra values

Sources/Sentry/SentryCrashReportConverter.m, Sources/Sentry/SentryEvent.m, Sources/Sentry/SentryJavaScriptBridgeHelper.m, Sources/Sentry/SentryScope.m, Sources/Sentry/include/SentryBreadcrumb.h, Sources/Sentry/include/SentryDefines.h, Sources/Sentry/include/SentryEvent.h, Sources/Sentry/include/SentryScope.h, Tests/SentryTests/SentryBreadcrumbTests.m, Tests/SentryTests/SentryFileManagerTests.m, Tests/SentryTests/SentryInterfacesTests.m, Tests/SentryTests/SentryJavaScriptBridgeHelperTests.m, Tests/SentryTests/SentryLogTests.m, Tests/SentryTests/SentryRequestTests.m, Tests/SentryTests/SentryScopeTests.m, Tests/SentryTests/SentryTests.m
* SentryLevelName mapping was missing a value
* The order of values was inverted (the higher the more severe)
* Added parameterless ctor to Event: not sending level uses server default (error).
* SentryEvent doesn't add level if value is none
* assigned the SentryEvent `NS_DESIGNATED_INITIALIZER`
=> fix: Sentry level

.travis.yml, CHANGELOG.md, Sources/Sentry/SentryHub.m
Fixes a bug where `configureScope` wasn't called for the SentryCrashIntegration and therefore not persisting scope data (breadcrumbs ...) for crashes because we were using `self.scope` instead of the getter `[self getScope]` which creates a new Scope instance in case there is none.
=> fix: Use getter for scope to receive an empty instance

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryHttpDateParser.m, Sources/Sentry/SentryHttpTransport.m, Sources/Sentry/SentryRateLimitParser.m, Sources/Sentry/include/Sentry.h, Sources/Sentry/include/SentryHttpDateParser.h, Sources/Sentry/include/SentryRateLimitParser.h, Tests/SentryTests/HttpDateFormatter.swift, Tests/SentryTests/SentryHttpDateParserTests.swift, Tests/SentryTests/SentryHttpTransportTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
Encapsulate the parsing of the http date into SentryHttpDateParser
so that NSDateFormatter is only initialised once for SentryHttpTransport
and not on each http response.
=> perf: Init NSDateFormatter once for Transport

Sources/Sentry/SentryHub.m
Relates to #442
This is the source of the `Sentry - Error:: Invalid JSON.` message.
=> fix: only cache session instance

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryDefaultRateLimits.m, Sources/Sentry/SentryHttpTransport.m, Sources/Sentry/SentryTransportFactory.m, Sources/Sentry/include/Sentry.h, Sources/Sentry/include/SentryDefaultRateLimits.h, Sources/Sentry/include/SentryHttpTransport.h, Sources/Sentry/include/SentryRateLimits.h, Tests/SentryTests/SentryDefaultRateLimitsTests.swift, Tests/SentryTests/SentryHttpTransportTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h, Tests/SentryTests/TestRateLimits.swift
Move the code for the rate limit logic to an extra class SentryDefaultRateLimits.
SentryHttpTransport interacts now with the protocol SentryRateLimits to make it easier
to test. The current RateLimit logic with both status code 429 and the custom
HTTP header "X-Sentry-Rate-Limits" is not included in this PR.
=> ref: Move rate limit logic to extra class

Sources/Sentry/SentryClient.m, Sources/Sentry/SentryHttpTransport.m, Sources/Sentry/include/SentryDefines.h, Tests/SentryTests/SentryHttpTransportTests.swift, Tests/SentryTests/TestConstants.swift, Tests/SentryTests/TestRequestManager.swift
Add more tests for SentryHttpTransport so that the coverage is almost 100%. Extracted duplicated code for sending a request from `sendEvent` and `sendEnvelope` to a new method.
=> test: Bring up test coverage for SentryHttpTransport

CHANGELOG.md, Sources/Sentry/SentryHub.m, Sources/Sentry/SentryOptions.m, Sources/Sentry/SentryScope.m, Sources/Sentry/include/SentryDefines.h, Sources/Sentry/include/SentryOptions.h, Tests/SentryTests/SentryHubTests.m
Using the option `maxBreadcrumbs` from `SentryOptions`.
Introduce hard cap for breadcrumbs.
=> fix: Use maxBreadcrumbs from options

Sources/Sentry/SentryDefaultRateLimits.m
Fixed date is nil in the log message when a RateLimit for all types is active.
=> fix: Logging for DefaultRateLimits

CHANGELOG.md, Sources/Sentry/SentryHttpTransport.m, Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Check in sendAllStoredEvents in SentryHttpTransport if the RateLimit is
active or not.
=> feat: RateLimit for sendAllStoredEvents

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryFileContents.m, Sources/Sentry/SentryFileManager.m, Sources/Sentry/SentryHttpTransport.m, Sources/Sentry/include/SentryFileContents.h, Sources/Sentry/include/SentryFileManager.h, Tests/SentryTests/SentryFileManagerTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
`SentryFileManager.getAllStoredEventsAndEnvelopes` returned `NSDictionary<NSString *, id>`. That dictionary was filled with `path` and `data`. A new class `SentryFileContents` is added that contains two properties for `path` and `contents`. The consumer of `getAllStoredEventsAndEnvelopes` doesn't have to look into the implementation to understand what the function returns.
=> ref: Add SentryFileContents

CHANGELOG.md, Sources/Sentry/SentryFileManager.m, Sources/Sentry/include/SentryFileManager.h, Tests/SentryTests/SentryFileManagerTests.swift
Add `getAllEvents` and `getAllEnvelopes` to `SentryFileManager`. `SentryHttpTransport` needs those methods to implement rate limiting.
=> feat: Store SentryEnvelopes in extra path

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryHttpTransport.m, Sources/Sentry/SentryRateLimitCategoryMapper.m, Sources/Sentry/SentrySerialization.m, Sources/Sentry/include/Sentry.h, Sources/Sentry/include/SentryEnvelope.h, Sources/Sentry/include/SentryEnvelopeItemType.h, Sources/Sentry/include/SentryRateLimitCategory.h, Sources/Sentry/include/SentryRateLimitCategoryMapper.h, Tests/SentryTests/Networking/RateLimits/SentryRateLimitCategoryMapperTests.swift, Tests/SentryTests/Networking/SentryHttpTransportTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
`SentryHttpTransport` used `SentryEnvelopeItemTypeEvent` as a category for
`SentryRateLimits`. This was not correct. Now `SentryRateLimitCategoryMapper`
takes care to map an event type to the correct category. Currently all eventTypes are
classified as `SentryRateLimitCategoryError` as discussed with @jan-auer.
=> fix: Use RateLimitCategoryError for events

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryEnvelope.m, Sources/Sentry/SentryEnvelopeRateLimit.m, Sources/Sentry/SentryHttpTransport.m, Sources/Sentry/SentryRateLimitCategoryMapper.m, Sources/Sentry/SentryTransportFactory.m, Sources/Sentry/include/SentryEnvelopeRateLimit.h, Sources/Sentry/include/SentryHttpTransport.h, Sources/Sentry/include/SentryRateLimitCategory.h, Sources/Sentry/include/SentryRateLimitCategoryMapper.h, Tests/SentryTests/Networking/RateLimits/SentryEnvelopeRateLimitTests.swift, Tests/SentryTests/Networking/RateLimits/SentryRateLimitCategoryMapperTests.swift, Tests/SentryTests/Networking/SentryHttpTransportTests.swift, Tests/SentryTests/Networking/TestRateLimits.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
When sending an envelope the rate limit for envelope items are checked. If a rate
limit is active the envelope item is removed. Checking rate limits for on disk
cached envelopes is going to be done in another PR.
=> feat: RateLimit for non cached Envelopes

CHANGELOG.md, Sources/Sentry/SentryEnvelopeRateLimit.m, Tests/SentryTests/Networking/RateLimits/SentryEnvelopeRateLimitTests.swift
Init new SentryEnvelope with header and not only headerId to avoid
the loss of details from the header.
=> fix: EnvelopeRateLimit init envelope with header

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryEnvelopeRateLimit.m, Sources/Sentry/SentryFileManager.m, Sources/Sentry/SentryHttpTransport.m, Sources/Sentry/include/SentryFileManager.h, Tests/SentryTests/Networking/RateLimits/SentryEnvelopeRateLimitTests.m, Tests/SentryTests/Networking/SentryHttpTransportTests.swift, Tests/SentryTests/SentryFileManagerTests.swift
Check if a rate limit is active for cached events and envelopes. The
sending of cached events and envelopes is split up. We don't deserialize
events because we use anyways always the rate limit category error. For
cached envelopes the same logic is applied as for sending envelopes in
the first place.
I removed the `dispatchGroup` for sending the cached events and envelopes, because if I'm not mistaken it was useless, because only the code only called `enter` and `leave` but never `wait` or `notify`. Please double-check @HazAT if don't break something here and this was here for a reason.
=> feat: RateLimiting for cached events and envelopes

Sources/Sentry/SentryClient.m, Sources/Sentry/SentryEvent.m, Sources/Sentry/SentryFileManager.m, Sources/Sentry/SentryOptions.m, Tests/SentryTests/SentryTests.m
```
Method accepting NSError** should have a non-void return value to indicate whether or not an error occurred
4. nil returned from a method that is expected to return a non-null value
```
=> ref: Refactor out warnings

Sources/Sentry/SentryOptions.m, Sources/Sentry/SentryTransportFactory.m, Sources/Sentry/include/SentryOptions.h, Tests/SentryTests/Networking/SentryTransportInitializerTests.swift, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryOptionsTest.m
Removing `HttpTransport` from options.
We plan to add a way to replace the transport further on. It'll probably be through ` `TransportFactory` instead.
Addresses #486
=> ref: Remove Transport from Options

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryConcurrentRateLimitsDictionary.m, Sources/Sentry/SentryDateUtil.m, Sources/Sentry/SentryDefaultRateLimits.m, Sources/Sentry/SentryRateLimitCategoryMapper.m, Sources/Sentry/SentryRateLimitParser.m, Sources/Sentry/include/SentryConcurrentRateLimitsDictionary.h, Sources/Sentry/include/SentryDateUtil.h, Sources/Sentry/include/SentryRateLimitCategoryMapper.h, Tests/SentryTests/Networking/RateLimits/SentryConcurrentRateLimitsDictionaryTests.swift, Tests/SentryTests/Networking/RateLimits/SentryDefaultRateLimitsTests.swift, Tests/SentryTests/Networking/RateLimits/SentryRateLimitCategoryMapperTests.swift, Tests/SentryTests/Networking/RateLimits/SentryRateLimitsParserTests.swift, Tests/SentryTests/SentryDateUtilTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
Always keep the maximum rate limit if multiple rate limits reference the same bucket.
If a new rate limit is shorter than an already cached rate limit, then keep the longer one.
To be consistent with our internal spec for rate limits.
Unit tests.
=> fix: Keep maximum rate limit

CHANGELOG.md, Sources/Sentry/SentrySessionTracker.m
Handle on close notification to close session as Exited
On device
=> fix: On app exit, close session as healthy

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/NSArray+SentrySanitize.h, Sources/Sentry/NSArray+SentrySanitize.m, Sources/Sentry/NSDictionary+SentrySanitize.m, Tests/SentryTests/SentryInterfacesTests.m
Change `[NSDictionary sentry_sanitize]` and add `[NSArray sentry_sanitize]` to convert values which chould not be serialized by a JSONSerializaion to string.
So that we can make sure sanitize result will always be encoded to json string successfully.
When reporting a network request failure, I tried to pass the userInfo property of NSError to `event.extra`. However, most of this kind of data are not convertable to json string. For example, decoding error from JSONDecoder has an array of `CodingKeys` in its userInfo to pointing out which key failed to decode. As a result, the whole event failed to send.
It seems pretty easy to pass data not created by ourself to an event. Crashlytics has apis to send NSError directly to SDK and makes this kind of conversion for userInfo. I think it will be …
=> feat: Add sentry_sanitize for NSArray

Sources/Sentry/SentryAutoSessionTrackingIntegration.m, Sources/Sentry/SentrySessionTracker.m, Sources/Sentry/include/SentryCurrentDateProvider.h, Sources/Sentry/include/SentrySessionTracker.h
Improve the testability of the SentrySessionTracker with using the
CurrentDateProvider for getting the current date.
Improve the testability of `SentrySessionTracker`.
Still compiles and looking at the code in detail. 
Add tests for `SentrySessionTracker`.
=> ref: Use CurrentDateProvider in SessionTracker

.travis.yml, .travis/run.sh, CONTRIBUTING.md, Makefile, Sources/Sentry/SentryHttpTransport.m, fastlane/Fastfile, scripts/check-clang-format.py
Let the lint job fail on Travis if Objective-C, C++, or C code is not properly formatted. 
With running Clang Format on the CI we can enforce that the code is properly formatted.
I [committed a line of code](https://github.com/getsentry/sentry-cocoa/pull/514/commits/876f4e26c9b1e0d155f19e7fd1eec6a5f28fd878) that is not properly formatted to check if the Travis lint job fails.
Format all Swift code, enforce Swiftlint on Travis.
=> ci: Run Clang Format on Travis

Tests/SentryTests/Helper/SentryCurrentDateTests.swift
Add test when no current date provider is set to reach 100%
code coverage for SentryCurrentDate.
=> test: Add test for SentryCurrentDate

Sources/Sentry/SentryHub.m
Reduce nesting for closeCachedSessionWithTimestamp.
=> ref: Reduce nesting in SentryHub

CHANGELOG.md, Sources/Sentry/SentrySessionTracker.m
It seems we don't have anything in our build process that fails the condition:
`#if SENTRY_HAS_UIKIT || TARGET_OS_OSX || TARGET_OS_MACCATALYST`
But `pod trunk` validation does flag it out.
=> fix: End file at the right place with #ifdef

CHANGELOG.md, Sources/Sentry/include/SentryCrashExceptionApplication.h
Import only NSApplication and move Foundation import to the top.
Fixes #526 
Trying sending crash events with macOS-Swift.
=> fix: Failing MacOS build

CHANGELOG.md, Sources/Sentry/SentryScope.m, Sources/Sentry/include/SentryScope.h, Tests/SentryTests/SentryScopeTests.m
Add remove methods for tag, context, and extra to SentryScope.
You can set tag, context, and extra on `SentryScope`, but you can't remove them. We have this implementation already on [Android](https://github.com/getsentry/sentry-android/blob/2798e65a6f9c5a15eecff6f79e4a59e60b083f87/sentry-core/src/main/java/io/sentry/core/Scope.java#L248).
Adding unit tests.
None.
=> feat: Add remove methods for SentryScope

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentrySession.m, Tests/SentryTests/SentrySessionTests.swift
Use `numberWithDouble` instead of `numberWithLongLong` for
initialising the duration in `SentrySession`.
Implicit conversion may lose precision.
Adding unit tests.
=> fix: Avoid Implicit conversion in SentrySession

CHANGELOG.md, Sources/Sentry/SentryHub.m, Sources/Sentry/SentrySession.m, Sources/Sentry/include/SentrySession.h, Tests/SentryTests/Helper/SentryFileManagerTests.swift, Tests/SentryTests/Networking/RateLimits/SentryEnvelopeRateLimitTests.swift, Tests/SentryTests/Networking/SentryHttpTransportTests.swift, Tests/SentryTests/SentrySessionTests.m, Tests/SentryTests/SentrySessionTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
Make all properties of SentrySession read-only except environment and user,
because those are set in the scope after a session is initialized.
The session properties should not be changeable.
Unit tests.
=> fix: Make properties of Session readonly

CHANGELOG.md, Sources/Sentry/SentryMeta.m
The constants in SentryMeta are defined with NSString *const which
can lead to clashes because the constant name appears in the global
symbol table. Adding the static keyword fixes this issue, because
the compiler replaces each occurrence of the constant.
Fixes GH-546
Adding another constant with the name `versionString` in the `SentryClient` failed before this fix and now it works.
=> fix: Duplicate symbol for SentryMeta

CHANGELOG.md, Sources/Configuration/Sentry.xcconfig
Set `SUPPORTS_MACCATALYST` to `YES` explicitly instead of relying on the implicit default.
`xcodebuild -showBuildSettings` does not emit implicit settings, so setting it explicitly allows for its output to reflect Catalyst support.
Ran `xcodebuild -showBuildSettings` before and after the change.
Looking for CHANGELOG and commit naming guidance if approved.
=> feat: Set SUPPORTS_MACCATALYST to YES explicitly

Sources/Sentry/SentryClient.m, Sources/Sentry/SentryEvent.m, Tests/SentryTests/SentryInterfacesTests.m
Moved setting the default event sdk info from `SentryEvent.m` to `SentryClient.m`.
Removed the `addSdkInformation` method from `SentryEvent`, and added the sdk setting code
to `SentryClient.prepareEvent`. `SentryEvent.addSimpleProperties` now just copies the sdk info from `self.sdk` instead.
Setting sdk info should be in `prepareEvent` and not be set on serialization only.
This is also so the sdk info can be accessed in `beforeSend`.
Removed `event.sdk` from interfaces tests and ran the provided tests.
=> ref: Event sdk info is now set in prepareEvent instead of during serialization

CHANGELOG.md, Sources/SentryCrash/Reporting/Filters/SentryCrashReportFilterBasic.m, Sources/SentryCrash/Reporting/Filters/Tools/Container+SentryDeepSearch.h, Sources/SentryCrash/Reporting/Filters/Tools/Container+SentryDeepSearch.m, Tests/SentryTests/SentryCrash/Container+DeepSearch_Tests.m
Prefix categories for NSDictionary and NSArray with sentry to avoid
accidental overriding.
Fixes GH-314
Tests are green.
None.
=> fix: Prefix category methods with sentry

CHANGELOG.md, Sources/SentryCrash/Recording/SentryCrashReport.c
Rollback to original conversion for UUID and not use
sentrycrashdl_convertBinaryImageUUID.
Trying it with a simulator.
=> fix: UUID for SentryCrashReport is null

Sources/SentryCrash/Recording/SentryCrashReport.c
Use sentrycrashdl_convertBinaryImageUUID in SentryCrashReport.addUUIDElemet.
We have the code for converting a binary image UUID twice.
With the emulator.
Add tests for SentryCrashReport
=> ref: Use UUIDConversion in SentryCrashReport

CHANGELOG.md, Sources/Sentry/include/SentryFileContents.h, Tests/SentryTests/Helper/SentryFileManagerTests.swift
This fixes a bug in the `SentryFileContents` object discarding `contents` (because it's weak) before we can actually use and send it. This resulted in an empty payload and therefore event being discarded.
React Native stores events to disk and sends it after restart. I notices that requests return `400` because the body we sent was empty.
=> fix: Remove weak ref file contents

CHANGELOG.md, Sources/SentryCrash/Recording/SentryCrashReportFixer.c, Sources/SentryCrash/Recording/Tools/SentryCrashJSONCodec.h, Sources/SentryCrash/Recording/Tools/SentryCrashJSONCodecObjC.m
Increases the max report length KSCrash can process by 10x
In react native it happens that sometimes when we try to process a crash we get this error:
```
2020-06-05 12:43:15.631482+0200 sample[70962:14350544] Sentry - Debug:: SDK initialized! Version: 5.1.3
ERROR: SentryCrashReportFixer.c (267): char *sentrycrashcrf_fixupCrashReport(const char *): Could not decode report: Data too long
ERROR: SentryCrashC.c (277): char *sentrycrash_readReport(int64_t): Failed to fixup report ID 56800000
```
Running this manually in react-native sample project. The fix removes this error.
=> fix: Increase max report length

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryClient.m, Tests/SentryTests/SentryClient+TestInit.h, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
Add a second internal initializer for SentryClient to be able to pass in dependencies
for testing. The internal initializer is exposed via a category in the tests.
We want to be able to test public classes with injecting internal test dependencies.
Unit tests and a quick test with the emulator.
Add tests for `SentryClient`
=> ref: Add internal init for SentryClient for testing

CHANGELOG.md, Sources/SentryCrash/Recording/Tools/SentryCrashJSONCodecObjC.m, Tests/SentryTests/SentryCrash/SentryCrashJSONCodec_Tests.m
`SentryCrashJSONCodecObjC.encodeObject` crashes when receiving a dictionary
with keys different than an `NSString`. Now `encodeObject` supports all types
of keys without crashing by converting the keys to NSString and not sorting
keys of dictionaries when they are different types.
We have a customer who ran into this issue, but we don't know why `SentryCrashJSONCodecObjC.encodeObject` received a dictionary with keys different than an `NSString` and this caused the SDK to crash.
Unit tests and smoke tests with emulators.
=> fix: SentryCrashJSON encodeObject crash

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryCrashIntegration.m, Sources/Sentry/SentryCrashReportConverter.m, Tests/SentryTests/Integrations/SentryCrashIntegrationTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
Custom release names configured in SentryOptions are ignored in crash reports.
This is fixed by passing the release name of the options to the user info of
SentryCrash.
Fixes GH-581
One unit test and with the sample projects.
=> fix: Custom release name for crash reports

Sources/Sentry/SentryHub.m
Use `CurrentDate` in `SentryHub`
Improve the testability of `SentryHub`.
=> ref: Use CurrentDate in SentryHub

CHANGELOG.md, Sources/Sentry/include/SentryAutoBreadcrumbTrackingIntegration.h, Sources/Sentry/include/SentryAutoSessionTrackingIntegration.h, Sources/Sentry/include/SentryCrashIntegration.h
`SentryAutoBreadcrumbTrackingIntegration` and `SentryAutoSessionTrackingIntegration`
now implement `SentryIntegrationProtocol`.
`SentrySDK.installIntegrations` needs the `SentryIntegrationProtocol` in order to init the integrations.
Unit tests.
=> ref: All integrations implement SentryIntegrationProtocol

CHANGELOG.md, Sources/Sentry/SentryClient.m, Tests/SentryTests/SentryClientTests.swift
SentryClient overwrote the stack trace (debug meta and threads) when sending an event that already has `debugMeta` and
`threads`. This caused stack traces of crashes logged by SentryCrash being overwritten. Now SentryClient keeps the threads and debug meta when sending an event and still attaches the stack trace for events that don't have those set when `attachStacktrace` is enabled or that contain an error or exception.
This issue was reported by a customer and we want to fix it.
=> fix: Overwriting stack trace for crashes

Sources/Sentry/SentryClient.m
When assigning shouldAttachStacktrace we now check if event.exceptions is not nil.
=> ref: Check for nil for exceptions in SentryClient

CHANGELOG.md, Sources/Sentry/SentryClient.m, Tests/SentryTests/Networking/TestTransport.swift, Tests/SentryTests/SentryClientTests.swift
When reading code to investigate #603 I noticed:
Prepared event isn't provided to the `beforeSend` callback.
Code isnt' using the reference returned by the `prepareEvent` method
Wrote a test that fails, fixed the test.
=> fix: beforeSend callback in SentryClient

Sources/Sentry/SentrySerialization.m, Sources/Sentry/include/SentryEnvelope.h, Sources/Sentry/include/SentrySerialization.h
Remove header imports in SentryEnvelope and SentrySerialization
and use class forward declaration.
=> ref: Minimize header imports for Envelope and Serialization

Sentry.xcodeproj/project.pbxproj, Tests/SentryTests/Integrations/SentrySessionGeneratorTests.swift, Tests/SentryTests/TestUtils/Async.swift
Move `delayNonBlocking` to an extra file so it can be reused.
We need this functionality in multiple tests.
Travis does this for me.
=> test: Extract delayNonBlocking to be reusable

Sources/Sentry/SentryClient.m, Sources/Sentry/SentryHttpTransport.m, Sources/Sentry/include/SentryTransport.h, Tests/SentryTests/Networking/SentryHttpTransportTests.swift, Tests/SentryTests/Networking/TestTransport.swift
The completion handler for sending events and envelopes in SentryTransport is always nil so we can
remove it. It also simplifies things when sending cached envelopes and events first.
Remove complexity we don't need.
Travis.
Make SentryTransport private until we align it with the unified API or just align it with the unified API.
=> ref: Remove completion handler in SentryTransport

Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m, Sources/SentryCrash/Recording/Tools/SentryCrashCPU.c
This is blocking customers from publishing their apps and needs to be dealt with ASAP.
Resolves #635
This removes the architecture that used to be reported as:
=> fix: Don't use API blocked by AppStore

CHANGELOG.md, Sources/Sentry/SentrySDK.m, Sources/Sentry/include/SentrySDK.h, Tests/SentryTests/SentrySDKTests.swift, Tests/SentryTests/SentrySwiftTests.swift, Tests/SentryTests/SentryTests.m
Both initWithOptionsObject and initWithOptions are marked as deprecated.
Those two methods are removed now from the SDK.
We want to get rid of deprecated code.
Travis.
=> feat: Remove deprecated SDK inits

Sources/Sentry/SentryTransportFactory.m, Sources/Sentry/include/SentryTransportFactory.h
Simplify code in `SentryTransportFactory` by removing the `_Nonnull`, which is not needed because of `NS_ASSUME_NONNULL`.
Simplify the code.
Travis.
=> ref: Remove redundant nonnull for TransportFactory

Sources/Sentry/SentryClient.m
captureSessions is internal and not used. Let's remove it to reduce complexity.
We want to remove code that is not used.
Travis.
=> ref: Remove captureSessions from SentryClient

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentrySession.m, Sources/Sentry/include/SentrySession.h, Tests/SentryTests/Protocol/SentrySession+Equality.h, Tests/SentryTests/Protocol/SentrySession+Equality.m, Tests/SentryTests/Protocol/SentryUser+Equality.h, Tests/SentryTests/Protocol/SentryUser+Equality.m, Tests/SentryTests/SentrySessionTests.swift
We want to be able to copy the SentrySession so we can pass a copy from the SentryHub
to the SentryClient and don't have to keep a lock so the same reference doesn't get modified
when sending it.
See description.
Unit tests.
=> feat: Implement NSCopying for SentrySession

CHANGELOG.md, Sentry.xcodeproj/xcshareddata/xcbaselines/63AA76641EB8CB2F00D153DE.xcbaseline/4487886E-B920-4AB1-99BD-1A9C5128C731.plist, Sources/Sentry/SentryHttpTransport.m, Sources/Sentry/include/SentrySession.h, Tests/SentryTests/Networking/SentryHttpTransportTests.swift
When a SentryEnvelope contains multiple items and a rate limit is active for not all items
the SentryEnvelope gets send even with the rate-limited items. This is fixed now. The
downside is that we have to serialize the SentryEnvelope once more.
We want that rate-limiting also applies to cached envelope items.
Unit tests.
=> fix: Rate limiting for cached envelope items

CHANGELOG.md, Samples/macOS-Swift/macOS-Swift/ViewController.swift, Sources/Sentry/SentrySDK.m, Sources/Sentry/include/SentrySDK.h, Tests/SentryTests/Protocol/SentryUserTests.swift, Tests/SentryTests/SentrySDKTests.swift
Add a property crashedLastRun to SentrySDK to check if the last program execution terminated
with a crash.
A customer nicely asked for this feature and we already had a similar feature in [4.x.x](https://github.com/getsentry/sentry-cocoa/blob/4.5.0/Sources/Sentry/include/SentryClient.h#L238).
Unit tests and with a simulator.
=> feat: Add crashedLastRun to SentrySDK

CHANGELOG.md, Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m, Samples/iOS-Swift/iOS-Swift/AppDelegate.swift, Samples/macOS-Swift/macOS-Swift/AppDelegate.swift, Samples/tvOS-Swift/tvOS-Swift/AppDelegate.swift, Samples/watchOS-Swift/watchOS-Swift WatchKit Extension/ExtensionDelegate.swift, Sources/Sentry/SentryOptions.m, Sources/Sentry/include/SentryOptions.h, Tests/SentryTests/SentryOptionsTest.m
The default value of enableAutoSessionTracking of SentryOptions is now @YES.
We want our customers to use this nice feature per default.
Unit tests.
=> feat: Enable auto session tracking per default

Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_MachException.c
I replaced a usage of the `==` equality operator with `strcmp()`.
This fixes the Xcode 12 (beta 6) compiler warning `Result of comparison against a string literal is unspecified (use an explicit string comparison function instead)`.
I built it and I ran the tests via `make test`. I did both of this against Xcode 11.6 as well as Xcode 12 (beta 6).
=> Use strcmp instead of == operator to compare threadName with literal

CHANGELOG.md, Sources/Sentry/SentryHttpTransport.m, Tests/SentryTests/Networking/SentryHttpTransportTests.swift, Tests/SentryTests/SentryClientTests.swift
These checks are actually redundant as `options.enabled` is already checked by the client in `prepareEvent`.
Customer is disabling the SDK by setting `enabled`.
https://app.asana.com/0/1142928854421177/1189984760680431/f
Removed enabled test cases for the transport, and added test cases to check that disabling or disabling then re-enabling the sdk in the options correctly ignores and captures the event respectively.
Tested on sample app.
=> fix: Remove redundant sdk options enable check in SentryHttpTransport

Tests/SentryTests/SentryScopeTests.m
Remove setUp and tearDown which are empty.
Remove empty methods.
=> test: Remove empty methods in SentryScopeTests

CHANGELOG.md, Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m, Sources/Sentry/SentryAutoSessionTrackingIntegration.m, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryOptions.m, Sources/Sentry/include/SentryOptions.h, Tests/SentryTests/SentryOptionsTest.m
Use BOOL for debug, enabled, enableAutoSessionTracking and attachStacktrace in SentryOptions
instead of NSNumber.
A BOOL for storing booleans is more straightforward.
Unit tests.
=> feat: Replace NSNumber with BOOL in SentryOptions

Sources/Sentry/SentryHttpTransport.m, Sources/Sentry/SentryTransportFactory.m, Sources/Sentry/include/SentryHttpTransport.h, Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Remove sentry prefixes for constructor of SentryHttpTransport.
We don't need those prefixes as they are just noise.
Travis.
=> ref: Remove Sentry prefixes in SentryHttpTransport

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryDispatchQueueWrapper.m, Sources/Sentry/SentryHttpTransport.m, Sources/Sentry/SentryTransportFactory.m, Sources/Sentry/include/SentryDispatchQueueWrapper.h, Sources/Sentry/include/SentryHttpTransport.h, Tests/SentryTests/Networking/SentryHttpTransportTests.swift, Tests/SentryTests/Networking/TestSentryDispatchQueueWrapper.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
The SentryHttpTransport was storing the envelope to disk on the calling thread. This is now
done one a background thread.
We don't want to do this on the calling thread as this can be the main thread of the application.
Unit tests are green and a smoke test on a real device.
=> fix: Async storing of envelope to disk

CHANGELOG.md, Sources/Sentry/include/SentryClient+Private.h, Sources/Sentry/include/SentrySession+Private.h
The imports for SentryClient+Private.h and SentrySession+Private.h were broken.
Therefore the SDK couldn't be imported via the Swift Package Manager. This is
fixed now.
We want to be able to add the SDK via the Swift Package Manager.
Adding the SDK via the Swift Package Manager in a sample project with Xcode.
=> fix: Header Imports for the Swift Package Manager

Utils/VersionBump/Package.swift
Compiling the VersionBump script which is called from craft ended with an error since
Swift 5.3 which comes with Xcode 12. This is fixed by updating some dependencies.
We want to be able to use VersionBump to be able to release the SDK.
By calling `swift build` in `Utils/VersionBump`.
=> ci: Fix VersionBump script

Tests/SentryTests/Integrations/SentrySessionTrackerTests.swift, Tests/SentryTests/TestClient.swift
Use TestConstants.dsn in TestClient to use the same folder in SentryFileManager.
We want SentryFileManager to use the same folder for all tests.
Travis.
=> test: Use TestConstant.dsn for FileManager

CHANGELOG.md, Sources/Sentry/SentryHub.m, Tests/SentryTests/Integrations/SentrySessionTrackerTests.swift, Tests/SentryTests/SentryHubTests.swift
The environment set via the SentryOptions is now set on SentrySessions.
We want the environment also on sessions.
Unit tests and SentrySessionGeneratorTests.
=> fix: Set environment for Sessions

MIGRATION.md
Migration Guide for 6.x
We want our users to be able to migrate easily to 6.x.
=> docs: Add migration guide for 6.x

CHANGELOG.md, Samples/iOS-ObjectiveC/iOS-ObjectiveC/ViewController.m, Samples/iOS-Swift/iOS-Swift/ViewController.swift, Samples/tvOS-Swift/tvOS-Swift/ContentView.swift, Samples/watchOS-Swift/watchOS-Swift WatchKit Extension/ContentView.swift, Sources/Sentry/SentryClient.m, Tests/SentryTests/SentryClientTests.swift
When capturing an NSError combine the error message of the error.domain and error.code.
The error.localizedDescription is still set in the context of the event as user info. Issues with the
message coming from the domain and code might not be grouped to existing issues which messages
stem from the error.localizedDescription although there origin is the same. For new issues this
is not going to have a big impact on grouping as it is based upon stack trace, exception, and
message.
PR for updating docs: https://github.com/getsentry/sentry-docs/pull/2395
The localizedDescription can be in any language and might be confusing for our users when they don't speak this specific language. The domain and code are way more descriptive when an error happened.
=> feat: Use error domain and code for event message

MIGRATION.md
Add to the migration guide that our users might lose a few cached events
when upgrading from 5.x to 6.x.
We want our users to know this important piece of information when upgrading.
=> docs: Update Migration Guide

Tests/SentryTests/Integrations/SentryCrashIntegrationTests.swift, Tests/SentryTests/Integrations/SentrySessionGeneratorTests.swift, Tests/SentryTests/SentryHubTests.swift, Tests/SentryTests/SentrySDKTests.swift
Remove setting enableAutoSessionTracking to true as it is enabled per default.
Less code.
Tavis.
=> test: Remove redundant setting of sessionTracking

CHANGELOG.md, Sources/Sentry/Public/SentryBreadcrumb.h, Sources/Sentry/Public/SentryScope.h, Sources/Sentry/Public/SentryUser.h, Sources/Sentry/SentryBreadcrumb.m, Sources/Sentry/SentryId.m, Sources/Sentry/SentryScope.m, Sources/Sentry/SentryUser.m, Tests/SentryTests/Protocol/SentrySdkInfo+Equality.h, Tests/SentryTests/Protocol/SentrySdkInfo+Equality.m, Tests/SentryTests/Protocol/SentrySession+Equality.h, Tests/SentryTests/Protocol/SentrySession+Equality.m
isEqual accepts nil. As we use NS_ASSUME_NONNULL_BEGIN we have to
make the id _Nullable explicitly.
We don't want warnings.
Travis.
=> fix: Make public isEqual _Nullable

CHANGELOG.md, MIGRATION.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/Public/Sentry.h, Sources/Sentry/Public/SentryEvent.h, Sources/Sentry/Public/SentryMessage.h, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryEnvelope.m, Sources/Sentry/SentryEvent.m, Sources/Sentry/SentryMessage.m, Sources/Sentry/include/SentrySdkInfo.h, Tests/SentryTests/Integrations/SentrySessionGeneratorTests.swift, Tests/SentryTests/Networking/SentryHttpTransportTests.swift, Tests/SentryTests/Protocol/SentryEnvelopeTests.swift, Tests/SentryTests/Protocol/SentryMessage+Equality.h, Tests/SentryTests/Protocol/SentryMessage+Equality.m, Tests/SentryTests/Protocol/SentryMessageTests.swift, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryHubTests.swift, Tests/SentryTests/SentrySDKTests.swift, Tests/SentryTests/SentrySwiftTests.swift, Tests/SentryTests/SentryTests.m, Tests/SentryTests/TestConstants.swift
Add type SentryMessage for the event.message. SentryMessage can carry a format
string and structured parameters. This can help to group similar messages into
the same issue.
Fixes https://github.com/getsentry/sentry-cocoa/issues/747
We want to support this [new type](https://develop.sentry.dev/sdk/event-payloads/message/).
Tavis and simulator.
=> feat: Add SentryMessage

CHANGELOG.md, Sources/Sentry/Public/SentryMessage.h, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryEnvelope.m, Sources/Sentry/SentryMessage.m, Tests/SentryTests/Protocol/SentryMessageTests.swift, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryTests.m
SentryMessage.formatted is required by our servers.
The message interface defines formatted as required https://develop.sentry.dev/sdk/event-payloads/message/, although it accepts an empty formatted for legacy reasons, as discussed with @jan-auer.
Travis and simulator.
=> fix: Make SentryMessage formatted required

Tests/SentryTests/Networking/TestRequestManager.swift
A reference to the nextResponse of the TestRequestManager inside an async block for a DispatchQueue
caused SentryHttpTransportTests to fail silently and writing a Namespace SIGNAL, Code 0xb to the
test diagnostics. This is solved now by getting a local reference to the nextResponse.
We want to be able to run all tests from xcodebuild so they run properly in the CI.
From the command line with `xcodebuild -workspace Sentry.xcworkspace -scheme Sentry -configuration Debug GCC_GENERATE_TEST_COVERAGE_FILES=YES -destination "platform=macOS" test | xcpretty -t`.
=> test: Fix TestRequestManager

.github/workflows/samples.yml
Call xcodebuild directly.
Calling xcodebuild directly gives us more control and we don't depend on an external Github Action.
=> ci: Build samples with xcodebuild

Tests/SentryTests/Helper/SentryFileManagerTests.swift, Tests/SentryTests/Networking/RateLimits/SentryConcurrentRateLimitsDictionaryTests.swift, Tests/SentryTests/Networking/SentryHttpDateParserTests.swift, Tests/SentryTests/Networking/SentryHttpTransportTests.swift, Tests/SentryTests/Networking/TestRequestManager.swift, Tests/SentryTests/SentryHubTests.swift, Tests/SentryTests/TestUtils/Async.swift
Add extension function waitWithTimeout to DispatchGroup so a test doesn't
get stuck forever.
We don't want our tests to get stuck and instead to fail fast.
Travis.
=> test: Wait with a timeout for DispatchGroup

.github/workflows/build.yml, .travis/stage-carthage.sh, CHANGELOG.md, Makefile, scripts/carthage-xcode12-workaround.sh
The build for Carthage was failing since using Xcode 12. This is a known issue at
https://github.com/Carthage/Carthage/issues/3019. It can be fixed with using a
workaround script:
https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md.
Furthermore, we now run a check with Github actions to avoid this in the future.
Fix Carthage.
Github Actions.
=> fix: Carthage for Xcode 12

CHANGELOG.md, Sources/Sentry/Public/SentryEvent.h
initWithJSON was removed with #768 in the .m file but not in the header.
Xcode displayed a warning for this.
Travis.
=> fix: Remove initWithJSON from SentryEvent

CHANGELOG.md, Sources/SentryCrash/Recording/Tools/SentryCrashObjC.c, Sources/SentryCrash/Recording/Tools/SentryCrashObjCApple.h
On iOS 13.4, Apple changed the Objective-C runtime code (objc4-781). The structure `class_rw_t ro`
pointer has changed. This fix originates from https://github.com/kstenerud/KSCrash/pull/380.
`testWithFaultyReport` failed when running `make test` locally and also on Travis some tests failed randomly. The stacktrace below is from a local run and displays some problems in SentryCrashMonitor_Zombie. 
```
0   io.sentry.Sentry              	0x0000000104aded20 sentrycrashobjc_ivarNamed + 176 (SentryCrashObjC.c:1056)
1   io.sentry.Sentry              	0x0000000104ac8bd9 copyStringIvar + 105 (SentryCrashMonitor_Zombie.c:71)
2   io.sentry.Sentry              	0x0000000104ac8b41 storeException + 81 (SentryCrashMonitor_Zombie.c:99)
3   io.sentry.Sentry              	0x0000000104ac8ac7 handleDealloc …
```
=> fix: iOS 13.4 Runtime Crash

CHANGELOG.md, Sources/Sentry/SentryClient.m, Tests/SentryTests/SentryClientTests.swift
This PR add sanatizing to the error's user info dictionary.
Certain errors would cause the event to drop the sdk and context properties, because the error's user info contained values that couldn't be serialized as JSON.
Changed the library in my project locally, and saw the error being reported in Sentry without the "A value set to the context or sdk is not serializable. Dropping context and sdk." breadcrumb, and with the context and sdk properties present.
I'm not sure where I should introduce a test for it. Preferably I would like to add a test that handles an error with problematic user info, and fails without my changes. But since the formatting of the event happens in SentryClient (covered by SentryClientTests), and the serialization in `SentrySerialization` (covered by …
=> fix: Sanitize UserInfo of NSError and NSException

Sources/Sentry/Public/SentryMessage.h
The code docs for SentryMessage.initWithFormatted were missing. Now they are added.
While writing tests I used SentryMessage.initWithFormatted and saw that they are missing.
CI.
=> docs: Document SentryMessage.initWithFormatted

Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
When tapping on captureUserFeedback in iOS-Swift both methods captureMessage and captureUserFeedback
are called, leading to both capturing a message and user feedback when tapping on captureUserFeedback.
The call to captureMessage is now removed.
See description
Simulator.
=> test: Remove duplicate click handler

CHANGELOG.md, Sources/Sentry/SentryEnvelope.m, Tests/SentryTests/Protocol/SentryEnvelopeTests.swift
The eventID should be set in the envelope header when sending user feedback, as mentioned
here: https://develop.sentry.dev/sdk/envelopes/#userreport.
https://develop.sentry.dev/sdk/envelopes/#userreport
CI and simulator.
=> fix: Add eventId to user feedback envelope header

README.md
Note min version for on-prem users
=> Min Sentry version for SDK 6.0.0 

CHANGELOG.md, Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard, Sources/Sentry/SentryBreadcrumbTracker.m, Tests/SentryTests/SentryHubTests.swift
swizzleViewDidAppear in SentryBreadcrumbTracker called scope `addBreadcrumb` which
didn't call the SentryBeforeBreadcrumbCallback. This is fixed now.
A customer wants to drop breadcrumbs stemming from swizzleViewDidAppear.
Simulator.
=> fix: Call beforeBreadcrumb for Breadcrumb Tracker

CHANGELOG.md, Sources/Sentry/Public/SentryBreadcrumb.h
When importing Sentry into an Obj-C++ file a user receives the warning
typedef 'SentryLevel' cannot be referenced with an enum specifier. This is
fixed now by removing the redundant enum specifier.
Customer issue.
I couldn't reproduce the issue in an Objective-C++ file, but you don't need to specify `enum` for properties if your enum is strongly typed, in other words, if you use `typedef` or `NS_ENUM`. We don't use it for other enums for example on `SentryOptions`. The customer didn't get any errors for enum properties in `SentryOptions`.
=> fix: Remove enum specifier for SentryLevel

Sentry.podspec
Cocoapods didn't work with Xcode 12, so a workaround was needed. With CocoaPods 1.10 this issue is fixed, so we can remove this workaround now.
Remove a not needed workaround.
CI
=> build: Undo Xcode 12 workaround for Cocoapods

CHANGELOG.md, Sources/Sentry/SentryClient.m, Tests/SentryTests/SentryClientTests.swift
Currently, the client sends Sessions without a release name to Sentry, which doesn't make sense, because
Sessions need a release name set. This is fixed now by dropping such sessions in the client.
We don't want to send Sessions that get dropped on the server anyway.
CI.
=> fix: Drop Sessions without release name

CHANGELOG.md, Sentry.xcodeproj/xcshareddata/xcbaselines/63AA76641EB8CB2F00D153DE.xcbaseline/1C0AB51E-7DAD-4469-8384-B6DE6A8E9023.plist, Sentry.xcodeproj/xcshareddata/xcbaselines/63AA76641EB8CB2F00D153DE.xcbaseline/Info.plist, Sources/Sentry/SentryCrashIntegration.m, Tests/SentryTests/Integrations/SentryCrashIntegrationTests.swift, Tests/SentryTests/SentrySDKTests.swift
Synchronize the scope to SentryCrash on a background thread instead of the calling thread,
because this can block the calling thread which can be the main thread for a few ms. We
accept the tradeoff that in case of a crash the scope might not be 100% up to date over
blocking the main thread.
A customer reported that automatic breadcrumbs can block the UI thread for around 200ms in some cases, which is unacceptable because this leads to UI glitches.
Unit tests.
=> perf: Async synching of scope on to SentryCrash

CHANGELOG.md, Sources/Sentry/Public/SentryClient.h, Sources/Sentry/SentryClient.m, Sources/Sentry/SentrySessionCrashedHandler.m, Sources/Sentry/SentrySessionTracker.m, Sources/Sentry/include/SentryClient+Private.h, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryHubTests.swift
Hybrid SDKs as react-native need a way to synchronously store an envelope to disk. Previously, this
was possible by exposing SentryFileManager on the SentryClient, but this breaks users of
react-native that use use_frameworks!,
see https://github.com/getsentry/sentry-react-native/issues/1171. A way to fix this would be to expose
SentryFileManager and SentryCurrentDateProvider as proposed in
https://github.com/getsentry/sentry-cocoa/pull/835. This has the downside of making classes public,
that shouldn't be public. A better workaround is to expose storeEnvelope on the SentryClient.
See https://github.com/getsentry/sentry-cocoa/pull/835.
Unit tests and CI.
=> feat: Add storeEnvelope on SentryClient

CHANGELOG.md, Sources/Sentry/Public/SentrySerializable.h, Sources/Sentry/SentryScope.m, Tests/SentryTests/Protocol/SentryBreadcrumbTests.swift, Tests/SentryTests/Protocol/SentryUserTests.swift, Tests/SentryTests/SentryScopeSwiftTests.swift
The SentryScope contains several properties that are dictionaries or arrays. The serialize method
returned a dictionary with references. So when for example a tag is added to the scope it is also
added to the serialized dictionary of the scope. This can lead to crashes when iterating over the
tags of the serialized dictionary while another thread adds a tag to the scope. This is fixed now
by adding a copy of these properties to the serialization dictionary instead of adding them by
reference.
A customer was pointing out infrequently `EXC_BAD_ACCESS (SIGSEGV)` when adding breadcrumbs on a background thread inside `SentryCrashJSONCodec.encodeObject` when calling `objectForKeyedSubscript`. `SentryCrashJSONCodec.encodeObject` is called from `SentryCrashIntegration` when the scope changes, …
=> fix: Serialization of SentryScope

Sources/Sentry/SentryHub.m, Tests/SentryTests/Integrations/SentrySessionGeneratorTests.swift, Tests/SentryTests/Integrations/SentrySessionTrackerTests.swift, Tests/SentryTests/SentryHubTests.swift, Tests/SentryTests/State/SentryHub+TestInit.h
The private property for SentryCrashWrapper is renamed to crashAdapter, because the type is
named SentryCrashAdapter.
Makes the code easier to read.
CI
=> ref: Rename CrashWrapper to CrashAdapter in Hub

CHANGELOG.md, Sources/Sentry/NSDate+SentryExtras.m, Tests/SentryTests/SentryInterfacesTests.m, Tests/SentryTests/SentryTests.m
Increase precision of iso8601 date formatter to millisecond
Fixes #857
Add more test cases.
=> fix: Increase precision of iso8601 date formatter

Sentry.xcodeproj/project.pbxproj, Tests/SentryTests/Integrations/SentryTestIntegration.h, Tests/SentryTests/Integrations/SentryTestIntegration.m, Tests/SentryTests/SentrySDKTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
Some parts of the SentrySDK were not covered by tests. Because this is the
main entry point for our SDK tests are now added.
`SentrySDK` is the main entry point of our SDK. It makes sense to add tests for it.
I added tests.
=> tests: Add tests for SentrySDK

Sentry.xcodeproj/xcshareddata/xcbaselines/63AA76641EB8CB2F00D153DE.xcbaseline/4487886E-B920-4AB1-99BD-1A9C5128C731.plist, Sources/Sentry/SentryDispatchQueueWrapper.m, Tests/SentryTests/SentrySDKTests.swift
Applying the fix from @tmm1 (thanks for identifying the bottle neck)
https://github.com/getsentry/sentry-cocoa/commit/d2e3ad7555f0415fbfdd091bc3a4ee39c17b8ac0
First stab at addressing #868
=> perf: Drop global dispatch queue (thanks @tmm1 )

Sources/Sentry/SentrySession.m
We used [NSNumber numberWithLong] to box an NSUInteger to an NSNumber. This can be
simplified by using boxed literals.
Simplify the code.
CI.
=> ref: Use boxed literals in SentrySession

CHANGELOG.md, Sources/Sentry/SentrySerialization.m, Sources/Sentry/SentrySession.m, Tests/SentryTests/Helper/SentrySerializationTests.swift, Tests/SentryTests/SentrySessionTests.swift
Calling SentrySession.initWithJsonObject with an invalid dictionary didn't set any values for some
properties, which are non-nullable. When calling serialize afterward this lead to a
NSInvalidArgumentException from [SentrySession serialize] due to nil object. This is fixed now,
by setting some default values.
Fixes GH-870
Unit tests and `SentrySessionGeneratorTests`.
=> fix: Crash in SentrySession.serialize

Sources/Sentry/include/SentryTransport.h
The comment for sendEvent in SentryTransport is out of date and can be removed
as SentryTransport is currently not public.
Remove unnecessary comments.
CI.
=> ref: Remove out of date comment in Transport

Samples/iOS-ObjectiveC/iOS-ObjectiveC/ViewController.m, Sources/Sentry/Public/SentryAttachment.h, Sources/Sentry/SentryAttachment.m
Rename all constructors in SentryAttachment from initPath to initWithPath. Stick to the Objective-C way. No effect on Swift.
I noticed this when writing the docs for Objective-C.
CI
Update the docs on the next alpha release.
=> ref: Rename initPath to initWithPath

CHANGELOG.md, Sources/Sentry/Public/SentryEnvelope.h, Sources/Sentry/Public/SentryOptions.h, Sources/Sentry/SentryEnvelope.m, Sources/Sentry/SentryHttpTransport.m, Sources/Sentry/SentryOptions.m, Tests/SentryTests/Networking/SentryHttpTransportTests.swift, Tests/SentryTests/Protocol/SentryEnvelopeTests.swift, Tests/SentryTests/SentryOptionsTest.m
Drop attachments that are larger than the specified maxAttachmentSize in SentryOptions.
We want to give the users of the SDK the possibility to drop large attachments.
Unit tests.
=> feat: Add maxAttachmentSize to SentryOptions

Sources/Sentry/SentryScope.m
In SentryScope.setFingerprint NSMutableArray is used to init a new array, but
the fingerprintArray is of type NSArray. Therefore we can change it to NSArray.
Using immutable types when possible.
CI
=> ref: Use NSArray for fingerprint on Scope

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryBreadcrumbTracker.m, Sources/Sentry/SentryHub.m, Sources/Sentry/SentryInstallation.m, Sources/Sentry/SentrySerialization.m
Including sentry-cocoa via the SPM prints shadow-ivar warnings, that are fixed now.
Furthermore, GCC_WARN_SHADOW is enabled to avoid shadow-ivar warnings.
This PR is based on https://github.com/getsentry/sentry-cocoa/pull/893.
GH-837
Adding sentry-cocoa to a Swift package to the hash of this commit like this: `.package(name: "Sentry", url: "https://github.com/getsentry/sentry-cocoa", .revision("d83582db32c15804f34a239297ff1d969df0c158"))` and building the package via `swift build` from the command line.
=> ref: Enable hidden local variables as warnings

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryBreadcrumbTracker.m, Sources/Sentry/SentryHub.m, Sources/Sentry/SentryInstallation.m, Sources/Sentry/SentrySerialization.m
We use `[self getClient]` to access the client in the hub. This is not needed and can be replaced by
accessing the instance variable directly via `_client`. This makes the code easier to read and also
slightly faster as we don't have to go through Objective-C method dispatch when accessing the
client via a property.
The Hub contains a few warnings for hidden local variables as described here https://github.com/getsentry/sentry-cocoa/issues/837. When trying to fix these warnings I saw that this can be fixed as well.
CI.
=> ref: Use instance variable in Hub to access Client

CHANGELOG.md, Sources/SentryCrash/Installations/SentryCrashInstallation.m, Sources/SentryCrash/Recording/SentryCrash.m, Sources/SentryCrash/Recording/Tools/NSError+SentrySimpleConstructor.h, Sources/SentryCrash/Recording/Tools/NSError+SentrySimpleConstructor.m, Sources/SentryCrash/Recording/Tools/SentryCrashJSONCodecObjC.m, Sources/SentryCrash/Reporting/Filters/SentryCrashReportFilterBasic.m, Tests/SentryTests/SentryCrash/NSError+SimpleConstructor_Tests.m, Tests/SentryTests/SentryTests.m
Rename the category SentrySimpleConstructor for  NSError that can conflict with other libraries using KSCrash.
It breaks people who use KSCrash on their own or as a transient dependency.
Unit tests.
=> fix: Duplicate symbol clash with KSCrash

CHANGELOG.md, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_AppState.c, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m
Fix clash with functions of KSCrash in SentryCrashMonitor_AppState.c and SentryCrashMonitor_System.m. Similar change as in https://github.com/kstenerud/KSCrash/commit/30fea9326e4eea76d6c737e78d0f523565bc9725.
This breaks people who use KSCrash on their own or as a transient dependency.
CI and smoke test on an emulator.
=> fix: Clash with KSCrash functions

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/Public/SentryHub.h, Sources/Sentry/SentryHub.m, Sources/Sentry/SentryLevelMapper.m, Sources/Sentry/SentrySerialization.m, Sources/Sentry/include/SentryLevelMapper.h, Sources/Sentry/include/SentrySerialization.h, Tests/SentryTests/Helper/SentryLevelMapperTests.swift, Tests/SentryTests/Helper/SentrySerializationTests.swift, Tests/SentryTests/SentryHubTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h, Tests/SentryTests/TestClient.swift
The SentryHub now increases the error count if an envelope is passed containing an event with
event.level error or higher. Ideally, we would check the mechanism and/or exception list, like the
Java and Python SDK do this, but this would require full deserialization of the event.
Fixes GH-861
Unit tests, before merging we still need to test it with React Native and Flutter.
Properly fix it like mentioned in GH-861
=> fix: Capture envelope updates session state

CHANGELOG.md, Sources/Sentry/SentrySessionTracker.m, Tests/SentryTests/Integrations/SentrySessionTrackerTests.swift, Tests/SentryTests/Integrations/TestNotificationCenter.swift
The Cocoa SDK didn't start a session after a hybrid app finished its initialization. That's because, in hybrid SDKs, we might initialize the Cocoa SDK after the hybrid engine is ready. The `SessionTracker` then misses the `didBecomeActive` notification from the OS and fails to start a session. To solve this, hybrid SDKs can post an internal notification with the name `SentryHybridSdkDidBecomeActive`. The `SessionTracker` starts a session if it receives such a notification.
Related to https://github.com/getsentry/sentry-dart/pull/274.
Fixes GH-912
=> fix: Sessions for Hybrid SDKs

Samples/iOS-ObjectiveC/iOS-ObjectiveC/ViewController.m, Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard, Samples/iOS-Swift/iOS-Swift/ViewController.swift, Samples/macOS-Swift/macOS-Swift/Base.lproj/Main.storyboard, Samples/macOS-Swift/macOS-Swift/ViewController.swift, Samples/tvOS-Swift/tvOS-Swift/ContentView.swift, Samples/watchOS-Swift/watchOS-Swift WatchKit Extension/ContentView.swift
Add captureTransaction to all sample apps.
We want to be able to test transactions on watchOS, iOS, macOS, and tvOS.
Simulators.
=> test: Add captureTransaction to sample apps

CHANGELOG.md, Sources/Sentry/Public/SentryOptions.h, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryOptions.m, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryOptionsTest.m
Add sendDefaultPii to SentryOptions. When enabled, the SDK sends personal identifiable along with
events. Currently, that only applies to the IP address of the user.
Fixes GH-910
Update the docs.
=> feat: Add sendDefaultPii to SentryOptions

Sources/Sentry/Public/SentryHub.h, Sources/Sentry/Public/SentrySDK.h
Improve code comments on methods for capturing transactions.
=> docs: Improve code comments on transactions

Tests/SentryTests/SentryCrash/SentryThreadInspectorTests.swift
The SentryThreadInspectorTests.testThreadNameIsNull was sometimes failing in CI. The
thread name was set to some weird characters as ȕ`\r\u{01}. This was because we used
an empty array to fill the buffer for the thread name and therefore accessed memory, which
we shouldn't. Now we use an array with all zeros as big as the buffer.
Failing tests.
=> test: Fix ThreadInspectorTests

.github/workflows/format-code.yml, .github/workflows/lint.yml, scripts/commit-formatted-code.sh
Replaced all non validated GitHub Actions by replicating the functionality
manually.
For uploading the Swift iOS sample app to TestFlight with https://github.com/getsentry/sentry-cocoa/pull/918, we added some secrets to the repo that we don't want to be exploited. By removing not validated GitHub Actions we make it harder to steal those secrets.
CI
=> ci: Replace not validated GitHub Actions

Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj, Samples/iOS-Swift/iOS-Swift/RandomErrors.swift, Samples/iOS-Swift/iOS-Swift/ViewController.swift
Add a do catch in `captureError` with randomly generated errors to make
the errors more realistic.
We want more realistic errors.
Simulator
=> test: Make captureError more realistic

CHANGELOG.md, Sources/Sentry/Public/SentrySession.h, Sources/Sentry/SentrySerialization.m, Sources/Sentry/SentrySession.m, Tests/SentryTests/Helper/SentryFileManagerTests.swift, Tests/SentryTests/Helper/SentrySerializationTests.swift, Tests/SentryTests/Integrations/SentryCrashIntegrationTests.swift, Tests/SentryTests/SentrySessionTests.swift
When the JSON contains a started that can't be converted to an NSDate the SDK sets
the _started to nil, which leads to a crash later as _started is nonnull. This is fixed now
by returning `nil` when the JSON passed to initWithJSONObject contains an error.
Fixes https://github.com/getsentry/sentry-cocoa/issues/937
Unit tests and SentrySessionGeneratorTests.
=> fix: Discard Sessions when JSON is faulty

CHANGELOG.md, Sources/Sentry/SentryClient.m, Tests/SentryTests/SentryClientTests.swift
Use the exception interface for NSErrors and SDK Fingerprinting to group NSErrors by domain and
code. So MyDomain 1 and MyDomain 2 are going to be two separate issues in Sentry.
See https://github.com/getsentry/sentry-cocoa/discussions/929
Unit tests and Simulator.
=> feat: Group NSError by domain and code

CHANGELOG.md, Sources/Sentry/SentryCrashStackEntryMapper.m, Tests/SentryTests/SentryCrash/SentryCrashStackEntryMapperTests.swift
The SDK marked almost all stack traces frames when capturing events on Simulators as inApp.
This is fixed now by changing the logic in SentryCrashStackEntryMapper.
Could fix https://github.com/getsentry/sentry-cocoa/issues/933.
Unit tests and simulators.
=> fix: Stacktrace inApp marking on Simulators

CHANGELOG.md, Sources/Sentry/Public/SentryEvent.h, Sources/Sentry/SentryEvent.m, Tests/SentryTests/Protocol/SentryEnvelopeTests.swift, Tests/SentryTests/Protocol/SentryEventTests.swift
The SentryEvent.message was marked as nonnullable. Actually, this property is optional.
Previously when initializing an Event, not setting a message and then accessing it in Swift
lead to a crash with bad access. This is fixed now by marking the property as nullable.
We don't want to crash.
Unit tests and CI.
=> fix: Mark SentryEvent.message as Nullable

CHANGELOG.md, Sources/Sentry/Public/SentryEvent.h, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryEvent.m, Tests/SentryTests/Protocol/SentryEventTests.swift, Tests/SentryTests/SentryClientTests.swift
Add an initializer initWithError and property error to SentryEvent. This change gives
our users the possibility to access the error in beforeSend.
When trying to write the docs for [SDK Fingerprinting](https://docs.sentry.io/platforms/java/data-management/event-grouping/sdk-fingerprinting/) for Cocoa, I realized that there is no proper way to access the error in `beforeSend`. The [Java](https://github.com/getsentry/sentry-java/blob/404ff7b0e84bb88324d7d41a6d3b7913d5d7f72c/sentry/src/main/java/io/sentry/SentryBaseEvent.java#L63) and [.NET](https://github.com/getsentry/sentry-dotnet/blob/6ce7f933f64bd517677b5e837d6c7e8cc37b4217/src/Sentry/SentryEvent.cs#L29) SDK have a similar property too on the SentryEvent.
Unit tests and with `beforeSend` in the sample projects.
=> feat: Add error to SentryEvent

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/Public/SentryHub.h, Sources/Sentry/Public/SentrySDK.h, Sources/Sentry/Public/SentrySpan.h, Sources/Sentry/Public/SentrySpanContext.h, Sources/Sentry/Public/SentryTransaction.h, Sources/Sentry/Public/SentryTransactionContext.h, Sources/Sentry/SentryHub.m, Sources/Sentry/SentrySDK.m, Sources/Sentry/SentrySpan.m, Sources/Sentry/SentrySpanContext.m, Sources/Sentry/SentrySpanId.m, Sources/Sentry/SentryTransaction.m, Sources/Sentry/SentryTransactionContext.m, Sources/Sentry/include/SentryTransaction+Private.h, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentrySpanContextTests.swift, Tests/SentryTests/SentrySpanIdTests.swift, Tests/SentryTests/SentrySpanTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h, Tests/SentryTests/SentryTransaction+Private.h, Tests/SentryTests/SentryTransactionTests.swift
Creating the SentrySpan class and allowing transactions to create child.
Requisite to the Performance API.
Unit tests
TBD
=> feat: Adding SentrySpan to performance monitoring.

CHANGELOG.md, Sources/Sentry/SentryMechanism.m, Tests/SentryTests/Protocol/SentryMechanismTests.swift, Tests/SentryTests/Protocol/TestData.swift
When serializing SentryMechanism the SDK didn't sanitize the data dictionary.
This is fixed now.
I stumbled across this in https://github.com/getsentry/sentry-cocoa/pull/946.
Unit tests.
=> fix: Sanitize SentryMechanism.data on serialize

.github/workflows/format-code.yml, Sources/Sentry/Public/SentryMechanism.h, scripts/commit-formatted-code.sh
The code formatting workflow was not able to commit formatted code,
because the Github Actions checks out in a detached HEAD state.
This is fixed now by fetching, creating a branch, and then pushing it.
We don't want this workflow to fail.
By pushing false formatted code.
=> ci: Fix code formatting

Sources/Sentry/SentryClient.m, Sources/Sentry/SentryFrameRemover.m, Sources/Sentry/SentryStacktraceBuilder.m, Sources/Sentry/include/SentryFrameRemover.h, Sources/Sentry/include/SentryStacktraceBuilder.h, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryCrash/SentryFrameRemoverTests.swift, Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift, Tests/SentryTests/SentryCrash/SentryThreadInspectorTests.swift
SentryFrameRemover had only one method that can be static. This is changed now
and simplifies some init methods.
Make the code simpler.
CI.
=> ref: Make SentryFrameRemover static

Sources/SentryCrash/Recording/Tools/SentryCrashCPU_arm64.c
UBSan detected an out-of-bounds read from machineContext.__ss.__x. The register that was previously shown as x29 in Sentry is in fact just the FP register. This commit removes the duplicate (and thus the out-of-bounds read that triggered UBSan).
Fixes #963
Ran it against my local Sentry instance, the stray register disappears and UBSan no longer reports errors:
=> fix: Redundant x29 GP register on arm64 and UBSan crash

Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
The bundle version string is not allowed to contain alpha, which was added by craft.
Removing the alpha fixes the Testflight upload.
Upload to Testflight is failing.
I didn't, but I'm confident that this is going to work.
Fix the bump version script that craft uses so this doesn't happen in the future.
=> fix: Testflight upload

Tests/SentryTests/Helper/SentryCurrentDateTests.swift, Tests/SentryTests/Helper/SentryFileManagerTests.swift, Tests/SentryTests/Integrations/SentryCrashIntegrationTests.swift, Tests/SentryTests/Integrations/SentrySessionTrackerTests.swift, Tests/SentryTests/Networking/SentryHttpTransportTests.swift, Tests/SentryTests/Networking/SentryTransportInitializerTests.swift, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryCrash/SentryCrashInstallationReporterTests.swift, Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift, Tests/SentryTests/SentryHubTests.swift, Tests/SentryTests/SentryNSURLRequestTests.swift, Tests/SentryTests/SentrySDKTests.swift, Tests/SentryTests/SentryScopeSwiftTests.swift, Tests/SentryTests/SentryTests.m, Tests/SentryTests/TestClient.swift, Tests/SentryTests/TestConstants.swift
Using a DSN per test case gives each test case a separate folder to store the envelopes,
reducing the chance of interference. This PR also contains a few minor fixes for other tests.
This is based on https://github.com/getsentry/sentry-cocoa/pull/968. 
Some tests as SentryClientTests or SentryHttpTransportTests are sometimes failing in CI.
CI and Xcode.
=> @philipphofmann test: DSN per TestCase

Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m, Samples/iOS-Swift/iOS-Swift/AppDelegate.swift, Samples/macOS-Swift/macOS-Swift/AppDelegate.swift, Samples/tvOS-Swift/tvOS-Swift/AppDelegate.swift, Samples/watchOS-Swift/watchOS-Swift WatchKit Extension/ExtensionDelegate.swift
attachStacktrace is enabled per default. No need to pass it.
Make the SDK init slimmer.
CI.
=> test: Remove attachStacktrace in SDK start

Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj, Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard, Samples/iOS-Swift/iOS-Swift/TraceTestViewController.swift, Samples/iOS-Swift/iOS-Swift/ViewController.swift, Sources/Sentry/SentryOptions.m, Tests/SentryTests/SentryOptionsTest.m
Added some transaction tests in Swift sample app. 
Requested in issue #970.
Include more Performance API samples as new features are being released.
=> feat: Transaction in Sample App

Gemfile
Dependabot can't read the plugins path as fastlane specified it in the Gemfile. 
Using the path directly in eval_gemfile should fix the issue, see https://github.com/dependabot/feedback/issues/945#issuecomment-638235801.
Fixes GH-981
Let's see if Dependabot again opens up an issue.
=> build: Fix Gemfile for Dependabot

fastlane/Fastfile
Using single quotes for the password allows special characters except for a single quote.
We want to allow special characters for the keychain password.
Running it locally.
=> ci: Use single quotes for keychain password

.github/workflows/buildandtest.yml, Samples/iOS-ObjectiveC/iOS-ObjectiveC/ViewController.m
When building the samples failed in CI the CI job didn't fail. This is fixed now.
=> ci: Fix let building samples fail CI

Sources/Sentry/SentryDispatchQueueWrapper.m, Sources/Sentry/SentryTransportFactory.m, Sources/Sentry/include/SentryDispatchQueueWrapper.h
Add a 2nd constructor to SentryDispatchQueueWrapper to allow passing
the name and attributes for the dispatch queue. This allows us to create different
dispatch queues with different strategies and priorities.
We don't want to only use on dispatch queue across the whole SDK. We don't want to use the same dispatch queue for sending envelopes to Sentry and updating the app state in the OOM integration. Updating the app state should run on a higher priority.
CI and simulator.
=> ref: Make DispatchQueueWrapper configurable

Sources/Sentry/SentryCrashIntegration.m, Tests/SentryTests/Integrations/SentryCrashIntegration+TestInit.h, Tests/SentryTests/Integrations/SentryCrashIntegrationTests.swift, Tests/SentryTests/Integrations/SentrySessionGeneratorTests.swift
Rename parameter crashWrapper to crashAdapter as the name of the
class ins crashAdapter.
We want to have consistent naming.
CI.
=> ref: Fix naming for test init of CrashIntegration

Tests/SentryTests/Integrations/SentrySessionGeneratorTests.swift
When leaving the `SessionGeneratorTests` on by accident, the `SessionTrackerTests` started to fail.
This is fixed now by adding a tearDown to SessionGeneratorTests.
When leaving the `SessionGeneratorTests` on by accident, the `SessionTrackerTests` start to fail.
CI.
=> test: TearDown for SessionGeneratorTests

Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
Enable MacCatalyst for iOS-Swift, so we can test MacCatalyst.
Helps us to reproduce https://github.com/getsentry/sentry-cocoa/issues/1009.
Locally on my Mac.
=> test: Enable Mac Catalyst for iOS-Swift

CHANGELOG.md, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryOutOfMemoryTracker.m, Sources/Sentry/include/SentryOutOfMemoryTracker.h, Tests/SentryTests/Integrations/SentryOutOfMemoryTrackerTests.swift, Tests/SentryTests/Protocol/TestData.swift
The type of the mechanism and the exception were not set according to the Sentry standard.
This is fixed now.
https://github.com/getsentry/sentry-cocoa/pull/1001#discussion_r599165629
Unit tests.
=> fix: OutOfMemory exception type

CHANGELOG.md, Sources/Sentry/SentryOptions.m, Tests/SentryTests/SentryOptionsTest.m
When passing for example self to maxBreadcrumbs when using the dict initialiser
for SentryOptions the SDK crashed. This is fixed now by checking if maxBreadcrumbs
is a NSNumber.
We don't want the SDK to crash.
=> fix: Crash when passing garbage to maxBreadcrumbs

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/Public/SentrySDK.h, Sources/Sentry/SentryBreadcrumbTracker.m, Sources/Sentry/SentryCrashIntegration.m, Sources/Sentry/SentryHub.m, Sources/Sentry/SentryNSURLRequest.m, Sources/Sentry/SentryOutOfMemoryLogic.m, Sources/Sentry/SentryRequestOperation.m, Sources/Sentry/SentrySDK.m, Sources/Sentry/SentrySessionCrashedHandler.m, Sources/Sentry/SentrySessionTracker.m, Sources/Sentry/include/SentrySDK+Private.h, Tests/SentryTests/SentrySDK+Tests.h, Tests/SentryTests/SentryTests-Bridging-Header.h, Tests/SentryTests/SentryTests.m
Remove SentrySDK.currentHub and SentrySDK.setCurrentHub, which are only
needed internally and by hybrid SDKs. They are not intended to be public API.
This breaks Hybrid SDKs, but we are going to fix this with adding `captureEnvelope` and `storeEnvelope` to `SentrySDK.m` but not in the header. The hybrid SDKs can create a category to make these two methods accessible. We use this pattern for the test initializers already.
See https://github.com/getsentry/develop/issues/248#issuecomment-765206789
CI.
=> ref: Remove currentHub from SentrySDK

CHANGELOG.md, Sources/Sentry/Public/SentryClient.h, Sources/Sentry/SentrySDK.m, Sources/Sentry/include/SentryClient+Private.h, Tests/SentryTests/SentrySDK+Tests.h, Tests/SentryTests/SentrySDKTests.swift, Tests/SentryTests/TestClient.swift
Add captureEnvelope and storeEnvelope to SentrySDK.m, so hybrid SDKs
have a nicer API to interact. The hybrid SDKs can create a category to make
these two methods accessible. We use this pattern for the test initializers
already. Make SentryClient.storeEnvelope private.
https://github.com/getsentry/develop/issues/248#issuecomment-765206789
Units tests.
=> ref: Improve envelope API for Hybrid SDKs

CHANGELOG.md, Sources/Sentry/Public/SentryHub.h, Sources/Sentry/Public/SentrySDK.h, Sources/Sentry/SentryHub.m, Sources/Sentry/SentrySDK.m, Tests/SentryTests/SentrySDKTests.swift
Add SentrySDK.startSession and SentrySDK.endSession to provide an
easy to use API for manual session tracking.
https://github.com/getsentry/develop/issues/248
Unit tests.
=> feat: Add start and endSession to SentrySDK

CHANGELOG.md, Sources/Sentry/Public/SentryHub.h, Sources/Sentry/SentrySessionTracker.m, Sources/Sentry/include/SentryHub+Private.h
Make Sentry.HubcloseCachedSessionWithTimestamp private as it is not intended
to be public API and is reserved for internal use only.
We don't want to have methods that are only supposed to be used internally to be public.
=> ref: Make closeCachedSessionWithTimestamp private

Sources/Sentry/Public/SentrySDK.h, Sources/Sentry/SentrySDK.m
The SentrySDK.crash method is the first one defined in the header. The
first functions in a class are usually the initializers. This is fixed now by
moving the method down.
Cleaning up the public header files for 7.0.0 GA.
CI.
=> ref: Move SentrySDK.crash method to bottom

CHANGELOG.md, Sources/Sentry/Public/SentryHub.h, Sources/Sentry/SentryHub.m
Removed deprecated SentryHub.getScope. Use SentryHub.scope instead.
We want to remove deprecated functions before GA 7.0.0
CI.
=> ref: Remove deprecated SentryHub.getScope

CHANGELOG.md, Sources/Sentry/Public/SentryException.h, Sources/Sentry/SentryCrashReportConverter.m, Sources/Sentry/SentryException.m, Tests/SentryTests/Protocol/SentryExceptionTests.swift, Tests/SentryTests/Protocol/TestData.swift, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryInterfacesTests.m, Tests/SentryTests/SentryKSCrashReportConverterTests.m
Replace SentryException.thread with threadId and stacktrace. This aligns
SentryException with the exception interface, see
https://develop.sentry.dev/sdk/event-payloads/exception/.
We want to align the SDK with our spec.
CI and simulator.
=> ref: Align SentryException with unified API

CHANGELOG.md, Sources/Sentry/SentryBreadcrumbTracker.m
We don't need to allocate a dictionary as SentryBreadcrumb.data is nullable.
I came across this when investigating a bug for a customer.
Simulator.
=> perf: Avoid allocating dict in BreadcrumbTracker

Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Issue tracking addressing this: #1031
=> Ignore flaky test in SentryHttpTransportTests.swift

Sources/Sentry/SentryQueueableRequestManager.m, Sources/Sentry/include/SentryRequestManager.h, Tests/SentryTests/Networking/TestRequestManager.swift
Remove not public unused function cancelAllOperations in SentryRequestManager.
We don't want to maintain unused code.
CI.
=> ref: Remove not used cancelAllOperations

Tests/SentryTests/Networking/SentryHttpTransportTests.swift
The rate limit in testRateLimitGetsActiveWhileSendAllEvents did
never apply. This is fixed now by setting the rate limit for all
envelopes and correcting the number of envelopes in the assert.
I found this problem while investigating flakey tests in SentryHttpTransportTests.
CI.
=> test: Fix a test in HttpTransportTests

Sources/Sentry/SentryTracer.m
Every new span child created need a reference to SentryTracer to be able to also create child.
To fix a problem.
Unit test.
=> fix: Pass SentryTracer to span child.

Sources/Sentry/Public/SentryIntegrationProtocol.h, Sources/Sentry/Public/SentrySDK.h, Sources/Sentry/SentryAutoBreadcrumbTrackingIntegration.m, Sources/Sentry/SentryAutoSessionTrackingIntegration.m, Sources/Sentry/SentryBreadcrumbTracker.m, Sources/Sentry/SentryCrashIntegration.m, Sources/Sentry/SentryOutOfMemoryTrackingIntegration.m, Sources/Sentry/SentrySDK.m, Sources/Sentry/SentrySystemEventsBreadcrumbs.m, Sources/Sentry/include/SentryBreadcrumbTracker.h, Sources/Sentry/include/SentrySystemEventsBreadcrumbs.h, Sources/SentryCrash/Recording/Tools/SentryHook.c, Sources/SentryCrash/Recording/Tools/SentryHook.h
This disables the Client and unsets the Hub.
It also tries to uninstall all the integrations, however some do not support
*really* uninstalling them, so they are being disabled instead.
It should be possible to completely disable the SDK in such cases where there is no user consent.
Inserted a `[SentrySDK close]` after the init and manually tested that none of the event methods do anything.
**However**, I noticed that a (automatic) Session is still being closed/sent.
=> feat: Add close method to SDK

CHANGELOG.md, Sources/Sentry/Public/SentryHub.h, Sources/Sentry/Public/SentrySDK.h, Sources/Sentry/Public/SentrySamplingContext.h, Sources/Sentry/SentryHub.m, Sources/Sentry/SentrySDK.m, Sources/Sentry/SentrySamplingContext.m
Make method overloads with customSamplingContext nonnullable for the sake
of null safety and API consistency.
=> ref: Make calls to customSamplingContext nonnull

Sources/Sentry/include/Random.h
Add a comment that `[Random nextNumber]` returns a number between 0.0 and 1.0. Currently, you have to check the implementation to find out.
`[Random nextNumber]` doesn't by its name what it is doing. You have to look into the implementation to find out.
=> docs: Add code docs for Random.nextNumber

CHANGELOG.md, Sources/Sentry/SentryTracer.m, Tests/SentryTests/SentrySpanTests.swift
Removeing the unfinished child spans from a transaction when capturing the transaction.
Issue #1057 
Unit Test
=> ref: Discard unfinished spans when capturing transaction

CHANGELOG.md, Sources/Sentry/SentryOptions.m, Tests/SentryTests/SentryOptionsTest.m
The default value of tracesSampleRate was 0 instead of @0.
See description.
Unit tests.
=> fix: SentryOptions.tracesSampleRate default value

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryRandom.m, Sources/Sentry/TracesSampler.m, Sources/Sentry/include/SentryRandom.h, Sources/Sentry/include/SentrySpan.h, Sources/Sentry/include/TracesSampler.h, Tests/SentryTests/SentryTests-Bridging-Header.h, Tests/SentryTests/TestUtils/TestRandom.swift
Prefix Random with Sentry to avoid namespace clashes.
When bumping sentry-cocoa to 7.0.0-beta.0 in sentry-react-native the CI fails https://github.com/getsentry/sentry-react-native/pull/1459/checks?check_run_id=2408810984.
CI
=> ref: Rename Random to SentryRandom

Tests/SentryTests/Categories/SentryUnsignedLongLongValueTest.m
Trying to address the breakage when building in Release mode:
https://github.com/getsentry/sentry-cocoa/pull/1076/checks?check_run_id=2415603793
=> fix: long string format test

.github/workflows/buildandtest.yml, CHANGELOG.md, Tests/SentryTests/Categories/SentryUnsignedLongLongValueTest.m
Does this mean we've been shipping Debug builds?
Building in Release was failing to compile due to:
```
❌  /Users/runner/work/sentry-cocoa/sentry-cocoa/Tests/SentryTests/Categories/SentryUnsignedLongLongValueTest.m:17:69: format specifies type 'long' but the argument has type 'long long' [-Werror,-Wformat]
NSString *longLongMaxValue = [NSString stringWithFormat:@"%ld", 0x7FFFFFFFFFFFFFFF];
~~~   ^~~~~~~~~~~~~~~~~~
❌  /Users/runner/work/sentry-cocoa/sentry-cocoa/Tests/SentryTests/Categories/SentryUnsignedLongLongValueTest.m:20:77: format specifies type 'long' but the argument has type 'unsigned long long' [-Werror,-Wformat]
NSString *negativelongLongMaxValue = [NSString stringWithFormat:@"%ld", -0x8000000000000000];
~~~   ^~~~~~~~~~~~~~~~~~~
❌ …
```
=> ci builds release mode

CHANGELOG.md, Sources/Sentry/SentryCrashIntegration.m, Sources/SentryCrash/Recording/Tools/SentryHook.c
Due to some problems with arm64 devices, we disable this feature until we find out how to fix them.
We don't want this feature to block 7.0.0 GA. The plan is to add a flag to SentryOptions for enabling
and disabling this feature in the future, see #1086.
See description.
Unit tests and on a real device.
=> ref: Disable Async Stacktraces

Tests/SentryTests/SentryInterfacesTests.m
SentryInterfacesTests contained a duplicate key in a dictionary	literal. This is fixed now.
Building tests with Xcode 14.5 results in a build error.
Building it locally.
=> tests: Fix build error for Xcode 14.5

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryHub.m, Sources/Sentry/SentryTracesSampler.m, Sources/Sentry/include/SentryTracesSampler.h
Rename TracesSampler to SentryTracesSampler to avoid namespace
clashes.
We want to avoid namespace clashes.
CI.
=> ref: Prefix TracesSampler with Sentry

Sources/Sentry/SentrySession.m
Log a warning when serializing and no string is found for SentrySessionStatus.
Saw the TODO in the code when checking some issue in the serialization of SentrySession.
CI.
=> ref: Log warning for serializing SentrySession

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/Public/Sentry.h
Users get an error when integrating Sentry via SPM that the umbrella header
for module 'Sentry' does not include header 'SentryMechanismMeta.h'. This is
fixed now.
Fixes GH-1101
Integrating the commit hash from this PR into a SPM sample project. I'm going to add a sample project to the SDK and build it in CI to avoid such issues in the future.
Add a SPM sample project.
=> fix: Add SentryMechanismMeta to Sentry.h

Sources/Sentry/Public/SentryOptions.h
We don't want typos in our code docs.
CI
=> docs: Fix typo for enableOutOfMemoryTracking

Sources/Sentry/Public/SentryHub.h, Sources/Sentry/Public/SentrySDK.h
There was an incorrect self-reference to `endSession` in the in-line documentation.
Makes the documentation consistent with its intention.
Verified that the correct function is referenced.
=> docs: Replace incorrect function reference

CHANGELOG.md, Samples/iOS-Swift/iOS-Swift/ViewController.swift, Sources/Sentry/SentrySpanContext.m, Tests/SentryTests/SentrySpanContextTests.swift
The serialization of the description of a span was missing. When setting
a description to a span the SDK didn't send it to Sentry. This is fixed now.
We want the span description to show up in Sentry like this
Unit tests and Simulator.
=> fix: Serialization of span description

CHANGELOG.md, Sources/Sentry/SentryPerformanceTracker.m, Sources/Sentry/SentryUIPerformanceTracker.m, Sources/Sentry/include/SentryPerformanceTracker.h
The performance tracker used the name for the operation. This is fixed
now by using both operation and description.
**Before**
Please ignore the app start spans
**After**
Sending transactions to Sentry.
=> fix: Set description for performance tracker spans

CHANGELOG.md, Package.swift
Xcode 13 now shows issues with packages in the issue navigator.
A few issues popped up for this SDK, namely that there is are invalid excludes in the Package.swift, this PR removes them.
This removes warnings from the Xcode 13 issue navigator
N/A
=> Remove invalid excludes from Package.swift

Sources/Sentry/Public/SentryOptions.h, Sources/Sentry/SentryAppStartTrackingIntegration.m, Sources/Sentry/SentryFramesTrackingIntegration.m, Sources/Sentry/SentryOptions.m, Tests/SentryTests/Integrations/SentryAppStartTrackingIntegrationTests.swift, Tests/SentryTests/Integrations/SentryFramesTrackingIntegrationTests.swift, Tests/SentryTests/SentryOptionsTest.m
Remove enableAppStartMeasuring and enableFrameRenderMeasuring. Check
enableAutoUIPerformanceTracking and isTracingEnabled instead to start
SentryAppStartTrackingIntegration and SentryAppStartTrackingIntegration.
https://github.com/getsentry/sentry-docs/pull/3712#discussion_r650949126
Unit tests.
=> ref: Enabling Auto UI Performance

.github/workflows/buildandtest.yml, CHANGELOG.md, Makefile
Since Carthage 0.38.0 we can support XCFrameworks by creating separate
.framework.zip and .xcframework.zip archives.
We want to support XCFrameworks with Carthage which is possible since [Carthage 0.38.0](https://github.com/Carthage/Carthage/releases/tag/0.38.0).
Fixes GH-945
I tested it locally by using a Carthage.json to link to the binary, like described here https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification.
=> feat: Support XCFramework for Carthage

Sources/Sentry/SentrySDK.m, Sources/Sentry/include/SentrySDK+Private.h, Tests/SentryTests/SentrySDKTests.swift
Added an internal method to SentrySDK that return the options used to initialize the SDK.
Options are required in many integrations across de SDK, every time we need to access options in the client from hub from SentrySDK.
Accessing options from a method in SentrySDK keeps things easier to maintain.
Unit Test
=> ref: Making options available in SentrySDK

.github/workflows/buildandtest.yml
The job for validating the Swift Package Manager failed sometimes
because it was using the pre-merge commit id instead of the commit ID
of the PR. This is fixed now.
See description.
CI.
=> ci: Fix Validate SPM

.github/workflows/buildandtest.yml
The validation for SPM packages didn't work on the master branch. This is fixed now.
See description
Running it in CI on this branch.
=> ci: Fix SPM validation for branches

.github/workflows/testflight.yml, Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj, Samples/iOS-Swift/iOS-Swift/AppDelegate.swift, Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard, Samples/iOS-Swift/iOS-Swift/DSNStorage.swift, Samples/iOS-Swift/iOS-Swift/ViewController.swift
Add a text field to be able to change the DSN. A restart of the app is required
to make the adjusted DSN effective.
For testing purposes, we want to be able to change the DSN after the app is built. 
With the simulator.
=> test: Make DSN changeable for iOS-Swift

Tests/SentryTests/Integrations/SentryCrashIntegrationTests.swift, Tests/SentryTests/SentryCrash/SentryCrashInstallationReporterTests.swift, Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift, Tests/SentryTests/SentrySDKTests.swift, Tests/SentryTests/SentrySwiftTests.swift
We should close the SDK in tests after starting it to leave
the test in a clean state.
=> test: Close SDK after starting it

Tests/SentryTests/SentryCrash/SentryThreadInspectorTests.swift
testLongThreadName was failing on MacBook Air with M1 chip.
This is fixed now.
=> test: Fix testLongThreadName

CHANGELOG.md, Sources/Sentry/SentryNetworkTracker.m, Tests/SentryTests/Integrations/SentryNetworkTrackerTests.swift
Adding concurrent tests for SentryNetworkTracker revealed some race
conditions that are now fixed.
We don't want to have race conditions in SentryNewtorkTracker.
=> fix: Race Conditions in NetworkTracker

Samples/iOS-Swift/iOS-Swift/TraceTestViewController.swift
With auto performance tracking we don't have to manually create transactions
and spans anymore to instrument a view controller.
=> test: Clean up TraceTestViewController

CHANGELOG.md, Sources/Sentry/SentrySpan.m, Sources/Sentry/SentrySpanContext.m, Tests/SentryTests/SentrySpanContextTests.swift, Tests/SentryTests/SentrySpanTests.swift
Only add tags and data if they are not empty when serializing the span.
Fixes GH-1219
Unit tests.
=> fix: Remove tags and data if empty for Span

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Tests/SentryTests/Integrations/URLSessionTaskMock.h, Tests/SentryTests/Integrations/URLSessionTaskMock.m, Tests/SentryTests/Networking/SentryHTTPInterceptorTests.swift, Tests/SentryTests/Networking/TestURLSession.h, Tests/SentryTests/Networking/TestURLSession.m, Tests/SentryTests/SentryTests-Bridging-Header.h
Fixed SentryHTTPInterceptorTests to work for MacCatalyst.
Test should work on as many platforms as possible.
Fixes GH-1238 
Unit tests
=> test: Make SentryHTTPInterceptorTests works for MacCatalyst

Sources/Sentry/Public/SentryHub.h, Sources/Sentry/Public/SentrySDK.h
The description for the param bindToScope contained a typo. This is fixed
now.
We don't want to have typos in our code docs.
CI.
=> docs: Fix typo for bindToScope

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/Public/PrivateSentrySDKOnly.h, Sources/Sentry/Public/SentryScreenFrames.h, Sources/Sentry/SentryFramesTracker.m, Sources/Sentry/SentryHybridSKdsOnly.m, Sources/Sentry/SentryScreenFrames.m, Sources/Sentry/SentryTracer.m, Sources/Sentry/include/SentryFramesTracker.h, Tests/SentryTests/ClearTestState.swift, Tests/SentryTests/Integrations/SentryFramesTrackerTests.swift, Tests/SentryTests/Integrations/TestDisplayLinkWrapper.swift, Tests/SentryTests/Performance/SentryTracerTests.swift, Tests/SentryTests/PrivateSentrySDKOnlyTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
Expose a method for HybridSDKs to get the current slow, frozen and total frames.
Hybrid SDKs want to add the frame rates to transactions.
CI and unit tests.
=> feat: Expose tracked screen frames

CHANGELOG.md, Sources/Sentry/SentryPerformanceTracker.m, Sources/Sentry/SentryUIViewControllerPerformanceTracker.m, Tests/SentryTests/Integrations/SentryPerformanceTrackerTests.swift, Tests/SentryTests/Integrations/SentryUIPerformanceTrackerTests.swift
The auto performance instrumentation was sometimes not calling the original
method of the swizzled UIViewController, which lead to crashes. This is fixed now,
by always calling the callback for every swizzled method.
A customer reported getting crashes from Sentry when upgrading to 7.2.0, which they didn't have in 7.1.4.
Unit tests.
=> fix: Callback issue for auto performance

CHANGELOG.md, Samples/iOS-Swift/iOS-Swift/NibViewController.swift, Sources/Sentry/SentryUIViewControllerPerformanceTracker.m, Sources/Sentry/SentryUIViewControllerSwizziling.m, Tests/SentryTests/Integrations/SentryUIPerformanceTrackerTests.swift
The SDK always swizzled the loadView method of an implementation of UIViewController.
When using an UIViewController with a nib, UIKit only loads the nib if the loadView method
is not overridden. Our swizzling confused the UIKit, and therefore, it didn't load the nib
leading to an empty view and then to a crash. This is fixed now by not swizzling
UIViewControllers with a nib file if they don't implement loadView.
UIViewController with nibs crashed.
With the simulator.
=> fix: Crash when swizzling Nib UIViewController

CHANGELOG.md, Samples/macOS-SPM-CommandLine/Package.swift, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/Public/Sentry.h
The build failed for users including the SDK via SPM. The CI should check such errors, but
it didn't treat warnings as errors. This is fixed now by treating warnings as errors and including
the missing header file in the umbrella header.
Fixes GH-1283
I checked that CI fails with the current version https://github.com/getsentry/sentry-cocoa/runs/3421733871?check_suite_focus=true. Now CI passes again.
=> fix: Build failure for SPM

.github/workflows/buildandtest.yml, .github/workflows/testflight.yml, Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj, fastlane/Fastfile
The signing of the iOS-Swift sample app failed. This is fixed
now by reverting some changes. Furthermore, the CI now builds
a release build of iOS-Swift on every PR to avoid such failures
in the future before merging the PR.
The Testflight upload was failing.
Validating it on this branch https://github.com/getsentry/sentry-cocoa/actions/runs/1173284912
=> ci: Fix Testflight Upload

CHANGELOG.md, Sources/Sentry/SentryNetworkTracker.m, Tests/SentryTests/Integrations/SentryNetworkTrackerTests.swift, Tests/SentryTests/Integrations/URLSessionTaskMock.h, Tests/SentryTests/Integrations/URLSessionTaskMock.m
Moved the URLSessionTask support check to the beginning of the interceptor method, now we don't try to retrieve any property before knowing if sentry supports that type of task.
Some type of tasks such as AVAggregateAssetDownloadTask throw an exception when currentRequest is accessed. 
Fixes #1293 
Unit test
=> fix: Apps crash when using a URLSessionTask subclass with currentRequest unavailable

CHANGELOG.md, Sources/Sentry/SentryNetworkSwizzling.m
iOS 13 doesn't have a method for HTTPAdditionalHeaders. Instead, it only
has a property. Therefore, the swizzling crashes on iOS 13. This is fixed now
by checking if NSURLSessionConfiguration has a method HTTPAdditionalHeaders.
The downside is that we don't add a trace header on iOS 13 anymore. This
is better than crashing though.
I will add a test matrix to run the tests on older iOS versions soon.
Fixes GH-1296
Running the tests on an iOS 13 simulator.
=> fix: Swizzling crash on iOS 13

CHANGELOG.md, Makefile
This fixes the zip command to use ditto which mimics Finder's zip which preserves things better.
While trying to use the Sentry.xcframework.zip in releases, I ran into issues getting it embedded & signed possibly due to framework symlinks not being present. (We don't use carthage but just the XCF directly)
Put it in place for our project, embed & sign succeeded now unlike before where there was a warning about Current not being a symlink.
=> fix: XCF zip creation clobbered symlinks

CHANGELOG.md, Sources/Sentry/SentryNetworkSwizzling.m, Tests/SentryTests/Integrations/SentryNetworkTrackerIntegrationTests.swift
Remove support for trace headers below iOS 14.0, because we need to swizzle
a private class, which brings a risk of being rejected from Apple when submitting
to the App store.
This PR is basically a revert from https://github.com/getsentry/sentry-cocoa/pull/1302. I modified the comments a bit though.
We don't want apps to be rejected using private APIs.
Clarify in docs, that trace headers are only supported above iOS 14.
=> fix: Remove Trace Headers below iOS 14.0

CHANGELOG.md, Samples/iOS-Swift/iOS-Swift/AppDelegate.swift, Sources/Sentry/SentryHub.m, Sources/Sentry/SentryPerformanceTracker.m, Sources/Sentry/SentryTracer.m, Sources/Sentry/SentryTransaction.m, Sources/Sentry/include/SentryHub+Private.h, Sources/Sentry/include/SentryTransaction.h, Tests/SentryTests/Integrations/SentryPerformanceTrackerTests.swift, Tests/SentryTests/Performance/SentryTracerTests.swift, Tests/SentryTests/SentrySpanTests.swift
Fixed SentryHub to check the spanContext `sampled` value.
Every span capture should respect tracesSampleRate 
Fixes #1314 
Unit tests
=> fix: SentryHub not checking spanContext sampled value

CHANGELOG.md, Sources/Sentry/SentryUIViewControllerSwizziling.m, Tests/SentryTests/Integrations/SentryUIViewControllerSwizzlingTests.m
Fixed a bug trying to get the image name from a class that does not have one.
Fixes #1331 
Unit test
=> fix: Trying to swizzle a class without a library name

.github/workflows/buildandtest.yml, .github/workflows/testflight.yml
actions/setup-ruby is deprecated and needs to be replaced with
ruby/setup-ruby, see https://github.com/actions/setup-ruby.
=> ci: Replace deprecated Setup Ruby

CHANGELOG.md, Sentry.xcodeproj/xcshareddata/xcbaselines/63AA76641EB8CB2F00D153DE.xcbaseline/4487886E-B920-4AB1-99BD-1A9C5128C731.plist, Sources/Sentry/include/SentrySpan.h, Tests/SentryTests/SentrySDKTests.swift
Creating multiple transactions with spans leads to an increased number
of performance objects that the ARC never deallocates. This problem
is fixed now by breaking a strong reference cycle between SentryTracer
and SentrySpan.
Fixes GH-1351
Unit tests and debug memory graph in Xcode.
=> fix: Memory Leak for Span

CHANGELOG.md, Sources/Sentry/SentryNetworkTracker.m, Tests/SentryTests/Integrations/SentryNetworkTrackerIntegrationTests.swift, Tests/SentryTests/Integrations/SentryNetworkTrackerTests.swift
The HTTP instrumentation in SentryNetworkTracker leads to EXC_BAD_ACCESS.
This problem could be due to not correctly removing the KVO observer in
SentryNetworkTracker. Other open-source projects had similar bugs due to
using KVO, which they fixed using swizzling instead. As swizzling doesn't work
for our current solution and removing KVO would be a lot of effort, this PR is the
best shot effort for fixing the crashes by removing the observer issue.
Fixes GH-1328
Unit tests
=> fix: HTTP instrumentation KVO crash

Sources/Sentry/SentrySwizzle.m
The dictionaries and sets in SentrySwizzle didn't have the types
specified, which makes the code harder to read. This is fixed now
by adding the explicit types.
This change makes the code easier to understand.
CI.
=> ref: Specify dict and set types for SentrySwizzle

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentrySpan.m, Sources/Sentry/SentryTracer.m, Sources/Sentry/include/SentryTracer.h, Tests/SentryTests/Performance/SentryTracerObjCTests.m, Tests/SentryTests/Performance/SentryTracerTests.swift
The tracer observes when one of its child spans finishes when waitForChildren
is enabled. A prior fix for memory leaks GH-1352 led to crashes when watching
the child spans with KVO. This problem is fixed now by replacing KVO with a
simple method call from span to tracer when the span finishes.
Fixes GH-1358
Unit tests and on iPhone.
=> fix: Crash When Observing Span Finished

CHANGELOG.md, Sources/Sentry/SentryOptions.m, Tests/SentryTests/SentryOptionsTest.m
When initializing the SentryOptions with a dictionary, you can pass in a different type
for a property than expected. The SentryOptions had some checks validating if the
types from the dictionary match the actual type of the property. Anyways, the logic
missed a few edge cases as NSNull or didn't check if callbacks are blocks. This is
fixed now by checking if all properties are not NSNull and if callbacks are of type block.
Fixes GH-1441
Unit tests
=> fix: SentryOptions initWithDict type errors

Sources/Sentry/SentryHttpTransport.m
The todos in SentryHttpTransport are out of date and don't make
any sense. Hence, they can be removed.
=> ref: Remove not needed todos in HttpTransport

.sauce/config.yml
When multiple tests for SauceLab run in parallel they often time out.
This is fixed now by increasing the timeout to 20m.
=> ci: Increase SauceLabs timeout

Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Some tests of SentryHttpTransportTests are a bit flaky. Maybe we can fix them
by calling waitForAllRequests in tearDown.
=> test: waitForRequests in Transport tearDown

Samples/iOS-SwiftUI/iOS-SwiftUI.xcodeproj/xcshareddata/xcschemes/iOS-SwiftUI.xcscheme
The iOS-SwiftUI.xcscheme was missing. This is fixed now by adding it.
=> test: Add iOS-SwiftUI XCScheme

.github/workflows/test.yml, Samples/watchOS-Swift/watchOS-Swift.xcodeproj/xcshareddata/xcschemes/watchOS-Swift WatchKit App.xcscheme, Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerIntegrationTests.swift, test-server/Sources/App/routes.swift
Modify test in SentryNetworkTrackerIntegrationTests to validate that the SDK creates a span
for a simple GET request to the test server and adds the sentry trace header.
Fixes GH-1458
=> test: Span and Trace Header for Get Request

CHANGELOG.md, Sources/Sentry/SentryNetworkTracker.m, Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerTests.swift
Added a check to determine whether the SDK support the task passed to `SentryNetworkTracker` `urlSessionTask:setState:`.
When an app uses AVAggregateAssetDownloadTask, it crashes.
We need to ignore this kind of task and other non supported tasks
Unit test
=> fix: Check task support on `setState:` 

CHANGELOG.md, Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj, Samples/iOS-Swift/iOS13-Swift/Base.lproj/Main.storyboard
The iOS13-Swift sample share some classes with or main sample.
Every time a new file is added to iOS-Swift sample we should add it to iOS13 as well if needed.
Fix #1519 
Building the sample
=> fix: iOS13-Swift build

.github/workflows/test.yml
Use Package.resolved as cache key instead of whole
folder.
Fixes GH-1528
=> ci: Fix Cache for Test Server

Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m
No need to instantiate an `NSNumber` and extract the unsigned integer value back out of it, we can just use the `UL` suffix on an integer literal (although even that is unnecessary in this case since, the magnitude is so small).
=> test: Use integer literal in example code

Makefile
Don't try to format files in `.build` or `libs` folders.
=> build: Ignore .build and libs for clang-format

CHANGELOG.md, Sources/Sentry/SentryCrashIntegration.m, Sources/Sentry/include/SentryScope+Private.h, Tests/SentryTests/Integrations/SentryCrash/SentryCrashIntegrationTests.swift, Tests/SentryTests/Integrations/TestNotificationCenter.swift
Send the current locale with events. The SDK puts the locale into the device
context of the event.
Fixes GH-1438
=> feat: Send Locale with Events

.github/workflows/build.yml
Default is to warn and one must open the action details to spot that.
Example: A build that was successful, now fails with:
=> chore(ci): break if missing artifact

.github/workflows/integration-tests.yml
Some tests of Alamofire are flaky even when not adding Sentry to it. Therefore, we disable these tests to make the test suite more stable.
Fixes GH-1565
=> ci: Skip Flaky Alamofire Tests

Samples/iOS-Swift/iOS-Swift/Tools/UIAssert.swift, Samples/iOS-Swift/iOS-Swift/ViewControllers/TraceTestViewController.swift, Samples/watchOS-Swift/watchOS-Swift.xcodeproj/xcshareddata/xcschemes/watchOS-Swift WatchKit App.xcscheme
Some UI tests are flaky. Mainly the ones that verify the information on the transaction.
In order to minimize this flakiness, this PR reproduce in a parallel manner, what happens automatically in the SDK, this way we can compare this two results.
=> test: Fixing UI Test

.github/workflows/integration-tests.yml, scripts/set-device-tests-environment.patch
Set ui-tests environment to Sentry of iOS-Swift init so we can inspect
transactions from ui-tests in Sentry.
=> ci: Set ui-tests Environment

CHANGELOG.md, Sources/Sentry/SentrySpan.m, Sources/Sentry/SentryTracer.m, Tests/SentryTests/Performance/SentryTracerTests.swift, Tests/SentryTests/Transaction/SentrySpanTests.swift
Instead of removing unfinished spans from the transaction in order to avoid the transaction to be discarded, we close all unfinished spans with `deadline_exceeded` status.
closes #1303 
Unit tests
=> feat: Include unfinished spans in transactions

Sources/Sentry/SentryNSURLRequest.m
The log message is always nil and logging the JSON of an envelope
is very verbose when having attachments. You can get the contents
of an envelope by looking at the stored file on disk instead.
=> ref: Remove not working log in SentryNSURLRequest

.github/workflows/test.yml, scripts/xcode-test.sh
Run unit tests on iOS 12 on macos-10.15.
I created issues for the skipped tests https://github.com/getsentry/sentry-cocoa/issues/1614 and the test-server problem https://github.com/getsentry/sentry-cocoa/issues/1615.
Fixes GH-1611
=> ci: Run unit tests on iOS 12

Makefile
Updating MakeFile test command to use `Test` configuration.
Solves #1595 
=> test: Change make test to use Test configuration

.github/workflows/test.yml
When the tests fail or crash the test logs in derived data can help
to investigate the cause of the failing tests.
=> ci: Archive derived data logs when tests fail

CHANGELOG.md, Sources/Sentry/SentryDefaultObjCRuntimeWrapper.m, Sources/Sentry/SentryObjCRuntimeWrapper.h, Sources/Sentry/SentrySubClassFinder.m, Tests/SentryTests/Helper/SentryTestObjCRuntimeWrapper.h, Tests/SentryTests/Helper/SentryTestObjCRuntimeWrapper.m, Tests/SentryTests/Integrations/Performance/SentrySubClassFinderTests.swift
When trying to find all subclasses of a given class, the code potentially
tried to access bad memory, leading to EXC_BAD_ACCESS. With this
PR, we don't iterate over all classes loaded by objc_getClassList when
the number of classes returned changes between its two invocations.
Instead, when the number changes, the code now throws away the
allocated memory and retries once.
This more defensive approach is worth a shot to fix GH-1634.
Unit tests.
=> fix: Crash in SentrySubClassFinder

.github/workflows/integration-tests.yml, scripts/add-sentry-to-alamofire.patch, scripts/add-sentry-to-homekit.patch, scripts/add-sentry-to-vlc.patch
Enable file IO APM for integration tests and send transactions
to Sentry with an integration-test environment.
=> test: Enable file IO for integration tests

scripts/add-sentry-to-homekit.patch
The CocoaPod for the home kit integration test was pointing to
a fixed version of Sentry. This is fixed now by pointing to the 
current commit hash.
=> test: Fix HomeKit integration test

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryOutOfMemoryTrackingIntegration.m, Tests/SentryTests/Integrations/OutOfMemory/SentryOutOfMemoryIntegrationTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
When unit tests are running don't start OOM tracking integration
to avoid reporting OOMs.
Docs PR https://github.com/getsentry/sentry-docs/pull/4646
We don't want to report OOMs when running unit tests.
=> fix: Don't track OOMs for unit tests

CHANGELOG.md, Sources/SentryCrash/Recording/Tools/SentryCrashFileUtils.c
The format for the log specifies two string arguments but only one is supplied potentially causing a crash
Assume the `path` variable was unintentionally omitted when logging the error. Adding it back to prevent a possible crash.
Fixes a crashing problem.
Made change in local project.
=> Fix crash in dirContentsCount() when dir == NULL

CHANGELOG.md, Sources/Sentry/SentryAppStartTracker.m, Sources/Sentry/SentryAppStartTrackingIntegration.m, Tests/SentryTests/Integrations/Performance/AppStartTracking/SentryAppStartTrackingIntegrationTests.swift
When used by a hybrid SDK, Cocoa SDK should track app start.
closes #1657
Unit test
=> fix: Always tracks App start for Hybrid SDKs

Sources/Sentry/Public/SentryOptions.h, Sources/Sentry/SentryClient.m
Explain the special casing of the Apple SDK for setting the ip_address
to {{auto}} on Sentry and how to disable the collection of users
IP addresses.
Fixes GH-1673
=> docs: Clarify sendDefaultPii

.github/workflows/test.yml
GitHub Actions were always falling back to the default simultor iOS
15.2, because it can't find the requested simulators. This is fixed now
by selecting the matching Xcode version.
Fixes GH-1638
=> ci: Fix Simulator UI Tests

Sources/Sentry/Public/PrivateSentrySDKOnly.h, Sources/Sentry/SentryFramesTrackingIntegration.m, Sources/Sentry/SentryHybridSKdsOnly.m, Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackingIntegrationTests.swift
Added support for hybrid SDKs to enable frame tracking using `PrivateSentrySDKOnly.framesTrackingMeasurementHybridSDKMode` flag.
Closes #1685 
Unit test
=> feat: Add support for hybrid SDKs to enable frame tracking

.github/workflows/lint.yml
=> pod lint in verbose mode

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryClient.m, Tests/SentryTests/SentryClient+TestInit.h, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryCrash/TestThreadInspector.swift
The SentryClientTests used SentryThreadInspector for asserting that SentryClient
appropriately calls the SentryThreadInspector, and it also validated the thread's
stacktraces. The assertion also compared the number of threads, which can easily
change between the call to SentryClient and the assertion later on. As
SentryThreadInspectorTests test the functionality of SentryThreadInspector, we can
instead use a test implementation in SentryClientTests to make the tests deterministic.
Fixes GH-1706
=> test: Fix flaky SentryClientTests

CHANGELOG.md, Sources/Sentry/Public/SentryOptions.h, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryDependencyContainer.m, Sources/Sentry/SentryTracesSampler.m, Sources/Sentry/include/SentryDependencyContainer.h, Tests/SentryTests/SentryClient+TestInit.h, Tests/SentryTests/SentryClientTests.swift
The SDK applied both sample rates for events and transactions when capturing transactions.
Previously, when setting sampleRate to 0.0, the SDK would sample all transactions. This is
fixed now by ignoring the sampleRate for transactions.
I had to refactor the code a bit to make it testable.
Came up when investigating https://github.com/getsentry/sentry-cocoa/issues/1655.
Unit tests.
=> fix: Wrongly sampling transactions

.sauce/config.yml
Updated Sauce Labs config file since they removed iOS 15.2 in favor of iOS 15.4.
=> fix: Updated Sauce Labs config file to a valid iOS version

CHANGELOG.md, Sources/Sentry/SentryClient.m, Tests/SentryTests/SentryClientTests.swift
Calling captureCrash inside the onCrashedLastRun callback leads to an
endless loop. As captureCrash is not public, the chances are low that this
ever happens. Nevertheless, we can easily fix this by setting the BOOL for
crashedLastRunCalled before executing the callback.
I spotted this while answering a question for onCrashedLastRun.
Unit tests.
=> fix: Possible endless loop for onCrashedLastRun

CHANGELOG.md, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_Deadlock.m, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_MachException.c, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_NSException.m, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_Signal.c, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_User.c, Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.c, Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.h, Tests/SentryTests/SentryCrash/SentryCrashMonitor_Tests.m
Apply patch https://github.com/kstenerud/KSCrash/pull/351 that was based on https://github.com/kstenerud/KSCrash/pull/321 
to SentryCrash to avoid a race condition when suspending and resuming the
environment.
Came up while investigating https://github.com/getsentry/sentry-cocoa/issues/1533.
Just applied the patch which didn't contain any tests.
=> fix: Avoid race condition in SentryCrash

CHANGELOG.md, Sources/Sentry/SentryOptions.m, Tests/SentryTests/SentryOptionsTest.m
The SentryOptions missed setting enableProfiling via initWithDict.
Came across this when doing https://github.com/getsentry/sentry-cocoa/pull/1742
Unit tests.
=> fix: enableProfiling option

.github/workflows/test.yml, Tests/SentryTests/Helper/SentryFileManagerTests.swift
Increase timeout for testDefaultMaxEnvelopesConcurrent because
the CI failed a few times due to timeout exceeded
Related to https://github.com/getsentry/sentry-cocoa/pull/1745
=> test: Increase timeout for SentryFileManagerTests

scripts/set-device-tests-environment.patch
The UI tests generate false OOMs and spam Sentry.
=> ci: Disable OOM for UI tests

fastlane/Fastfile
Use sentry_upload_dif instead of sentry_upload_dsym.
Sentry was not able to symbolicate the stacktrace from Testflight builds properly.
Uploading a build to TestFlight
=> ci: Fix BCSymbolMaps for Testflight

Tests/SentryTests/Helper/SentryFileManagerTests.swift
This test sometimes fails with timeout exceeded in CI. Let's increase the timeout.
=> test: Increase timeout for testDefaultMaxEnvelopesConcurrent

CHANGELOG.md
Remove a changelog entry that was duplicated between 7.13.0 and Unreleased. The actual change is unreleased.
=> fix: Remove duplicate changelog entry

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryAutoBreadcrumbTrackingIntegration.m, Sources/Sentry/SentryBreadcrumbTracker.m, Sources/Sentry/SentryDependencyContainer.m, Sources/Sentry/SentrySwizzleWrapper.m, Sources/Sentry/include/SentryBreadcrumbTracker.h, Sources/Sentry/include/SentryDependencyContainer.h, Sources/Sentry/include/SentrySwizzleWrapper.h, Tests/SentryTests/ClearTestState.swift, Tests/SentryTests/Helper/SentrySwizzleWrapperTests.swift, Tests/SentryTests/Integrations/Breadcrumbs/SentryAutoBreadcrumbTrackingIntegrationTests.swift, Tests/SentryTests/Integrations/Breadcrumbs/SentryBreadcrumbTrackerTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
Add a wrapper around swizzling sendAction:to:from:forEvent:
for testability and to only swizzle once when multiple implementations
need to be called for the same swizzled method.
This PR is preparation for transactions for UI events.
Unit tests and simulator
Crumb before
https://sentry.io/organizations/sentry-sdks/issues/2895893229/events/f797f149447e4a7ebe8c68a0c2ac4f63/?project=5428557
Crumb after
https://sentry.io/organizations/sentry-sdks/issues/2895893229/events/794156d2586e4abca8d598ea63f20548/?project=5428557
=> ref: Add SwizzleWrapper

Sources/Sentry/Public/PrivateSentrySDKOnly.h, Sources/Sentry/SentryDependencyContainer.m, Sources/Sentry/SentryHybridSKdsOnly.m, Sources/Sentry/include/SentryDependencyContainer.h, Tests/SentryTests/PrivateSentrySDKOnlyTests.swift
Other methods in PrivateSentrySDKOnly are static. `getDebugImages` not being static makes no sense. 
See https://github.com/getsentry/sentry-dart/pull/823/files#r845811128
=> ref: Make getDebugImages static for private SDKs

.github/workflows/ui-tests.yml
Running CI with 0.94.0 fails. Let's pin saucectl to 0.93.0 to make it
work again.
=> ci: Set fixed saucectl version

CHANGELOG.md
See https://github.com/getsentry/develop/pull/564
=> docs: Mention min Sentry version for 7.13.0

CHANGELOG.md
I merged my PR after the 7.14.0 release had been cut, so this item went in the wrong section.
=> fix: Changelog to move #1782 to the Unreleased section

Sources/Sentry/Public/SentryDebugImageProvider.h, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryDebugImageProvider.m, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryCrash/SentryDebugImageProviderTests.swift
Instead of sending every binary image for each Event, we filter only those that are referenced in the event threads.
close #1676 
Unit test
=> perf: Reduce the number of binary image in an event

Sources/Sentry/SentryDebugImageProvider.m, Sources/Sentry/SentryScreenshot.m
Fixes the casing of the import in SentryScreenshot.m and SentryDebugImageProvider.m
It broke builds on case sensitive file systems.
Tested the build in an iOS app
=> fix: Case sensitive header import error

Sentry.podspec
Update Podspec syntax that was deprecated with Cocoapods 0.38 in 2015, which fixes the pod’s settings overwriting settings of an app target using the pod.
#1652 added `CLANG_CXX_LANGUAGE_STANDARD = c++14` to the list of xcconfig flags, which causes every app using the pod to use that C++ language standard, even if the app target itself specifies a different standard. Using the newer Podspec syntax fixes this issue.
Relevant documentation/discussion:
https://blog.cocoapods.org/CocoaPods-0.38/#split-of-xcconfig
https://github.com/CocoaPods/CocoaPods/issues/3813#issuecomment-128445627
=> Use pod_target_xcconfig for Podspec

Sources/Sentry/SentryOutOfMemoryLogic.m, Sources/Sentry/include/SentryOutOfMemoryLogic.h
Just a spelling mistake I noticed
Correct spelling! :)
=> ref: Fix spelling of adapter

CHANGELOG.md, Sources/Sentry/SentryOptions.m, Tests/SentryTests/SentryOptionsTest.m
Enables users to override the SDK info
This allows other SDKs that use sentry-cocoa internally to identify the events. Enables https://github.com/getsentry/sentry-unity/issues/616
Added a test case
=> feat: Allow setting SDK info with Options initWithDict

CHANGELOG.md, Sources/SentryCrash/Recording/Tools/SentryCrashObjC.c, Sources/SentryCrash/Recording/Tools/SentryCrashObjCApple.h
Running SentryCrashObjC_Tests locally leads to a crash. This is
fixed now by using the FAST_DATA_MASK pointed out in
https://opensource.apple.com/source/objc4/objc4-680/runtime/objc-runtime-new.h.auto.html
and also used in a patch for KSCrash https://github.com/kstenerud/KSCrash/pull/429. 
Thanks, @Rui4u, for the PR to KSCrash.
We want to be able to run our tests locally.
Unit tests.
=> Fix getting class data mask in SentryCrash

Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard, Samples/iOS-Swift/iOS-Swift/ViewControllers/SplitViewController.swift, Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift, Sources/Sentry/SentryUIViewControllerPerformanceTracker.m
Renamed SplitViewSecondaryController in samples to SecondarySplitViewController.
Removed a `SentryUIViewControllerPerformanceTracker` transaction stack redundancy.
Only view controller which name contains `viewcontroller` are swizzled. Because of that, SplitViewSecondaryController transactions are not being created.
Check in Sentry.io
=> ref: Change SplitViewSecondaryController

CHANGELOG.md, Sources/Sentry/Public/SentryEnvelopeItemType.h, Sources/Sentry/SentryDataCategoryMapper.m, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/SentryRateLimitParser.m, Sources/Sentry/include/SentryDataCategory.h, Tests/SentryTests/Networking/RateLimits/SentryRateLimitsParserTests.swift, Tests/SentryTests/Networking/SentryDataCategoryMapperTests.swift
Add profile data category for rate limiting to support rate limiting for
profile envelope items.
Fixes GH-1798
Unit tests
=> Add profile data category for rate limiting

CHANGELOG.md, Sources/Sentry/SentrySubClassFinder.m, Tests/SentryTests/Integrations/Performance/SentrySubClassFinderTests.swift
Removed the name checking for view controller when swizzling.
Turn out the approach to search all the view controllers inside the app binary image is fast and we don't need to include this restriction that will cause confusion.
In a project with 1000 classes (a big project), it took only ~3ms to check all classes. 
Profiling for performance and unit tests to know if the method that searches view controllers is picking the right ones.
=> feat: Remove ViewController name match for swizzling

CHANGELOG.md, Sources/Sentry/SentryBacktrace.cpp, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/SentryThreadHandle.cpp, Sources/Sentry/SentryThreadMetadataCache.cpp, Sources/Sentry/include/SentryBacktrace.hpp, Sources/Sentry/include/SentryThreadHandle.hpp, Sources/Sentry/include/SentryThreadMetadataCache.hpp, Tests/SentryTests/Profiling/SentryThreadMetadataCacheTests.mm
We previously avoided collecting queue names because the `dispatch_qaddr` field (see diff) would point to a queue that was no longer valid by the time we read the field, causing a crash. I found a note in some Apple code that explains what was happening here: https://github.com/WebKit/WebKit/blob/09225dc168d445890bb0e2a5fa8bc19aef8556f2/Source/WebCore/page/cocoa/ResourceUsageThreadCocoa.mm#L119
The queue had been deallocated by the time we were reading the field. In order to avoid this race condition, in this PR, we suspend the thread before trying to read the field from the queue. Suspending the thread *should* prevent the dispatch queue from deallocated, assuming the deallocation happens on the thread that the queue is currently assigned to. I am not yet 100% confident in this behavior …
=> feat: Collect queue label information for profiles

.github/workflows/test.yml
We had an issue with hanging tests, reverted https://github.com/getsentry/sentry-cocoa/pull/1808.
The default of GH actions is 360 minutes. This PR reduces the time-out to 20 minutes for unit tests, 
so they don't hang for 6 hours.
=> ci: Set timeout to 20 minutes for unit tests

.github/workflows/test.yml
Use Xcode 13.2.1 for unit tests instead of 13.0.
=> ci: Use Xcode 13.2.1 for unit tests

Samples/README.md, Samples/watchOS-Swift/watchOS-Swift.xcodeproj/xcshareddata/xcschemes/watchOS-Swift WatchKit App.xcscheme, Sentry.xcodeproj/project.pbxproj, Sentry.xcworkspace/contents.xcworkspacedata, Tests/README.md
- xcode project reorg (see screenshot below):
- add a few files to the Xcode project navigator for easy editing ~, including `test-server/` which also pulls in its SPM dependencies~ (this broke things in CI)
- reogranize sample apps under a group to match the file structure
- convert some included top-level folders containing files not belonging to any targets to folder references
- add a readme to for the sample apps and updates a readme that was out of date
screenshot showing before/after xcodeproj reorg: 
I made these changes while diving into the source/project for the first time.
Ensure it passes CI; no code changes, so as long as tests don't break we're good 👍🏻
=> chore: Xcode project reorgs

.github/workflows/test.yml, scripts/xcode-test.sh
Attach the raw test output as an artifact to make investigations easier.
=> ci: Raw test log as artifact

Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
Set target membership for a few needed source files to a target that was failing to build.
I discovered this while trying to build various sample apps in the project.
Build passed locally; ensure CI still passes.
=> fix: add sources to iOS13-Swift target that was broken

Sources/Sentry/SentryCrashIntegration.m, Sources/Sentry/SentryCrashWrapper.m, Sources/Sentry/include/SentryCrashIntegration.h, Sources/Sentry/include/SentryCrashWrapper.h, Tests/SentryTests/Integrations/SentryCrash/SentryCrashIntegrationTests.swift, Tests/SentryTests/SentryCrash/TestSentryCrashWrapper.m, Tests/SentryTests/TestUtils/SentryTestObserver.m
Handle edge case when systemInfo is empty in SentryCrashIntegration.
I actually wanted to fix GH-1104, because I thought I can do it in an hour as I had to use a workaround in https://github.com/getsentry/sentry-cocoa/pull/1815 to get the scope data, see https://github.com/getsentry/sentry-cocoa/blob/b1ce7c5cd4cbb16a0c97ca417b0891831b779b84/Tests/SentryTests/TestUtils/SentryTestObserver.m#L50-L51
I stopped working on fishing GH-1104 as it turns out not to be a quick fix. I didn't want to throw away some of the refactorings though.
Unit tests.
=> ref: Handle systemInfo empty in CrashIntegration

CHANGELOG.md, Sources/Sentry/SentryProfiler.mm, Tests/SentryTests/SentryHubTests.swift
Calling `-[SentryDebugMeta serialize]` encodes the data in the older "apple" format: https://github.com/getsentry/relay/blob/master/relay-general/src/protocol/debugmeta.rs#L107
This switches it over to the new "macho" format that symbolicator supports: https://github.com/getsentry/relay/blob/master/relay-general/src/protocol/debugmeta.rs#L309
This **only impacts Profiling**. A more extensive change would change the implementation of `-serialize` so that all debug_meta (including for crashes) use the new format, but this change would require more testing.
* Move to a newer, more supported format
* This may help us address some issues where symbolicator isn't returning the correct file name / line number information for symbolicated frames
* Updated unit tests
* Test that the Profiling …
=> feat: Use the macho format for debug information in Profiling

.swiftlint.yml, Makefile
Ignore more paths for clang-format and swiftlint. Use swiftlint --fix
over deprecated autocorrect.
=> Improvements for code formatting

.github/workflows/build.yml, .github/workflows/format-code.yml, .github/workflows/lint.yml, .github/workflows/saucelabs-UI-tests.yml, .github/workflows/test.yml, Samples/iOS-ObjectiveC/iOS-ObjectiveC.xcodeproj/project.pbxproj, Samples/tvOS-Swift/tvOS-Swift.xcodeproj/project.pbxproj, develop-docs/README.md
- made it more explicit which UI tests run on simulators and which run in Sauce Labs
- ensured that the UI tests for `iOS-Swift` and `iOS-SwiftUI` run in the right workflows
- reenabled iOS 13 testing now that #1564 is resolved
- change the cron schedule for the UI tests on saucelabs to run once every day ([0 0 \* \* \*](https://crontab.guru/#0_0_*_*_*)) (it was previously set to [* */4 * * *](https://crontab.guru/#*_*/4_*_*_*), which runs every minute for every fourth hour of the day–360 times per day instead of 1)
- trigger reruns of workflows when they're edited
=> test: fix UI test naming and runs

CHANGELOG.md, Sources/Sentry/SentryOutOfMemoryLogic.m, Sources/Sentry/SentrySDK.m, Sources/Sentry/include/SentrySDK+Private.h, Tests/SentryTests/ClearTestState.swift, Tests/SentryTests/Integrations/OutOfMemory/SentryOutOfMemoryTrackerTests.swift, Tests/SentryTests/Integrations/SentryCrash/SentryCrashIntegrationTests.swift, Tests/SentryTests/SentrySDKTests.swift
When calling SentrySDK.start twice, we wrongly reported an OOM. This is
fixed now by only reporting an OOM when the user starts the SDK the first
time.
Fixes GH-1877, and maybe https://github.com/getsentry/sentry-cocoa/issues/1852 and https://github.com/getsentry/sentry-react-native/issues/1830
=> Fix reporting wrong OOM when starting SDK twice

CHANGELOG.md, Sources/Sentry/SentryBreadcrumb.m, Tests/SentryTests/Protocol/SentryBreadcrumbTests.swift
Implement the description method for SentryBreadcrumb so that when adding
breadcrumbs you see in the log what the breadcrumb contains.
Came up while investigating APM for SwiftUI.
Unit test.
=> Implement description for SentryBreadcrumb

.github/dependabot.yml
So we can avoid manual PRs like https://github.com/getsentry/sentry-cocoa/pull/1845 and https://github.com/getsentry/sentry-cocoa/pull/1846
=> ci: Add GH actions to dependabot

Sources/SentryCrash/Recording/Tools/SentryCrashObjC.c
https://github.com/getsentry/sentry-cocoa/security/code-scanning/1
=> fix: prevent possible overflow

.github/workflows/testflight.yml, scripts/ci-select-xcode.sh
I noticed a few redundancies in the workflow that should be taken care of by default in the github action macos image.
=> ci: udpate testflight job steps

.github/workflows/build.yml, .github/workflows/integration-tests.yml, .github/workflows/saucelabs-UI-tests.yml, .github/workflows/test.yml, .github/workflows/testflight.yml, fastlane/Fastfile
Replace our custom keychain logic with Fastlane's [`setup_ci`](https://docs.fastlane.tools/actions/setup_ci/). These changes allow running the lanes locally and succeeding in the codesign steps, for testing before pushing to CI.
Also:
- Lets the values from Appfile be automatically fetched instead of explicitly extracting with CredentialsManager.
- Fix some typos, casing and indentation.
=> ci: use `setup_ci` instead of our custom keychain setup

CHANGELOG.md, Sources/Sentry/SentryAppStartTracker.m, Tests/SentryTests/Integrations/Performance/AppStartTracking/SentryAppStartTrackerTests.swift
Since iOS 15, the system might decide to pre-warm your app
before the user tries to open it. In such cases, we can't reliably
measure the app start, and we drop it. Otherwise, we would get
app start times ranging from one minute to even days.
Docs PR https://github.com/getsentry/sentry-docs/pull/5169
Fixes GH-1849
Unit test
=> Stop reporting pre warmed app starts

CHANGELOG.md, Sources/Sentry/SentryAppStartTracker.m, Tests/SentryTests/Integrations/Performance/AppStartTracking/SentryAppStartTrackerTests.swift
The max app start duration was 5 seconds, which is too short. This
is fixed now by setting it to 60s.
I noticed that while investigating https://github.com/getsentry/sentry-cocoa/issues/1897
Unit test.
=> Set max app start duration to 60s

CHANGELOG.md, Sources/Sentry/SentryTracer.m, Tests/SentryTests/Performance/SentryTracerTests.swift
Set scope span to nil when finishing an idle transaction without children.
Came up when investigating https://github.com/getsentry/sentry-cocoa/issues/1897
Unit test.
=> Unset scope span when finishing idle transaction

Samples/iOS-Swift/iOS-Swift/AppDelegate.swift, Samples/iOS-Swift/iOS-SwiftUITests/SDKPerformanceBenchmarkTests.swift
This was causing the profiler to stop too early, throwing off the benchmark numbers.
=> fix: disable automatic user interaction tracing when benchmarking

Sources/Sentry/include/SentryCompiler.h
This check was breaking a customer's build, as reported in https://github.com/getsentry/sentry-cocoa/issues/1913#issuecomment-1165562212. We aren't sure why, but we don't really need the check, so we'll remove it for now.
=> fix: remove webkit/optimization check

Sentry.xcodeproj/project.pbxproj
Just like the sample folder already did, now the top level Sentry folder also uses 4 spaces for indentation.
=> chore: Configure the root of the project to use four spaces for indentation

Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj, Samples/iOS-Swift/iOS-Swift/ViewController.swift, Samples/iOS-Swift/iOS13-Swift/iOS13-Swift-Bridging-Header.h
iOS13 sample shares files with iOS Swift Sample. Sometimes we add files to one without adding it to the other preventing it from compiling.
=> fix: iOS13 Swift Sample is not compiling

.pre-commit-config.yaml, Brewfile, CONTRIBUTING.md, Makefile
Add pre-commit to call clang-format and a couple
of other checks.
=> meta: Add Pre Commit Hook

.github/workflows/build.yml
Try to compile `iOS13-Swift` sample during CI to ensure all required files were added.
close #1938
=> chore: Compile iOS13-Swift sample

.pre-commit-config.yaml
Remove trailing-whitespace of pre-commit hook cause
it causes some formatting issues in combination with Xcode.
=> build: Remove trailing-whitespace

Tests/SentryTests/Integrations/ANR/SentryANRTrackerTests.swift
This never fail in the local machine, even repeating it 1000 times. But it fails regularly with CI.
I believe 0.1 second to wait all expectations to be fulfilled may be not enough time in some situations and environments.
close #1948 
=> fix: SentryANRTrackerTests flaky test

CHANGELOG.md, Sources/Sentry/SentryHttpTransport.m, Tests/SentryTests/Networking/SentryHttpTransportTests.swift
The docs state that errors with status code 429 should not be sent as network_error. The SDK didn't follow this rule yet.
Fixes #1753
Unit test.
=> fix: Don't send error 429 as network_error

CHANGELOG.md, Sources/Sentry/SentryProfilingLogging.mm
Call `va_end` *after* creating the `NSString *`, otherwise this is undefined behavior and can crash.
Customer reported a crash:
Manually verified that logging still works, we will deploy the fix and ask the customer to check whether this resolves their issue.
=> fix: Crash in profiling logger

CHANGELOG.md, Sources/Sentry/SentrySpan.m, Sources/Sentry/SentryTracer.m, Tests/SentryTests/Transaction/SentrySpanTests.swift
Sanitize span data when serializing.
Closes #1307
Unit tests
=> fix: sanitize span data

CHANGELOG.md, Sources/Sentry/SentryCrashWrapper.m, Sources/Sentry/SentryOutOfMemoryLogic.m, Sources/Sentry/include/SentryCrashWrapper.h, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.h, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m, Tests/SentryTests/Integrations/OutOfMemory/SentryOutOfMemoryTrackerTests.swift, Tests/SentryTests/SentryCrash/TestSentryCrashWrapper.h, Tests/SentryTests/SentryCrash/TestSentryCrashWrapper.m
Stop reporting OOMs for simulator builds, as the watchdog doesn't kill simulators
when they are hungry for memory.
Saw the isSimulatorBuild code in SentryCrashMonitor_System and thought it makes sense for OOMs.
Unit tests and real device.
=> Don't track OOMs for simulators

CHANGELOG.md, Sources/Sentry/SentryBacktrace.cpp, Tests/SentryTests/Profiling/SentryBacktraceTests.mm, Tests/SentryTests/Profiling/SentrySamplingProfilerTests.mm
Remove the check that skips collecting a sample for an idle thread.
We were seeing an issue where we found function frames in profiles that were taking way longer than they should, because of missing samples in between: 
That's because we were intentionally skipping collecting samples when the thread was idle (which is frequently the case). Not collecting a sample when the thread is idle means that we will have irregular sample timestamps, which cause an incorrect calculation of the function durations.
Log sample timestamps and ensure that we're consistently able to collect timestamps every ~10ms for a profiler that is intended to sample at 100hz, even when the thread is idling.
=> fix: Collect samples for idle threads in iOS profiler

CHANGELOG.md, Sources/Sentry/PrivateSentrySDKOnly.m, Sources/Sentry/Public/PrivateSentrySDKOnly.h, Sources/Sentry/include/SentryHub+Private.h, Tests/SentryTests/PrivateSentrySDKOnlyTests.swift
Hybrid SDKs can now access the options of the current client, or will get an empty SentryOptions object back if no hub/client was set. 
Requested by @marandaneto. Closes #1665.
Unit tests.
@marandaneto and @brustolin can you please have a look?
=> feat: Provide private access to SentryOptions for hybrid SDKs

scripts/ci-select-xcode.sh
The current links point to a fixed commit. When GH adds new Xcode
versions we don't see them as the commit points to the past.
This is fixed by pointing to the latest version in the readme.
=> ci: Update available GH actions Xcode link

Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift, Samples/tvOS-Swift/tvOS-SwiftUITests/LaunchUITests.swift
Add parameter message to waitForExistence to make it required
to use an assertion message so we know what is wrong when
waitForExistence times out.
=> test: Make message for waitForExistence required

CHANGELOG.md, Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard, Sources/Sentry/SentryBaggage.m, Sources/Sentry/SentryNetworkTracker.m, Sources/Sentry/SentrySerialization.m, Sources/Sentry/include/SentryBaggage.h, Sources/Sentry/include/SentrySerialization.h, Tests/SentryTests/Helper/SentrySerializationTests.swift, Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerTests.swift, Tests/SentryTests/Transaction/SentryBaggageTests.swift
`SentryNetworkTracker` adds a baggage header with some sentry keys and values, but it does so by completely overwriting any possibly existing baggage header. And when we remove the baggage header when `SentrySDK.currentHub.scope.span` is `nil`, we also do that by removing the entire baggage header instead of only the `sentry-trace_id` key that we actually need to remove.
Now we respect the existing baggage header, if it's there, by modifying it.
Closes #1911
Unit tests.
=> fix: Respect existing baggage header instead of overwriting it

Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift
Comment out the tests to disable them.
These are consistently failing or flaking and are blocking releases: https://github.com/getsentry/sentry-cocoa/runs/7504874535?check_suite_focus=true
=> fix: Disable broken LaunchUITests to unblock release

Sources/Sentry/Public/SentryOptions.h
Update the message to tell users what the new API is.
The old API was marked as deprecated but without information on what the replacement was.
Build
=> fix: Add more descriptive deprecation message for enableProfiling

Samples/iOS-Swift/PerformanceBenchmarks/SentrySDKPerformanceBenchmarkTests.m, Samples/iOS-Swift/iOS-Swift/ViewControllers/PerformanceViewController.swift
Maxing out CPU with a hot while loop also prevented the test runner app from
being able to query the accessibility system to hit the stop button. This causes
lots of retries and eventual failures or timeouts in other areas, and the tests
to run a long time in general.
Instead of having a button press stop the benchmark and contending for time on
the main run loop, just remove the start/stop buttons and start when the view
controller appears, and set a 15 second delay to stop the benchmarks. Then the
test runner queries the text field for results as usual. Removing the steps needed 
to press the start and stop buttons also saves time.
=> ci: fix ui thread starvation in benchmarks

.sauce/config.yml
iPhone 13 pro iOS version 15.5 is no longer available in Saucelabs.
=> fix: Sauce labs iPhone 13 pro iOS version

Tests/SentryTests/Helper/SentryFileManagerTests.swift
Fix the test with https://github.com/getsentry/sentry-cocoa/issues/2017
=> Disable flaky tesDefaultMaxEnvelopesConcurrent

Sources/Sentry/SentryThreadHandle.cpp
Use a constant for max thread name length instead of a hardcoded `128`
The system already defines a constant for the max allowable length of a thread name, we don't have to pick a number for it.
Build
=> fix: Use constant for max thread name size instead of magic number

CHANGELOG.md, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/SentryThreadMetadataCache.cpp
Handle this failure gracefully and only log a thread priority if reading it was successful.
Reading the thread priority can return `-1` in failure cases and we don't want to store this in the profile payload if we're not able to read a legitimate value. This also fixes a flake with the `testStartTransaction_ProfilingDataIsValid` test which checked for a valid priority and failed about 20% of the time on macOS.
Verify that `testStartTransaction_ProfilingDataIsValid` no longer flakes on macOS.
=> fix: Handle failure to read thread priority gracefully

CHANGELOG.md, Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift, Sources/Sentry/SentryBacktrace.cpp, Tests/SentryTests/SentryHubTests.swift
* Fix test breakage in https://github.com/getsentry/sentry-cocoa/issues/2000
* Revert https://github.com/getsentry/sentry-cocoa/pull/2003
* Replace stacks for idle threads with an empty sample so that it doesn't render in the profile
Collecting stacks for idle threads produces this kind of data, where we have a stack that just shows the thread waiting on a function like `mach_msg_trap`. Instead of collecting these stacks, we can just log an empty sample, which will prevent it from rendering in the flamegraph.
This also fixes a bug in iOS 12 where we would repeatedly fail to suspend an idle thread, which broke some tests (https://github.com/getsentry/sentry-cocoa/issues/2000). With this new implementation we won't attempt to suspend an idle thread.
* Run existing tests for …
=> fix: Log empty samples instead of collecting stacks for idle threads

CHANGELOG.md, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryCrashWrapper.m, Sources/Sentry/include/SentryCrashIntegration.h, Sources/Sentry/include/SentryCrashWrapper.h, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryCrash/TestSentryCrashWrapper.h, Tests/SentryTests/SentryCrash/TestSentryCrashWrapper.m
Just like we're reporting free memory (see #1962), we are now reporting app memory usage.
Closes #999
Unit tests, manual test.
=> feat: Report App Memory Usage

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/NSLocale+Sentry.m, Sources/Sentry/SentryClient.m, Sources/Sentry/include/NSLocale+Sentry.h, Tests/SentryTests/Protocol/SentryDebugMetaEquality.swift, Tests/SentryTests/Protocol/SentryThreadEquality.swift, Tests/SentryTests/SentryClient+TestInit.h, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/TestClient.swift
A picture is worth a 1000 words.
Closes #1534.
Manually + unit tests
=> feat: add culture context to event

Sources/Sentry/Public/SentryHub.h, Sources/Sentry/SentryCrashIntegration.m, Sources/Sentry/SentryHub.m
Cleaning up `getIntegration` code from SentryHub
=> ref: Cleaning SentryHub getIntegration

Sources/Sentry/Public/SentryDefines.h, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryPermissionsObserver.m, Tests/SentryTests/SentryClientTests.swift
While reading https://github.com/getsentry/team-mobile/issues/6 I noticed that the spec supports "partial" app permissions. This is great, and the SDK now uses this as well.
#skip-changelog, as this is part of the same release that includes #1984.
This is a follow-up of https://github.com/getsentry/sentry-cocoa/pull/1984. See https://github.com/getsentry/team-mobile/issues/6.
Unit tests.
=> feat: include "partial" app permissions

CHANGELOG.md, Sources/Sentry/Public/SentryHub.h, Sources/Sentry/Public/SentryOptions.h, Sources/Sentry/SentryBaseIntegration.m, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryCrashIntegration.m, Sources/Sentry/SentryHub.m, Sources/Sentry/SentryOptions.m, Sources/Sentry/SentrySDK.m, Sources/Sentry/include/SentryBaseIntegration.h, Sources/Sentry/include/SentryCrashIntegration.h, Sources/Sentry/include/SentryHub+Private.h, Sources/Sentry/include/SentryOptions+Private.h, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryOptionsTest.m
- Added a new option `enableCrashHandler`, which controls if `SentryCrashIntegration` is installed or not
- Deprecated `SentryOptions.integrations`, by adding a setter which logs a warning (actually marking it as deprecated with a macro is not possible since our tests no longer compile - no way to silence warnings in Swift files!)
- Removed `SentryOptions.enabledIntegrations`, `SentryOptions.disabledIntegrations` and `SentryOptions.removeEnabledIntegration`
- Added `installedIntegrationNames` to SentryHub, which is used to send the list of installed integrations to Sentry. 
Cleaning up SentryOptions and prepare to remove deprecated arrays when v8 comes around. Closes #2043.
Unit tests.
=> feat: Clean up SentryOptions

CHANGELOG.md, Samples/iOS-Swift/iOS-Swift/AppDelegate.swift, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/Public/SentryOptions.h, Sources/Sentry/SentryBaseIntegration.m, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryDependencyContainer.m, Sources/Sentry/SentryOptions.m, Sources/Sentry/SentryScreenshotIntegration.m, Sources/Sentry/SentryViewHierarchy.m, Sources/Sentry/SentryViewHierarchyIntegration.m, Sources/Sentry/include/SentryBaseIntegration.h, Sources/Sentry/include/SentryClient+Private.h, Sources/Sentry/include/SentryDependencyContainer.h, Sources/Sentry/include/SentryViewHierarchy.h, Sources/Sentry/include/SentryViewHierarchyIntegration.h, Tests/SentryTests/Integrations/Screenshot/SentryScreenshotIntegrationTests.swift, Tests/SentryTests/Integrations/ViewHierarchy/SentryViewHierarchyTests.swift, Tests/SentryTests/Integrations/ViewHierarchy/TestSentryViewHierarchy.swift, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
All errors and exceptions can now get the full window's view hierarchy added as attachments. This is controlled by a new option `attachViewHierarchy` which I defaulted to false.
Closes #1772
Manual, and unit tests.
=> feat: Attach view hierarchy to events

CHANGELOG.md, Sources/Sentry/SentrySpan.m, Tests/SentryTests/Transaction/SentrySpanTests.swift
We added a way to change span timestamp manually but forgot that timestamp was used to check whether the spans was finished or not.
Added a flag to keep span finish status.
=> fix: Add span finish flag

Sources/Sentry/Public/SentryOptions.h
Adding "Experimental Feature" to the screenshot option because we don't have enough feedback on this feature to turn it on by default yet.
=> chore: Update SentryOptions screenshot comment

CHANGELOG.md, Sources/Sentry/SentryClient.m, Sources/Sentry/SentrySamplingProfiler.cpp, Sources/Sentry/SentryUIViewControllerSwizzling.m
Currently our SDK doesn't compile using Swift 5.5 because of 2 errors:
- Unrecognized platform name macCatalyst
- Missing include <malloc/_malloc.h>
In the case that the macCatalyst check is for the same version as for the iOS check, we can drop that check: "You don't have to guard Catalyst separately from iOS if they're the same version". We do have one place where we check for a different version, so that is a bit of an ugly fix now.
Closes #2057
Everything still builds and tests complete.
=> fix: Restore Swift 5.5 compatibility

.github/workflows/integration-tests.yml, .github/workflows/test.yml, Sources/Sentry/Public/SentryOptions.h
We have some jobs that attempt to cache results of some steps, but never actual skip the job if there's a cache hit. Here's how much time we save by skipping the work:
- integration tests
- home assistant
- gem install: 30s
- pod install: 75s
- vlc pods: 60s
- unit tests
- test-server build: 120s (x 11 platforms/variants)
= 24.75 minutes per PR (with a full test suite run)
Also `test-server` is not supposed to run on non-macOS-11 jobs, but the condition to skip it was malformed so it would still run. This didn't seem to break on master, but broke on this branch without changing the condition. In any case, the new form works, so I think we should stick with it.
=> ci: skip steps that have cached results

Samples/TrendingMovies/TrendingMovies/Utilities/Tracer.swift, Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryCrashReportSink.m, Sources/Sentry/SentryScreenshotIntegration.m, Sources/Sentry/SentryViewHierarchy.m, Sources/Sentry/SentryViewHierarchyIntegration.m, Sources/Sentry/include/SentryDependencyContainer.h, Sources/Sentry/include/SentryViewHierarchy.h, Sources/SentryCrash/Recording/SentryCrash.h, Sources/SentryCrash/Recording/SentryCrash.m, Sources/SentryCrash/Recording/SentryCrashC.c, Sources/SentryCrash/Recording/SentryCrashC.h, Sources/SentryCrash/Recording/SentryCrashReportStore.c, Sources/SentryCrash/Recording/SentryCrashReportStore.h, Tests/SentryTests/Integrations/ViewHierarchy/SentryViewHierarchyIntegrationTests.swift, Tests/SentryTests/Integrations/ViewHierarchy/SentryViewHierarchyTests.swift, Tests/SentryTests/SentryCrash/SentryCrashReportSinkTest.swift, Tests/SentryTests/SentryCrash/SentryCrashReportStore_Tests.m, Tests/SentryTests/SentryCrash/SentryCrashTests.m, Tests/SentryTests/SentryViewHierarchyTests.swift, scripts/set-device-tests-environment.patch
Follow up of #2044. We now also create view hierarchy attachments for crashes, just like the screenshots integration. Streamlined the code to deal with a common "attachments" folder.
Feature parity with the screenshots feature.
Manually by crashing the sample app, and with added unit tests (mirroring the tests from screenshots).
=> feat: Attach view hierarchy for crashes

CHANGELOG.md, Sources/Sentry/Public/SentryUser.h, Sources/Sentry/SentryUser.m, Tests/SentryTests/Protocol/SentryUserTests.swift
`SentryUser.userId` should be nullable to align with the docs / specs.
Fixes #2035
Unit tests.
=> fix: SentryUser.userId should be nullable

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/NSData+Sentry.m, Sources/Sentry/NSLocale+Sentry.m, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryCrashScopeObserver.m, Sources/Sentry/SentryUIViewControllerSwizzling.m, Sources/Sentry/SentryViewHierarchy.m, Sources/Sentry/UIView+Sentry.m, Sources/Sentry/UIViewController+Sentry.m, Sources/Sentry/include/NSData+Sentry.h, Sources/Sentry/include/NSLocale+Sentry.h, Sources/Sentry/include/UIView+Sentry.h, Sources/Sentry/include/UIViewController+Sentry.h, Sources/SentryCrash/Recording/SentryCrash.m, Tests/SentryTests/Categories/UIViewControllerSentryTests.swift, Tests/SentryTests/Categories/UIViewRecursiveDescriptionTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
Follow up of #2044 and #2063. Reimplemented `recursiveDescription` so we're not using private API. Output is equal to Apple's version. Bonus: we now have the basis to make tweaks to the output for when we want to standardize across platforms.
Don't use private API.
Verified same output, and same tests still succeed.
=> feat: Reimplemented recursiveDescription so we're not using private API

CHANGELOG.md, Sources/Sentry/SentryProfiler.mm, Tests/SentryTests/Profiling/SentrySamplingProfilerTests.mm
We simply change the profiler's internal sampling rate from 100 to 101 (a prime number).
This reduces the potential for [lock-step](https://stackoverflow.com/a/45471031) problems. With a composite number, it's possible for repeated subroutines with durations that are divisors of the sample rate to occur in phase with the sampler's starting and/or stopping, which can produce misleading results.
~- [ ] I added tests to verify the changes~
~- [ ] I updated the docs if needed~
~- [ ] Review from the native team if needed~
=> fix: use prime sample rate to reduce profiler lock-step potential

Tests/SentryTests/Helper/SentryFileManagerTests.swift
=> tests: Reenable testDefaultMaxEnvelopesConcurrent

.github/workflows/benchmarking.yml, .github/workflows/profile-data-generator.yml, .github/workflows/saucelabs-UI-tests.yml, Gemfile.lock, Samples/TrendingMovies/TrendingMovies.xcodeproj/xcshareddata/xcschemes/ProfileDataGeneratorUITest.xcscheme, Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-SwiftUITests.xcscheme, fastlane/Fastfile
We have "unknown" symbols for some sample app profiling flamegraphs. To try to fix this we will make sure all sample apps' dSYMs are uploaded when running jobs that send profiling information when running on a real device.
Because this could incur lots of new symbol uploads since the jobs run frequently, also cache all the build products involved for each:
- the app itself
- the app's dSYM
- the test runner app
This way only when the sources have changed is a new dSYM uploaded.
Caching the compilations also helps speed up CI workflows in general:
- UI tests:
- ~2.5 minutes x2 (two different xcode versions each build a version)
- benchmarks: ~2.5 min
- test profile data generation: ~6.5 minutes
For a grand total of ~14 minutes of compute per full CI run.
=> ci: upload dSYMs for all jobs that run on real devices

Makefile
closes https://github.com/getsentry/sentry-cocoa/issues/2053
=> meta: separate long-running task from `make init`

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/Public/SentryDefines.h, Sources/Sentry/Public/SentryEvent.h, Sources/Sentry/Public/SentryHub.h, Sources/Sentry/Public/SentryTransactionContext.h, Sources/Sentry/SentryHub.m, Sources/Sentry/SentryPerformanceTracker.m, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/SentrySDK.m, Sources/Sentry/SentryScope.m, Sources/Sentry/SentrySpanContext.m, Sources/Sentry/SentryTraceContext.m, Sources/Sentry/SentryTracer.m, Sources/Sentry/SentryTransaction.m, Sources/Sentry/SentryTransactionContext.m, Sources/Sentry/SentryUIEventTracker.m, Sources/Sentry/include/SentryHub+Private.h, Sources/Sentry/include/SentrySDK+Private.h, Sources/Sentry/include/SentryTracer.h, Sources/Sentry/include/SentryTransaction.h, Sources/Sentry/include/SentryTransactionContext+Private.h, Tests/SentryTests/Integrations/Performance/SentryPerformanceTrackerTests.swift, Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerPerformanceTrackerTests.swift, Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerSwizzlingTests.swift, Tests/SentryTests/Integrations/UIEvents/SentryUIEventTrackerTests.swift, Tests/SentryTests/Integrations/UIEvents/SentryUIEventTrackingIntegrationTests.swift, Tests/SentryTests/SentryHubTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h, Tests/SentryTests/Transaction/SentryTransactionTests.swift
Added a new property to the transaction context: the name source. By default this is "custom", but we can set a different one in our integrations. See https://develop.sentry.dev/sdk/event-payloads/transaction/#transaction-annotations.
Users of the SDK can't set a name source, it'll always be "custom" when they start a transaction with a name.
Closes #2075.
Unit tests
=> feat: Transaction name source

.github/workflows/test.yml
Fix for a copypasta/typo from #2045, that resulted in a cached test-server binary still being rebuilt unnecessarily.
=> fix: test server cache step id

CHANGELOG.md, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m
I noticed we were sending the localized time zone abbreviation instead of the time zone name.
For example, we should be sending `"America/Los_Angeles"`, not `"PDT"`
Fixes #1033 
Simple property change, visible on any `NSTimeZone` instance.
In fact, `name` is much more reliable than `abbreviation`, because it's the non-localized IANA identifier that is used as a key when retrieving a time zone.  A time zone will always have a name.  It may or may not have an abbreviation.
=> Send time zone name, not abbreviation

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Tests/SentryTests/Integrations/Performance/CoreData/SentryCoreDataTrackingIntegrationTest.swift, Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerIntegrationTests.swift, Tests/SentryTests/Integrations/Performance/SentrySubClassFinderTests.swift, Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerPerformanceTrackerTests.swift, Tests/SentryTests/Integrations/Session/SentrySessionGeneratorTests.swift, Tests/SentryTests/Networking/RateLimits/SentryDefaultRateLimitsTests.swift, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift, Tests/SentryTests/SentryHubTests.swift
~We had a bunch of test cases marked private, which Xcode will not run as tests.~ These weren't tests, so have been renamed instead.
We also had some tests that were purposefully skipped by malforming the name to exploit the fact that it picks up any function starting with `test`. This should instead be done by unchecking the test cases in the scheme. (See [here](https://github.com/getsentry/sentry-cocoa/issues/1415). [here](https://github.com/getsentry/sentry-cocoa/issues/2102) and [here](https://github.com/getsentry/sentry-cocoa/issues/2103).)
=> test: skip tests via Xcode scheme

CHANGELOG.md, Samples/iOS-Swift/iOS-Swift/AppDelegate.swift, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/SentryTracer.m, Sources/Sentry/include/SentryClient+Private.h, Sources/Sentry/include/SentryProfiler.h, Sources/Sentry/include/SentryScope+Private.h, Tests/SentryTests/SentryHubTests.swift, Tests/SentryTests/SentryScopeTests.m
Fixes https://github.com/getsentry/team-profiling/issues/54
=> fix: pull `environment` from where its currently written at profile serialization time

Tests/SentryTests/Integrations/UIEvents/SentryUIEventTrackerTests.swift
=> fix: typo in test string literal

scripts/ci-select-xcode.sh
To know which Swift version Xcode is using. Came up in https://github.com/getsentry/sentry-cocoa/pull/2060.
=> ci: Print Swift Version

Sources/Sentry/SentrySDK.m
Closes #2081 
I missed your comment about wrapping `dispatch_once` @philipphofmann, but part of this was motivated by removing the need to manage the invocation count in tests, and remove the tests associated with that state. Let me know what you think.
=> docs: add comment explaining the purpose of `startInvocations`

CHANGELOG.md, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryPermissionsObserver.m, Sources/Sentry/include/SentryPermissionsObserver.h, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryCrash/TestSentryPermissionsObserver.swift
Removed media library permission check from permission observer.
We're getting complains that the SDK is preventing people from publishing their apps because they are missing NSAppleMusicUsageDescription information, for more information see #2065 
We intended to create an alpha release with this feature to capture more feedback, but the feature was rollout into GA. The amount of value added is minimum compared to the head ache that this could cause if we're really the problem, so we decide to remove this for now until more investigation is done.
closes #2065 
Updated unit tests
=> fix: Remove Media Library Permission check from permission observer

Sources/Sentry/PrivateSentrySDKOnly.m, Sources/Sentry/Public/PrivateSentrySDKOnly.h, Sources/Sentry/SentryClient.m, Tests/SentryTests/PrivateSentrySDKOnlyTests.swift
Added a function to private SDKs change only the SDK name value.
Added functions to retrieve SDK name and version.
Related to #2010
=> feat: Allow Private SDK to change only SDK name

.sauce/benchmarking-config.yml
Saucelab updated the iPad iOS version, we need to update the yaml file.
=> Fix: Saucelab iPad benchmark test

Package.swift, Samples/SPM-Dynamic/Package.swift, Sources/Sentry/SentrySpan.m, Sources/Sentry/SentryTracer.m, Sources/Sentry/include/SentrySpan.h, Tests/SentryTests/Performance/SentryTracerObjCTests.m, Tests/SentryTests/Transaction/SentrySpanTests.swift
Looks like this might've been a casualty of a faulty search/replace in https://github.com/getsentry/sentry-cocoa/pull/1400. It's tripped me up a couple times so I think should be changed.
=> fix: SentryTracer instances should be called "tracer", not "transaction"

Samples/iOS-Swift/iOS-Swift/Tools/SpanObserver.swift, Samples/tvOS-Swift/tvOS-SBSwift/ViewController.swift, Tests/SentryTests/Helper/UrlSessionDelegateSpy.swift, Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackerTests.swift, Tests/SentryTests/Integrations/Performance/IO/SentryFileIOTrackingIntegrationTests.swift, Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerSwizzlingTests.swift, Tests/SentryTests/Networking/TestRequestManager.swift, Tests/SentryTests/Networking/TestSentryDispatchQueueWrapper.swift, Tests/SentryTests/SentryScreenShotTests.swift, Tests/SentryTests/Transaction/SentrySpanTests.swift
Fixes the three errors as reported in #2144.
Also a new version of SwiftFormat doing its thing 🤷‍♂️
=> Fix compile errors in Xcode 14

Sources/Sentry/SentryClient.m, Sources/Sentry/SentrySerialization.m, Sources/Sentry/SentrySwizzle.m, Sources/SentryCrash/Recording/Tools/SentryCrashJSONCodecObjC.m
Provide fallbacks for assertions in production.
Closes #2109
=> Provide fallbacks for assertions in production

.github/workflows/test.yml, scripts/xcode-test.sh
=> Run tests on iOS 16 using Xcode 14.0

.github/workflows/benchmarking.yml, .github/workflows/profile-data-generator.yml
We're trying to validate where spikes are originating from for symbol uploads, this is a likely candidate.
=> ci: temporarily disable profile generation scheduled runs

CHANGELOG.md, Sources/Sentry/SentryAppStartTracker.m
Use isEqualToString instead of isEqual. This could potentially lead to wrong prewarmed app start detection.
It seems like the logic is not working properly. Still saw a few pre-warmed app starts in customer data. Maybe this is the root cause.
Unit tests use the same string constant so it won't fail.
=> fix: Prewarmed app start detection

scripts/process-benchmark-raw-results.py
The script that processes benchmark results now generates a graph like the following:
=> test: generate graphs for benchmarks

CONTRIBUTING.md
Came up in https://github.com/getsentry/sentry-cocoa/pull/2097
=> docs: Add a note on flaky tests to Contributing

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme
Locally it's 100% fine and I haven't seen this one come up in https://github.com/getsentry/sentry-cocoa/pull/2142 either. Let's see what happens and if we can re-enable it.
=> fix: Enable testCaptureMessage again

.github/workflows/testflight.yml, Gemfile.lock, fastlane/Fastfile
The upload to Testflight via Fastlane failed with
```
error: The CFBundleVersion of an App Clip ('1') must match that of its containing parent app ('817').
```
This is fixed now by using `increment_build_number` instead of using `set_info_plist_value`.
[Successful run](https://github.com/getsentry/sentry-cocoa/actions/runs/3065964712/jobs/4950617570). 
=> ci: Fix fastlane bundle version mismatch

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryPerformanceTracker.m, Sources/Sentry/SentryUIViewControllerPerformanceTracker.m, Sources/Sentry/include/SentryPerformanceTracker+Private.h, Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerPerformanceTrackerTests.swift
I don't think this needs a changelog entry, what do you guys think?
Closes #2125
Unit test
=> fix: Use the `component` name source for SentryPerformanceTracker

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift
See https://github.com/getsentry/sentry-cocoa/pull/2142#discussion_r969392752
=> fix: Make testAsyncStacktraces pass again 

.github/workflows/test.yml, scripts/xcode-test.sh, test-server/Package.swift
Compiles the test server only once and stores it as an artifact. This allows us
to run the `SentryNetworkTrackerIntegrationTests` on iOS 12.
Fixes GH-1615
=> ci: Compile test-server once

.sauce/benchmarking-config.yml
Don't pin specific OS versions for test suites,
as when SauceLabs updates devices, the tests
start to fail.
=> ci: Use major OS versions for SauceLabs

Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
I've checked "automatically manage signing" on the "iOS-Swift" and "iOS-SwiftClip" targets, so that I can run the app on my actual device and let Xcode register my device etc (after discussing this with Philip). If I undo those checkmarks I am pretty sure I am back to a non-working setup where it needs a provisioning profile that doesn't include my device.
Is there a reason not to check this for debug builds on these 2 targets? Will this mess with CI? Let's find out! 😅
=> meta: Automatically manage signing

Sources/Sentry/SentryDispatchQueueWrapper.m, Sources/Sentry/SentryTracer.m, Sources/Sentry/include/SentryDispatchQueueWrapper.h, Tests/SentryTests/Networking/TestSentryDispatchQueueWrapper.swift, Tests/SentryTests/Performance/SentryTracerTests.swift
The testIdleTimeout_InvokesDispatchAfterWithCorrectWhen always failed on M1 Macs. This was because we used a different way of calculating the expected dispatch_time in the tests than in the ObjC code. The failing test's purpose is to validate that the proper timeout is used to schedule the cancel block. This PR restructures the code so the SentryDispatchQueueWrapper hides this complexity, and callers don't need to calculate the dispatch_time themselves. Now the test validates that the proper timeout is passed down to SentryDispatchQueueWrapper.
Fixes GH-2164
=> test: Fix dispatch failure on M1

Sources/Sentry/Public/SentryOptions.h
The code docs on enableNetworkTracking were stating wrong information. This is fixed now.
Fixes GH-2191
=> docs: Fix network option code docs

Sources/Sentry/SentryAppStartTracker.m, Sources/Sentry/SentryCrashIntegration.m, Sources/Sentry/SentryOutOfMemoryTracker.m, Sources/Sentry/SentrySessionTracker.m
According to Apple docs it's better to remove NSNotification observers with the most specific detail possible. This came up when investigating flaky SentrySessionTracker tests.
=> ref: Specifically remove notification observers

Sources/Sentry/SentrySession.m, Sources/Sentry/include/SentrySession+Private.h, Tests/SentryTests/Integrations/Session/SentrySessionTrackerTests.swift, Tests/SentryTests/SentrySessionTests.swift
Previously, the assert message displayed the raw value of the SessionStatus. Now it shows the string description.
=> test: Session status description for failing tests

.github/workflows/test.yml, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryAutoSessionTrackingIntegration.m, Sources/Sentry/SentryDependencyContainer.m, Sources/Sentry/SentryNSNotificationCenterWrapper.m, Sources/Sentry/SentryOutOfMemoryTracker.m, Sources/Sentry/SentrySessionTracker.m, Sources/Sentry/include/SentryDependencyContainer.h, Sources/Sentry/include/SentryNSNotificationCenterWrapper.h, Sources/Sentry/include/SentrySessionTracker.h, Tests/SentryTests/Helper/SentryNSNotificationCenterWrapperTests.swift, Tests/SentryTests/Helper/TestNSNotificationCenterWrapper.swift, Tests/SentryTests/Integrations/NotificationCenterTestCase.swift, Tests/SentryTests/Integrations/Session/SentrySessionTrackerTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
Testing with NSNotificationCenter in CI leads to flaky tests.
Therefore, we use a wrapper around NSNotificationCenter to not
depend on it. Instead, we call the methods NSNotificationCenter
would call with Dynamic and ensure that sut properly subscribes
to NSNotificationCenter.
Fixes https://github.com/getsentry/sentry-cocoa/issues/2062
Unit tests.
=> test: Fix flaky session tracker tests

Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m, Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS13-Swift.xcscheme, Samples/iOS-Swift/iOS13-Swift/AppDelegate.swift, Samples/macOS-Swift/macOS-Swift.xcodeproj/xcshareddata/xcschemes/macOS-Swift.xcscheme, Samples/macOS-Swift/macOS-Swift/AppDelegate.swift
I've needed to test profiling in a few other apps that didn't have it yet. Instead of just adding it to always run, I gated it behind a launch argument.
Also turned debugging back on for macOS-Swift runs.
=> meta: allow enabling profiling in more sample apps

fastlane/Fastfile
The re-enabled Benchmark test doesn't work with automatic code signing which we enabled a little while ago.
Closes #2207
=> ci: Fix broken Benchmark test

CHANGELOG.md, Sources/Sentry/Public/SentryOptions.h
Make file IO tracking GA and keep it disabled by default.
The feature was in beta since the beginning of 2022 with https://github.com/getsentry/sentry-cocoa/pull/1557. We have 45 orgs that tried the feature in the past 90 days and didn't report any issues. Therefore it's safe to remove the experimental flag for this.
Docs PR https://github.com/getsentry/sentry-docs/pull/5548
=> feat: File I/O Tracking GA

CHANGELOG.md, Sources/Sentry/Public/SentryOptions.h, fastlane/Fastfile
Make core data IO tracking GA and keep it disabled by default.
The feature has been in beta since around March 2022 with https://github.com/getsentry/sentry-cocoa/pull/1682. We have 45 orgs that tried the feature in the past 90 days and didn't report any issues. Therefore it's safe to remove the experimental flag for this.
Docs PR https://github.com/getsentry/sentry-docs/pull/5548
=> feat: Core Data Tracking is stable

.github/workflows/benchmarking.yml, .github/workflows/saucelabs-UI-tests.yml
Add cache for benchmarks and saucelabs UI tests again, but don't skip compiling.
Related to https://github.com/getsentry/sentry-cocoa/pull/2210.
=> ci: Read cache for UI tests

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryCrashIntegration.m, Sources/Sentry/SentryCrashWrapper.m, Sources/Sentry/include/SentryCrashWrapper.h, Sources/Sentry/include/SentryInternalDefines.h, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitorContext.h, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.h, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m, Sources/SentryCrash/Recording/SentryCrash.m, Sources/SentryCrash/Recording/SentryCrashReport.c, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryCrash/TestSentryCrashWrapper.h, Tests/SentryTests/SentryCrash/TestSentryCrashWrapper.m
This should make it clear what kind of size these variables are. Are they KB, MB, GB? Nope, they are all bytes.
=> ref: Add typealias for bytes

CHANGELOG.md, Sources/Sentry/include/SentryCoreDataTracker.h, Tests/SentryTests/Integrations/Performance/CoreData/SentryCoreDataTrackerTest.swift, Tests/SentryTests/Integrations/Performance/CoreData/SentryCoreDataTrackingIntegrationTest.swift
Rename db.query to db.sql.query and db.transaction to db.sql.transaction.
[Aligning span operation names](https://www.notion.so/sentry/Set-up-an-audit-for-SDK-consistency-for-span-operations-to-enable-performance-issues-addf02a8fa234dda8acf48d4ff9b8efb).
Unit tests.
=> fix: Align core data span operations

CHANGELOG.md
The PR was reverted with https://github.com/getsentry/sentry-cocoa/pull/2225.
=> meta: Fix Changelog concurrent transactions

Sources/Sentry/SentryTracer.m
Clarify the concept of waitForChildren with renamings and adding some comments.
It was a bit confusing for @armcknight.
=> ref: Clarify waitForChildren in SentryTracer

.github/CODEOWNERS
I think we only added @indragiek because I was on parental leave. As I've been back for over a month already,
I think we can safely remove you, @indragiek.
=> meta: Remove Indragie from code owners

CHANGELOG.md, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m
This uses the check as suggested in the ticket, and I've found similar suggestions in StackOverflow and in HockeySDK-iOS (the old HockeyApp SDK). But I have no way of verifying this, and it feels a bit scary. I am also not sure how well this will age, maybe this will change with future iOS versions?
If users already have a way of overriding the build type, I am not 100% convinced we should add this to the SDK.
Closes #778
Impossible :/
=> fix: Correctly attribute enterprise builds

CHANGELOG.md
The feature list will show start-up crashes after merging https://github.com/getsentry/sentry-docs/pull/5579.
=> meta: Changelog link start-up crashes

.github/workflows/benchmarking.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/format-code.yml, .github/workflows/integration-tests.yml, .github/workflows/profile-data-generator.yml, .github/workflows/saucelabs-UI-tests.yml, .github/workflows/stale.yml, .github/workflows/test.yml, .github/workflows/testflight.yml
Used `Get-ChildItem . -Filter *.yml | Foreach-Object { pin-github-action --allow 'actions/*,getsentry/*' $_.FullName }` and manually reverted the most disturbing formatting changes it's making (line breaks on long lines)...
There should be no need to do this again + new PRs will automatically get a failure through Danger.
=> ci: update and pin GHA to commit hash

.github/workflows/lint.yml
Since October 3rd, the default Xcode version is 14.0.1 on [GH actions macos-12](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md), which breaks pod lib lint. Ideally, we fix the underlying issue but for now, let's keep using Xcode 13.4.1 for pod lib lint.
Issue for making it work for Xcode 14.0.1 https://github.com/getsentry/sentry-cocoa/issues/2254
=> ci: Fix Validate podspec

.github/workflows/lint.yml
Pod lib lint runs validations for all platforms sequentially. We can speed up CI by using a matrix for each platform, so they run in parallel.
=> ci: Run pod lib lint in parallel

.github/workflows/build.yml
Was broken with https://github.com/getsentry/sentry-cocoa/pull/2256, as this PR removed it from the workspace. Now we call the
project directly.
=> ci: Fix building watchOS sample

Sources/Sentry/SentryAppStateManager.m, Sources/Sentry/SentryFileManager.m, Sources/Sentry/SentryOutOfMemoryLogic.m, Sources/Sentry/SentryOutOfMemoryTracker.m, Sources/Sentry/SentrySDK.m, Sources/Sentry/include/SentryAppStateManager.h, Sources/Sentry/include/SentryFileManager.h, Tests/SentryTests/Helper/SentryFileManagerTests.swift, Tests/SentryTests/Integrations/OutOfMemory/SentryOutOfMemoryTrackerTests.swift, Tests/SentryTests/Integrations/SentryCrash/SentryCrashIntegrationTests.swift, Tests/SentryTests/TestClient.swift
From my chat with Philipp:
> The thing that worries me the most with the OOM implementation is `SentryAppState *previousAppState = [self.appStateManager loadCurrentAppState]` inside of `SentryOutOfMemoryLogic`. That seems so vulnerable to a race condition, as `SentryOutOfMemoryTracker.start` actually writes a brand new app state to disk. 
> 
> I know that it executes `[self.outOfMemoryLogic isOOM]` before `[self.appStateManager storeCurrentAppState]`, but still.. seems a bit fragile.
> 
> Same with `SentrySessionCrashedHandler.endCurrentSessionAsCrashedWhenCrashOrOOM`: it also calls `SentryOutOfMemoryLogic.isOOM`. And it relies on the order of the integrations basically to make sure that this is done before starting the OOM integration.
We can fix this possible race condition in two ways: …
=> ref: Remove a possible race condition related to reading previous app state

CHANGELOG.md, Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Sources/Sentry/SentryTracer.m, Tests/SentryTests/Integrations/Performance/IO/SentryFileIOTrackingIntegrationTests.swift, Tests/SentryTests/Performance/SentryTracerTests.swift, Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift
The SDK added the app start measurement and spans to the first finished auto-generated UIViewController transaction. The first finished UIViewController transaction is not necessarily the transaction of the first loaded screen. As auto-generated transactions for UIViewControllers wait for all children to finish, it may kick off, for example, a web request that lasts for a couple of seconds in the background. In the meantime, the user navigates to another screen, which finishes loading before the web request. The SDK added the app start data to the wrong transaction in such an edge case. This is fixed now by adding the app start data to the first started transaction.
Fixes GH-2248
Unit tests and on a real device with the steps described in GH-2248.
[LoremIpsumViewController without the app …
=> fix: Add app start to first finished transaction

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Tests/SentryTests/Integrations/SentryCrash/SentryCrashIntegrationTests.swift
Disabling per https://github.com/getsentry/sentry-cocoa/issues/2269
=> test: disable testStartUpCrash_CallsFlush as it flakes

Brewfile.lock.json, Gemfile.lock, Samples/TrendingMovies/ProfileDataGeneratorUITest/ProfileDataGeneratorUITest.m, Samples/TrendingMovies/TrendingMovies.xcodeproj/xcshareddata/xcschemes/TrendingMovies.xcscheme, Samples/TrendingMovies/TrendingMovies/Movies/MovieCollectionViewCell.swift, Samples/TrendingMovies/TrendingMovies/Utilities/Tracer.swift
To help with demos, this generates profiles with either an efficient implementation of blurring a background image on a utility queue, vs on the main queue for an inefficient implementation. Each CI run generates multiple sessions; each session flips between using either efficient or inefficient methods. A tag is set on the scope to help find the different profiles.
=> test: generate profiles with different levels of efficiency

Samples/iOS-SwiftUI/iOS-SwiftUI.xcodeproj/project.pbxproj, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryAppStartTracker.m, Sources/Sentry/SentryAppState.m, Sources/Sentry/SentryAppStateManager.m, Sources/Sentry/SentryDependencyContainer.m, Sources/Sentry/SentryOutOfMemoryTracker.m, Sources/Sentry/SentrySessionTracker.m, Sources/Sentry/include/SentryAppStateManager.h, Tests/SentryTests/Helper/SentryAppStateManagerTests.swift, Tests/SentryTests/Integrations/OutOfMemory/SentryOutOfMemoryLogicTests.swift, Tests/SentryTests/Integrations/OutOfMemory/SentryOutOfMemoryTrackerTests.swift, Tests/SentryTests/Integrations/Performance/AppStartTracking/SentryAppStartTrackerTests.swift
Now the SentryAppStateManager is itself responsible for keep the app state up to date by listening to the various notifications. And both the OOM and AppStart trackers start this process, while making sure it's not started twice.
#skip-changelog (as nothing changes for the enduser)
Closes #1149
Unit tests
=> ref: Don't only update App State in the OOM tracker

Samples/TrendingMovies/ProfileDataGeneratorUITest/ProfileDataGeneratorUITest.m, Samples/TrendingMovies/TrendingMovies.xcodeproj/xcshareddata/xcschemes/TrendingMovies.xcscheme, Samples/TrendingMovies/TrendingMovies/Movies/MovieCellConfigurator.swift, Samples/TrendingMovies/TrendingMovies/Movies/MovieCollectionViewCell.swift, Samples/TrendingMovies/TrendingMovies/Movies/MoviesViewController.swift, Samples/TrendingMovies/TrendingMovies/Utilities/Tracer.swift
A previous PR introduced some inefficient implementations to the profile test data generator, so we can compare profiles for demo purposes (#2274). However, the spans it works with are too short. This introduces a span that runs the duration of a scroll operation in TrendingMovies' collection view, providing ample time to collect more information and hopefully produce profiles we can better use for demo purposes.
=> test: use a longer span to compare efficient implementations

.github/workflows/profile-data-generator.yml
Only run the profile data generator workflow on schedule.
@armcknight, any reason we should also run them on master and every PR? As they generate data, I think a scheduled run should be sufficient. These runs eat up quite some CI time, and I don't think we need to run them for every PR.
=> ci: Generate profile data only on schedule

.sauce/profile-data-generator-config.yml
Expand to any iPhone Pro and not only iPhone Pro Max 13 to speed up CI. 
Currently, the run profile data generator for high-end devices often times out, see, for example, https://github.com/getsentry/sentry-cocoa/actions/runs/3247850509/jobs/5329186271
=> ci: Specify only iPhone Pro for high-end devices

Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme, Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Tests/SentryTests/Integrations/OutOfMemory/SentryOutOfMemoryIntegrationTests.swift, Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerIntegrationTests.swift, Tests/SentryTests/Integrations/Session/SentrySessionGeneratorTests.swift, Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Recorded in https://github.com/getsentry/sentry-cocoa/issues/2287
=> test: disable flaky tests

CHANGELOG.md, Sources/Sentry/SentryHttpTransport.m, Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Use a double-checked lock to avoid unnecessary locks when calling flush. Also fix the flaky test testFlush_CalledMultipleTimes_ImmidiatelyReturnsFalse.
If this doesn't fix the flaky test, we could consider removing it or making it less strict. Calling flush on multiple threads in a tight loop is definitely an edge case.
I identified that we could use a double-checked lock while investigating the flaky test
`testFlush_CalledMultipleTimes_ImmidiatelyReturnsFalse` GH-2267
Unit tests.
=> perf: Use double-checked lock for flush

.sauce/profile-data-generator-config.yml
The high end tests quite often time out in Saucelabs. The tests usually pass in 10m or less. Reduce the timeout to speed up retry.
=> ci: Reduce saucelabs profile data timeout to 10m

Sources/Sentry/SentryCrashIntegration.m, Tests/SentryTests/TestUtils/SentryTestObserver.m
What I found via Google is that it's a bug with the iOS 15 and 16 simulator. And yup, it does run fine with iOS 14.
I don't think there is a "proper" fix for this, and just skipping these 2 lines seems to make a lot more sense than skipping the entire SentrySDK initialization.
Closes #2284
=> fix: Fix test hangs when accessing UIScreen.mainScreen

.github/workflows/profile-data-generator.yml
A couple PRs were submitted to try to shorten how long profile generation runs (https://github.com/getsentry/sentry-cocoa/pull/2291 and https://github.com/getsentry/sentry-cocoa/pull/2292). Overall, the job could still run up to an hour (the default GitHub Action timeout) in certain cases.
This sets a timeout on the GitHub action job that runs the saucelabs job, and ignores if that fails (like if it times out on their end). We can see from the dashboard if this job is really failing and can fix it in that case, but this particular workflow should never cause a CI failure since it's not really testing anything, just providing us with test data.
=> test: shorten profile generation jobs

Tests/SentryTests/TestUtils/SentryTestObserver.m
We can replace thread sleep with flush to wait until the event gets sent to Sentry.
=> test: Use flush in TestObserver

Tests/SentryTests/Integrations/Session/SentrySessionTrackerTests.swift, Tests/SentryTests/Integrations/UIEvents/SentryUIEventTrackerTests.swift, Tests/SentryTests/Networking/SentryHttpTransportTests.swift
We should all enable spellchecker in Xcode to help catch these kinds of things: 
=> fix: typos

.github/workflows/integration-tests.yml
Add a timeout for the VLC integration tests so they don't keep hanging forever when something goes wrong.
=> ci: Timeout for VLC tests

.github/workflows/test.yml
As we don't have any retry mechanisms, the tests sometimes time out, and the tests usually succeed in around seven minutes or less, we can reduce the timeout to 15 min.
=> ci: Reduce unit test timeout to 15 min

Sources/Sentry/Public/SentryOptions.h
Add proper code docs for `SentryOptions.dist`. Copied them from https://develop.sentry.dev/sdk/event-payloads/.
=> Fix code docs for options dist

CHANGELOG.md, Sources/Configuration/Sentry.xcconfig
Manually enabled bitcode
Xcode 14 changed the default value for BitCote to 'NO', now our framework generated with Carthage don't have the bitcode information and this causes warning on customer projects that uses bitcode. 
closes #2304
=> Enable bitcode

.github/workflows/testflight.yml, fastlane/Fastfile
Use a workaround pointed out in https://github.com/fastlane/fastlane/issues/20741. 
Fixes https://github.com/getsentry/sentry-cocoa/issues/2309
Workaround works see https://github.com/getsentry/sentry-cocoa/actions/runs/3295118090/jobs/5433332076
=> ci: Fix TestFlight upload with workaround

Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m, Samples/iOS-Swift/iOS-Swift/AppDelegate.swift, Samples/iOS-Swift/iOS-SwiftClip/AppDelegate.swift, Samples/iOS-Swift/iOS13-Swift/AppDelegate.swift, Samples/iOS-SwiftUI/iOS-SwiftUI/SwiftUIApp.swift, Samples/iOS15-SwiftUI/iOS15-SwiftUI/App.swift, Samples/macOS-Swift/macOS-Swift/AppDelegate.swift, Samples/tvOS-Swift/tvOS-SBSwift/AppDelegate.swift, Samples/tvOS-Swift/tvOS-Swift/AppDelegate.swift, Tests/SentryTests/TestConstants.swift, Tests/SentryTests/TestUtils/SentryTestObserver.m, scripts/add-sentry-to-alamofire.patch, scripts/add-sentry-to-homekit.patch, scripts/add-sentry-to-vlc.patch
It seems like somebody is using our test DSN. Let's rotate it and
soon deprecate the old one to eliminate the noise.
=> ci: Rotate test DSN

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Tests/SentryTests/SentryHubTests.swift
Issue to fix it https://github.com/getsentry/sentry-cocoa/issues/2314
=> Disable testProfilingDataContainsEnvironmentSetFromConfigureScope

Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj, Samples/iOS-Swift/iOS-Swift/AppDelegate.swift, Samples/iOS-Swift/iOS-Swift/Tools/MetricKitManager.swift
Add code to the iOS-Swift sample app to collect MetricKit payloads by sending them to Sentry as receiving an MXDiagnosticPayload via Xcode debug Simulate MeticKit Payload doesn't work.
Related to https://github.com/getsentry/sentry-cocoa/issues/1661
=> test: Collect MetricKit payloads

Sources/Sentry/Public/SentryEvent.h
The SentryEvent had a @class definition for SentryContext, which doesn't exist.
=> ref: Remove not existent SentryContext

.github/workflows/test.yml, Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift, develop-docs/README.md, scripts/ci-select-xcode.sh
GH actions will remove the macOS-10.15 image, which contains an iOS 12 simulator on 12/1/22; see https://github.com/actions/runner-images/issues/5583. Neither the[ macOS-11](https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md#installed-sdks) nor the [macOS-12](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#installed-sdks) image contains an iOS 12 simulator. GH [concluded](https://github.com/actions/runner-images/issues/551#issuecomment-788822538) to not add more pre-installed simulators. SauceLabs doesn't support running unit tests and adding another cloud solution as Firebase TestLab would increase the complexity of CI. Not running the unit tests on iOS 12 opens a risk of introducing bugs, which has already happened in …
=> ci: Remove macos-10.15 usage

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Tests/SentryTests/SentryHubTests.swift
try extending the delay to ensure that samples are taken, maybe this is what is causing debug image data to be absent
To fix #2300 and #2314.
=> test: fix profiling tests that stopped receiving debug image data

Sources/Sentry/SentryProfiler.mm, Tests/SentryTests/SentryHubTests.swift
To conform to the changes in https://github.com/getsentry/relay/pull/1462
=> ref: update profile payload schema

CHANGELOG.md, Sources/Configuration/Sentry.xcconfig
Disabled bitcode
We [recently](https://github.com/getsentry/sentry-cocoa/pull/2307) enabled bitcode because of some [complaints](https://github.com/getsentry/sentry-cocoa/issues/2304) (plus Unity project not compiling), this is basically a breaking change, but one enforced by Apple.
It turns out Apple will not accept new Apps with bitcode enabled, the solution for this complaints will be to tell users to also disabled it in their projects.
From [Apple's release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes) 
> Deprecations
Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.
> 
> Xcode no longer builds bitcode by default and generates a …
=> feat: Disable bitcode for Carthage distribution

CHANGELOG.md, Sources/Sentry/SentryProfiler.mm, Tests/SentryTests/Profiling/SentryProfilerTests.mm
Fixes https://github.com/getsentry/sentry-cocoa/issues/2342
=> fix: dont require profiler to start on main thread

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Tests/SentryTests/Networking/SentryHttpTransportTests.swift
failing: https://github.com/getsentry/sentry-cocoa/actions/runs/3342304891/jobs/5534412242#step:9:42
passing again: https://github.com/getsentry/sentry-cocoa/actions/runs/3342304891/jobs/5546207690
=> test: disable flaky testFlush_CalledMultipleTimes_ImmediatelyReturnsFalse

Sources/Sentry/SentryHttpTransport.m, Sources/Sentry/SentryLog.m, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/include/SentryLog.h, Tests/SentryTests/Helper/SentryLogTests.swift, Tests/SentryTests/Integrations/SentryBaseIntegrationTests.swift, Tests/SentryTests/Transaction/SentrySpanTests.swift
As I've been adding more logging, it's getting harder to keep track of things. This PR adds a new part to the format denoting which class/file the log originated from (and the line number). I also standardized how the different tokens are formatted in the log statement, like our SDK name, log level, and the newly added log source.
Before:
```
Sentry - debug:: SentryFileManager.cachePath: /Users/andrewmcknight/Library/Developer/CoreSimulator/Devices/9DA57C91-8188-405D-87DD-4CCFFD376F99/data/Containers/Data/Application/0D15944C-6F34-4C95-BE40-3E9B5CF41ED9/Library/Caches
Sentry - debug:: SentryHttpTransport: sendAllCachedEnvelopes start.
Sentry - debug:: SentryHttpTransport: No envelopes left to send.
Sentry - debug:: SentryHttpTransport: Finished sending.
Sentry - debug:: SDK initialized! …
```
=> meta: add log source to format; update log format

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Sources/Sentry/include/SentrySystemEventBreadcrumbs.h, Tests/SentryTests/Integrations/Breadcrumbs/SentrySystemEventBreadcrumbsTest.swift
Locally it never failed; I can run it 1000 times repeatedly and it will succeed just fine. Maybe adding this tiny sleep will help on CI.
Closes #2247
=> fix: Fixed flaky testTimezoneChangeNotificationBreadcrumb

Sources/Sentry/SentryProfiler.mm, Sources/Sentry/include/NSDate+SentryExtras.h, Tests/SentryTests/Profiling/SentryProfilerSwiftTests.swift
This was causing profiles with the new schema to fail validation.
=> fix: sampled profile format validation errors

CHANGELOG.md, Sources/Sentry/SentryCoreDataTracker.m, Tests/SentryTests/Integrations/Performance/CoreData/SentryCoreDataTrackerTest.swift, Tests/SentryTests/Integrations/Performance/CoreData/SentryCoreDataTrackingIntegrationTest.swift, Tests/SentryTests/Integrations/Performance/CoreData/TestCoreDataStack.swift
Fixes #2328 and possible bug in CoreData tracker.
I originally noticed a system error logged for us using a non-designated initializer for an NSManagedObject subclass. Fixing that led to some test failures: 
which led to me discovering that we might have only ever tracked CoreData entity transactions using "NSManagedObject" in the span descriptions instead of the actual entity names being used by developers.
=> fix: CoreData tracking entity name retrieval

.github/workflows/lint.yml, Makefile
Call make analyze in CI, so you can quickly run analyze locally with the same config as in CI.
=> ci: Call make for analyze

CHANGELOG.md, Sources/SentryCrash/Recording/Tools/SentryCrashJSONCodec.c, Tests/SentryTests/SentryCrash/SentryCrashJSONCodec_Tests.m
Instead of writing `nan` (which is invalid for json format) in the crash report for invalid numbers, start writing `null`.
closes #2327 
Unit test
=> fix: SentryCrash writing nan for invalid number

Samples/macOS-SPM-CommandLine/Sources/macOS-SPM-CommandLine/main.swift
Replace delay with DispatchQueue with flush.
=> test: Use flush for macOS-SPM sample

CHANGELOG.md, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/SentrySpan.m, Sources/Sentry/SentryTracer.m, Tests/SentryTests/Profiling/SentryProfilerSwiftTests.swift
follows on with #2358 to fix some backend validation issues with how we're building profiles in the client. fixes #2352 
The quick fix here is to simply discard transactions that end before the profiler started, and discard profiles that have no transactions associated after removing such. This will probably always be a good check to make, but we will want to try to minimize the time between transaction start and profiler start, so we can still gather shorter and shorter transactions instead of throwing them out.
=> fix: profiling transaction timestamps

.github/workflows/format-code.yml, CONTRIBUTING.md
Explain why GH actions can suddenly format code
differently.
=> docs: Why GH actions formats code differently

Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerIntegrationTests.swift
`testGetCaptureFailedRequestsEnabled` should fail and not crash when the test server is not running.
=> test: Fixing 'testGetCaptureFailedRequestsEnabled'

Samples/iOS-Swift/iOS-Swift/Tools/iOS-Swift-Bridging-Header.h, Samples/iOS-Swift/iOS13-Swift/iOS13-Swift-Bridging-Header.h, Sentry.podspec, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/Public/Sentry.h, Sources/Sentry/include/PrivateSentrySDKOnly.h
Remove PrivateSentrySDKOnly.h from umbrella headers to prevent users from use it by mistake.
=> chore: Remove PrivateSentrySDKOnly.h from umbrella header

CHANGELOG.md, Sources/Sentry/Public/SentryOptions.h, Sources/Sentry/SentryClient.m, Tests/SentryTests/SentryClientTests.swift
Reverts getsentry/sentry-cocoa#2368
We can already track this in Looker with the mechanism type
https://github.com/getsentry/sentry-cocoa/blob/59afa00cc8164effb2b774ed683685eda7ae017c/Sources/Sentry/SentryNetworkTracker.m#L339
Sorry about that, @kevinrenskers. We can undo this PR. No need to send the data twice.
=> Revert "feat: Track usage of the enableCaptureFailedRequests option"

fastlane/Fastfile
Add a new task to Fastfile that recreate certificates and provisioning profiles.
=> chore: Add match_local to Fastfile

CHANGELOG.md, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/include/SentryProfiler+Test.h, Tests/SentryTests/Profiling/SentryProfilerTests.mm, Tests/SentryTests/SentryTests-Bridging-Header.h
There were a couple remaining issues with profile payloads:
- sometimes we still try to send an envelope with 0 samples, presumably for very fast start/stop of profiler. we simply discard these and log for now
- we weren't deduplicating frames across an entire profile, only per sample
- we weren't performing a correct deep equality check between stacks
=> fix: profile payload issues

.pre-commit-config.yaml, Makefile, Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
Split Swift and Clang format for pre-commit, so it runs faster. 
Now, if you only edit Swift files, clang-format doesn't run. 
##skip-changelog
=> build: Split Swift and Clang format for pre-commit

Sources/Sentry/SentrySessionTracker.m
Came up in https://github.com/getsentry/sentry-cocoa/issues/2150#issuecomment-1308532229.
=> ref: Fix outdated comment in SessionTracker

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Tests/SentryTests/Protocol/SentryNSErrorTests.swift
Flaky run https://github.com/getsentry/sentry-cocoa/actions/runs/3465967126/jobs/5789326262.
PR to fix https://github.com/getsentry/sentry-cocoa/issues/2388.
=> test: Disable flaky testSerializeWithUnderlyingNSException

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Tests/SentryTests/SentryCrash/SentryCrashReportStore_Tests.m
Flaky run https://github.com/getsentry/sentry-cocoa/actions/runs/3468073035/jobs/5793558333.
Issue to fix https://github.com/getsentry/sentry-cocoa/issues/2390
=> test: Disable flaky testCrashReportCount1

.github/workflows/test.yml
The unit tests for iOS 12 need to install a simulator first, which can take a couple of minutes.
The job sometimes times out in CI. We can increase the timeout only for that job.
=> ci: Increase test timeout for iOS 12

Sources/Sentry/PrivateSentrySDKOnly.m, Sources/Sentry/include/PrivateSentrySDKOnly.h, Sources/Sentry/include/SentryScreenshot.h
To avoid duplication code I would like to expose the screenshot function via the PrivateSDKOnly header.
- https://github.com/getsentry/team-mobile/issues/11
- https://github.com/getsentry/sentry-react-native/pull/2610
Not yet.
=> feat(hybrid-sdks): Add captureScreenshots to PrivateSDKOnly

Tests/SentryTests/Helper/SentrySerializationTests.swift
Fix flaky test
SentrySerializationTests.testSerializationFailsWithInvalidJSONObject
=> test: Fix SentrySerializationTests.testSerializationFailsWithInvalidJSONObject

CHANGELOG.md, Sources/Sentry/SentryOutOfMemoryTracker.m, Tests/SentryTests/Integrations/OutOfMemory/SentryOutOfMemoryTrackerTests.swift
Use the last breadcrumb's timestamp as the OOM event timestamp
Fixes #2383
Unit tests, and ran the sample app, creating an OOM and waiting a few minutes before starting the app again. The OOM event has the correct timestamp: https://sentry.io/organizations/sentry-sdks/issues/2291658301/?project=5428557&query=is%3Aunresolved&referrer=issue-stream.
=> Fix: Set the correct OOM event timestamp

.github/workflows/benchmarking.yml, .github/workflows/profile-data-generator.yml, .github/workflows/saucelabs-UI-tests.yml
Previously, test apps that link in compiled Sentry sources weren't getting rebuilt even if the sentry sources changed.
=> test: include Sentry changes in hash keys

Tests/SentryTests/ClearTestState.swift
To avoid unnecessary extra work.
=> test: Disable NSDataTracker in clearTestState

Tests/SentryTests/Integrations/Performance/SentryPerformanceTrackerTests.swift, Tests/SentryTests/Performance/SentryTracerTests.swift, Tests/SentryTests/SentryScopeSwiftTests.swift, Tests/SentryTests/TestClient.swift
This reverts commit 189472a1a0654f1c4f94941fefa46da76eb05a4a.
I should have merged this to 8.0.0.
=> Revert "test: shorten some tests (#2422)"

Tests/SentryTests/Integrations/Performance/SentryPerformanceTrackerTests.swift, Tests/SentryTests/Performance/SentryTracerTests.swift, Tests/SentryTests/SentryScopeSwiftTests.swift, Tests/SentryTests/TestClient.swift
Original PR https://github.com/getsentry/sentry-cocoa/pull/2422. I merged this accidentally to master. Should be merged to 8.0.0.
=> test: shorten some tests

Sources/Sentry/SentryFileManager.m, Sources/Sentry/SentryPerformanceTracker.m, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/SentrySpan.m, Sources/Sentry/SentrySpanContext.m, Sources/Sentry/SentrySwizzleWrapper.m, Sources/Sentry/SentryTracer.m, Sources/Sentry/SentryTransactionContext.mm, Sources/Sentry/SentryUIEventTracker.m, Sources/Sentry/SentryUIViewControllerPerformanceTracker.m, Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerPerformanceTrackerTests.swift, Tests/SentryTests/Profiling/SentryProfilerSwiftTests.swift, Tests/SentryTests/TestLogOutput.swift, Tests/SentryTests/TestUtils/SentryTestObserver.m
I accumulated a lot of added logs while debugging another branch so wanted to separate these out into a separate PR to cut down the noise in the other one (https://github.com/getsentry/sentry-cocoa/pull/2228)
=> meta: add/improve logging

Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerPerformanceTrackerTests.swift, Tests/SentryTests/Networking/SentryHttpTransportTests.swift, Tests/SentryTests/SentrySDKTests.swift
While testing after making changes for #2228, the test suite would crash in various places due to changes in behavior changing e.g. the amount of things in an array. Change such logic to allow graceful degradation into simply failing the test case instead of crashing the test run.
=> test: prevent crashing on nil or index out of bounds

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Tests/SentryTests/Transaction/SentrySpanTests.swift
Ticket to fix the test: https://github.com/getsentry/sentry-cocoa/issues/2437.
=> tests: Disable flaky testAddAndRemoveData

CHANGELOG.md, Sources/Sentry/SentryHub.m, Sources/Sentry/SentrySession.m, Sources/Sentry/include/SentrySession+Private.h, Tests/SentryTests/SentryHubTests.swift
Errors shortly after SentrySDK.init now do affect the session.
Closes #2150
Unit test
=> fix: Errors shortly after SentrySDK.init don't affect the session

CHANGELOG.md, Sources/Sentry/SentryANRTrackingIntegration.m, Tests/SentryTests/Integrations/ANR/SentryANRTrackingIntegrationTests.swift
Marked App hang's event stacktrace snapshot as true.
Fixes #2323 
Unit test
=> feat: Marks App hang's event stacktrace snapshot as true

Sources/Sentry/Public/SentryEvent.h
Updated the description of `transaction` property in  `SentryEvent` to copy develop docs description.
This is the last think to close #1437 
=> chore: Update description for Event.transaction

.github/workflows/integration-tests.yml
Fixed the web integration test by pinning the version of `firewalk`
=> fix: Fix web integration test

CHANGELOG.md, Samples/iOS-Swift/iOS-Swift/ViewController.swift, Sources/Sentry/Public/SentryUser.h, Tests/SentryTests/Protocol/SentryUserTests.swift, Tests/SentryTests/Protocol/TestData.swift, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryHubTests.swift, Tests/SentryTests/SentryScopeSwiftTests.swift, Tests/SentryTests/SentrySessionTests.swift, Tests/SentryTests/Transaction/SentryTraceStateTests.swift
Reverted renaming of User to SentryUser
=> revert: Rename of User to SentryUser

CHANGELOG.md, Sources/Sentry/SentryAppState.m, Sources/Sentry/SentryAppStateManager.m, Sources/Sentry/SentryOutOfMemoryLogic.m, Sources/Sentry/include/SentryAppState.h, Tests/SentryTests/Helper/SentryAppStateManagerTests.swift, Tests/SentryTests/Helper/SentryAppStateTests.swift, Tests/SentryTests/Integrations/OutOfMemory/SentryOutOfMemoryTrackerTests.swift, Tests/SentryTests/SentrySDKTests.swift
The app state has a new property `isSDKRunning` which gets set to `false` when the SDK closes. This property is then used in the OOM logic, returning `false` when `isSDKRunning` is `false`.
Closes #2457
Unit tests, and steps as described in #2457.
=> fix: SDK reports OOM when crashing after calling close

Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard, Samples/iOS-Swift/iOS-Swift/ViewController.swift
This was needed to reproduce #1667, but is still handy to keep in the sample project.
=> chore: Added a force unwrapped optional crash to the sample project

Samples/TrendingMovies/TrendingMovies/Utilities/Tracer.swift
https://github.com/getsentry/sentry-cocoa/pull/2408 changed API that broke TrendingMovies but was not caught in CI due to invalid caching strategy (fixed in #2479 )
=> fix: trending movies build

.github/workflows/benchmarking.yml, .github/workflows/profile-data-generator.yml, .github/workflows/saucelabs-UI-tests.yml
We were trying to compute a cache key on an invalid path, which did not invalidate the cached app builds when they should have been to test changes to the SDK.
I actually also found a build error on the default branch in trending movies indicating that it hasn't been built since the change that made that code invalid: https://github.com/getsentry/sentry-cocoa/pull/2480
=> ci: fix caching in some CI jobs

.github/workflows/test.yml
Codecov uploads sometimes fail. There is a workaround for this as described in https://github.com/codecov/codecov-action/issues/557#issuecomment-1224970469
=> ci: Specify Codecov token

.github/workflows/test.yml, .slather.yml, Gemfile, Gemfile.lock, Makefile, scripts/xcode-test.sh
Slather, most of the time, reported code coverage of 0%. This is fixed now by removing the extra flags when calling Xcode
`GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES -enableCodeCoverage YES` as we already enable gathering code coverage in the Xcode schema.
Furthermore, `make test` calls the `xcode-test.sh` to make it easier to call unit tests the same way CI does.
=> ci: Fix Slather for Codecov

.github/workflows/format-code.yml, Brewfile.lock.json, Samples/TrendingMovies/TrendingMovies/ImageProcessing/ColorArt.swift, Samples/iOS-Swift/iOS-Swift/ViewControllers/PerformanceViewController.swift, Sources/Sentry/SentryCurrentDate.m, Sources/Sentry/SentryDateUtil.m, Tests/SentryTests/Integrations/Performance/AppStartTracking/SentryAppStartTrackerTests.swift, Tests/SentryTests/Integrations/SentryCrash/SentryCrashScopeObserverTests.swift, Tests/SentryTests/Networking/SentryHttpTransportTests.swift, Tests/SentryTests/SentryCrash/SentryCrashReportSinkTests.swift, Tests/SentryTests/SentryScopeSwiftTests.swift
I am running a different version of SwiftLint locally, and CI is running an old version, which causes code formatting mismatches, so CI keeps overwriting the code formatting again. See the commit history in https://github.com/getsentry/sentry-cocoa/pull/2489.
Not sure if this is the correct way to fix it? Let's see.
=> chore: Update homebrew bundle

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryMetricKitIntegration.m, Tests/SentryTests/Integrations/MetricKit/SentryMetricKitIntegrationTests.swift, Tests/SentryTests/TestUtils/FormatHexAddress.swift
MXFrames are in reversed order compared to how we order them in Sentry. This is fixed now by reversing them.
This is one of the multiple fixes for the MetricKit integration. Instead of doing all of them in one branch, I split these up into multiple PRs targeting the `feat/metric-kit` branch so they are easier to review.
Unit tests and sending sample crash events see
Before: https://sentry.io/organizations/sentry-sdks/issues/3780372963/events/5c5a780f3b6c48a58c287e84f36c8255/?project=5428557
After: https://sentry.io/organizations/sentry-sdks/issues/3780372963/events/7aa6bfda7bd443daa4894f858c72c6c7/?project=5428557
=> fix: MXFrames reversed

CHANGELOG.md, Sources/Sentry/Public/SentryMechanism.h, Sources/Sentry/SentryMechanism.m, Tests/SentryTests/Protocol/SentryMechanismTests.swift, Tests/SentryTests/Protocol/TestData.swift
Add synthetic property for SentryMechanism as it's part of the protocol https://develop.sentry.dev/sdk/event-payloads/exception/#exception-mechanism
https://github.com/getsentry/sentry-cocoa/issues/1192
Unit tests
=> feat: Add synthetic for mechanism

CHANGELOG.md, Sources/Sentry/Public/SentryOptions.h
Remove the EXPERIMENTAL comment.
Part of #2298.
No tests needed. Just removing a comment.
=> feat: enableUserInteractionTracing is GA

CHANGELOG.md
See https://github.com/getsentry/sentry-cocoa/blob/bd284cf0e4c0c759aebc240e29d1569b44a3d5ea/Sources/Sentry/SentryOptions.m#L81
=> meta: User interaction tracing enabled per default

Tests/SentryTests/Helper/TestNSNotificationCenterWrapper.swift, Tests/SentryTests/SentryCrash/SentryCrashInstallationTests.m
Two asserts wrapped with SentryCrashCRASH_HAS_UIAPPLICATION were not executed. This is fixed now.
Came up in https://github.com/getsentry/sentry-cocoa/pull/2440#discussion_r1035083448
=> test: Fix asserts for SentryCrashTestInstallation

CHANGELOG.md, Sources/Sentry/SentryClient.m, Tests/SentryTests/SentryClientTests.swift
The client attached the current app, permission, and culture context to crashes. We can't guarantee that this data matches the data of a previous run when the app crashed. As this data could be misleading, we remove it from crashes.
I came across this while removing context data for MetricKit events.
Unit tests.
Make the removed context data available for crashes with https://github.com/getsentry/sentry-cocoa/issues/2524.
=> fix: Don't add out of date context for crashes

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Sources/Sentry/SentryAppStateManager.m, Sources/Sentry/SentryFileManager.m, Tests/SentryTests/Integrations/WatchdogTerminations/SentryWatchdogTerminationsIntegrationTests.swift, Tests/SentryTests/TestClient.swift
- The test calls `SentryWatchdogTerminationTrackingIntegration.anrDetected`.
- This calls `self.appStateManager.updateAppState`, but that used the TestFileManager under the hood!
- `updateAppState` fails because `[self.fileManager readAppState]` returns `nil`.
Using the normal file manager fixes the test. 
Closes #2522
Unit test
=> Fix and reenable testANRDetected_UpdatesAppStateToTrue

CHANGELOG.md, Sources/Sentry/SentryFileManager.m, Tests/SentryTests/Helper/SentryFileManagerTests.swift
The SentryFileManager kept a strong reference to self for running code 10 seconds delayed. The strong reference stops ARC from deallocating the SentryFileManager. This is fixed now by using a weak reference.
Came across this cause tests are sometimes crashing with `malloc: double free for ptr`
The raw logs show logs from SentryFileManager
```
Test Case '-[SentryTests.SentryProfilerSwiftTests testStartTransaction_NotSamplingProfileUsingSampleRate]' started.
2022-12-13 09:52:30.402191+0000 xctest[5072:27885] [Sentry] [error] [SentryFileManager:215] Couldn't load files in folder /Users/runner/Library/Caches/io.sentry/envelopes/envelopes: Error Domain=NSCocoaErrorDomain Code=260 "The folder “envelopes” doesn’t exist." UserInfo={NSFilePath=/Users/runner/Library/Caches/io.sentry/envelopes/envelo …
```
=> fix: ARC issue for FileManager

CHANGELOG.md, Sources/Sentry/SentryOptions.m, Tests/SentryTests/SentryOptionsTest.m
We now read the `SENTRY_DSN` environment variable, on macOS only.
Closes #2515 
Unit tests
=> feat: support SENTRY_DSN environment var on macOS

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Sources/Sentry/SentryUIApplication.m, Sources/Sentry/include/SentryUIApplication.h, Tests/SentryTests/MockUIScene.h, Tests/SentryTests/MockUIScene.m, Tests/SentryTests/SentryTests-Bridging-Header.h, Tests/SentryTests/SentryUIApplicationTests.swift
Add a check to ensure application delegate has window
Unit Tests
=> fix: Screenshot crashes when application delegate has no window. 

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Tests/SentryTests/Transaction/SentrySpanTests.swift
I initially thought the test had failed twice, but it was actually only once. And the test failure wasn't a real test failure I think:
```
Failing tests:
SentryTests:
SentrySpanTests.testAddAndRemoveData()
```
But absolutely nowhere is there any information on which assert failed, and how. But since the test only uses `XCTAssertEqual` and `XCTAssertNil`, we should get proper failure messages. 
So I don't know why the test failed in https://github.com/getsentry/sentry-cocoa/actions/runs/3530734813/jobs/5923080490, but I don't think it's because the actual test function is flaky.
=> tests: Reenable testAddAndRemoveData

CHANGELOG.md, Sources/Sentry/SentryFileManager.m, Tests/SentryTests/Helper/SentryFileManagerTests.swift, Tests/SentryTests/Integrations/WatchdogTerminations/SentryWatchdogTerminationsTrackerTests.swift, Tests/SentryTests/Networking/TestSentryDispatchQueueWrapper.swift
The SentryFileManager deleted old envelopes after 10 seconds, which resulted in accessing double-freed pointers. We delayed the deletion for 10 seconds to avoid additional operations when starting the SDK. As the overhead of deleting the old envelope items should be minimal, we remove the delay because this is simpler than not running the delayed deletion for tests and reduces complexity.
Crashes in tests related to the deletion of the old envelopes.
Unit tests.
=> fix: Remove delay for deleting old envelopes

Tests/SentryTests/Helper/TestNSNotificationCenterWrapper.swift, Tests/SentryTests/Integrations/Breadcrumbs/SentrySystemEventBreadcrumbsTest.swift
The SystemEventBreadcrumbTests are failing in CI. We had a similar problem in the past that we fixed by using the TestNSNotificationCenterWrapper.
=> test: Fix SystemEventBreadcrumbTests

CHANGELOG.md, Sources/Sentry/SentryHttpTransport.m, Tests/SentryTests/Networking/SentryHttpTransportTests.swift, Tests/SentryTests/Networking/TestSentryReachability.swift
Dealloc for the SentryHttpTransport was never called. This is fixed now by using weak references to break the strong reference cycle.
Came across this while investigating test crashes due to `malloc: double free for ptr`.
Unit tests.
=> fix: Strong reference cycle for HttpTransport

CHANGELOG.md, Sources/Sentry/SentryFileManager.m, Tests/SentryTests/Helper/SentryFileManagerTests.swift
The SentryFileManager doesn't append the DSN hash to the basePath if the DSN is nil. We didn't handle this edge case when deleting old envelopes. This is fixed now.
Came up while investigating flaky tests, such as https://github.com/getsentry/sentry-cocoa/actions/runs/3792592319.
```
Test Case '-[SentryTests.SentrySystemEventBreadcrumbsTest testBatteryChargingStateBreadcrumb]' started.
2022-12-28 08:11:48.336935+0000 xctest[7787:30340] [Sentry] [debug] [SentryFileManager:644] SentryFileManager.cachePath: /Users/runner/Library/Developer/CoreSimulator/Devices/DB259A71-C861-4F5F-8C86-76C405AD45E4/data/Library/Caches
2022-12-28 08:11:48.337176+0000 xctest[7787:30340] [Sentry] [debug] [SentryFileManager:227] Deleting /Users/runner/Library/Developer/CoreSimulator/Devices/DB259A71-C861-4F5F-8C86- …
```
=> fix: Deleting old envelopes for empty DSN

.github/workflows/testflight.yml, fastlane/Fastfile
Enable source context for TestFlight builds by adding the include_sources
for Fastlane.
Successful ci run: https://github.com/getsentry/sentry-cocoa/actions/runs/3827637963/jobs/6512391581.
[Event with source context](https://sentry.io/organizations/sentry-sdks/issues/2862440026/events/33fc8f10333840eeaf96d4970d86fee0/?project=5428557)
Related to https://github.com/getsentry/team-mobile/issues/42
=> ci: Enable source context for TestFlight

CHANGELOG.md, Sources/Sentry/SentryBreadcrumbTracker.m, Sources/Sentry/SentryEvent.m, Tests/SentryTests/Protocol/SentryEventTests.swift, Tests/SentryTests/SentryInterfacesTests.m, Tests/SentryTests/TestClient.swift
Removed `__sentry_transaction`  added to the scope during `viewDidAppear`.
Now we have automatic view controller transactions and this tag is confusing hack
=> chore: Remove confusing transaction tag 

Sources/Sentry/Public/SentryOptions.h
=> fix: Mention which MetricKit data the SDKs sends

.craft.yml
Remove until we fix the podspec (https://github.com/getsentry/sentry-cocoa/issues/2581) so we can release successfully.
=> chore: Remove SwiftUI from craft

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryDependencyContainer.m, Sources/Swift/MetricKit/SentryMXManager.swift, Tests/SentryTests/Integrations/MetricKit/SentryMXManagerTests.swift, Tests/SentryTests/Integrations/MetricKit/SentryMetricKitIntegrationTests.swift
Disable crash diagnostics as we only use it for validation of the symbolication of stacktraces, because crashes are easy to trigger for MetricKit. We don't want crash reports of MetricKit in production as we have SentryCrash.
=> fix: Disable crashes for MetricKit

.github/workflows/integration-tests.yml
The home assistant integration tests fail because of an expired SSL certificate. Building
the home assistant app locally results in the same error.
Failing CI job https://github.com/getsentry/sentry-cocoa/actions/runs/3872279080/jobs/6600947067
=> ci: Disable Home Assistant integration test

Samples/iOS-SwiftUI/iOS-SwiftUI/ContentView.swift, Samples/iOS-SwiftUI/iOS-SwiftUI/LoremIpsumView.swift, Sentry.xcodeproj/project.pbxproj, Sources/SentrySwiftUI/SentryTracedView.swift
As pointed out by @armcknight, `TraceView` may be mistaken as a view that shows Trace, as "TracedView" shows an action being taken.
close #2550 
=> chore: Rename SentryTraceView to SentryTracedView

.github/workflows/integration-tests.yml
Underlying issue has been fixed
https://github.com/realm/realm-swift/issues/8092.
We can enable the tests again.
=> ci: Enable HomeKit integration tests again

CONTRIBUTING.md, fastlane/Fastfile
Added instructions into `CONTRIBUTING` file on how to setup certificate and provisioning profiles in order to run samples on a real device.
=> chore: Improve documentation on how to setup certificate and provisioning profiles

CHANGELOG.md, Sources/Sentry/Public/SentryOptions.h, Sources/Sentry/SentryOptions.m, Tests/SentryTests/SentryOptionsTest.m
Enable Core Data Tracing By Default. Docs PR https://github.com/getsentry/sentry-docs/pull/6059
The feature is GA, and we want to give users more value out of the box by default.
Was already tested before, but enabling the feature by default is tested by unit tests.
=> feat: Enable Core Data Tracing By Default

.github/.codecov.yml, .github/workflows/benchmarking.yml, .github/workflows/build.yml, .github/workflows/integration-tests.yml, .github/workflows/lint.yml, .github/workflows/saucelabs-UI-tests.yml, .github/workflows/test.yml, .github/workflows/testflight.yml, CHANGELOG.md, README.md, develop-docs/README.md
Rename the master branch to main with entries to changelog and decision log.
=> chore: Rename master branch to main

Sources/Sentry/Public/SentryOptions.h
Was forgotten to add in GH-1920.
=> docs: Mention attachScreenshot works for crashes

CHANGELOG.md, README.md
It should be for package managers pointing to the master branch, and not package managers not pointing to the master branch.
=> chore: Fix wording for master branch

SentrySwiftUI.podspec, Sources/SentrySwiftUI/SentryTracedView.swift, develop-docs/README.md
I couldn't find out whether this is a feature or a bug, but in order to be able to publish SentrySwiftUI it need to have the same version of the other podspecs in the repo.
We can go forward with this approach (fine by me), or we can open a cocoapod github issue to find out if this is a bug or intended behaviour.
=> chore: Fix SentrySwiftUI pod publish

Sources/Sentry/include/HybridPublic/SentryOptions+HybridSDKs.h
Fix error if a Hybrid SDKs imports `SentryOptions+HybridSDK.h` while using Carthage to add Sentry framework.
=> fix: SentryOption.h reference from SentryOption+HybridSDK.h

CHANGELOG.md, Sources/Sentry/SentryViewHierarchy.m, Tests/SentryTests/SentryViewHierarchyTests.swift
Reads UI Windows in the main thread while fetching view hierarchy
Closes #2586 
Unit test
=> fix: Reads UI Windows in the main thread while fetching view hierarchy

.pre-commit-config.yaml
main and master are default for no-commit-to-branch; see https://github.com/pre-commit/pre-commit-hooks#no-commit-to-branch.
=> chore: Remove args for no-commit-to-branch

CHANGELOG.md, Sources/SentryCrash/Recording/SentryCrashReport.c, Sources/SentryCrash/Recording/Tools/SentryCrashJSONCodec.c, Sources/SentryCrash/Recording/Tools/SentryCrashJSONCodec.h, Sources/SentryCrash/Recording/Tools/SentryCrashJSONCodecObjC.m, Tests/SentryTests/SentryCrash/SentryCrashJSONCodec_Tests.m
Follow up on #2631 to use uint64 instead of double for encoding and decoding crash reports.
Came up while investigating https://github.com/getsentry/sentry-cocoa/issues/1589. KSCrash has some fixes in https://github.com/kstenerud/KSCrash/commits/master/Source/KSCrash/Recording/Monitors/KSCrashMonitor_MachException.c that we can apply to our fork. https://github.com/kstenerud/KSCrash/pull/350 is a first step and adding support for uint64 is one change we can apply.
Thanks again @GLinnik21, for the initial work on KSCrash.
Unit tests.
=> fix: Use uint64 instead of double in crash report

Sources/Sentry/SentryCrashInstallationReporter.m, Sources/Sentry/SentryCrashIntegration.m, Sources/Sentry/include/SentryCrashInstallationReporter.h, Tests/SentryTests/SentryCrash/SentryCrashInstallationReporterTests.swift
The test validated the wrong invocation on the test client. Instead of captureEventWithScopeInvocations it should have been captureCrashEventInvocations. Anyways, we can improve the test by not validating no events being passed down to the client but instead using the completion callback of the SentryCrashInstallationReporter to get rid of the delayNonBlocking.
=> test: Fix flaky testFaultyReportIsNotSentAndDeleted

Sources/Sentry/SentryClient.m, Sources/Sentry/SentryFileManager.m, Sources/Sentry/include/SentryFileManager.h, Tests/SentryTests/Helper/SentryFileManagerTests.swift, Tests/SentryTests/Integrations/WatchdogTerminations/SentryWatchdogTerminationsTrackerTests.swift, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/TestClient.swift
Deleting old envelope items in the SentryFileManager can cause side effects for tests as it could delete envelope items needed for other tests async. Now the SentryClient runs the deletion in production and we only run the deletion for selected tests.
Came up in https://github.com/getsentry/sentry-cocoa/actions/runs/4013580316
=> test: Skip delete old envelopes for most tests

Sources/Sentry/SentryStacktraceBuilder.m, Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor.c, Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor.h, Sources/SentryCrash/Recording/Tools/SentryCrashSymbolicator.c, Sources/SentryCrash/Recording/Tools/SentryCrashSymbolicator.h
Instead of adding an extra field to the struct we change the symbolication function in StacktraceBuilder.
=> ref: Remove useDlAddr from struct

Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift
Created a ui test for iOS-Swift sample that press the crash button and try to open the app again.
If we introduce any error in the crash report process this test may identify it.
To avoid issues like https://github.com/getsentry/sentry-cocoa/pull/2664.
=> CI: UITest for crash recoverability 

Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift
Since `testCrashRecovery` always fails on the iOS 12 simulator, we removed this test from this particular version, it looks more like a tooling issue than a problem with the test or the SDK. This way we can continue testing the crash recovery capability of the SDK on another iOS versions.
=> CI: Remove testCrashRecovery from iOS 12

README.md
We decided to remove the master branch from the GH repo, as users pointing to it won't notice that we migrated to the main branch. Pointing to the master branch is considered a bit experimental cause you always point to the latest changes without relying on official SDK releases.
=> chore: Remove master branch from ReadMe

.github/pull_request_template.md
Add an item to remind the author of a PR to communicate breaking changes for hybrid SDKs.
Fixes https://github.com/getsentry/sentry-cocoa/issues/2672
Related to https://github.com/getsentry/sentry-java/pull/2511.
=> PR template breaking changes for hybrid SDKs

Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
The SentryClientTests failed on my MacBook cause I had a different timezone configured that hard coded in the tests. This is fixed now.
=> test: ClientTests don't depend on specific locale

CHANGELOG.md, Sources/Sentry/SentryANRTracker.m, Sources/Sentry/SentryThreadWrapper.m, Sources/Sentry/include/SentryThreadWrapper.h, Tests/SentryTests/Helper/SentryTestThreadWrapper.swift, Tests/SentryTests/Integrations/ANR/SentryANRTrackerTests.swift
When closing the SDK directly after starting it, it could happen that the ANRTracker didn't start its watchdog thread yet. Canceling the ANRTrackers thread required the instance of the watchdog thread and didn't work correctly. This is fixed now by using simple state management in the ANRTracker. While this is an edge case, it can help with flaky tests, as the test logs showed signs of the ANRTracker running in the background.
This came up while checking the raw test logs of failing tests on the main branch, see https://github.com/getsentry/sentry-cocoa/actions/runs/4045915250/jobs/6958149321. The logs contain several statements, although the ANRTracker shouldn't be running.
```
Test Case '-[SentryTests.SentryLogTests testLevelNone_PrintsEverythingExceptNone]' started.
2023-01-30 …
```
=> fix: Cleanup AppHangTracking properly when closing SDK

CHANGELOG.md, Sources/Sentry/include/SentrySamplingProfiler.hpp
Add missing atomic import for SentryProfilingConditionals as for some nightly Swift versions the project didn't compile.
Fixes GH-2678
I didn't. Testing this with a nightly swift version is not worth the effort. We only added one import.
=> fix: Add missing atomic import

CHANGELOG.md, Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme, Sources/Sentry/SentryBreadcrumbTracker.m, Tests/SentryTests/Integrations/Breadcrumbs/SentryBreadcrumbTrackerTests.swift
Created a filter to avoid creating breadcrumbs for every key pressed in a UITextField control
close #2682 
Unit tests
=> fix: Don't create breadcrumb for UITextField editingChanged event

CHANGELOG.md
We missed adding https://github.com/getsentry/sentry-cocoa/pull/2535 to the Changelog of 8.0.0.
=> chore: Add missing changelog for 2535

Sources/Sentry/Public/SentrySpanProtocol.h
Adding the `strong` attribute to `SentrySpanProtocol` where applicable.
I consume the Cocoa SDK `8.1.0` as part of the Unreal SDK in this form:
```
Mac/
├─ bin/
│  ├─ sentry.dylib
├─ include/
│  ├─ Headers/
│  ├─ PrivateHeaders/
```
When trying to build the compilation fails with
```
error - no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Werror,-Wobjc-property-no-attribute]
error - default property attribute 'assign' not appropriate for object [-Werror,-Wobjc-property-no-attribute]
```
After going over it with @brustolin it looks like `assign` is indeed the [wrong attribute](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjectiveC/Chapters/ocProperties.html#:~:text=%C2%A0%20protocol.-,assign,this%20attribute%20for%20scalar%20typ …
=> fix: Added 'strong' attribute to `SentrySpanProtocol` properties

CHANGELOG.md, Sources/Sentry/SentryTracer.m, Tests/SentryTests/Performance/SentryTracerTests.swift
Fix EXC_BAD_ACCESS in SentryTracer by using a weak reference when dispatching the idle timeout to avoid accessing a garbage pointer.
Fixes GH-2696
Unit test.
=> fix: EXC_BAD_ACCESS in SentryTracer

.github/pull_request_template.md
Make it clearer to check all checkboxes of the checklist before merging a PR.
=> chore: PR template check all checkboxes

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/Public/SentryDebugMeta.h, Sources/Sentry/SentryCrashReportConverter.m, Sources/Sentry/SentryDebugImageProvider.m, Sources/Sentry/SentryDebugMeta.m, Sources/Sentry/SentryMetricKitIntegration.m, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/include/SentryCrashWrapper.h, Sources/Sentry/include/SentryInternalCDefines.h, Sources/Sentry/include/SentryInternalDefines.h, Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.h, Tests/Resources/converted-event.json, Tests/SentryTests/Integrations/MetricKit/SentryMetricKitIntegrationTests.swift, Tests/SentryTests/Protocol/SentryDebugMetaEquality.swift, Tests/SentryTests/Protocol/SentryDebugMetaTests.swift, Tests/SentryTests/Protocol/TestData.swift, Tests/SentryTests/SentryCrash/SentryDebugImageProviderTests.swift, Tests/SentryTests/SentryInterfacesTests.m, Tests/SentryTests/SentryKSCrashReportConverterTests.m
Change debug image from apple to macho cause apple was deprecated.
Fixes GH-2591
Unit tests, and a real device to ensure it doesn't impact grouping.
=> impr: Change debug image to macho

Sources/Sentry/Public/SentryThread.h
Change _Nullable to nullable for SentryThread.
=> ref: SentryThread change to nullable

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/NSMutableDictionary+Sentry.m, Sources/Sentry/SentryFrame.m, Sources/Sentry/SentryMechanism.m, Sources/Sentry/SentrySession.m, Sources/Sentry/SentryStacktrace.m, Sources/Sentry/SentryThread.m, Sources/Sentry/include/NSMutableDictionary+Sentry.h, Tests/SentryTests/Categories/NSMutableDictionarySentryTests.swift, Tests/SentryTests/Protocol/SentryFrameTests.swift, Tests/SentryTests/Protocol/SentryMechanismTests.swift, Tests/SentryTests/Protocol/SentryStacktraceTests.swift, Tests/SentryTests/Protocol/SentryThreadTests.swift, Tests/SentryTests/SentrySessionTests.swift, Tests/SentryTests/SentryTests-Bridging-Header.h, Tests/SentryTests/TestUtils/SentryBooleanSerialization.h, Tests/SentryTests/TestUtils/SentryBooleanSerialization.m
The protocol contains a couple of nullable BOOLs that are of type NSNumber. Setting these properties to something different than 0 or 1 leads to a serialized NSNumber, which violates the protocol. With this refactoring 0 value always means false, and any nonzero value is interpreted as true when serializing such nullable BOOLs.
Came up while investigating issues for MetricKit, as the server complained for invalid boolean values.
Unit tests.
=> fix: Serialization of nullable booleans

Gemfile, Gemfile.lock
https://github.com/fastlane/fastlane/issues/20960 is now fixed so we can update to the latest version.
=> build: Update fastlane from 2.210.1 to 2.212.0

Sources/Sentry/SentryAutoBreadcrumbTrackingIntegration.m, Sources/Sentry/SentrySystemEventBreadcrumbs.m, Sources/Sentry/include/SentryAutoBreadcrumbTrackingIntegration.h, Sources/Sentry/include/SentrySystemEventBreadcrumbs.h, Tests/SentryTests/Integrations/Breadcrumbs/SentryAutoBreadcrumbTrackingIntegrationTests.swift, Tests/SentryTests/Integrations/Breadcrumbs/SentrySystemEventBreadcrumbsTest.swift
Add a delegate for SentrySystemEventBreadcrumbs to be independent of SentrySDK to make validating crumbs easier in SentrySystemEventBreadcrumbsTests, and only one test in SentryAutoBreadcrumbTrackingIntegrationTests has to use the global state of the SentrySDK for testing to reduce flakiness. Furthermore, use test classes in SentryAutoBreadcrumbTrackingIntegrationTests when calling install to reduce side effects when testing.
`testBatteryLevelBreadcrumb` were failing here https://github.com/getsentry/sentry-cocoa/actions/runs/4225003147/jobs/7336716875.
The raw logs display logs of `SentryFileManager` and `SentryHttpTransport` which aren't required for running `testBatteryLevelBreadcrumb`.
```
Test Case '-[SentryTests.SentrySystemEventBreadcrumbsTest …
```
=> ref: Add delegate for SystemEventCrumbs

fastlane/Fastfile
Include symbols for iOS-Swift TestFlight upload, to get meaningful stack traces for energy reports in the Xcode Organizer, which helps to decipher MetricKit stack traces.
=> test: Include symbols for TestFlight upload

Tests/Perf/metrics-test.yml
We exceeded the limit for a few KiB. 420 is still acceptable.
=> ci: Increase binary size test limit

CHANGELOG.md, Sources/Sentry/SentryANRTrackingIntegration.m, Tests/SentryTests/Integrations/ANR/SentryANRTrackingIntegrationTests.swift, Tests/SentryTests/SentrySDKIntegrationTestsBase.swift
Fix a crash (index 0 beyond bounds for empty array) in the AppHangs logic when creating the app hang event, and the SDK can't retrieve threads by not reporting an AppHang in such a case.
Fixes GH-2713
Unit tests.
=> fix: Crash in AppHangs when no threads

CHANGELOG.md, Sources/Sentry/SentryMetricKitIntegration.m, Tests/SentryTests/Integrations/MetricKit/SentryMetricKitIntegrationTests.swift
Apply the InAppLogic for MetricKit stack traces.
Fixes GH-2738
Unit tests.
=> fix: InApp for MetricKit stack traces

Sources/Sentry/SentryANRTracker.m, Sources/Sentry/SentryANRTrackingIntegration.m, Tests/SentryTests/Integrations/ANR/SentryANRTrackerTests.swift, Tests/SentryTests/Integrations/ANR/SentryANRTrackingIntegrationTests.swift
Replace NSMutableSet with NSHashTable and use weakObjectsHashTable to avoid retaining strong references to ANR tracker listeners.
A failing flaky test contained a message of the ANRTrackingIntegration, although the `ANRTrackingIntegration` should not be running.
```
SentryTests.SentryLogTests
ertEqual failed: ("["[Sentry] [fatal] 0", "[Sentry] [error] 1", "[Sentry] [warning] 2", "[Sentry] [info] 3", "[Sentry] [debug] 4"]") is not equal to ("["[Sentry] [fatal] 0", "[Sentry] [warning] [SentryANRTracker:120] ANR detected.", "[Sentry] [warning] [SentryANRTrackingIntegration:66] Getting current thread returned an empty list. Can\'t create AppHang event without a stacktrace.", "[Sentry] [error] 1", "[Sentry] [warning] 2", "[Sentry] [info] 3", "[Sentry] [debug] 4"]") …
```
=> ref: Use weak references for ANRTracker listeners

CHANGELOG.md, Sources/Sentry/SentryTracer.m, Tests/SentryTests/Performance/SentryTracerTests.swift
Use copy of children span array to avoid Collection was mutated while being enumerated exception.
A customer reported this crash.
Unit test.
=> fix: Mutating while enumerating crash in Tracer

Sources/Sentry/SentryClient.m, Tests/SentryTests/Integrations/SentryCrash/SentryCrashIntegrationTests.swift, Tests/SentryTests/SentryClient+TestInit.h, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/TestClient.swift
Use the TestTransportAdapter in default init of TestClient, and only deleteOldEnvelopeItems in production.
The `SentryProfilerSwiftTests` keep failing, and the test logs show entries of calls in SentryHttpTransport and SentryFileManager.
https://github.com/getsentry/sentry-cocoa/actions/runs/4321925443/jobs/7545278715
=> test: Improvements for TestClient

.github/workflows/saucelabs-UI-tests.yml, .github/workflows/test.yml
I noticed in https://github.com/getsentry/sentry-cocoa/pull/2761 that changes to scheme options weren't running the tests associated with the scheme.
=> test: run tests on scheme changes

Sources/Sentry/SentryProfiler.mm, Tests/SentryProfilerTests/SentryProfilerSwiftTests.swift
if there is one, or fall back to previous behavior
for https://github.com/getsentry/team-profiling/issues/191
=> fix: set the profile payload "timestamp" field to the transaction's start

Samples/iOS-ObjectiveC/iOS-ObjectiveC.xcodeproj/xcshareddata/xcschemes/iOS-ObjectiveC.xcscheme, Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme
Fixing test_DataConsistency_readUrl and test_DataConsistency_readPath
=> fix: SentryFileIOTrackingIntegrationTests flaky tests

Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerTests.swift, Tests/SentryTests/Protocol/SentryUserTests.swift
As we bumped the min supported OS versions, we could remove the available annotations for tests
using the dispatch queue. We forgot to remove the comments explaining why we used the available
annotation.
=> test: Remove not needed thread safe comment

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/Public/SentryClient.h, Sources/Sentry/Public/SentryHub.h, Sources/Sentry/SentryHub.m, Sources/Sentry/SentryTraceContext.m, Sources/Sentry/include/HybridPublic/PrivateSentrySDKOnly.h, Sources/Sentry/include/HybridPublic/SentryEnvelope.h, Sources/Sentry/include/SentryClient+Private.h, Sources/Sentry/include/SentrySdkInfo.h, Sources/Sentry/include/SentryTraceContext.h, develop-docs/README.md
We made SentrySession private but we did not remove references from public headers.
Also changing a few forward declarations to #import to help with .NET hybrid SDK.
**This may be considered a "breaking change" since we're removing property from a public header, but is a property that was not meant to be used.**
=> chore: Remove private references from public headers

CHANGELOG.md, Sources/Sentry/SentryThreadInspector.m, Sources/SentryCrash/Recording/SentryCrash.m, Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.c, Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.h, Tests/SentryTests/SentryCrash/SentryThreadInspectorTests.swift
Add a limit of 70 threads to report App hang. 
More than 100 is causing the SDK to crash, we add an extra safety margin.
closes #2794 
Unit tests
=> fix: App Hang report crashes with too many threads

.github/workflows/build.yml, Makefile
I had the [xcframework validation build fail](https://github.com/getsentry/sentry-cocoa/actions/runs/4418446156/jobs/7745583784#step:4:13) but with no clues as to why. This tries to capture the build output.
=> output xcodebuild logs from carthage build and archive if failed

CHANGELOG.md, Sources/Sentry/SentryClient.m, Tests/SentryTests/SentryClientTests.swift
Added the amount of CPU cores in the device context.
closes #2740 
Unit test
=> feat: Add CPU Core count in device context

Sources/Sentry/Public/SentryOptions.h, Sources/SentrySwiftUI/SentryTracedView.swift
Add notes and beta warnings to all public-facing APIs for profiling.
=> docs: call out beta status for all public-facing profiling APIs

.github/workflows/test.yml
This was producing raw output logs from ui test runs that overwrote each other because they collided when no differentiating pieces existed to interpolate: 
=> test: fix raw log output ids for ui tests

Sources/Sentry/SentryDependencyContainer.m
Avoid allocating one extra dispatch queue in the dependency container.
=> ref: Use dispatch queue in dependency container

CHANGELOG.md, SentryTestUtils/TestSentryDispatchQueueWrapper.swift, Sources/Sentry/SentryDispatchQueueWrapper.m, Sources/Sentry/SentryTracer.m, Sources/Sentry/include/SentryDispatchQueueWrapper.h, Tests/SentryTests/Performance/SentryTracerTests.swift
dispatch_block_create can return NULL. If it does, we finish the transaction and don't schedule the timeout.
Fixes GH-2832, GH-2769
Unit tests, and on an iPhone to validate UI event transactions are still working properly.
=> fix: Crash in Tracer for idle timeout

Sources/Sentry/SentryPerformanceTracker.m
Remove not needed check for isKindOfClass SentryTracer in SentryPerformanceTracker as the code calls startTransactionWithContext, which always returns a SentryTracer.
=> ref: Remove not needed check for SentryTracer

.github/workflows/saucelabs-UI-tests.yml, .sauce/config.yml, CHANGELOG.md, Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj, Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard, Samples/iOS-Swift/iOS-Swift/ViewController.swift, Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift, Samples/iOS-Swift/iOS-SwiftUITests/ProfilingUITests.swift, Samples/iOS-Swift/iOS-SwiftUITests/UITestHelpers.swift, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/include/SentryMetricProfiler.h, Sources/SentryCrash/Recording/SentryCrash.m, fastlane/Fastfile
We never installed a default frames tracker for the profiler, so it wasn't getting GPU frame render information. 
Also, only process frame rate info if there are slow/frozen frames to report. Otherwise it's uneeded.
Added a UI test that triggers an ANR inside of a profiled transaction to force slow and frozen frames. Then it inspects the profile payload, via a new way to get the payload data out of the profiler: a notification is posted when testing, which is observed in iOS-Swift.ViewController, which serializes the dictionary to JSON data, base64 encodes that into a string and presents that string in an alert text field, which the UI test can extract to perform assertions.
=> fix: missing GPU frame info in profiler

Tests/SentryTests/Integrations/Performance/UIViewController/SentryTimeToDisplayTrackerTest.swift
looks like [this pr](https://github.com/getsentry/sentry-cocoa/pull/2821/files#diff-aa3354dc4f53abbd601caf720ac9b121b1aa5a6ffcd6cf345841f413c8e02c42L81-L99) inadvertently broke a test on `main`: https://github.com/getsentry/sentry-cocoa/actions/runs/4619928851
[this other pr](https://github.com/getsentry/sentry-cocoa/pull/2843/files#diff-dcef7541efabf9ddb4cef77f33a2d118975aec4f6aa9c55ab1f0120b31acec76R241) added a test using a SentryTracer init that was removed in the other one, but CI wasn't smart enough to rerun in the PR. 
This changes to the new API to use for the equivalent initialization.
=> fix: use new API to fix test compilation error

Tests/SentryTests/Helper/SentryFileManagerTests.swift
CI can't compare the performance test with `measure` against anything, as Xcode needs baseline files for the same computer. In CI, the computer specifications might change frequently, so it's a lot of effort to create those baseline files. This test only slows down CI, and therefore, we can remove it. For more context see https://github.com/getsentry/sentry-cocoa/issues/1482.
=> test: FileManager remove perf test

Tests/SentryTests/Transaction/SentryTracerTests.swift
Replace fatalError with XCTUnwrap in SentryTracerTests.
The fatalError lets the tests crash, which is not ideal for the test suite.
https://github.com/getsentry/sentry-cocoa/blob/4654f668feee8e05221a56f0e08178b8c9824068/Tests/SentryTests/Transaction/SentryTracerTests.swift#L1018
This came up a couple of time in this test run:
https://github.com/getsentry/sentry-cocoa/actions/runs/4616495172
=> test: Replace fatalError with XCTUnwrap

Sources/SentryCrash/Installations/SentryCrashInstallation+Private.h, Sources/SentryCrash/Installations/SentryCrashInstallation.m, Sources/SentryCrash/Reporting/Filters/Tools/SentryCrashVarArgs.h
I was looking at a couple places where we use a dynamic key to insert values into dictionaries as possible candidates for an exception to be thrown, and found a couple macros that expand to such code, but don't appear to be used in the codebase.
=> ref: remove some dead code

SentryTestUtils/TestSentryNSTimerWrapper.swift, Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerTests.swift, Tests/SentryTests/State/TestHub.swift, Tests/SentryTests/Transaction/SentryTracerTests.swift
Use thread-safe Invocation in TestHub, as running the tests locally sometimes lead to crashes in capturedTransactionsWithScope. Furthermore, remove DispatchGroup so we can remove plenty of calls to fixture.hub.group.wait().
=> test: Use Invocation in TestHub

CHANGELOG.md, Sources/Sentry/SentryScreenshot.m, Tests/SentryTests/SentryScreenShotTests.swift
I noticed a test error on a Runtime Issue breakpoint for the test case that tries to take a screenshot of a 0 width window, when setting up the graphics context. We should never even let it get that far. 
I'll still leave the check for the image size, just in case somehow a nonzero width/height window still produces an image like that. But I changed the `||` to a `&&` in the comparison to make sure that _both_ dimensions must be greater than zero; otherwise, there's not much customers could do with something like that.
Added new unit tests.
=> fix: avoid screenshots with either dimension of 0

Tests/SentryTests/Helper/UrlSessionDelegateSpy.swift, Tests/SentryTests/Integrations/Performance/AppStartTracking/SentryAppStartTrackingIntegrationTests.swift, Tests/SentryTests/Integrations/Performance/UIViewController/SentryTimeToDisplayTrackerTest.swift, Tests/SentryTests/Integrations/SentryCrash/SentryCrashIntegrationTests.swift, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryHubTests.swift, Tests/SentryTests/SentrySDKTests.swift
A couple things I noticed looking through the test suite trying to find what is causing issues, including the intermittent crash in `testStartWithConfigureOptions` (which I believe is still an outstanding issue).
=> test: various fixes

SentryTestUtils/ClearTestState.swift, SentryTestUtils/TestDisplayLinkWrapper.swift, SentryTestUtils/TestSentryNSTimerWrapper.swift, Sources/Sentry/SentryFramesTracker.m, Sources/Sentry/SentryNSTimerWrapper.m, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/SentryTracer.m, Sources/Sentry/SentryTracerConcurrency.mm, Sources/Sentry/include/SentryNSTimerWrapper.h, Sources/Sentry/include/SentryProfiler.h, Sources/Sentry/include/SentryTracerConcurrency.h, Tests/SentryProfilerTests/SentryProfilerSwiftTests.swift, Tests/SentryTests/Helper/SentryProfiler+SwiftTest.h, Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackerTests.swift, Tests/SentryTests/Transaction/SentryTracer+Test.h
We realized that we were working under an incorrect assumption when recording GPU frame timestamps. This PR changes the timestamp that we use when we record that a slow or frozen timestamp has been encountered.
It also contains some refactoring of the associated logic in SentryProfiler and SentryFramesTracker and refactors and fixes for the profiler tests. This also includes: 
- converting the remainder of the profiling tests to use the mock date provider instead of delayed dispatches to achieve timeouts... this solves a long-standing request to speed up the profiling tests @philipphofmann!
- this let us remove _most_ of the delayed dispatches; the remainder were exercising the profiler's timeout logic; to complete this, also used the SentryNSTimerWrapper for the NSTimer the profiler uses …
=> fix: profiling GPU information timestamp choice

Sources/Sentry/SentrySDK.m, Sources/Sentry/include/SentrySDK+Private.h, Tests/SentryTests/SentrySDKTests.swift
Remove two nonpublic start transaction methods not used [anywhere](https://github.com/search?q=org%3Agetsentry%20startTransactionWithName&type=code) in the SDK or by HybridSDKs.
=> ref: Remove unused start transaction methods

Sources/Sentry/SentryHub.m, Sources/Sentry/SentrySDK.m, Sources/Sentry/include/SentryHub+Private.h, Tests/SentryTests/SentrySDKTests.swift
Remove not required unused start transaction methods in the SentryHub.
Related to https://github.com/getsentry/sentry-cocoa/pull/2886.
Preparation for https://github.com/getsentry/sentry-cocoa/issues/2537
=> ref: Remove unused start transaction methods in hub

.github/workflows/test.yml, Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Sources/Sentry/SentryAppStartTracker.m, Sources/Sentry/include/SentryAppStartTracker.h, Tests/SentryTests/Integrations/Performance/AppStartTracking/SentryAppStartTrackingIntegrationTests.swift, Tests/SentryTests/SentryViewHierarchyTests.swift
This PR changes two things:
- Remove UITests for iOS 12 from running in the GH simulators. We still run it with SauceLabs.
- Remove Unit tests for view hierarchy from running on iOS 12 tests. GH is hanging when running this tests. We have view hierarchy enabled for UI tests that run in Saucelabs and iOS 12.
=> Chore : Fixing CI

.github/workflows/saucelabs-UI-tests.yml, .github/workflows/test.yml, .sauce/config.yml, Sources/Sentry/SentryNetworkTracker.m, develop-docs/README.md, scripts/no-changes-in-high-risk-files.sh
Remove running unit tests on iOS 12 simulator as the xcode-install tool is being sunset. Instead, we now run UI tests in saucelabs on iOS 12.
Other usages of iOS 12 simulators are removed with https://github.com/getsentry/sentry-cocoa/pull/2889.
Fixes GH-2862
=> ci: Remove iOS 12 simulator

SentryTestUtils/ClearTestState.swift, SentryTestUtils/TestDisplayLinkWrapper.swift, SentryTestUtils/TestSentryNSTimerWrapper.swift, Sources/Sentry/SentryFramesTracker.m, Sources/Sentry/SentryMetricProfiler.mm, Sources/Sentry/SentryNSTimerWrapper.m, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/SentryTracer.m, Sources/Sentry/SentryTracerConcurrency.mm, Sources/Sentry/include/SentryNSTimerWrapper.h, Sources/Sentry/include/SentryProfiler.h, Sources/Sentry/include/SentryTime.h, Sources/Sentry/include/SentryTracerConcurrency.h, Tests/SentryProfilerTests/SentryProfilerSwiftTests.swift, Tests/SentryTests/Helper/SentryProfiler+SwiftTest.h, Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackerTests.swift, Tests/SentryTests/Transaction/SentryTracer+Test.h
I noticed recently that a frozen GPU frame reported during an ANR from iOS-Swift was not aligned to where it should be with the stack frames that likely caused it ([profile](https://sentry-sdks.sentry.io/profiling/profile/sentry-cocoa/b09733aa309b4b1f875eb987abf20363/flamechart/?colorCoding=by+system+vs+application+frame&query=&sorting=call+order&tid=12291&view=top+down)): 
This is an investigation to see if there's an SDK bug.
As part of this, I'm refactoring the profiling tests to validate the timestamp values of the reported metrics, originally mentioned [here](https://github.com/getsentry/sentry-cocoa/pull/2545#discussion_r1113599464) (and later, [here](https://github.com/getsentry/sentry-cocoa/pull/2786#issuecomment-1468537060) and …
=> ref: mock clock for GPU metrics tests and fix slicing logic

Sources/Sentry/SentrySpanContext.m
Use sample decision instead of bool in SentrySpanContext.
=> ref: Use sample decision instead of bool

Sentry.xcodeproj/project.pbxproj, Tests/SentryTests/SentryScopeSwiftTests.swift, Tests/SentryTests/TestLogOutput.swift, Tests/SentryTests/TestUtils/TestConncurrentModifications.swift
When running the tests locally, I got a SIGABRT in the TestLogOutput when writing to the loggedMessages. I added a test to reproduce the same error by writing and reading the loggedMessages from different threads. The problem is fixed now by using a dispatch queue.
=> test: Make TestLogOutput thread safe

Tests/SentryTests/Integrations/Performance/IO/SentryFileIOTrackingIntegrationObjCTests.m
When running the SentryFileIOTrackingIntegrationObjCTests locally they failed. This is fixed now by using the SentryByteCountFormatter instead of the NSByteCountFormatter.
=> test: Fix failing FileIOTracking tests

Tests/SentryTests/Integrations/Performance/IO/SentryNSDataTrackerTests.swift
When running the SentryNSDataTrackerTests locally they failed. This is fixed now by using the SentryByteCountFormatter instead of the NSByteCountFormatter.
Related to https://github.com/getsentry/sentry-cocoa/pull/2902.
=> test: Fix failing NSDataTracker tests

Sources/Sentry/SentryTransaction.m, Tests/SentryTests/Transaction/SentryTransactionTests.swift
The serialization of `transactionContext.name` was missing a test case.
=> test: Add missing test for transaction name

SentryTestUtils/TestSentryNSTimerWrapper.swift, Tests/SentryTests/Transaction/SentryTracerTests.swift
We subclassed NSTimer, which is not allowed see:
https://developer.apple.com/documentation/foundation/nstimer#1770465.
This sometimes leads to crashes in TestSentryNSTimerWrapper with EXC_BAD_ACCESS.
The subclass is now removed.
=> test: Remove subclass of NSTimer

Sources/Sentry/SentryTracer.m
The SentryTracer.finish and SentryTracer.finishWithStatus both logged similar debug messages, which is not required as SentryTracer.finish calls SentryTracer.finishWithStatus.
=> ref: Simplify Tracer finish logging

Sources/Sentry/SentryClient.m, Sources/Sentry/SentryHub.m, Sources/Sentry/SentrySDK.m
Add some extra log messages when closing the SDK in the client, hub, and SDK.
=> ref: Add some log messages when closing the SDK

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentrySystemEventBreadcrumbs.m, Sources/Sentry/include/SentryAutoBreadcrumbTrackingIntegration.h, Sources/Sentry/include/SentryBreadcrumbDelegate.h, Sources/Sentry/include/SentrySystemEventBreadcrumbs.h, Tests/SentryTests/Integrations/Breadcrumbs/SentryAutoBreadcrumbTrackingIntegrationTests.swift, Tests/SentryTests/Integrations/Breadcrumbs/SentryBreadcrumbTestDelegate.swift, Tests/SentryTests/Integrations/Breadcrumbs/SentrySystemEventBreadcrumbsTest.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
This change is a prerequisite for removing the reference to SentrySDK in SentryBreadcrumbTracker to make testing easier, similar to https://github.com/getsentry/sentry-cocoa/pull/2709. We do this cause `SentryBreadcrumbTracker.test_avoidSender` times out sometimes see: https://github.com/getsentry/sentry-cocoa/issues/2911.
Rename SentrySystemEventBreadcrumbsDelegate to SentryBreadcrumbDelegate so we can reuse it for SentryBreadcrumbTracker.
=> ref: Rename SentryBreadcrumbDelegate

Tests/SentryTests/Integrations/Session/SentrySessionGeneratorTests.swift, Tests/SentryTests/Integrations/WatchdogTerminations/SentryWatchdogTerminationsIntegrationTests.swift, Tests/SentryTests/Integrations/WatchdogTerminations/SentryWatchdogTerminationsScopeObserverTests.swift, Tests/SentryTests/SentryHubTests.swift
Following a finding in #2906, init the remaining live file managers in the test suite with test dispatch queue wrappers, to keep them from delaying dispatches that cause issues in later test cases.
We should consider if some/all of these could also instead be converted to test file manager subclasses instead of the SDK file manager.
=> test: use dispatch queue wrappers for all file managers in tests

.github/workflows/integration-tests.yml, Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme, Sources/Sentry/SentryStacktraceBuilder.m
We stopped by mistake marking the start frame after an async frame marker.
Rolling back the code to fix this.
=> fix: Start frame check removed

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryAutoBreadcrumbTrackingIntegration.m, Sources/Sentry/SentryBreadcrumbTracker.m, Sources/Sentry/SentrySystemEventBreadcrumbs.m, Sources/Sentry/include/SentryAutoBreadcrumbTrackingIntegration.h, Sources/Sentry/include/SentryBreadcrumbDelegate.h, Sources/Sentry/include/SentryBreadcrumbTracker.h, Sources/Sentry/include/SentrySystemEventBreadcrumbs.h, Tests/SentryTests/Integrations/Breadcrumbs/SentryAutoBreadcrumbTrackingIntegrationTests.swift, Tests/SentryTests/Integrations/Breadcrumbs/SentryBreadcrumbTestDelegate.swift, Tests/SentryTests/Integrations/Breadcrumbs/SentryBreadcrumbTrackerTests.swift, Tests/SentryTests/Integrations/Breadcrumbs/SentrySystemEventBreadcrumbsTest.swift, Tests/SentryTests/SentryTests-Bridging-Header.h
Replace usages of SentrySDK.addBreadcrumb with delegate except one usage inside of swizzling, which can't be easily replaced cause we can't reference an instance of SentryBreadcrumbTracker inside SwizzleInstanceMethod. To get rid of SentrySDK we need to add swizzling viewDidAppear to swizzleWrapper, which we are going to do in a subsequent PR.
This PR is based on https://github.com/getsentry/sentry-cocoa/pull/2913.
It partly tackles https://github.com/getsentry/sentry-cocoa/issues/2911.
Breadcrumbs are still working see https://sentry-sdks.sentry.io/issues/2895893229/events/d3022f614ada4bb8a567af3954d77762/.
=> ref: Add delegate to SentryBreadcrumbTracker

Tests/SentryTests/SentryPredicateDescriptorTests.swift
Running the SentryPredicateDescriptorTests on iOS 14 simulators locally crashed with EXC_BAD_ACCESS. This is fixed now by providing an argument array.
=> test: Fix predicate descriptor on iOS 14

.pre-commit-config.yaml, Makefile
Add validating no changes in high-risk files to the pre-commit hook.
=> chore: Add high risk files check to pre commit

.github/workflows/codeql-analysis.yml
There's a warning in the codeql-analyze job because we have a pull_request trigger with no arguments. It still draws a notification on the job even though it passes, which is distracting.
=> ci: set a path filter for codeql-analyze

Sources/Sentry/SentryFileManager.m, Sources/Sentry/include/SentryFileManager.h
Instead of deleting all the envelope items individually, delete the folder containing the envelope items to minimize the acquisition of locks. This change should speed up tests but has no performance impact on the SDK, as we use deleteAllEnvelopes only for tests.
=> ref: Delete envelopes folder instead of files

Tests/SentryTests/SentryHubTests.swift, Tests/SentryTests/SentryScopeSwiftTests.swift
Set log level to error for testPeformanceOfSyncToSentryCrash and testBreadcrumbCapLimit to avoid spamming the raw test logs.
=> test: Set log level to error for spammy tests

.github/workflows/codeql-analysis.yml, Sources/Sentry/SentryFileManager.m
The storeData method was only used by storeEnvelope. Both methods used @synchronized. Now the storeData is moved into storeEnvelope and only one invocation of @ synchronized is needed.
This PR is based on https://github.com/getsentry/sentry-cocoa/pull/2965.
=> ref: Move storeData into storeEnvelope

Tests/SentryTests/Helper/SentryFileManagerTests.swift
Set maxCacheItems to 1, so the testDefaultMaxEnvelopesConcurrent test doesn't need to store 30 envelope items but only 1 for the max envelopes items logic to run.
Test timed out here https://github.com/getsentry/sentry-cocoa/actions/runs/4807094860/jobs/8555451492.
=> test: Speed up testDefaultMaxEnvelopesConcurrent

Sources/Sentry/SentryFramesTracker.m, Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackerTests.swift
SentryFrameTracker makes uses of CADisplayLink to increment the number of slow and frozen frames.
CADisplayLink only uses the main thread, we dont need to worry about a variable increment discrepancy. 
This also removes the slowest Test in our CI, responsible for almost 15% of unit test time alone.
=> chore: Removing SentryFrameTracker atomic operation

Sources/Sentry/Public/SentrySDK.h
Clarify in code docs not to use a debugger attached when testing the SDK with SentrySDK.crash.
Came up in https://github.com/getsentry/sentry-cocoa/issues/2975.
=> docs: Clarify no debugger for SentrySDK.crash

CHANGELOG.md, Sources/Sentry/Public/SentryOptions.h, Sources/Sentry/SentryClient.m, Sources/Sentry/SentryCrashIntegration.m, Sources/Sentry/SentryCrashWrapper.m, Sources/Sentry/SentryOptions.m, Tests/SentryTests/Integrations/SentryCrash/SentryCrashIntegrationTests.swift, Tests/SentryTests/SentryClientTests.swift, Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift, Tests/SentryTests/SentryCrash/SentryThreadInspectorTests.swift, Tests/SentryTests/SentryOptionsTest.m
Removed `stitchAsyncCode` from SentryOption because it is not working. 
=> Breaking: Remove stitchAsyncCode from SentryOption

Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
The TestFlight version number was stuck at 7.31.5 for a long time. This PR aligns it with the current release number 8.6.0, so future updates will be covered by the bump.sh script used by craft.
=> chore: Fix TestFlight version number

.github/workflows/test.yml
Print hardware info for tests to determine if our tests are slow or fail on a specific hardware type.
Tests will print now something like
```
Hardware Overview:
Model Name: Mac
Model Identifier: VMware[7](https://github.com/getsentry/sentry-cocoa/actions/runs/4869504613/jobs/8684174080?pr=2988#step:4:8),1
Processor Name: Unknown
Processor Speed: 3.33 GHz
Number of Processors: 1
Total Number of Cores: 3
L2 Cache (per Core): 256 KB
L3 Cache: 12 MB
Memory: 14 GB
System Firmware Version: VMW71.00V.139[8](https://github.com/getsentry/sentry-cocoa/actions/runs/4869504613/jobs/8684174080?pr=2988#step:4:9)[9](https://github.com/getsentry/sentry-cocoa/actions/runs/4869504613/jobs/8684174080?pr=2988#step:4:10)454.B64.1906190538
Apple ROM Info: …
```
=> ci: Print hardware info for tests

.github/workflows/test.yml, Samples/iOS-Swift/iOS-SwiftUITests/UIEventBreadcrumbTests.swift
Solving testNoBreadcrumbForTextFieldEditingChanged flakiness in the CI simulator.
=> fix: testNoBreadcrumbForTextFieldEditingChanged flakiness 

.github/workflows/test.yml
We often see GH actions canceling test jobs because they time out. While 20 minutes is not ideal, it's better than a canceled test job. We will work on improving the test suite so it runs faster.
=> ci: Increase test timeout to 20 minutes

.codecov.yml
SentryProfilerTests are [included in the CodeCov report](https://app.codecov.io/gh/getsentry/sentry-cocoa/commit/073b20d988681f2e34950fd5be347f291ce4196f/tree/Tests). To fix this, ignore the whole test folder.
=> chore: Ignore test folder for CodeCov

.github/workflows/test.yml
Run tests once every hour to get some data on how long they take and what the failure rate is.
We hypothesize that tests take longer and fail more often when the US is online.
=> ci: Schedule tests once an hour

.github/workflows/test.yml
Cause building catalyst took more than 14 minutes on this [CI job](https://github.com/getsentry/sentry-cocoa/actions/runs/4891384756/jobs/8731849536). Let's use the macOS 13 image, which is way faster.
=> ci: Run Catalyst tests on macOS 13

.github/workflows/test.yml
To avoid failing CI jobs such as
https://github.com/getsentry/sentry-cocoa/actions/runs/4912764852/jobs/8772174301.
=> ci: Skip CodeCov upload for scheduled jobs

.github/workflows/test.yml, Sentry.xcodeproj/project.pbxproj
I've seen many codecov step failures, often due to network request failures (see [latest example](https://github.com/getsentry/sentry-cocoa/actions/runs/4913855191/jobs/8776836428?pr=2995)). Perform one retry just in case. Because there's no script invocation, we can't use the same kind of retry strategy as elsewhere where we use a bash for loop, and we can't use the [retry-step action from the GitHub Action marketplace](https://github.com/marketplace/actions/retry-step), so I used the duplicate action strategy mentioned here: https://www.thisdot.co/blog/how-to-retry-failed-steps-in-github-action-workflows
=> ci: retry codecov steps one time if they fail

.github/workflows/test.yml, Tests/SentryProfilerTests/SentryProfilerSwiftTests.swift
I got the idea because a test run recently failed with a crash that I don't expect, so I'd like more information on what happened: https://github.com/getsentry/sentry-cocoa/actions/runs/4913855191/jobs/8774525689?pr=2995
=> ci: archive any crash reports on test failures

.github/workflows/test.yml
Scheduled runs try to upload coverage. I guess that's because the `${{` wasn't put at the beginning of the if statement in the yml.
https://github.com/getsentry/sentry-cocoa/actions/runs/4922793243/jobs/8793926172
=> ci: Fix skipping codecov2 upload for scheduled

.github/workflows/test.yml
I noticed a case where it took several minutes to archive derived data logs [here](https://github.com/getsentry/sentry-cocoa/actions/runs/4914931513/jobs/8777452063?pr=3009): 
This happened due to a test failure. Now that we've split up the build and runtest steps, I think we only need derived data logs if the build step fails. Once the build succeeds, these logs can't help for test run failures, so the step linked above didn't actually need to run.
=> ci: only archive derived data logs if the build step fails

.github/workflows/test.yml
We hypothesized that tests take longer and fail more often when the US is online. We didn't find strong evidence for this claim. There could be a slight correlation between the US being online and the tests failing more often. Even with a weak correlation, there isn't much we can do except improve the test suite. Therefore, keeping the tests running on a schedule doesn't make sense.
=> ci: Remove schedule of unit tests

CHANGELOG.md, Sources/Sentry/SentryTracer.m, Tests/SentryTests/Transaction/SentryTracerTests.swift
Finishing multiple spans on different threads that cancel and reschedule the idle timeout for user interaction transactions could lead to EXC_BAD_ACCESS crashes. This is fixed now by synchronizing the access to the idleTimeout block.
Fixes GH-3002
Unit test
=> fix: A crash for user interaction transactions

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/include/SentryProfiler+Private.h, Sources/Sentry/include/SentryProfiler+Test.h, Sources/Sentry/include/SentryProfiler.h, Tests/SentryProfilerTests/SentryProfilerTests.mm
While debugging the memory leaks reported in #2980 I found additional data race issues on top of the ones fixed in #3018. This is a larger refactor that fixes those issues but also simplifies the way that synchronization works.
In #3018, there was a change to add locking where `processBacktrace` mutated data structures that could be accessed concurrently. It attempted to separate the code that did not access the shared data structures, and moved all mutating code to a section at the end of the function. However, it missed a few reads from those data structures that also needed to be synchronized (e.g. `frames.count` and `stacks.count`). Generally, separating the critical section from the rest of the logic in that function is not worth the pain because the taking the lock for the entire …
=> fix: additional profiling data races

Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj, Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard, Samples/iOS-Swift/iOS-Swift/Tools/SentryExposure.h, Samples/iOS-Swift/iOS-Swift/Tools/iOS-Swift-Bridging-Header.h, Samples/iOS-Swift/iOS-Swift/ViewControllers/InfoForBreadcrumbController.swift, Samples/iOS-Swift/iOS-SwiftUITests/UIEventBreadcrumbTests.swift, Tests/SentryTests/Integrations/Breadcrumbs/SentryBreadcrumbTrackerTests.swift
Moved view info for breadcrumb unit test to ui tests.
close #3025 
=> chore: Move breadcrumb tests to UITest

develop-docs/README.md, develop-docs/Swift-Usage.md
Added documentation on how to use swift in the framework.
[Formated document](https://github.com/getsentry/sentry-cocoa/blob/chore/swift-usage/develop-docs/Swift-Usage.md)
=> chore: Swift usage documentation

CHANGELOG.md, Sources/Sentry/SentrySamplingProfiler.cpp, Sources/Sentry/include/SentrySamplingProfiler.hpp
This is a follow up to #3055 that fixes the final memory leak reported in #2980
`std::thread` appears to have some kind of bug (or maybe we were using it incorrectly, but I don't understand how) that causes it to not free the parameters that were passed to the thread entry function. In this PR we switch to using the `pthread` APIs directly and managing memory manually, which fixes the leak.
Verified with Instruments that the leak no longer reproduces:
=> fix: Profiling memory leak in std::thread

.github/workflows/saucelabs-UI-tests.yml
As you can only upload apps to the app store with Xcode 14, there is no 
need to keep still compiling our UI tests with Xcode 13. We can bump to
Xcode 14 and use the macOS 13 GH actions runner, which is faster.
=> ci: Build UI tests with Xcode 14

.github/workflows/testflight.yml, .pre-commit-config.yaml, Gemfile, Gemfile.lock
Remove pinned Fastlane version as 2.213.0 contains a possible fix for WWDC
certificate error, see https://github.com/fastlane/fastlane/pull/21271.
Test run with fastlane 2.213.0 in CI: https://github.com/getsentry/sentry-cocoa/actions/runs/5081757057/jobs/9130562210
=> build: Update Fastlane to 2.213.0

.pre-commit-config.yaml
The precommit check fails when adding a valid macos-13 as a runner.
We can add the check back once https://github.com/SchemaStore/schemastore/pull/2979 is merged and `check-jsonschema` starts using the new schema as pointed out in https://github.com/python-jsonschema/check-jsonschema/pull/268.
=> chore: Remove precommit GH actions check

.github/workflows/test.yml, CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, Sources/Sentry/Public/SentryOptions.h, Sources/Sentry/SentryOptions.m, Sources/Sentry/SentrySwiftAsyncIntegration.m, Sources/Sentry/include/SentrySwiftAsyncIntegration.h, Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_SelfThread.h, Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_SelfThread.m, Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift, Tests/SentryTests/SentryOptionsTest.m
> This PR was created By [kabiroberai](https://github.com/kabiroberai) at #2983, but CI was strange and I wanted to test this properly.
Adds support for stitching async Swift Concurrency frames using [backtrace_async](https://keith.github.io/xcode-man-pages/backtrace.3.html#backtrace_async).
Switching from `backtrace` to `backtrace_async` is super trivial and gets Sentry 90% of the way to offering good Swift Concurrency support. The man page mentions that backtrace_async is identical to backtrace in all circumstances except when Swift Concurrency `Task`s are involved, so IMO it's a no-brainer to make the jump.
Unfortunately the story isn't as easy for profiling, since the code there manually walks the stack — I think a good approach there could be to mimic how backtrace_async is …
=> feat: Experimental support for Swift Async stacktraces

.pre-commit-config.yaml
Was removed with https://github.com/getsentry/sentry-cocoa/pull/3064, cause it caused problems. Which are fixed now with v 0.23.01.
=> chore: Readd precommit GH actions check

CHANGELOG.md, Sources/SentryCrash/Recording/SentryCrashReport.c
Follows https://github.com/getsentry/sentry-cocoa/pull/2866 to convert potentially unsafe usage of `sprintf` to `snprintf`. See https://github.com/getsentry/sentry-cocoa/issues/2785.
This also causes Xcode 13+ builds to break when using address sanitizer after making the changes in https://github.com/getsentry/sentry-cocoa/pull/3075
~- [ ] I added tests to verify the changes.~ The tests required for this would require extensive effort disproportionate to the simplicity of the change.
~- [ ] I updated the docs if needed.~
~- [ ] Review from the native team if needed.~
=> ref: convert last sprintf call to snprintf

.github/workflows/build.yml, .github/workflows/test.yml
I noticed that https://github.com/getsentry/sentry-cocoa/pull/3071 didn't run build or test checks, which probably should've happened. We didn't actually configure those checks to run those on a project config change.
=> test: add triggers to build/test if a change occurs in the sentry xcode project

Sources/Sentry/SentryNSProcessInfoWrapper.mm, Sources/Sentry/include/SentryNSProcessInfoWrapper.h, Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerSwizzlingTests.swift
Fixed SentryUIViewControllerSwizzlingTests because it broke with latest swift/xcode updates.
=> fix: SentryUIViewControllerSwizzlingTests

Sources/Sentry/SentryNSProcessInfoWrapper.mm
Renaming a definition that may collide with build params.
=> fix: Rename EXECUTABLE_PATH

CHANGELOG.md, Sources/Sentry/SentryProfiler.mm
Stops the crash from occurring that was reported in #3082 
~- [ ] I added tests to verify the changes.~
~- [ ] I updated the docs if needed.~
~- [ ] Review from the native team if needed.~
=> fix: avoid inserting a nil into the gpu data dictionary literal

Sources/Sentry/SentryHub.m, Sources/Sentry/SentrySerialization.m, Sources/Sentry/include/SentryHub+Private.h, Sources/Sentry/include/SentrySerialization.h, Tests/SentryTests/SentryHubTests.swift
Closes session as crashed for hybrids SDK when a new envelope with unhandled crashed event is captured, and start a new session.
closes #2593 
=> feat: Close session for unhandled error

Sources/Sentry/SentryNetworkTracker.m
I have renamed the wrong header name to the correct one.
When integrating the latest release via SPM there is a new warning caused by wrong capitalization of one header name. Interestingly it's not happening when opening the workspace. The causing commit happened in #3058.
When opening the project as a Package the error is now gone and everything compiles; related Unit tests are also working.
=> fix: import warning in package

scripts/no-changes-in-high-risk-files.sh
An [user PR](https://github.com/getsentry/sentry-cocoa/pull/3109) changed `SentryNetworkTracker.m`, so we need to fix `no-changes-in-high-risk-files.sh`
=> Fix no-changes-in-high-risk-files.sh

SentryTestUtils/ClearTestState.swift, Sources/Sentry/PrivateSentrySDKOnly.m, Sources/Sentry/SentryDependencyContainer.m, Sources/Sentry/SentryFramesTracker.m, Sources/Sentry/SentryFramesTrackingIntegration.m, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/SentryTimeToDisplayTracker.m, Sources/Sentry/SentryTracer.m, Sources/Sentry/SentryUIViewControllerPerformanceTracker.m, Sources/Sentry/include/SentryDependencyContainer.h, Sources/Sentry/include/SentryFramesTracker.h, Sources/Sentry/include/SentryTimeToDisplayTracker.h, Tests/SentryProfilerTests/SentryProfilerSwiftTests.swift, Tests/SentryTests/Helper/SentryProfiler+SwiftTest.h, Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackingIntegrationTests.swift, Tests/SentryTests/Integrations/Performance/UIViewController/SentryTimeToDisplayTrackerTest.swift, Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerPerformanceTrackerTests.swift, Tests/SentryTests/PrivateSentrySDKOnlyTests.swift, Tests/SentryTests/SentryHubTests.swift, Tests/SentryTests/Transaction/SentryTracerTests.swift
In service of reworking SentryProfiler's management of GPU frame data in https://github.com/getsentry/sentry-cocoa/pull/3090, I need to simplify how it keeps a reference to the frames tracker. 
This has bugged me for some time because we vend a singleton of the frames tracker, but then various other objects keep and pass references to it, which is unnecessary; it can just be accessed via SentryDependencyContainer. This seemed like a good opportunity to fix it everywhere.
=> ref: centralize frames tracker access in SentryDependencyContainer

.github/workflows/testflight.yml, fastlane/Fastfile
The TestFlight upload failed with 
```
error: The CFBundleShortVersionString of an App Clip ('8.9.0-beta.1') must match that of its containing parent app ('8.9.0').
```
see https://github.com/getsentry/sentry-cocoa/actions/runs/5394909043/jobs/9927428203
This PR fixes that problem by also removing the beta version suffix for the `MARKETING_VERSION`.
Successful TestFlight upload CI run: https://github.com/getsentry/sentry-cocoa/actions/runs/5476461387/jobs/9974043082
=> ci: Fix version suffix beta issue for app clip

.github/workflows/testflight.yml, fastlane/Fastfile
Speed up upload to TestFlight by skipping waiting for the build to be
processed, which isn't required anymore as we don't have bitcode
enabled.
Previously, the upload took from around 10 up to 20 minutes, depending on how fast AppStoreConnect is with processing the build. Now CI takes around 5 minutes.
Successful CI run https://github.com/getsentry/sentry-cocoa/actions/runs/5476620487
=> ci: Speed up upload to TestFlight

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/Profiling/SentryProfilerState.mm, Sources/Sentry/Profiling/SentrySample.m, Sources/Sentry/SentryProfileTimeseries.mm, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/include/SentryProfileTimeseries.h, Sources/Sentry/include/SentryProfiler.h, Sources/Sentry/include/SentryProfilerState.h, Sources/Sentry/include/SentrySample.h, Tests/SentryProfilerTests/SentryProfilerTests.mm
I forgot to move the implementation of SentryProfilerState in #3124 
=> ref: extract implementations of other classes from SentryProfiler.mm

Tests/SentryProfilerTests/SentryBacktraceTests.mm, Tests/SentryProfilerTests/SentrySamplingProfilerTests.mm, Tests/SentryProfilerTests/SentryThreadMetadataCacheTests.mm
After looking at the list of 20 slowest tests for a [recent CI run](https://github.com/getsentry/sentry-cocoa/actions/runs/5483115319/jobs/9989134033?pr=3132#step:13:7), I realized some of the sleeps in profiler tests are unnecessary, and others are unnecessarily long.
=> test: speed up some profiling tests

.sauce/config.yml
Only specify major platform version, so CI doesn't break when Saucelabs update their devices.
=> ci: Fix Saucelabs  platform version

CHANGELOG.md, Sentry.xcodeproj/project.pbxproj, SentryTestUtils/ClearTestState.swift, SentryTestUtils/SentryTestUtils-ObjC-BridgingHeader.h, Sources/Sentry/SentryFramesTracker.m, Sources/Sentry/SentryNSNotificationCenterWrapper.m, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/SentryScreenFrames.m, Sources/Sentry/SentryTracer.m, Sources/Sentry/SentryTracerConcurrency.mm, Sources/Sentry/include/HybridPublic/SentryScreenFrames.h, Sources/Sentry/include/SentryNSNotificationCenterWrapper.h, Sources/Sentry/include/SentryProfiler+Private.h, Sources/Sentry/include/SentryProfiler.h, Sources/Sentry/include/SentryTracerConcurrency.h, Tests/SentryProfilerTests/SentryProfilerSwiftTests.swift, Tests/SentryProfilerTests/SentryProfilerTests.mm, Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackerTests.swift, Tests/SentryTests/Transaction/SentryTracerObjCTests.m
Following on from #3133, write a test that exercises the situation that is causing the memory growth bug. We actually already had a test that sets up the scenario, but prior to being able to mock backtraces, which that linked PR provides the ability to do, we were not able to distinguish which profile data comes from which profiler–and therefore tell that one had been lost. Now that we can disambiguate them with different mock data, we can ensure both are preserved. This test should fail in this PR and then pass in #3135 with the fixes.
=> fix: profiling memory growth fix

Sentry.xcodeproj/project.pbxproj, Sources/Sentry/SentryProfiler.mm, Sources/Sentry/SentryThreadWrapper.m, Sources/Sentry/SentryTracer.m, Sources/Sentry/include/SentryThreadWrapper.h, Tests/SentryTests/Helper/SentryThreadWrapperTests.swift
And use to schedule the NSTimer in SentryTracer on the main thread.
=> ref: add method to SentryThreadWrapper to ensure code runs on main thread

Sources/Sentry/SentryNSTimerFactory.m, Sources/Sentry/SentryProfileTimeseries.mm, Sources/Sentry/SentryTracerConcurrency.mm, Sources/Sentry/include/SentryInternalDefines.h
Add an assert/warning to timer factory if attempting to schedule a timer from a non-main context. Also add more macros that don't need to return the result of the condition if only a warning log is needed. Use in a couple other places.
=> ref: asserts and warnings

Sources/Sentry/SentryCoreDataTracker.m
Users can pass in a `nil` error parameter when calling Core Data methods like `save:` and `executeFetchRequest:`. We were incorrectly handling that nil error parameter and trying to dereference it inside SENTRY_LOG_DEBUG calls. This commit fixes that by instead checking the *result* of the call, as recommended by the [Cocoa Error Handling Guide](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ErrorHandlingCocoa/CreateCustomizeNSError/CreateCustomizeNSError.html#//apple_ref/doc/uid/TP40001806-CH204-BAJIIGCC).
This fixes https://github.com/getsentry/sentry-cocoa/issues/3151.
Honestly, I didn't. But I'm making the logging logic match the same logic used in `[fetchSpan finishWithStatus:]`
=> Avoid crashing in SentryCoreDataTracker

Sources/Sentry/Public/SentryDefines.h, Sources/Sentry/SentryCrashIntegration.m, Sources/Sentry/SentryReachability.m, Tests/SentryTests/Networking/SentryReachabilityTests.m
One was defined in terms of the other, replicating it. Remove so there's just one.
=> ref: remove SENTRY_HAS_UIDEVICE in favor of identical SENTRY_HAS_UIKIT

CHANGELOG.md
Explain that not symbolicating locally speeds up certain SDK actions.
Came up in https://github.com/getsentry/sentry-cocoa/issues/3167#issuecomment-1641789633.
=> chore: Add note on improvement of #3135

CHANGELOG.md, Sources/Sentry/SentryOptions.m, Tests/SentryTests/SentryOptionsTest.m
We [recently](https://github.com/getsentry/sentry-cocoa/pull/3157/files#diff-a29fc90c9efdf9bef7ce45c2687a50708114e90208d518b9fe3bad5ef8e0951b) changed the integration order, which is causing a problem to report crashed sessions.
This PR fix the order of integration.
close #3181 
Sample
Investigate a way to update the integrations so they don't require a specific order.
=> fix: Crashed session not being reported as crashed

CHANGELOG.md
Adds a note about a serious issue in version `8.9.2`.
=> chore: Add bug note in changelog for 8.9.2

Sources/Sentry/SentryFileManager.m, Tests/SentryTests/Helper/SentryFileManagerTests.swift
Saw this when debugging a test failure. `%zd` specifies a `size_t`, but this is formatting an amount of seconds. It seemed inappropriate to mix a value of time type with a type meant for memory values.
=> fix: use correct format specifier for NSInteger (either an int or a long int)

.github/workflows/build.yml, CHANGELOG.md, Package.swift
Removes `C++` and `Z` linker settings from Package.swift.
It seems this is not necessary since it don't break the build for Xcode 14,
also this will be necessary for Xcode 15.
closes #3122
=> Fix: Remove linker settings from Package.swift

Samples/TrendingMovies/TrendingMovies/TMDb/TMDbCredentials.swift
The security team received a report concerning the API key in the TMDb sample application. The API key is invalid, but it's not immediately clear.
=> fix: indicate api key in sample project is a test key

CHANGELOG.md, Sources/Sentry/Profiling/SentryProfilerState.mm
This code is only compiled in debug builds, but we were forgetting to `free` the pointer returned by `backtrace_symbols`. The documentation (https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/backtrace_symbols.3.html)  says:
> It is allocated using malloc() and should be released using free()
Customer reported a memory leak in a call to `backtrace_symbols`, this is the cause.
Verify that the memory is freed and does not leak in a debug build.
=> fix: Free memory returned by backtrace_symbols() in debug builds

Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard, Samples/iOS-Swift/iOS-Swift/ViewController.swift, Samples/iOS-Swift/iOS-SwiftUITests/ProfilingUITests.swift
I wrote this to help debug a potential issue. It lets you start a transaction from the main thread or bg thread, keeps a list of transactions that you've started, and then when stopping a transaction, gives you a list to choose which one to stop, and then lets you stop it from either the main thread or a bg thread.
https://github.com/getsentry/sentry-cocoa/assets/3241469/9fcc5e37-eef8-4dea-a563-47fb47c72357
=> test: allow starting/stopping txs from either main/bg threads

develop-docs/README.md
I've done this a couple times now and had to go through `history` to remember it, so figured I'd write it down here.
=> add notes on using match

Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard, Samples/iOS-Swift/iOS-Swift/ExtraViewController.swift
I needed an easy, unambiguous way to generate a profile with a frozen frame for testing a new feature. 
=> test: add function to cause frozen frames
