getsentry/sentry-cocoa

SentrySwift.xcodeproj/project.pbxproj
SentrySwiftTests/SentrySwiftObjCTests.m
SentrySwiftTests/SentrySwiftTests.swift
Sources/Event.swift
Sources/Exception.swift

NOTE: does not include `Stacktrace` interface

Add Basic Exception Interface

---

SentrySwiftTests/SentrySwiftTests.swift
Sources/Event.swift
Sources/Sentry.swift

No user/developer interaction required

Added device and sdk attributes

---

Sources/KSCrashHandler.swift

Send no message on crash

---

SentrySwiftTests/SentrySwiftObjCTests.m
SentrySwiftTests/SentrySwiftTests.swift
Sources/Event.swift

Removing culprit because not relevant to this platform

---

SentrySwiftTests/SentrySwiftObjCTests.m
SentrySwiftTests/SentrySwiftTests.swift
Sources/Event.swift

Reverts getsentry/sentry-swift#29

Revert "Removing culprit because not relevant to this platform"

---

Cartfile
Cartfile.resolved
Examples/MacExample/Podfile.lock
Examples/ObjCExample/Podfile.lock
Examples/SwiftExample/Podfile.lock
Examples/SwiftExample/SwiftExample.xcodeproj/project.pbxproj
Examples/SwiftTVOSExample/Podfile.lock
SentrySwift.podspec
SentrySwift.xcodeproj/project.pbxproj
SentrySwiftTests/SentrySwiftTests.swift
Sources/Context.swift
Sources/Event.swift

Fixes #39 
Fixes #8 
```
// macOS
"device":{
"model":"MacBookPro12,1",
"machine":"x86_64",
"family":"MacBookPro",
"architecture":"x86"
}
​
// iOS Device
device":{
"model":"iPhone7,2",
"family":"iPhone",
"model_id":"iPhone7,2",
"simulator":false,
"architecture":"arm64"
}
​
// iOS Sim
"device":{
"simulator":true,
"architecture":"x86",
"family":"iPhone",
"model":"iPhone5,1"
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-swift/44)

New device and os context

---

Examples/ObjCExample/Podfile.lock
Examples/SwiftExample/Podfile.lock
Examples/SwiftTVOSExample/Podfile.lock
Sources/EventOffline.swift

Fixes #43
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-swift/46)

Not logging failure to find folder as error anymore

---

Examples/ObjCExample/Podfile.lock
Examples/SwiftExample/Podfile.lock
Examples/SwiftExample/SwiftExample/ViewController.swift
Examples/SwiftTVOSExample/Podfile.lock
SentrySwiftTests/SentrySwiftTests.swift
Sources/DSN.swift
Sources/Sentry.swift

Fixes #23
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-swift/45)

Notify user of misconfigured DSN

---

SentrySwiftTests/SentrySwiftErrorTests.swift
SentrySwiftTests/SentrySwiftObjCTests.m
SentrySwiftTests/SentrySwiftSourceLocationTests.swift
SentrySwiftTests/SentrySwiftTests.swift

Fixes #38
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-swift/47)

Changed all tests to use XCTAssert

---

SentrySwiftTests/SentrySwiftErrorTests.swift
Sources/Event.swift
Sources/Stacktrace.swift

Fixes #53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/sentry-swift/55)

Fix for stacktrace and frames not serializing to JSON properly

---

SentrySwiftTests/SentrySwiftObjCTests.m
Sources/Contexts.swift
Sources/Event.swift
Sources/KSCrashHandler.swift
Sources/Sentry.swift

Event sending in background

---

SentrySwift.xcodeproj/project.pbxproj

Convert SwiftLint Wrrors to Warnings instead

---

SentrySwift.podspec
SentrySwift/Info.plist
Sources/BreadcrumbStore.swift
Sources/EventOffline.swift
Sources/Request.swift
Sources/Sentry.swift
Sources/SentryEndpoint.swift
docs/sentry-doc-config.json

Make session static var
Add timestamp to saved events
Filter events for timestamp
Bump version
Fix #96

Add rate limiting for requests

---

SentrySwiftTests/SentrySwiftTests.swift
Sources/KSCrashHandler.swift
Sources/Sentry.swift
docs/index.rst

Crash Client Properties

---

Cartfile
Cartfile.resolved
Examples/MacExample/Podfile.lock
Examples/ObjCExample/Podfile.lock
Examples/SwiftExample/Podfile.lock
Examples/SwiftTVOSExample/Podfile.lock
Examples/SwiftWatchOSExample/Podfile.lock
Makefile
SentrySwift.podspec
SentrySwift/Info.plist
SentrySwiftTests/SentryClientTests.swift
SentrySwiftTests/SentrySwiftObjCTests.m
Sources/BinaryImage.swift
Sources/Contexts.swift
Sources/CrashReportConverter.swift
Sources/Event.swift
Sources/EventProperties.swift
Sources/KSCrashHandler.swift
Sources/Sentry.swift

Add memory/storage/buildnumber

---

SentryTests/SentryBreadcrumbTests.swift
Sources/BreadcrumbStore.swift
docs/advanced.rst

Expose maxBreadcrumbs

---

SentryTests/SentryCrashProbeTests.swift
SentryTests/crashReports/ios-simulator-debug/incomplete.json
Sources/CrashReportConverter.swift
Sources/KSCrashHandler.swift
Sources/Sentry.swift

Add compatibility for incomplete crashes from KSCrash

---

.swiftlint.yml
SentryTests/SentryContextsTests.swift
Sources/BinaryImage.swift
Sources/Breadcrumb.swift
Sources/BreadcrumbStore.swift
Sources/Contexts.swift
Sources/CrashReportConverter.swift
Sources/DebugMeta.swift
Sources/Event.swift
Sources/EventOffline.swift
Sources/EventSerializable.swift
Sources/Exception.swift
Sources/KSCrashHandler.swift
Sources/Log.swift
Sources/QueueableRequestManager.swift
Sources/Thread.swift
Sources/ios/UserFeedbackTableViewController.swift
Sources/ios/UserFeedbackViewModel.swift

https://github.com/getsentry/getsentry/issues/750
@mitsuhiko These are the fields we need right?

Add more fields to device context

---

docs/index.rst

needed for https://github.com/getsentry/sentry-docs/pull/114/

add docs link to debug symbols

---

Sources/Sentry+Event.swift
Sources/Sentry.swift

This PR adds functionality that whenever an event was sent successfully a notification with the serialized event will be sent.

EventSuccessfullySent Notification

---

Sources/RequestOperation.swift

Fix use internal vars in async operation

---

Sources/Sentry/SentryKSCrashInstallation.m
Sources/Sentry/SentryKSCrashReportSink.m
Sources/Sentry/include/SentryDefines.h

Re-order the dependencies for WITH_KSCRASH - fixes #168

---

Sentry.xcodeproj/project.pbxproj
Sources/Sentry/SentryClient.m
Sources/Sentry/include/SentryClient.h
Tests/SentryTests/SentryRequestTests.m
docs/advanced.rst

Add appendStacktraceToEvent function to client

---

Sources/Sentry/SentryFileManager.m

Add nil check and thread safety for reading files

---

Sources/Sentry/SentryKSCrashReportConverter.m

Add nil check for crash reason

---

Sources/Sentry/SentryKSCrashReportConverter.m
Sources/Sentry/SentryUser.m
Sources/Sentry/include/SentryUser.h
Tests/SentryTests/SentryInterfacesTests.m
Tests/SentryTests/SentryRequestTests.m
Tests/SentryTests/SentrySwiftTests.swift

Fixes #200
https://github.com/getsentry/sentry/issues/5792

Make userId optional

---

Sources/Sentry/SentryKSCrashReportConverter.m
Tests/SentryTests/SentryKSCrashReportConverterTests.m

Fixes https://github.com/getsentry/sentry/issues/5875
Fixes https://github.com/getsentry/sentry-cocoa/issues/177

Fix exception interface and threads

---

KSCrash/Sentry-KSCrash.xcodeproj/project.pbxproj
Sentry.podspec
Sentry.xcodeproj/project.pbxproj
Sources/Sentry/Sentry.modulemap
Sources/Sentry/SentryCrashExceptionApplication.m
Sources/Sentry/include/SentryCrashExceptionApplication.h
docs/advanced.rst

Fixes #203
This PR depends on https://github.com/kstenerud/KSCrash/pull/252

Add uncaught exception handling for macOS

---

Sentry.xcodeproj/project.pbxproj

Tick allow-app-extension-API-only box

---

.gitignore
Sources/Sentry/SentryKSCrashReportConverter.m
Tests/SentryTests/SentryKSCrashReportConverterTests.m

fix: Send release version of the crash instead of actual app version

---

KSCrash/Sentry-KSCrash.xcodeproj/project.pbxproj
Sentry.xcodeproj/project.pbxproj
Sources/Sentry/SentryJavaScriptBridgeHelper.m
Sources/Sentry/include/Sentry.h
Sources/Sentry/include/SentryJavaScriptBridgeHelper.h
Tests/Resources/raven-rejectedpromise.json
Tests/Resources/raven-sendMessage.json
Tests/Resources/raven-throwerror.json
Tests/SentryTests/SentryJavaScriptBridgeHelperTests.m

This moves all common code for JavaScript like react native, cordova into a static testable class.

JavaScript Bridge Helper

---

Sources/Sentry/SentryKSCrashReportConverter.m

fix: notableAddresses array count check

---

Sources/Sentry/SentryFileManager.m
Sources/Sentry/SentryJavaScriptBridgeHelper.m
Sources/Sentry/SentryNSURLRequest.m
Tests/SentryTests/SentryDsnTests.m
Tests/SentryTests/SentryFileManagerTests.m

Fixes #236 
Fixes #235 
cc @sahil290791

fix: Parse dsn with last path component

---

Sources/Sentry/SentryKSCrashReportConverter.m
Tests/SentryTests/SentryRequestTests.m

fix: thread index check for crashed thread

---

Sources/Sentry/SentryClient.m
Tests/SentryTests/SentryTests.m

fix: Don't emit nslog if loglevel is none

---

docs/dsym.rst

Fixed typo

---

Sources/Sentry/SentryClient.m
Sources/Sentry/SentryFileManager.m
Sources/Sentry/include/SentryClient.h
Sources/Sentry/include/SentryFileManager.h
Tests/SentryTests/SentryBreadcrumbTests.m
Tests/SentryTests/SentryFileManagerTests.m

Fixes https://github.com/getsentry/sentry-cocoa/issues/258

feat: Add properties to increase filemanager limit

---

Sources/SentryCrash/Recording/Tools/NSError+SimpleConstructor.m
Sources/SentryCrash/Recording/Tools/SentryCrashObjC.c
Sources/SentryCrash/Reporting/Filters/Tools/Container+DeepSearch.m

Prefix or static SentryCrash symbols

---

Sources/Sentry/SentryClient.m

useful in situations where you might want to delay app initialisation until sentry sent events if it crashed last launch

post Sentry/allStoredEventsSent notification after all events sent

---

Sources/Sentry/SentryJavaScriptBridgeHelper.m

Added missing property 'environment' to createSentryEventFromJavaScriptEvent

Add environment support to createSentryEventFromJavaScriptEvent()

---

CHANGELOG.md
Sentry.xcodeproj/project.pbxproj
Sources/Sentry/NSData+SentryCompression.m
Sources/Sentry/NSDate+SentryExtras.m
Sources/Sentry/NSDictionary+SentrySanitize.m
Sources/Sentry/Sentry.modulemap
Sources/Sentry/SentryBreadcrumb.m
Sources/Sentry/SentryCrashReportConverter.m
Sources/Sentry/SentryCrashReportSink.m
Sources/Sentry/SentryEvent.m
Sources/Sentry/SentryNSURLRequest.m
Sources/Sentry/SentryUser.m
Sources/Sentry/include/NSData+SentryCompression.h
Sources/Sentry/include/NSDate+SentryExtras.h
Sources/Sentry/include/NSDictionary+SentrySanitize.h
Sources/SentryCrash/Reporting/Filters/SentryCrashReportFilterBasic.m
Sources/SentryCrash/Reporting/Filters/Tools/Container+SentryDeepSearch.h
Sources/SentryCrash/Reporting/Filters/Tools/Container+SentryDeepSearch.m
Tests/SentryTests/SentryBreadcrumbTests.m
Tests/SentryTests/SentryCrash/Container+DeepSearch_Tests.m
Tests/SentryTests/SentryInterfacesTests.m
Tests/SentryTests/SentryNSDataCompressionTests.m
Tests/SentryTests/SentryRequestTests.m
Tests/SentryTests/SentryTests.m

Rename categories
Emit error log message in case of missconfiguration

fix: Make eventIds lowercase

---

Sentry.xcodeproj/project.pbxproj
Sources/Sentry/NSString+SentryNSUIntegerValue.m
Sources/Sentry/Sentry.modulemap
Sources/Sentry/SentryCrashReportConverter.m
Sources/Sentry/SentryEvent.m
Sources/Sentry/include/NSString+SentryNSUIntegerValue.h
Tests/SentryTests/Categories/SentryNSUIntegerValueTest.m

fix: NSUInteregerValue Category

---

.travis.yml
Sentry.xcodeproj/project.pbxproj
fastlane/Fastfile

@HazAT part of the implementation was within the fastlane lane oc_lint. kept it that way.

fix oclint implementation

---

CHANGELOG.md

meta: 4.4.3

---

Sources/Sentry/NSDictionary+SentrySanitize.m
Tests/SentryTests/SentryInterfacesTests.m

[WIP] Check type of key before use it as NSString

---

Sources/Sentry/NSDictionary+SentrySanitize.m
Tests/SentryTests/SentryInterfacesTests.m

This pr fixes the issue mentioned in #383

fix: Use rawKey to get object from dictionary

---

Sources/Sentry/SentryClient.m
Sources/Sentry/SentryEnvelope.m
Sources/Sentry/SentryFileManager.m
Sources/Sentry/SentrySerialization.m
Sources/Sentry/SentryTransport.m
Sources/Sentry/include/SentryClient.h
Sources/Sentry/include/SentryDefines.h
Sources/Sentry/include/SentryEnvelope.h
Sources/Sentry/include/SentryFileManager.h
Sources/Sentry/include/SentryTransport.h

(cherry picked from commit bc0f4524824f5824071b3ffc55bd32edd528f117)

feat: Add captureEnvelope method to the client

---

Sentry.xcodeproj/project.pbxproj
Sources/Sentry/SentryClient.m
Sources/Sentry/SentryCrashInstallationReporter.m
Sources/Sentry/SentryCrashIntegration.m
Sources/Sentry/SentryHub.m
Sources/Sentry/SentryInstallation.m
Sources/Sentry/SentryNSURLRequest.m
Sources/Sentry/SentrySession.m
Sources/Sentry/SentryTransport.m
Sources/Sentry/SentryUIKitMemoryWarningIntegration.m
Sources/Sentry/include/Sentry.h
Sources/Sentry/include/SentryCrashInstallationReporter.h
Sources/Sentry/include/SentryInstallation.h
Sources/Sentry/include/SentryNSURLRequest.h
Sources/Sentry/include/SentrySession.h
Tests/SentryTests/SentryInstallationTests.m
Tests/SentryTests/SentryTests.m

A collection of hacks to get some sessions in the UI using installation id

feat: Sentry installation

---

Sources/Sentry/SentryHub.m
Sources/Sentry/SentrySDK.m
Sources/Sentry/SentryScope.m
Sources/Sentry/SentrySession.m
Sources/Sentry/include/SentryHub.h

My proposal and I don't think this a hack.

feat: Hub init with Client and Scope

---

Samples/iOS-ObjectiveC/iOS-ObjectiveC.xcodeproj/project.pbxproj
Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme

fyi
@philipphofmann 
@bruno-garcia 
Now building the apps and running them without debugger works.

feat: Add framework to samples

---

Sentry.xcodeproj/project.pbxproj
Sources/Sentry/SentryHttpTransport.m
Sources/Sentry/SentryRequestManager.h
Sources/Sentry/include/SentryHttpTransport.h
Sources/Sentry/include/SentryQueueableRequestManager.h
Sources/Sentry/include/SentryTransportFactory.m

Init SentryRequestManager in SentryTransportFactory
and pass it into SentryHttpTransport to make it easier
to test.

ref: Inject SentryRequestManager

---

Sentry.xcodeproj/project.pbxproj
Sources/Sentry/SentryRateLimitParser.m
Sources/Sentry/include/Sentry.h
Sources/Sentry/include/SentryRateLimitParser.h
Tests/SentryTests/SentryRateLimitsParserTests.m
Tests/SentryTests/SentryRateLimitsParserTests.swift
Tests/SentryTests/SentryTests-Bridging-Header.h

Parses the http header for X-Sentry-Rate-Limits into
a dictionary of categories and retry date.

feat: Parse X-Sentry-Rate-Limits http header 

---

CHANGELOG.md
Sources/Sentry/SentryCrashReportConverter.m
Sources/Sentry/SentryFrame.m
Sources/Sentry/include/SentryFrame.h

Fix the default in app detection in the SDK.
Before:
After:

fix: Frame in app detection

---

Tests/SentryTests/SentryHubTests.m

Create methods for duplicated code for `SentryHubTests`. Also use the boundaries
of equivalence classes to test the max breadcrumbs. This helps to detect off by one
errors.

test: Reduce duplicate code SentryHubTests

---

Sources/Sentry/SentryRateLimitParser.m
Sources/Sentry/include/SentryRateLimitParser.h

Add comments to SentryRateLimitParser.m and add a documentation comment
to SentryRateLimitParser.h.

ref: Add comments to SentryRateLimitParser

---

CHANGELOG.md
Sources/Sentry/SentrySessionTracker.m

This adds auto session starting for macOS applications

feat: Add auto session starting for macOS

---

CHANGELOG.md
Sources/Sentry/SentryHub.m
Sources/Sentry/SentryOptions.m
Sources/Sentry/SentryScope.m
Sources/Sentry/include/SentryScope.h
Tests/SentryTests/SentryOptionsTest.m
Tests/SentryTests/SentryScopeTests.m

fix: remove release from scope

---

CHANGELOG.md
Sentry.xcodeproj/project.pbxproj
Sources/Sentry/SentryNSURLRequest.m
Tests/SentryTests/SentryNSURLRequestTests.swift

I've tested with sessions (only use of envelopes we have right now)

feat: Use envelope endpoint

---

CHANGELOG.md
Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
Samples/iOS-Swift/iOS-Swift/iOS-Swift.entitlements
Sentry.xcodeproj/project.pbxproj

Add support for Mac Catalyst apps, fix was what @ndmanvar posted in the issue.
Fixes https://github.com/getsentry/sentry-cocoa/issues/317

feat: Add support for mac catalyst

---

Sources/Sentry/include/SentryHub.h

fix: session is nullable

---

CHANGELOG.md

Lets add the `unreleased` when the first item lands

changelog 5.0.0-rc.1

---

Makefile
Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
Sources/Configuration/Sentry.xcconfig
Tests/Configuration/SentryTests.xcconfig

Mac Catalyst is not in Carthage yet
https://github.com/Carthage/Carthage/pull/2801

fix: Carthage build

---

.github/pull_request_template.md

Create a PR template
so we don't forget things like me to update the changelog every time
use the template

enha: Create a PR template

---

Sources/Sentry/SentryHttpTransport.m

Format the code for SentryHttpTransport.
Makes the code nicer to read.
If the build is green, nothing broke.
None.

style: Format SentryHttpTransport

---

CHANGELOG.md

meta: Changelog for 5.0.2

---

Sentry.xcodeproj/project.pbxproj
Tests/SentryTests/Integrations/SentrySessionTrackerTests.swift
Tests/SentryTests/SentryTests-Bridging-Header.h
Tests/SentryTests/State/TestHub.swift
Tests/SentryTests/TestClient.swift

Add tests for `SentrySessionTracker`.
Improves the changeability of the code.
I added tests.
None, currently.

test: Add tests for SentrySessionTracker

---

Package.swift
Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
Samples/iOS-Swift/iOS-Swift/SceneDelegate.swift
Samples/iOS-Swift/iOS-Swift/ViewController.swift
Samples/macOS-Swift/macOS-Swift/AppDelegate.swift
Samples/macOS-Swift/macOS-Swift/ViewController.swift
Utils/VersionBump/Package.swift

Formatting all Swift code except tests, because they contain several swiftlint errors and I think it is better to fix those in a separate PR.
Looking at the code and it still compiles.
Format the test code.

style: Format all Swift code

---

.swiftlint.yml
Samples/iOS-Swift/iOS-Swift/ViewController.swift
Tests/SentryTests/Helper/SentryCurrentDateTests.swift
Tests/SentryTests/Helper/SentryDateUtilTests.swift
Tests/SentryTests/Helper/SentryFileManagerTests.swift
Tests/SentryTests/Helper/TestCurrentDateProvider.swift
Tests/SentryTests/Integrations/SentrySessionTrackerTests.swift
Tests/SentryTests/Networking/HttpDateFormatter.swift
Tests/SentryTests/Networking/RateLimits/SentryConcurrentRateLimitsDictionaryTests.swift
Tests/SentryTests/Networking/RateLimits/SentryDefaultRateLimitsTests.swift
Tests/SentryTests/Networking/RateLimits/SentryEnvelopeRateLimitTests.swift
Tests/SentryTests/Networking/RateLimits/SentryRateLimitCategoryMapperTests.swift
Tests/SentryTests/Networking/RateLimits/SentryRateLimitsParserTests.swift
Tests/SentryTests/Networking/RateLimits/SentryRetryAfterHeaderParserTests.swift
Tests/SentryTests/Networking/SentryHttpDateParserTests.swift
Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Tests/SentryTests/Networking/SentryTransportInitializerTests.swift
Tests/SentryTests/Networking/TestRateLimits.swift
Tests/SentryTests/Networking/TestRequestManager.swift
Tests/SentryTests/Networking/TestResponseFactory.swift
Tests/SentryTests/Networking/TestTransport.swift
Tests/SentryTests/SentryClientTests.swift
Tests/SentryTests/SentryNSURLRequestTests.swift
Tests/SentryTests/SentrySwiftTests.swift
Tests/SentryTests/State/TestHub.swift
Tests/SentryTests/TestConstants.swift

Enable SwiftLint also for tests.
Most of our Swift code is test code. Test code should be treated with
the same care as the real code. Therefore it makes sense to
enable SwiftLint also for tests.
Tests are green.
Fix all SwiftLint warnings.

style: Enable SwiftLint for tests

---

Sources/Sentry/SentryCrashReportConverter.m

Use Subscripting in SentryCrashReportConverter to improve the readability.
Unit tests are still passing.

ref: Use Subscripting in CrashReportConverter

---

Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.h
Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m
Samples/iOS-ObjectiveC/iOS-ObjectiveC/SceneDelegate.h
Samples/iOS-ObjectiveC/iOS-ObjectiveC/SceneDelegate.m
Samples/iOS-ObjectiveC/iOS-ObjectiveC/ViewController.h
Samples/iOS-ObjectiveC/iOS-ObjectiveC/ViewController.m
Samples/iOS-ObjectiveC/iOS-ObjectiveC/main.m
Tests/SentryTests/Categories/SentryNSUIntegerValueTest.m
Tests/SentryTests/Helper/SentryLogTests.m
Tests/SentryTests/Helper/SentrySwizzleTests.m
Tests/SentryTests/Networking/SentryDsnTests.m
Tests/SentryTests/SentryBreadcrumbTests.m
Tests/SentryTests/SentryCrash/SentryCrashReportFixer_Tests.m
Tests/SentryTests/SentryInterfacesTests.m
Tests/SentryTests/SentryKSCrashReportConverterTests.m
Tests/SentryTests/SentryNSDataCompressionTests.m
Tests/SentryTests/SentryOptionsTest.m
Tests/SentryTests/SentryScopeTests.m
Tests/SentryTests/SentryTests.m

We don't need the copyright comments as we can see from the git history who created the file.
Tests are green.
None.

style: Remove Copyright comments

---

Sentry.xcodeproj/project.pbxproj

The SentrySessionTests were not executed when running all tests.
We want to run all our tests.
When I call `make test` SentrySessionTests are now also executed.

test: Fix SentrySessionTests for project

---

Samples/tvOS-Swift/tvOS-Swift.xcodeproj/project.pbxproj
Samples/tvOS-Swift/tvOS-Swift/AppDelegate.swift
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Assets.xcassets/Contents.json
Samples/tvOS-Swift/tvOS-Swift/Base.lproj/LaunchScreen.storyboard
Samples/tvOS-Swift/tvOS-Swift/ContentView.swift
Samples/tvOS-Swift/tvOS-Swift/Info.plist
Sentry.xcworkspace/contents.xcworkspacedata

Add a sample app for tvOS to be able to test the SDK on tvOS.
Running the sample app on an emulator and checking the events in Sentry.

test: Add tvOS-Swift sample app

---

Sources/Sentry/SentryClient.m
Tests/SentryTests/Networking/TestTransport.swift
Tests/SentryTests/SentryClientTests.swift

Increase the test coverage for `SentryClient`.

test: Add tests for SentryClient

---

Tests/SentryTests/Integrations/SentrySessionTrackerTests.swift

Add fixture pattern to SentrySessionTrackerTests.
We want to use the fixture pattern in more tests.
None.

test: Fixture for SentrySessionTrackerTests

---

.github/pull_request_template.md

We have GitHub checks to make sure passing tests before merging.
Having a checkbox is redundent

chore: Simplify PR template

---

README.md

See Readme.
We don't want our users to expect that Sentry is working on watchOS as it is on the other platforms.

docs: Update Readme about watchOS support

---

.travis.yml

Tell Travis to build PRs for 6.0.0.
We want to keep the branch 6.0.0 stable as we do with master.
Travis.

ci: Enable Travis for branch 6.0.0

---

Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m

Fix lint issues.
We don't want the lint job on Travis to fail.

style: Fix lint issues for SentryCrashMonitor_System

---

Sources/Sentry/include/Sentry.h
Sources/Sentry/include/SentryClient.h

Remove Copyright © from Sentry.h and SentryClient.h.
We once decided to remove these Copyright © and we want to remove it everywhere.
Travis.

ref: Remove remaining Copyright ©

---

Sources/Sentry/include/SentrySession.h

Remove import for SentryUser and use forward declaration.
Avoids tight coupling of classes.
Travis.

ref: Minimize imports for SentrySession

---

Samples/macOS-Swift/macOS-Swift/ViewController.swift
Tests/SentryTests/Protocol/SentryUserTests.swift

Minor code formatting fixes.
Have all code properly formatted.
Travis.

style: Fix code formatting issues in two Swift files

---

Tests/SentryTests/Integrations/TestNotificationCenter.swift
Tests/SentryTests/Networking/RateLimits/SentryConcurrentRateLimitsDictionaryTests.swift
Tests/SentryTests/Networking/SentryHttpDateParserTests.swift
Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Tests/SentryTests/SentryHubTests.swift

Fix tests on tvOS
Compiling the tests for tvOS didn't work.

test: Fix tests on tvOS

---

.travis.yml

We want to use the latest Xcode version.

ci: Update Travis to Xcode 11.6

---

.github/pull_request_template.md

meta: Fix small typos in the PR template

---

Sources/Sentry/SentryCrashReportConverter.m

Remove commented code in CrashReportConverter.
Remove commented code.
Travis.

ref: Remove commented code in CrashReportConverter

---

Sources/Sentry/SentryStacktraceBuilder.m

Remove unused imports for SentryStacktraceBuilder.
Less code.
Travis.

ref: Remove unused imports for StacktraceBuilder

---

.travis.yml
fastlane/Fastfile

We run linters now with Github Actions.
We don't need to run them twice.
Didn't

ci: Remove linting from Travis

---

.craft.yml
.github/workflows/buildandtest.yml

Use Github as an artifact provider for craft instead of Zeus.
We want to use Github Artifact Provider.
CI

ci: Remove Zeus

---

.slather.yml

We don't use Slather anymore. We can remove the yml file.
Remove files we don't need.

build: Remove slather yml

---

.github/.codecov.yml
.github/workflows/buildandtest.yml

Add a configuration file for Codecov that ignores Sources/SentryCrash
for code coverage and defines a valid range for code coverage.
The code coverage reports are not working properly.
CI.

ci: Add Codecov.yml

---

Sources/SentryCrash/Recording/Tools/SentryCrashObjC.c

https://github.com/kstenerud/KSCrash/pull/383
Introduced by https://github.com/getsentry/sentry-cocoa/pull/786

fix: Not crash during crash reporting

---

README.md

Update Readme on Carthage issue with Xcode 12.
GH-818
Don't need to, it's a Readme update.

docs: Update Readme on Carthage issue

---

Tests/SentryTests/Networking/RateLimits/SentryRateLimitsParserTests.swift

Add test for reason in rate limit response, see https://github.com/getsentry/relay/pull/850.
https://github.com/getsentry/relay/pull/850
I added a test.

test: For reason code in rate limit response

---

Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m
Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
Samples/macOS-Swift/macOS-Swift/AppDelegate.swift
Samples/tvOS-Swift/tvOS-Swift/AppDelegate.swift
Samples/watchOS-Swift/watchOS-Swift WatchKit Extension/ExtensionDelegate.swift
Tests/SentryTests/Integrations/SentrySessionGeneratorTests.swift

We receive events from other apps into our test project. Let's rotate the DSN to get rid of them.
See description
Smoke test with a simulator.
Remove the DSN from the Sentry test project.

test: Rotate DSN for samples and tests

---

.github/workflows/buildandtest.yml
scripts/ci-select-xcode.sh

Use Xcode 12.4 for Github Actions.
We want to use the latest Xcode version.
CI.

ci: Use Xcode 12.4

---

CONTRIBUTING.md

Added them as I was explaining them to @brustolin via Discord, so this is visible for future contributors.

meta: Add test guidelines to Contributing

---

Tests/SentryTests/Networking/RateLimits/SentryConcurrentRateLimitsDictionaryTests.swift
Tests/SentryTests/Networking/RateLimits/SentryEnvelopeRateLimitTests.swift
Tests/SentryTests/Networking/SentryHttpDateParserTests.swift
Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Tests/SentryTests/Protocol/SentryUserTests.swift
Tests/SentryTests/SentryHubTests.swift
Tests/SentryTests/SentrySDKTests.swift
Tests/SentryTests/SentryScopeSwiftTests.swift

Replace Array with Range in for loops.
Makes the code simpler.
CI.

test: Replace Array with Range

---

CHANGELOG.md

Changelog for 6.2.0 with a note on grouping.

meta: Changelog for 6.2.0

---

fastlane/Fastfile

Download all dSYMs and wait for processing to finish.
Some dSYMs are missing for the sample app.
Running fastlane locally.

ci: Download all dSYMs

---

Samples/iOS-ObjectiveC/iOS-ObjectiveC/ViewController.m
Samples/iOS-Swift/iOS-Swift/TraceTestViewController.swift
Samples/tvOS-Swift/tvOS-Swift/ContentView.swift
Samples/watchOS-Swift/watchOS-Swift WatchKit Extension/ContentView.swift

The samples contained build failures. This is fixed now.
We don't want the samples to fail.
Building the samples locally.

test: Fix build failures in Samples

---

Sources/Sentry/Public/SentryHub.h
Sources/Sentry/Public/SentrySDK.h
Sources/Sentry/SentryHub.m
Sources/Sentry/SentrySDK.m

Minor fixes to code docs of SentrySDK and Hub.
We want to have proper code docs for our public classes.
CI.

docs: Fixes for SentrySDK and Hub

---

.craft.yml

craft: auto changelog

---

Sources/Sentry/SentryHttpTransport.m

Remove not needed return in SentryHttpTransport.
Make the code simpler.
CI.

ref: Remove redundant return in HttpTransport

---

.github/workflows/danger.yml
dangerfile.js

add danger: changelog check

---

Sources/Sentry/Public/SentryHub.h
Sources/Sentry/Public/SentrySDK.h

We don't want to have typos in our code docs.
CI

docs: Fix typo for binding to hub

---

.github/CODEOWNERS
Sources/Sentry/Public/SentrySDK.h
Sources/Sentry/Public/SentrySpanProtocol.h
Sources/Sentry/include/SentrySpan.h
Sources/Sentry/include/SentryTracer.h
Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m
Sources/SentryCrash/Recording/SentryCrashReport.c
Tests/SentryTests/SentryCrash/RFC3339UTFString_Tests.m

To get tagged on PRs automatically

meta: add bruno to codeowners

---

.github/workflows/codeql-analysis.yml

fix CodeQL

---

CHANGELOG.md
Sources/Sentry/SentryScope.m
Sources/Sentry/SentrySpan.m
Sources/Sentry/SentryTracer.m
Sources/Sentry/SentryTransaction.m
Sources/Sentry/include/SentrySpan.h
Sources/Sentry/include/SentryTransaction.h

Resolves #1070
We definitely need a step in CI to validate this going forward.

fix: performance headers

---

CHANGELOG.md
Sources/Sentry/SentryScope.m
Tests/SentryTests/SentryScopeSwiftTests.swift

Serializing the span from scope in the Event trace context.
Issue #990 
Unit test

feat: Add trace information from scope to event capture

---

CHANGELOG.md

meta: Changelog for 7.0.0

---

Sources/Sentry/SentryTracer.m
Sources/Sentry/include/SentryTracer.h

See title.
`waitChildren` is a confusing name.
CI.

ref: Rename waitChildren to waitForChildren

---

Sources/Sentry/SentrySpanContext.m

Remove not needed check for nil for nonnullable field operation.
Simplify the code a bit. I came across this when opening https://github.com/getsentry/sentry-cocoa/pull/1147.
CI.

ref: Serialization for SentrySpanContext

---

CHANGELOG.md
Sources/Sentry/SentryTracer.m

Fix SentryTracer that was not waiting for all children to be finished.
Issue #1141
Using the Swift sample project.
CI tests coming next.

fix: Tracer Waiting For all Child Spans

---

CHANGELOG.md
Sources/Sentry/SentryTracer.m
Sources/Sentry/include/SentryUIPerformanceTracker.h
Tests/SentryTests/Performance/SentryTracerTests.swift

Rename `app start` to `app.start.warm` or `app.start.cold` and `ui.rendering` to `ui.load`.
Fixes GH-1129
Unit tests.

fix: Operation names for auto instrumentation

---

Sources/Sentry/SentryPerformanceTrackingIntegration.m
Sources/Sentry/SentryUISwizziling.m
Sources/Sentry/include/SentryUISwizziling.h

ref: SentryUISwizziling only for UIKit

---

.github/workflows/buildandtest.yml

Was not working on master branch.
CI

ci: Fix SPM validation again

---

README.md

docs: Add note about performance preview in ReadMe

---

Tests/SentryTests/Performance/TransactionGeneratorTests.swift

test: Disable TransactionGeneratorTests

---

Sources/Sentry/SentryCrashIntegration.m
Tests/SentryTests/Integrations/SentryCrashIntegrationTests.swift

Running all tests on a local MacBook Pro fails. This is fixed now.
We want to be able to run all the tests locally.
Running the tests locally.

test: Fix running tests locally

---

.github/workflows/buildandtest.yml
Makefile

The upload of the code coverage to codecov was failing. This
is fixed now.
We want to upload code coverage to codecov.
By running the changes in CI and seeing the result in [codecov](https://codecov.io/gh/getsentry/sentry-cocoa/commit/785dff947be0d1065c8df5159adaa8dd7125d2cb).

ci: Fix uploading to Codecov

---

Gemfile.lock

build: Update sentry-fastlane to 1.8.3

---

Sources/Sentry/SentryAppStartTracker.m

ref: Remove unused imports in AppStartTracker

---

CHANGELOG.md

meta: Prepare Changelog for 7.2.0

---

Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
Samples/iOS-Swift/iOS-Swift/NibViewController.swift
Samples/iOS-Swift/iOS-Swift/NibViewController.xib
Samples/iOS-Swift/iOS-Swift/ViewController.swift

Added a  Show NIB button in the home that opens a view controller based on a XIB.
A customer reported a crash with Nib UIViewControllers.
It's for testing.

test: Add XIB based UIViewController

---

.github/workflows/buildandtest.yml
Tests/SentryTests/Integrations/SentryNetworkTrackerIntegrationTests.swift
Tests/SentryTests/Integrations/SentryPerformanceTrackerTests.swift
Tests/SentryTests/Integrations/URLSessionTaskMock.h
Tests/SentryTests/Integrations/URLSessionTaskMock.m
scripts/ci-select-xcode.sh

Run UI and unit tests on more OS versions to make sure the SDK is working.
We had a problem on iOS 13 recently, see https://github.com/getsentry/sentry-cocoa/issues/1296
CI.

ci: Run tests on more OS versions

---

Samples/macOS-Swift/macOS-Swift/ViewController.swift

test: macOS-Swift Remove empty function

---

Tests/SentryTests/Integrations/SentryNetworkTrackerIntegrationTests.swift
Tests/SentryTests/Networking/SentryHttpTransportTests.swift

Ignore flaky tests
part of https://github.com/getsentry/sentry-cocoa/issues/1031
flaky tests may fail a new release

Ignore flaky tests

---

.github/workflows/test.yml

ci: Fix AppCenter Tests

---

.github/workflows/test.yml

ci: Fix hashFiles

---

.github/workflows/test.yml

ci: Fix unit test cache

---

.github/workflows/test.yml

ci: Fix Integration Web Requests on Master

---

Makefile

build: Fix makefile

---

.github/workflows/lint.yml
Makefile
Sources/Sentry/SentryClient.m
Sources/Sentry/SentryEnvelope.m
Sources/Sentry/SentryFileManager.m
Sources/Sentry/SentryHttpTransport.m
Sources/Sentry/SentryHub.m
Sources/Sentry/SentryOptions.m
Sources/Sentry/SentrySDK.m
Sources/Sentry/SentrySwizzle.m
Sources/Sentry/SentrySystemEventsBreadcrumbs.m
Sources/Sentry/SentryTransaction.m
Sources/SentryCrash/Recording/SentryCrash.h
Sources/SentryCrash/Recording/SentryCrash.m
Sources/SentryCrash/Recording/Tools/SentryCrashFileUtils.c

Run xcodebuild analyze in CI. Fixed all the analyze warnings in our code as well. Mitigates https://github.com/getsentry/sentry-cocoa/pull/1385.

ref: Fix Xcode Analyze Errors

---

.github/workflows/build.yml
.github/workflows/format-code.yml
.github/workflows/testflight.yml

ci: Specify paths for build and format-code

---

.github/workflows/lint.yml

ci: Run lint on master and specify paths

---

Samples/macOS-Swift/macOS-Swift.xcodeproj/project.pbxproj
Samples/macOS-Swift/macOS-Swift.xcodeproj/xcshareddata/xcschemes/macOS-Swift.xcscheme
Samples/macOS-Swift/macOS-Swift/Base.lproj/Main.storyboard
Samples/macOS-Swift/macOS-Swift/CppSample.cpp
Samples/macOS-Swift/macOS-Swift/CppSample.hpp
Samples/macOS-Swift/macOS-Swift/CppWrapper.h
Samples/macOS-Swift/macOS-Swift/CppWrapper.m
Samples/macOS-Swift/macOS-Swift/ViewController.swift
Samples/macOS-Swift/macOS-Swift/macOS-Swift-Bridging-Header.h

Add a button to throw an unhandled CPP exception to be able to test https://github.com/getsentry/sentry/issues/30399.

test: Add CppException to macOS Sample

---

.github/workflows/test.yml
.sauce/config.yml

ci: Retry SauceLab tests

---

.github/workflows/test.yml

ci: Fix broken test.yml

---

.github/workflows/test.yml

ci: Retry for Alamofire tests

---

CONTRIBUTING.md

docs: Update Commit Guidelines in Contributing

---

.github/workflows/test.yml

Might fix https://github.com/getsentry/sentry-cocoa/issues/1527.

test: Update Alamofire Integration Tests

---

.github/workflows/test.yml

test: Add Retry for UI Tests

---

.github/workflows/integration-tests.yml

ci: Remove ci branch for integration tests

---

Samples/iOS-Swift/iOS-Swift/ViewControllers/NibViewController.xib
Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift

test: Use accessibility modifier for lonely button

---

Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift

Add a default timeout for waitForExistence, so the test code is
more precise.

test: Add default waitForExistence

---

.github/workflows/integration-tests.yml

ci: Remove Matrix for Home Assistant

---

.github/workflows/add-to-project.yml

ci: Add new issues and PRs to Team Mobile Project

---

Sources/Sentry/Public/SentryOptions.h

docs: Update docs for enableNetworkTracking

---

.github/workflows/integration-tests.yml

ci: Run integration tests for risky branches

---

Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m
Samples/iOS-SwiftUI/iOS-SwiftUI/SwiftUIApp.swift
Samples/iOS15-SwiftUI/iOS15-SwiftUI/App.swift
Samples/macOS-Swift/macOS-Swift/AppDelegate.swift
Samples/tvOS-Swift/tvOS-Swift/AppDelegate.swift
Samples/watchOS-Swift/watchOS-Swift WatchKit Extension/ExtensionDelegate.swift

test: Enable file IO tracking for sample apps

---

.github/workflows/integration-tests.yml

ci: Use iOS 15.2 for integration tests

---

Tests/SentryTests/Helper/SentrySwizzleTests.m

test: Fix build for Xcode 13.3

---

CHANGELOG.md

meta: Fix Changelog

---

Tests/SentryTests/SentryTests-Bridging-Header.h

test: Fix bridging header build failure

---

Tests/SentryTests/SentryClientTests.swift

test: Disable flaky tests in Client

---

Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard

test: Fix layout for iPhone 13

---

Sources/Sentry/include/SentryEnvelopeRateLimit.h

docs: Add missing * for EnvelopeRateLimit

---

Sources/Sentry/SentryUserFeedback.m

ref: Simplify UserFeedback serialize

---

Sources/Sentry/include/SentryDataCategory.h

For context see https://github.com/getsentry/develop/pull/529.

ref: Fix code comment on DataCategory

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/test.yml
scripts/ci-select-xcode.sh

It's time to use the latest Xcode version and we also get warnings from Apple after uploading to TestFlight.

ci: Make Xcode 13.2.1 default

---

Sources/Sentry/Public/SentryOptions.h
Sources/Sentry/SentryHttpTransport.m
Sources/Sentry/SentryOptions.m
Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Tests/SentryTests/SentryOptionsTest.m

feat: Add sendClientReports to options

---

Tests/SentryTests/Helper/SentryFileManagerTests.swift

Use test expectation instead of DispatchGroup to try to fix
flaky testDefaultMaxEnvelopesConcurrent.
Fixes GH-1718

test: Fix flaky test in SentryFileManager

---

Sources/Sentry/Public/SentryError.h
Sources/Sentry/SentryANRTracker.m
Sources/Sentry/SentryAutoBreadcrumbTrackingIntegration.m
Sources/Sentry/SentryClient.m
Sources/Sentry/SentryCrashExceptionApplication.m
Sources/Sentry/SentryDateUtil.m
Sources/Sentry/SentryDefaultCurrentDateProvider.m
Sources/Sentry/SentryDefaultObjCRuntimeWrapper.m
Sources/Sentry/SentryFileManager.m
Sources/Sentry/SentryLevelMapper.m
Sources/Sentry/SentryLogOutput.m
Sources/Sentry/SentryMigrateSessionInit.m
Sources/Sentry/SentryOptions.m
Sources/Sentry/SentrySerialization.m
Sources/Sentry/SentrySysctl.m
Sources/Sentry/SentryThreadWrapper.m
Sources/Sentry/include/SentryLevelMapper.h
Sources/Sentry/include/SentryThreadWrapper.h

ref: Optimize some imports

---

Gemfile.lock

build: bump sentry fastlane plugin to 1.11.1

---

CHANGELOG.md

meta: Mention min Sentry version for profiling

---

Sources/Sentry/SentryDependencyContainer.m

Adding a double check lock for performance increase with DependencyContainer.

perf: Double check lock for DependencyContainer

---

.github/workflows/test.yml
scripts/xcode-test.sh

ci: Only report failing tests on master

---

.github/workflows/test.yml

ci: Upload raw test logs when cancelled

---

Sources/Sentry/SentryProfiler.mm

ref: remove unused variable captured in profiler block

---

Samples/TrendingMovies/TrendingMovies/AppDelegate.swift

Add Sentry to TrendingMovies sample

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/danger.yml
.github/workflows/format-code.yml
.github/workflows/integration-tests.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/testflight.yml
.github/workflows/ui-tests.yml

ci: Update to checkout@v3 from v2

---

Samples/iOS-Swift/iOS-Swift/ViewControllers/TraceTestViewController.swift

Noticed that the first time you navigate to the Image screen in iOS-Swift, there's a main thread fault due to us displaying some UI on the NSURLSession bg thread:

fix: dispatch to main thread in the network->assert path

---

Sources/Sentry/SentryTracer.m
Sources/Sentry/SentryTransaction.m
Sources/Sentry/include/SentryTransaction.h
Tests/SentryTests/Performance/SentryTracerTests.swift
Tests/SentryTests/SentryClientTests.swift
Tests/SentryTests/Transaction/SentryTransactionTests.swift

The PR #1826 was not correctly formatted, but I didn't want to ping the
contributor again to fix the formatting. I wanted to get the PR merged.

Fix code formatting

---

.github/workflows/build.yml
.github/workflows/saucelabs-UI-tests.yml
.github/workflows/test.yml
.github/workflows/testflight.yml
Sources/Sentry/SentrySubClassFinder.m

Updates versions of some tools used in CI workflows. Also improved some wording in a debug log I noticed.

ci: update tooling

---

develop-docs/README.md

docs: Decision not capturing screenshots for crashes

---

Samples/iOS-SwiftUI/iOS-SwiftUI.xcodeproj/project.pbxproj
Samples/iOS-SwiftUI/iOS-SwiftUI/ContentView.swift
Samples/iOS-SwiftUI/iOS-SwiftUI/LoremIpsumView.swift

Add two screens to the SwiftUI sample to be able to test
APM.

test: Add some screens to SwiftUI sample

---

.github/dependabot.yml

ci: Fix dependabot

---

Samples/iOS-Swift/iOS-Swift/Tools/SentryBenchmarking.mm
Samples/iOS-Swift/iOS-SwiftUITests/SDKPerformanceBenchmarkTests.swift

ci: benchmarking fixes

---

Sources/Sentry/SentryAppStartTracker.m

Add link to pre warm launch docs

---

Tests/SentryTests/Integrations/ANR/SentryANRTrackerTests.swift

Fixed a flake test for app hangs.

fix: Flake app hang test

---

CONTRIBUTING.md

meta: Add sut to contributing

---

CONTRIBUTING.md

meta: Mention draft PRs in Contributing

---

CONTRIBUTING.md

meta: Add LOGAF scale to Contributing

---

Samples/iOS-ObjectiveC/iOS-ObjectiveC/ViewController.m
Samples/iOS-Swift/iOS-Swift/ViewController.swift
Sources/Sentry/Public/SentryEvent.h

docs: update some docs/comments to read a little better

---

Samples/watchOS-Swift/watchOS-Swift.xcodeproj/xcshareddata/xcschemes/watchOS-Swift WatchKit App.xcscheme
Sources/Sentry/SentryCrashWrapper.m
Sources/Sentry/include/SentryCrashWrapper.h
Tests/SentryTests/SentryCrash/TestSentryCrashWrapper.h
Tests/SentryTests/SentryCrash/TestSentryCrashWrapper.m

ref: Fix linter error

---

.github/CODEOWNERS

meta: add armcknight as a codeowner

---

Sources/Sentry/SentryAppStartTrackingIntegration.m
Sources/Sentry/SentryFramesTrackingIntegration.m
Sources/Sentry/SentryPerformanceTrackingIntegration.m
Sources/Sentry/include/SentryPerformanceTrackingIntegration.h
Tests/SentryTests/Integrations/Performance/AppStartTracking/SentryAppStartTrackingIntegrationTests.swift
Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackingIntegrationTests.swift

fix log message option name

---

Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerTests.swift
Tests/SentryTests/Transaction/SentryBaggageTests.swift

Fix build failure in unit tests

---

CHANGELOG.md

These items went in the wrong locations due to a bad merge.

fix: Bad merge on CHANGELOG.md

---

.github/workflows/profile-data-generator.yml

ci: run profile generator 4x per day

---

.github/CODEOWNERS

meta: add indragie as a codeowner

---

.github/workflows/test.yml
Sources/Sentry/NSDate+SentryExtras.m
Sources/Sentry/NSLocale+Sentry.m
Sources/Sentry/SentryNSURLSessionTaskSearch.m
Tests/SentryTests/Integrations/UIEvents/SentryUIEventTrackingIntegrationTests.swift
scripts/xcode-test.sh

Retry failing tests, a max of 3 times in total.

tests: Retry failed tests

---

Tests/SentryTests/Integrations/Session/SentrySessionTrackerTests.swift

In pursuit of https://github.com/getsentry/sentry-cocoa/issues/2062

test: add descriptions to assertions

---

Sources/Sentry/SentryCoreDataTracker.m
Sources/Sentry/SentryUIEventTracker.m

ref: Improve log logic

---

.github/workflows/benchmarking.yml
.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/profile-data-generator.yml
.github/workflows/saucelabs-UI-tests.yml
.github/workflows/test.yml
.github/workflows/testflight.yml

ci: trigger workflow runs when scripts they use change

---

Sources/Sentry/SentryCrashIntegration.m
Sources/SentryCrash/Recording/Monitors/SentryCrashMonitorContext.h
Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m
Sources/SentryCrash/Recording/SentryCrash.m
Sources/SentryCrash/Recording/SentryCrashReport.c
Sources/SentryCrash/Recording/SentryCrashReportFields.h

Continuation of #2036. See https://github.com/getsentry/sentry-cocoa/issues/2092#issuecomment-1225736484.

feat: Remove timezone from device context

---

CHANGELOG.md
Sources/Sentry/SentryANRTracker.m
Tests/SentryTests/Integrations/ANR/SentryANRTrackerTests.swift

See https://github.com/getsentry/sentry-cocoa/issues/1865#issuecomment-1216310438.
Closes #1865
Existing unit tests, plus manually in the sample app.

fix: Improve App Hangs detection

---

Sources/Sentry/SentryUIViewControllerSwizzling.m

ref: Improve logs for UIViewControllerSwizzling

---

Sources/Sentry/Public/SentryOptions.h

ref: Mention app hang default value in comments

---

Samples/tvOS-Swift/tvOS-Swift/AppDelegate.swift
Samples/tvOS-Swift/tvOS-Swift/ContentView.swift

Added the sample code when testing https://github.com/getsentry/sentry-cocoa/issues/2116.

test: Add file IO and HTTP spans to tvOS sample

---

CONTRIBUTING.md

meta: Clarify PR rules in Contributing

---

CHANGELOG.md
Package.swift
Samples/SPM-Dynamic/Package.swift
Sources/Sentry/SentryOptions.m
Tests/SentryTests/PrivateSentrySDKOnlyTests.swift
Tests/SentryTests/SentryOptionsTest.m

fix: setting SDK name through options[sdk][name] shouldn't clear version

---

Sources/Sentry/SentryTime.mm
Sources/Sentry/include/SentryTime.h
Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerSwizzlingTests.swift

ref: Fix Xcode 14 compile issues

---

Sources/Sentry/PrivateSentrySDKOnly.m

ref: Fix typo in measurement

---

Gemfile.lock

build: bump fastlane to 2.210.0

---

test-server/Package.swift

Update vapor in test server to the latest version.
##skip-changelog

test: Update vapor to 4.65.2

---

develop-docs/README.md

docs: How to find SauceLabs available devices

---

.github/workflows/benchmarking.yml
.github/workflows/profile-data-generator.yml
.github/workflows/saucelabs-UI-tests.yml

ci: Update saucectl from 0.99.4 to 0.107.2

---

CONTRIBUTING.md

meta: Contributing md lint fixes

---

.sauce/config.yml
.sauce/profile-data-generator-config.yml

SauceLabs updated its iOS 15.6 to 15.7.

chore: Update SauceLabs config

---

Tests/SentryTests/Integrations/NotificationCenterTestCase.swift

test: Fix test notification center for macOS

---

CHANGELOG.md

meta: Add docs link for custom error desc

---

Tests/SentryTests/SentryCrash/SentryCrashMonitor_AppState_Tests.m

test: Remove empty assert msg for AppStateTests

---

.github/workflows/test.yml

ci: Fix typo in comments for tests.yml

---

.github/workflows/integration-tests.yml
scripts/add-sentry-to-vlc.patch

Update VLC integration tests to latest commit hash.

ci: Point to latest GH hash for VLC tests

---

Sentry.xcworkspace/contents.xcworkspacedata

as it is rarely worked on and constantly dirties the index

ref: remove watchkit project from workspace

---

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme
Tests/SentryTests/SentryHubTests.swift

Issue to fix flaky test https://github.com/getsentry/sentry-cocoa/issues/2300

Disable testStartTransaction_ProfilingDataIsValid

---

Sources/Sentry/SentryCoreDataTracker.m
Tests/SentryTests/Helper/SentrySwizzleWrapperTests.swift
Tests/SentryTests/Integrations/UIEvents/SentryUIEventTrackingIntegrationTests.swift

fix various typos

---

.github/ISSUE_TEMPLATE/flaky-test.yml
CONTRIBUTING.md

Add an issue template for flaky tests.

meta: Add flaky test issue template

---

Sentry.xcodeproj/project.pbxproj
Sources/Sentry/Public/SentryHttpStatusCodeRange.h
Sources/Sentry/SentryNetworkTracker.m
Sources/Sentry/include/SentryHttpStatusCodeRange+Private.h
Tests/SentryTests/SentryTests-Bridging-Header.h

ref: Make isInRange private

---

.github/workflows/format-code.yml
CONTRIBUTING.md
Sources/SentryCrash/Recording/SentryCrash.m

ci: Update brew before installing clang-format

---

Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerIntegrationTests.swift

Fix typos in NetworkTrackerIntegrationTests

---

Samples/iOS-Swift/iOS-Swift/Tools/MetricKitManager.swift

test: Fix MetricKit attachment filename

---

CHANGELOG.md

Fixing what looks like a merge error in changelog.

fix: changelog merge error

---

CHANGELOG.md

Updating extra information in the 8.0.0 version changelog.

Update 8.0.0 CHANGELOG

---

Sources/Sentry/SentryOutOfMemoryTracker.m

ref: Fix typos in OOMTracker

---

.swiftlint.yml

meta: Enable `yoda_condition` rule for SwiftLint

---

Samples/TrendingMovies/TrendingMovies/TMDb/TMDbClient.swift

meta: disable swiftlint file length check in TBDBClient.swift

---

.github/workflows/test.yml
Gemfile
Gemfile.lock
Makefile
scripts/xcode-test.sh

ci: Fix Codecov

---

.github/.codecov.yml
.github/workflows/test.yml

Run slather only for iOS. Fixes for codecov.yml

ci: Various fixes for Codecov

---

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme
Tests/SentryTests/Profiling/SentryProfilerSwiftTests.swift

test: Disable testConcurrentSpansWithTimeout_disabled

---

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme

test: Fix disabled failing watchdog test

---

Sources/Sentry/SentryClient.m

ref: Rename isOOM to watchdog in Client

---

CHANGELOG.md

Remove duplicate changelog entry

---

.craft.yml

meta: Add SwiftUI to craft

---

Sentry.xcodeproj/project.pbxproj
Sources/SentrySwiftUI/SentryTraceView.swift

Rename the SentryTracerView file to SentryTraceView, and fix one reference of SentryTracerView in code comments.

ref: Fix SentryTraceView naming

---

Samples/iOS-SwiftUI/iOS-SwiftUI/LoremIpsumView.swift

test: Instrument LoremIpsum of the SwiftUI sample

---

Tests/SentryTests/Performance/SentryTracerTests.swift

ref: Fix lint issue in tracer

---

CHANGELOG.md

Clarify SwiftUI is experimental in Changelog

---

.github/workflows/benchmarking.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/integration-tests.yml
.github/workflows/lint.yml
.github/workflows/saucelabs-UI-tests.yml
.github/workflows/test.yml
.github/workflows/testflight.yml
.pre-commit-config.yaml
Samples/SPM-Dynamic/Package.swift
Samples/macOS-SPM-CommandLine/Package.swift
scripts/xcode-test.sh

Remove remaining master branch references, or replace them with main.

chore: Remove master branch references

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml

Kindly ask if users want to submit a PR when opening an issue. The field is not required.

chore: Ask for PR in templates

---

Samples/macOS-SPM-CommandLine/Package.swift

Added SentrySwiftUI with SPM in a sample project to validate it during CI.

ci: Validate SentrySwiftUI SPM

---

Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme

Issue https://github.com/getsentry/sentry-cocoa/issues/2647

test: Disable testMetricProfiler

---

.github/pull_request_template.md

chore: Add PII to PR template

---

Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m

chore: Fix typo in CrashMonitor_System

---

Samples/watchOS-Swift/watchOS-Swift WatchKit Extension/ContentView.swift
Samples/watchOS-Swift/watchOS-Swift WatchKit Extension/ExtensionDelegate.swift

Repro for https://github.com/getsentry/sentry-cocoa/issues/2713.

test: Add cause ANR for watchOS sample

---

Sources/Sentry/SentryANRTracker.m
Sources/Sentry/SentryBreadcrumbTracker.m
Sources/Sentry/SentryCrashDefaultMachineContextWrapper.m
Sources/Sentry/SentryCrashReportSink.m
Sources/Sentry/SentryHub.m
Sources/Sentry/SentryPerformanceTracker.m
Sources/Sentry/SentrySpanContext.m
Sources/Sentry/SentryStacktraceBuilder.m
Sources/Sentry/SentrySubClassFinder.m
Sources/Sentry/SentrySwizzle.m
Sources/Sentry/SentryThreadInspector.m
Sources/Sentry/SentryViewHierarchy.m

Changing `true` to `YES` and `false` to `NO` in objc files.

chore: Use YES and NO for objc BOOL

---

CHANGELOG.md

chore: Add #2729 to Changelog

---

CHANGELOG.md

Add note to 8.3.0 changelog about Profiling crash and fix PR reference in 8.3.1 changelog.

chore: Add note to 8.3.0 changelog and fix PR reference in 8.3.1 changelog

---

README.md

Fix readme.md workflow shields badge for build status

---

Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
Samples/iOS-Swift/iOS-Swift/ViewController.swift

Added a button that will start 100 threads that will be alive for 10 seconds.
I believe is enough time to click any other button to try a feature with that many threads running.

chore: Add a button to iOSSwift sample to start threads

---

Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift
Samples/iOS-Swift/iOS13-SwiftTests/LaunchUITest.swift

fix: typo Existense->Existence

---

Samples/iOS-ObjectiveC/iOS-ObjectiveC/InitializerViewController.h
Sources/Sentry/SentryUIViewControllerSwizzling.m

fix: typo Swizziling -> Swizzling

---

Samples/iOS-Swift/PerformanceBenchmarks/SentryProcessInfo.m
Samples/iOS-Swift/iOS-Swift/Tools/SentryBenchmarking.mm
Samples/macOS-Swift/macOS-Swift/CppSample.cpp
Sources/Sentry/SentrySwizzle.m
Sources/Sentry/SentrySysctl.m
Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor.c
Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_AppState.c
Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp
Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_MachException.c
Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_NSException.m
Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_Signal.c
Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m
Sources/SentryCrash/Recording/SentryCrash.m
Sources/SentryCrash/Recording/SentryCrashC.c
Sources/SentryCrash/Recording/SentryCrashCachedData.c
Sources/SentryCrash/Recording/SentryCrashReportStore.c
Sources/SentryCrash/Recording/Tools/SentryCrashDynamicLinker.c
Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.c
Sources/SentryCrash/Recording/Tools/SentryCrashSysCtl.c
Sources/SentryCrash/Recording/Tools/SentryCrashThread.c
Sources/SentryCrash/Recording/Tools/SentryHook.c
Tests/SentryProfilerTests/SentryBacktraceTests.mm
Tests/SentryProfilerTests/SentryThreadHandleTests.mm
Tests/SentryTests/SentryCrash/SentryCrashMonitor_CppException_Tests.mm

Xcode 14.3 is complaining everywhere about this:

fix: Functions without prototype error

---

.github/workflows/saucelabs-UI-tests.yml
.sauce/config.yml

ci: Run UI tests on iOS 16

---

.github/workflows/test.yml

ci: Run unit tests on tvOS 16 and macOS 13

---

Tests/SentryTests/TestLogOutput.swift

Don't call super when running testLoggingFromMulitpleThreads to avoid spamming the test logs.
<details><summary>Test Logs of testLoggingFromMulitpleThreads</summary>
<p>
```
Test Case '-[SentryTests.TestLogOutPutTests testLoggingFromMulitpleThreads]' started.
2023-04-14 11:38:56.598755+0000 xctest[4997:20773] Some message 0
2023-04-14 11:38:56.598788+0000 xctest[4997:19473] Some message 0
2023-04-14 11:38:56.598858+0000 xctest[4997:19473] Some message 1
2023-04-14 11:38:56.598927+0000 xctest[4997:19473] Some message 2
2023-04-14 11:38:56.598982+0000 xctest[4997:19473] Some message 3
2023-04-14 11:38:56.599035+0000 xctest[4997:19473] Some message 4
2023-04-14 11:38:56.599087+0000 xctest[4997:19473] Some message 5
2023-04-14 11:38:56.599138+0000 xctest[4997:19473] Some …
```

test: Remove noisy logs for TestLogTests

---

CHANGELOG.md

meta: fix a changelog entry and add one for GPU timestamps

---

Brewfile.lock.json

Run brew bundle to update brews to the latest version.

build: Update brew

---

scripts/set-device-tests-environment.patch

Broken with https://github.com/getsentry/sentry-cocoa/pull/2936.

ci: Fix device tests patch

---

Sources/Sentry/Public/SentryOptions.h

docs: Add default for user interaction tracing

---

Samples/iOS-SwiftUI/iOS-SwiftUI/ContentView.swift

Organize SwiftUI sample to have more room for buttons after trace origin PR added more item to the screen.

chore: Swiftui sample fix

---

Sources/Sentry/SentryFileManager.m
Sources/Sentry/include/SentryFileManager.h
Tests/SentryTests/Helper/SentryFileManagerTests.swift

Remove the unused method storeDictionary:toPath.

ref: Remove unused FileManager.storeDictionary

---

.github/workflows/testflight.yml

ci: Use macOS 13 and Xcode 14.3 for Testflight

---

scripts/ci-select-xcode.sh

chore: Add macOS 13 GH actions image link

---

Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m
Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
Samples/macOS-Swift/macOS-Swift/AppDelegate.swift
Samples/tvOS-Swift/tvOS-Swift/AppDelegate.swift
Sources/Sentry/Public/SentryOptions.h
Sources/Sentry/SentrySDK.m
Tests/SentryTests/SentryOptionsTest.m

Related PR https://github.com/getsentry/sentry-cocoa/pull/2982.

test: Use initialScope in sample apps

---

.spi.yml

Fixes https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2374

Fix SPI watchOS build error

---

Sources/Sentry/Public/SentryRequest.h
Sources/Sentry/SentryClient.m
Sources/Sentry/SentryEnvelope.m
Sources/Sentry/SentryHub.m
Sources/Sentry/SentryNSURLRequest.m
Sources/Sentry/SentrySession.m
Sources/Sentry/include/SentrySerialization.h
Tests/SentryTests/SentryHubTests.swift
Tests/SentryTests/SentryInterfacesTests.m
Tests/SentryTests/SentrySessionTests.m

Remove a couple of stale todos in the code base.

chore: Remove stale todos

---

.pre-commit-config.yaml

Copied from https://github.com/getsentry/sentry/blob/1b31bea3d9f2e93ebe03ddff6573eb36e2091ba9/.pre-commit-config.yaml#L64-L69

chore: Add precommit check for GH actions and workflows

---

CHANGELOG.md

This was a hotfix and not a feature release.

Fix changelog for 8.7.1

---

scripts/no-changes-in-high-risk-files.sh

Updated the script that check for changes in high risk files.

Fix no changes in high risk files

---

Samples/iOS-Swift/iOS-Swift/ViewControllers/TraceTestViewController.swift

Fixing `testNavigationTransaction` UI Test.

Fixing testNavigationTransaction

---

CHANGELOG.md

chore: Fix CHANGELOG

---

Samples/iOS-SwiftUI/iOS-SwiftUI.xcodeproj/xcshareddata/xcschemes/iOS-SwiftUI.xcscheme
Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme
Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerIntegrationTests.swift

Im enabling some tests to be able to fix them.
This is related to #2607 #2605 #2606 #2388 

chore: Enabling some flake tests to be able to monitor it

---

CHANGELOG.md

docs: Add note on in-app frames for 8.2.0

---

CHANGELOG.md

chore: Prepare Changelog for 8.9.0

---

CHANGELOG.md
Sources/Sentry/SentrySystemWrapper.mm

Accidentally left in from #3217

fix: remove noisy NSLog

---

CHANGELOG.md

meta: Fix typo in changelog

---

Sources/Sentry/SentryOptions.m

meta: clean up some redundant flags and comment on their closures

---

CHANGELOG.md

meta: changelog tsan fixes

---

Sources/Sentry/SentryFrame.m

ref: Shorten SentryFrame init

---

Sources/Sentry/SentryTransportFactory.m

ref: Remove unused reachability import

---

Sources/Sentry/SentryProfiler.mm

Noticed this when investigating something around this code area. Classic copypasta.

meta: fix log statement

---

Sources/Sentry/SentryUIEventTracker.m

Define an extra method for handling the send action callback to make the code easier to read.

ref: Reduce nesting for UIEventTracker

---

.github/workflows/build.yml
CHANGELOG.md

The XCFramework attached to GitHub releases is now built with Xcode 15.
Fixes GH-3411
CI

impr: Build XCFramework with Xcode 15

---

.github/ISSUE_TEMPLATE/bug.yml

Add environment and allow selecting multiple platforms for the bug template.

chore: Improve bug template

---

Sources/Sentry/SentryUIViewControllerPerformanceTracker.m

ref: Remove unused import in performance tracker

---

Tests/SentryTests/SentryCrash/SentryCrashInstallationReporterTests.swift

Use the same options when installing the SentryCrashInstallationReporter and starting the SDK so SentryCrashInstallationReporter.install doesn't have to retrieve the cacheDirectoryPath from the PrivateSentrySDKOnly. Furthermore, validate that the TestClient has a captured crash event.
I noticed this while investigating the flaky test `SentryCrashInstallationReporter. testReportIsSentAndDeleted` in CI https://github.com/getsentry/sentry-cocoa/actions/runs/7709958370/job/21012298308?pr=3594. While the change might not solve the flaky test 100%, it improves the quality of the tests.

test: Improve for CrashInstallationReporterTests

---

.github/workflows/benchmarking.yml
.github/workflows/saucelabs-UI-tests.yml

ci: Bump saucectl from 0.171.0 to 0.173.2

---

.github/workflows/ui-tests.yml

ci: Remove address sanitizer for iOSSwift UI tests

---

Samples/macOS-Swift/macOS-Swift/AppDelegate.swift
Samples/macOS-Swift/macOS-Swift/ViewController.swift

Use NSApplicationCrashOnExceptions in the AppDelegate and call reportException. 
For investigating https://github.com/getsentry/sentry-cocoa/issues/3265#issuecomment-1973135855.

test: Update reporting NSException

---

Sentry.xcodeproj/project.pbxproj

So that include/HybridPublic also works.

ref: Make Swift include paths recursive

---

SentryTestUtils/SentryTestUtils-ObjC-BridgingHeader.h
Sources/Sentry/PrivateSentrySDKOnly.mm
Sources/Sentry/SentryBaggage.m
Sources/Sentry/include/HybridPublic/PrivateSentrySDKOnly.h
Sources/Sentry/include/SentryTraceContext.h

This PR is based on https://github.com/getsentry/sentry-cocoa/pull/3723.

ref: Cleanup PrivateSDKOnly imports

---

Sources/Sentry/Public/SentryAttachment.h

ref: Remove unused import for attachment

---

Sources/Sentry/Public/SentryUser.h
Sources/Sentry/SentryUser.m

ref: Move Geo import to impl for User

---

Sources/Sentry/SentrySpan.m
Sources/Sentry/include/SentryNoOpSpan.h
Tests/SentryTests/TestUtils/SentryBooleanSerialization.h
Tests/SentryTests/TestUtils/SentryBooleanSerialization.m

ref: Remove unused Serializable imports

---

CHANGELOG.md

Add more information on the removal of SentryPrivate

chore: Add more details for SentryPrivate

---

CHANGELOG.md
Samples/iOS-Swift/iOS-Swift/ViewControllers/ReplaceContentViewController.swift
Sources/Sentry/SentryUIApplication.m

Small follow up fixes for GH-3753.

ref: Follow up fixes for contributor PR 3753

---

Makefile

[suggestion] chore: Move XCFrameworks to root after building

---

develop-docs/DECISIONS.md

Fix typos in DECISIONS.md

---

.gitattributes
Sentry.xcodeproj/project.pbxproj

meta: add some config files to pbxproj for easy editing and clean up the list

---

Samples/iOS-Swift/iOS-Swift/Profiling/ProfilingViewController.swift
Samples/iOS-Swift/iOS-Swift/Tools/SentryBenchmarking.mm

test: dont crash if tapping button to stop benchmark before starting one

---

Sources/Sentry/include/SentryUIApplication.h

ref: Remove unused property in SentryUIApplication

---

.github/workflows/test.yml

We already include all sources via Sample/**.
https://github.com/getsentry/sentry-cocoa/blob/6813f7c156f1e842058549f1801b2eede804f37f/.github/workflows/test.yml#L14

ci: Remove duplicate sample paths in test.yml

---

LICENSE.md

date range to license - 2015-2024

---

Sources/Sentry/SentryPropagationContext.h
Sources/Sentry/SentryPropagationContext.m

ref: Cleanup PropagationContext imports

---

CHANGELOG.md

Fix CHANGELOG.md for 8.29.1

---

Makefile
Samples/iOS-Swift/iOS13-Swift/AppDelegate.swift
scripts/build-xcframework.sh

chore: Fix Typo for CI asset

---

SentryTestUtils/SentryTestUtils-ObjC-BridgingHeader.h
SentryTestUtils/TestHub.swift

Fixes compiling unit tests introduced with GH-4085.

test: Fix broken unit test builds

---

Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme
Samples/iOS-Swift/iOS-Swift/AppDelegate.swift

Attempt to automatically derive a unique username per developer using the sample app. Also allow overrides from the xcschema.

test: usernames and emails

---

Sources/Sentry/SentryOptions.m

ref(SentryOptions): remove dead implementation of setMeasurement

---

.github/workflows/release.yml

fix release workflow typo that dropped an artifact

---

CHANGELOG.md
Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
Samples/iOS-Swift/iOS-Swift/ExtraViewController.swift
Samples/iOS-Swift/iOS-Swift/ViewControllers/WebViewController.swift
Sources/Swift/Tools/UIRedactBuilder.swift
Tests/SentryTests/UIRedactBuilderTests.swift

Redact web view from replay
Close #4155
Sample 

Feat: Redact web view from replay

---

.sauce/benchmarking-config.yml

fix: Benchmark CI - low devices

---

README.md

See Laravel PR as reference: https://github.com/getsentry/sentry-laravel/pull/938

chore: Update ReadMe Sentry Logo

---

CHANGELOG.md

Add a primer to update to 8.33.0 for an important bug fix for release health.

chore: Add primer for important bug fix

---

Tests/SentryTests/Networking/SentryHttpTransportTests.swift

Only init the transaction including the transaction for the transaction envelope for the tests that use it, because the tracer initializes the SentryFramesTracker and might have other side effects.
I identified this while looking at a [flaky test](https://github.com/getsentry/sentry-cocoa/actions/runs/10282702155/job/28454998924):
```
Test Case '-[SentryTests.SentryHttpTransportTests testFlush_WhenNoInternet_BlocksAndFinishes]' started.
[Sentry] [debug] [SentrySpanContext:93] Created span context with trace ID ae4ee473279f428784da29cbe4405841; span ID 385ce66c3aed4b2c; parent span ID (null); operation SomeOperation
[Sentry] [debug] [SentryTransactionContext:147] Created transaction context with name SomeTransaction
[Sentry] [debug] [SentryFramesTracker:89] Initialized frame tracker …
```

test: Stop init tracer for all HttpTransportTests

---

SentryTestUtils/TestNSNotificationCenterWrapper.swift
Sources/Sentry/SentryNSNotificationCenterWrapper.m
Sources/Sentry/include/SentryNSNotificationCenterWrapper.h
Tests/SentryTests/Helper/SentryNSNotificationCenterWrapperTests.swift

I need the block observation API for a change in #4214

chore(SentryNSNotificationCenterWrapper): add block observation

---

.github/workflows/lint.yml
.pre-commit-config.yaml
scripts/build-xcframework.sh
scripts/bump.sh
scripts/check-uikit-linkage.sh
scripts/ci-select-xcode.sh
scripts/commit-formatted-code.sh
scripts/create-simulator.sh
scripts/test-alamofire.sh
scripts/test-homekit.sh
scripts/update-package-sha.sh
scripts/upload-dsyms-with-xcode-build-phase.sh
scripts/xcode-slowest-tests.sh
scripts/xcode-test.sh

chore: add shellcheck precommit hook

---

Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayIntegrationTests.swift
Tests/SentryTests/SentrySDKTests.swift

Trying to refactor flaky tests

ref: Tests

---

Samples/iOS-Swift/iOS-Swift-UITests/LaunchUITests.swift

Fix: testCorruptEnvelope Test

---

Samples/macOS-Swift/macOS-Swift.xcodeproj/project.pbxproj
Samples/macOS-Swift/macOS-Swift/AppDelegate.swift
Samples/macOS-Swift/macOS-Swift/Base.lproj/Main.storyboard
Samples/macOS-Swift/macOS-Swift/DiskWriteException.swift
Samples/macOS-Swift/macOS-Swift/SwiftUIView.swift
Samples/macOS-Swift/macOS-Swift/ViewController.swift

- Add captureError and captureException examples to macOS app
- Add diskWriteException
- Add SwiftUI view
Add some functionality for manual tests for [#4300](https://github.com/getsentry/sentry-cocoa/issues/4300)

Update macOS sample app

---

Tests/SentryTests/Helper/SentrySerializationTests.swift

Add more tests for SentrySerialization.envelopeWithData to cover more edge cases.

test: Add more tests for envelopeWithData

---

Sources/Sentry/SentrySerialization.m
Tests/SentryTests/Helper/SentrySerializationTests.swift

Small refactorings for SentrySerialization.envelopeWithData.
This PR is based on https://github.com/getsentry/sentry-cocoa/pull/4342.

ref: For envelopeWithData serialization

---

Tests/SentryTests/Helper/SentrySerializationTests.swift

Add more tests for SentrySerialization.envelopeWithData.

test: Add tests for envelopeWithData

---

Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackIntegration.swift

Disable the SwiftLint Todo rule for the in progress SentryUserFeedbackIntegration.

chore: Disable swiftlint todo for user feedback

---

Brewfile.lock.json

chore: Update clang-format from 19.1.0 to 19.1.1

---

CHANGELOG.md

Update 8.38.0 CHANGELOG.md

---

CHANGELOG.md

chore(changelog): Remove trailing whitespaces

---

Brewfile.lock.json

chore(local-dev): Bump clang-format to 19.1.3

---

Sources/Sentry/SentrySessionReplayIntegration.m

chore: Format SRIntegration

---

Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
Sentry.xcodeproj/project.pbxproj
Sources/Swift/Helper/SentryIconography.swift
Sources/Swift/Integrations/UserFeedback/Configuration/SentryUserFeedbackConfiguration.swift
Sources/Swift/Integrations/UserFeedback/Configuration/SentryUserFeedbackFormConfiguration.swift
Sources/Swift/Integrations/UserFeedback/Configuration/SentryUserFeedbackThemeConfiguration.swift
Sources/Swift/Integrations/UserFeedback/Configuration/SentryUserFeedbackWidgetConfiguration.swift
Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackForm.swift
Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackWidget.swift
Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackWidgetButtonMegaphoneIconView.swift
Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackWidgetButtonView.swift

for https://github.com/getsentry/sentry-cocoa/issues/4187?issue=getsentry%7Csentry-cocoa%7C4271; #skip-changelog
this is not feature complete or full polish for the form, we just want to shift towards iterating on end-to-end functionality, and then circle back to completing the implementation and UI polish.
functionality still needed after this PR, so should not be tested here:
- error states if required fields are not filled
- adding/removing screenshots
- automatically filling sentry user name/email
known issues:
- custom outline colors break text field padding
- logo doesn't scale and is sometimes clipped with certain font sizes
continued in https://github.com/getsentry/sentry-cocoa/pull/4544

feat(user feedback): input form

---

Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackForm.swift
Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackWidget.swift

Ideally, we shouldn't have any todos. I ignored them for now to make swiftlint happy.

fix: SwiftLint Todos

---

CHANGELOG.md

- Move unreleased changelog entries to unreleased section
- Remove duplicate entry

Move unreleased changelog entries to unreleased section

---

.github/CODEOWNERS

As requested by @kahest I am adding myself as a code owner.

chore: add philprime to CODEOWNERS

---

CHANGELOG.md

chore: fixup changelog

---

Sentry.xcodeproj/project.pbxproj
Sources/Swift/Protocol/Codable/SentryMechanismCodable.swift
Tests/SentryTests/Protocol/SentryMechanismTests.swift

feat: Deserializing SentryMechanism

---

CHANGELOG.md

Prepare CHANGELOG.md for 8.44.0

---

Sentry.xcodeproj/project.pbxproj
Sources/Swift/Protocol/Codable/SentryThreadCodable.swift
Tests/SentryTests/Protocol/SentryThreadTests.swift

Add Decodable/Deserializing of SentryThread.
This PR is based on https://github.com/getsentry/sentry-cocoa/pull/4789.

feat: Deserialize SentryThread

---

Sentry.xcodeproj/project.pbxproj
Sources/Sentry/Public/SentryEvent.h
Sources/Sentry/SentryEvent.m
Sources/Sentry/SentryLevelHelper.m
Sources/Sentry/include/SentryLevelHelper.h
Sources/Swift/Protocol/Codable/DecodeArbitraryData.swift
Sources/Swift/Protocol/Codable/SentryEventCodable.swift
Tests/SentryTests/Protocol/SentryEventTests.swift
Tests/SentryTests/Protocol/TestData.swift

Add Decodable/Deserializing of SentryEvent.

feat: Deserialize SentryEvent

---

CHANGELOG.md

chore: Fix Changelog Fixes Heading

---

Sources/Sentry/SentryFileManager.m
Sources/Sentry/include/SentryFileManager.h

Restructure the code in SentryFileManager into pragma mark sections so it's easier to read.
This PR only moved code around. No other changes.

ref: Add Pragma Marks for FileManager

---

Samples/.swiftlint.yml
Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
Samples/iOS-Swift/iOS-Swift/ExtraViewController.swift

Add a button triggering a deadlock on the main thread for testing fatal app hangs.

test: Add deadlock on the main thread for ANRs

---

develop-docs/README.md

chore(docs): fix path to Xcode screenshots

---

Tests/SentryTests/SentrySDKIntegrationTestsBase.swift

test: Remove unused code in SDKIntegrationTestBase

---

Sources/Sentry/SentryClient.m

Add an early return for SentryClient.sendEvent to reduce code nesting to improve readability.
Nothing changed in the logic. As the git diff is messed up, you can check it here:
Before 
```ObjC
- (SentryId *)sendEvent:(SentryEvent *)event
withSession:(SentrySession *)session
withScope:(SentryScope *)scope
{
if (nil != event) {
NSArray *attachments = [self attachmentsForEvent:event scope:scope];
if (event.isCrashEvent && event.context[@"replay"] &&
[event.context[@"replay"] isKindOfClass:NSDictionary.class]) {
NSDictionary *replay = event.context[@"replay"];
scope.replayId = replay[@"replay_id"];
}
SentryTraceContext *traceContext = [self getTraceStateWithEvent:event withScope:scope];
if (nil == session.releaseName || [session.releaseName length] == 0) { …
```

ref: Early return for SentryClient.sendEvent

---

develop-docs/README.md

Document how to use test assertions for a more consistent test code base.
I also fixed some headings in this PR so that there is one section for testing. 

chore: Recommendation for test assertions

---

Tests/SentryTests/Integrations/SessionReplay/SentryTouchTrackerTests.swift

The test flaked here https://github.com/getsentry/sentry-cocoa/actions/runs/13897038496/job/38880559094.
Instead of only simply increasing the timeout, I also improved the test a bit.
Instead of having three async operations iterating 1000 times over each method, add an async operation for each method all running concurrently to increase the likeliness of identifying synchronization issues potentially leading to crashes.
Furthermore, increase the timeout to 5 seconds so the test times out less frequently in CI.

test: Improve touch tracker lock tests

---

.github/workflows/build.yml
.github/workflows/integration-test.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/ui-tests.yml
scripts/ci-select-xcode.sh
scripts/tests-with-thread-sanitizer.sh

Replace manual selecting Xcode version with xcodes.

ci: Use xcodes in ci-select-xcode.sh

---

Tests/SentryTests/Integrations/ANR/SentryANRTrackingIntegrationTests.swift

When looking at the code pauseAppHangTracking doesn't impact AppHangsV2 at all, but still add two test cases to validate it stays like this.
Fixes GH-5000
Unit tests.

test: Add tests for pausing app hang V2

---

Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerTests.swift

test: Remove force_unwrap for NetworkTrackerTests

---

Tests/SentryTests/SentrySessionTests.swift

test: Remove force_unwrap for SessionTests

---

Tests/.swiftlint.yml
Tests/SentryTests/Helper/SentryFileManagerTestExtension.swift
Tests/SentryTests/Helper/SentryFileManagerTests.swift
Tests/SentryTests/Helper/SentrySerializationTests.swift
Tests/SentryTests/Integrations/Performance/IO/DataSentryTracingIntegrationTests.swift
Tests/SentryTests/Integrations/Performance/IO/FileManagerTracingIntegrationTests.swift
Tests/SentryTests/Integrations/Performance/IO/SentryFileIOTrackerTests.swift
Tests/SentryTests/Integrations/Performance/IO/SentryFileIOTrackingIntegrationTests.swift
Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerTests.swift
Tests/SentryTests/Integrations/SessionReplay/SentryOnDemandReplayTests.swift
Tests/SentryTests/Integrations/ViewHierarchy/SentryViewHierarchyIntegrationTests.swift
Tests/SentryTests/PrivateSentrySDKOnlyTests.swift
Tests/SentryTests/Protocol/Codable/ArbitraryDataTests.swift
Tests/SentryTests/Protocol/Codable/NSNumberDecodableWrapperTests.swift
Tests/SentryTests/Protocol/Codable/SentryCodableTests.swift
Tests/SentryTests/Protocol/Codable/SentryDateCodableTests.swift
Tests/SentryTests/Protocol/SentryAttachmentTests.swift
Tests/SentryTests/Protocol/SentryEnvelopeTests.swift
Tests/SentryTests/Protocol/TestData.swift
Tests/SentryTests/SentryClientTests.swift
Tests/SentryTests/SentrySDKTests.swift
Tests/SentryTests/SentrySessionTests.swift

test: Remove force_unwrap for Serialization tests

---

Gemfile.lock

chore: Update sentry-fastlane-plugin to 1.28.1

---

.swiftlint.yml
Samples/iOS-Swift/iOS-Swift/SentrySDKWrapper.swift
Samples/macOS-Swift/macOS-Swift/AppDelegate.swift
Samples/tvOS-Swift/tvOS-Swift/AppDelegate.swift
Samples/watchOS-Swift/watchOS-Swift WatchKit Extension/ExtensionDelegate.swift
Tests/.swiftlint.yml

Fix remaining Non-optional String -> Data Conversion warnings and enable non_optional_string_data_conversion for all Swift files.

chore: Enable non_optional_string_data_conversion

---

.codecov.yml
.github/dependabot.yml
.github/file-filters.yml
.github/workflows/benchmarking.yml
.github/workflows/build.yml
.github/workflows/changes-in-high-risk-code.yml
.github/workflows/codeql-analysis.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/testflight.yml
.github/workflows/ui-tests-critical.yml
.github/workflows/ui-tests.yml
.pre-commit-config.yaml
.prettierignore
.swiftlint.yml
Makefile
Utils/VersionBump/.swiftlint.yml
test-server/docker-compose.yml

Adds linting and formatting of YAML files similar to Markdown and JSON files using prettier.
Based on this https://github.com/getsentry/sentry-cocoa/pull/5055#discussion_r2034127805 by @armcknight 

style: add prettier configuration for YAML files

---

Samples/macOS-Swift/macOS-Swift/Base.lproj/Main.storyboard

- Adds missing auto-layout constraints to the macOS sample UI

chore: add auto layout constraints to macOS sample

---

.github/workflows/changes-in-high-risk-code.yml

Failed here: https://github.com/getsentry/sentry-cocoa/actions/runs/14752051972/job/41411624802?pr=5154

fix(ci): fix changes-in-high-risk-code.yml with no previous comments

---

.github/workflows/version-bump-util.yml

Fix prettier formatting issues for version bump util yml for GH actions.

chore: Fix prettier formatting issues

---

CHANGELOG.md

chore: Changelog prep for 8.50.1

---

.github/CODEOWNERS

meta: add emerge tools cocoa devs as code owners 🎉

---

Samples/SentrySampleShared/SentrySampleShared/SentrySDKWrapper.swift

test: inject the ui test name into the scope

---

.github/workflows/version-bump-util.yml
Makefile
Utils/VersionBump/main.swift

Adds a verify parameter to check if a the version was properly bumped.
Make sure our bump utility is working properly
Ran the bump util locally and then ran the verify step.

ci: Verify bumped version on CI

---

.github/workflows/version-bump-util.yml

Change the Version Bump Util workflow to only trigger on changes on related files
Avoid unnecesary runs
Not yet tested

ci: Trigger version bump util test only on related changes

---

.github/workflows/lint-shellcheck.yml

ci: Include all shell scripts in subdirectories

---

Sentry.xcodeproj/project.pbxproj
Tests/SentryTests/SampleError.swift

test: Remove unused SampleError enum

---

Sources/Sentry/SentryFeedbackAPI.m
Sources/Sentry/include/SentrySwift.h

These imports needs to be modified to work from SPM

Fix a few SPM imports

---

Sources/Sentry/include/SentrySwift.h

chore: Fix code formatting in SentrySwift.h

---

CHANGELOG.md

fix(changelog): Include beta entries in the unreleased section

---

.pre-commit-config.yaml

Exclude sdk_api.json formatting

---

.gitignore

We don't want this folder in version control

chore: Add MaestroLogs to .gitignore

---

.github/actions/capture-screenshot/action.yml

Update screenshot artifact naming to include run ID to avoid conflicts
Upload names should be unique within a workflow

ci: Update screenshot artifact naming to include run ID to avoid conflicts

---

Makefile

ci: Fix init script

---

Samples/macOS-Swift/Shared/Base.lproj/Main.storyboard
Samples/macOS-Swift/Shared/ViewController.swift

test: add a start profile button to mac sample app

---

.github/workflows/ui-tests.yml

Update Xcode version so ui tests can access new simulators

test: Update ui tests xcode version

---

.github/workflows/objc-conversion-analysis.yml

Missed these two spots when I changed the format in my previous PR

fix: Fix PNG to SVG

---

Sentry.xcodeproj/project.pbxproj

Just figured it'd be nice to be able to work with these sources from the main workspace.

chore: add duplicated binary test harness to workspace

---

.github/workflows/test.yml
.github/workflows/ui-tests-common.yml
.github/workflows/ui-tests.yml

Trying the new codecov test analytics as mentioned in #3897 (docs at https://docs.codecov.com/docs/test-analytics)

test: try codecov test analytics

---

.github/workflows/test-cross-platform.yml
Sources/Sentry/include/HybridPublic/SentryEnvelope.h
Sources/Sentry/include/SentryPrivate.h

This wasn't failing CI if it errored. 
This fixes it so it errors, and fixes the errors that had crept in while this check wasn't working

ci: Fix RN tester

---

TestSamples/SwiftUICrashTest/SwiftUICrashTest/ContentView.swift
TestSamples/SwiftUICrashTest/test-crash-and-relaunch.sh

Adds a new screenshot + text in the app to help debugging
Should help debug failed tests: https://github.com/getsentry/sentry-cocoa/actions/runs/16654220113/job/47134863689?pr=5772

ci: Add more screenshots to debug crash test errors

---

Sources/Sentry/SentryTransaction.m

_This PR is derived from https://github.com/getsentry/sentry-cocoa/pull/5572 in an effort to make the large amount of changes easier to review for https://github.com/getsentry/sentry-cocoa/issues/5577._
Adds nullability-handling and type checking to serialization of `SentryTransaction`.
While fixing the warnings I also noticed that we add the trace tags twice to the `traceTags`, once while creating the `mutableCopy` and then once using `addEntriesFromDictionary`.
```objective-c
NSMutableDictionary<NSString *, id> *traceTags = [sentry_sanitize(self.trace.tags) mutableCopy];
[traceTags addEntriesFromDictionary:sentry_sanitize(self.trace.tags)];
```

fix: Remove duplicate adding of trace tags in transaction serialization

---

Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerTests.swift

Replace the dispatch group with an XCTestExpectation to get a failure message when the wait times out.
Contributes to GH-5789

test: Use XCTestExpectation for NetworkTracker

---

Tests/SentryTests/Integrations/SessionReplay/SentryOnDemandReplayTests.swift

Replace the dispatch group with an XCTestExpectation to get a failure message when the wait times out.
Contributes to GH-5789

test: Use XCTestExpectation for OnDemandReplay

---

.github/workflows/release.yml
.github/workflows/version-bump-util.yml
Package.swift
scripts/update-package-sha.sh
scripts/verify-package-sha.sh

Adds the new framework variant to package.swift and all steps required to release a new version

feat: Added new ARM64e binary target to Package.swift

---

Package.swift

chore: Add new library product for Sentry-Dynamic-WithARM64e in Package.swift

---

Samples/iOS-Cocoapods-Swift6/Podfile
Samples/iOS-Cocoapods-Swift6/iOS-Cocoapods-Swift6.xcodeproj/project.pbxproj

Fixes some broken references in the xcproject

ref: Cleanup broken references and paths on Cocoapods project

---

CHANGELOG.md
scripts/remove-architectures.sh

Release 8.55.1

---

CHANGELOG.md

Adds a changelog entry for: https://github.com/getsentry/sentry-cocoa/pull/5877

chore(changelog): Added automatic IP inference change to changelog

---

.github/actions/prepare-package.swift/action.yml
.github/workflows/version-bump-util.yml
CHANGELOG.md
Package.swift
scripts/update-package-sha.sh
scripts/verify-package-sha.sh

Fixes: https://github.com/getsentry/sentry-cocoa/issues/6099
Also updated script to updated package SHA when releasing
Closes #6161

feat: Make Sentry-WithoutUIKitOrAppKit available with SPM

---

CHANGELOG.md

chore: Add changes from alpha releases to v8.56.0 changelog

---

.gitignore

chore: Add DistributionSample to .gitignore
