- CHANGELOG.md
- Sources/Sentry/SentryMetricProfiler.mm
- Sources/Sentry/SentrySystemWrapper.mm
- Sources/Sentry/include/SentryMetricProfiler.h
- Sources/Sentry/include/SentrySystemWrapper.h
Extracted from #3187 for release to production.
> feat: measure cpu energy usage estimates

- Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
The IBAction connections for CPU work start/end in the new profiling area added in #3216 were not hooked up right and crashed the app.
> fix IBAction connections

- fastlane/Fastfile
Fixes an error on CI to bump the version.
> Fix: `remove_preview_version_suffixes` Lane

- Sources/Sentry/SentryScope.m
- Sources/Sentry/include/SentryScope+Private.h
Interface extensions > private categories (see #3236 for elaboration)
> ref: convert SentryScope (Private) category to an interface extension

- Sources/Sentry/SentryBinaryImageCache.m
- Sources/Sentry/SentryCrashStackEntryMapper.m
- Sources/Sentry/SentryDependencyContainer.m
- Sources/Sentry/SentrySDK.m
- Sources/Sentry/SentryThreadInspector.m
- Sources/Sentry/include/HybridPublic/SentryBinaryImageCache.h
- Sources/Sentry/include/HybridPublic/SentryDependencyContainer.h
- Sources/Sentry/include/SentryCrashStackEntryMapper.h
- Sources/Sentry/include/SentryStacktraceBuilder.h
- Tests/SentryTests/SentryBinaryImageCacheTests.swift
- Tests/SentryTests/SentryCrash/SentryBinaryImageCacheTests.m
- Tests/SentryTests/SentryCrash/SentryCrashStackEntryMapperTests.swift
- Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift
- Tests/SentryTests/SentryCrash/SentryThreadInspectorTests.swift
- Tests/SentryTests/SentryCrash/TestThreadInspector.swift
- Tests/SentryTests/SentrySDKTests.swift
This was a singleton, but then we'd pass the reference around in various constructors and properties. Just centralize it in SentryDependencyContainer.
> ref: centralize SentryBinaryImageCache singleton in SentryDependencyContainer

- Samples/TrendingMovies/Cartfile
- Samples/TrendingMovies/Cartfile.resolved
- Samples/TrendingMovies/TrendingMovies.xcodeproj/project.pbxproj
- Samples/TrendingMovies/TrendingMovies/Credits/CreditCollectionViewCell.swift
- Samples/TrendingMovies/TrendingMovies/Movies/MovieCollectionViewCell.swift
- Remove FaceAware dependency as it no longer builds
- Re-compile frameworks for Swift 5.8
- Fix a bug where the backdrop of the cells was not rendered correctly
Build & run the app
> fix: TrendingMovies build on Swift 5.8 & UI glitches

- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/PrivateSentrySDKOnly.m
- Sources/Sentry/PrivateSentrySDKOnly.mm
- Sources/Sentry/include/HybridPublic/PrivateSentrySDKOnly.h
- Tests/SentryTests/PrivateSentrySDKOnlyTests.swift
Some changes coming from actual integration into the Flutter SDK.
> chore: update profiling API for hybrid SDKs

- fastlane/Fastfile
For some reason if these jobs are both run on ci sequentially, the second one fails in the match phase. I think setup_ci lets the previous run's keychain get used for the subsequent run's, and then something fails. In any case, these are the only jobs that don't call this with force: true.
This is also failing nondeterminstically; sometimes it works on PRs, sometimes not.
> ci: always run setup_ci

- .github/workflows/benchmarking.yml
- .github/workflows/build.yml
- .github/workflows/profile-data-generator.yml
- .github/workflows/saucelabs-UI-tests.yml
- .github/workflows/testflight.yml
always invoke `fastlane` via `bundle exec`
Saw this log in some PR test logs: 
```
fastlane detected a Gemfile in the current directory
However, it seems like you didn't use `bundle exec`
To launch fastlane faster, please use
bundle exec fastlane build_perf_test_app_sentry
Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
```
This means we're using a slower invocation for CI and also are always using the version we expect instead of whatever is on the actions runners.
> ci: use bundled fastlane

- SentryTestUtils/ClearTestState.swift
- Sources/Sentry/SentryAutoBreadcrumbTrackingIntegration.m
- Sources/Sentry/SentryBreadcrumbTracker.m
- Sources/Sentry/SentryDependencyContainer.m
- Sources/Sentry/SentrySwizzleWrapper.m
- Sources/Sentry/SentryUIEventTracker.m
- Sources/Sentry/SentryUIEventTrackingIntegration.m
- Sources/Sentry/include/SentryBreadcrumbTracker.h
- Sources/Sentry/include/SentrySwizzleWrapper.h
- Sources/Sentry/include/SentryUIEventTracker.h
- Tests/SentryTests/Helper/SentrySwizzleWrapperTests.swift
- Tests/SentryTests/Integrations/Breadcrumbs/SentryAutoBreadcrumbTrackingIntegrationTests.swift
- Tests/SentryTests/Integrations/Breadcrumbs/SentryBreadcrumbTrackerTests.swift
- Tests/SentryTests/Integrations/UIEvents/SentryUIEventTrackerTests.swift
- scripts/no-changes-in-high-risk-files.sh
We already had a property on SentryDependencyContainer for this, but that still accessed SentrySwizzleWrapper.sharedInstance and we still also passed around the reference.
> ref: access SentrySwizzleWrapper via existing SentryDependencyContainer property

- Sources/Sentry/SentryDependencyContainer.m
- Sources/Sentry/SentryExtraContextProvider.h
- Sources/Sentry/SentryExtraContextProvider.m
- Sources/Sentry/SentryUIDeviceWrapper.m
- Sources/Sentry/include/HybridPublic/SentryDependencyContainer.h
- Sources/Sentry/include/SentryUIDeviceWrapper.h
- Tests/SentryTests/Helper/SentryExtraContextProviderTests.swift
- Tests/SentryTests/SentryClient+TestInit.h
- Tests/SentryTests/SentryClientTests.swift
- Tests/SentryTests/SentryCrash/SentryUIDeviceWrapperTests.swift
- Tests/SentryTests/SentryCrash/TestSentryUIDeviceWrapper.swift
Similar to https://github.com/getsentry/sentry-cocoa/pull/3242, there really only needs to ever be one instance of this.
> ref: access SentryUIDeviceWrapper from SentryDependencyContainer

- CHANGELOG.md
- Sources/Sentry/SentryCoreDataTracker.m
- Tests/SentryTests/Integrations/Performance/CoreData/SentryCoreDataTrackerTest.swift
- Tests/SentryTests/Integrations/Performance/CoreData/TestCoreDataStack.swift
Add the persistent store types and URLs to the span data for Core Data tracking.
Also a couple refactors:
- fix a copypasta variable name and log statement that were "fetch" but should've been "save"
- the fetch tracker method grabs a span inside block scope and then the rest of the method proceeds afterwards; but in save tracking, it's all done in the block scope. bump out the save method's logic to match the fetch method's (less indentation -> more code per line).
- rename method to be more descriptive
- moved/combined `SentryCoreDataTrackerTests.TestNSManagedContext` to `TestCoreDataStack.managedObjectContext`
https://github.com/getsentry/sentry-cocoa/issues/3212
> feat: add more db info on span data

- .github/workflows/benchmarking.yml
Missed this job in #3257. This will un-break this benchmark job.
> ci: install/cache bundle for other jobs needing it

- CHANGELOG.md
- Sources/Sentry/SentryMetricProfiler.mm
- Sources/Sentry/include/SentryMetricProfiler.h
- Tests/SentryProfilerTests/SentryProfilerSwiftTests.swift
Copypasta in #3217 led to reporting the wrong units for energy profiling metrics.
> fix: report energy usage in nanojoules

- CHANGELOG.md
- Sources/Sentry/SentryNetworkTracker.m
- Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerTests.swift
- scripts/no-changes-in-high-risk-files.sh
Renamed "http.method" to "http.request.method" for network Spans
close #3234 
Unit tests
> ref: Rename "http.method" to "http.request.method" for network Spans

- CHANGELOG.md
- Sources/Sentry/SentryPropagationContext.m
> fix: Remove warning about non-portable path to file "SentryDsn.h"

- Sources/Sentry/SentryOptions.m
- Sources/Sentry/include/HybridPublic/SentryBreadcrumb+Private.h
- Sources/Sentry/include/HybridPublic/SentryOptions+HybridSDKs.h
- Sources/Sentry/include/HybridPublic/SentryUser+Private.h
- Sources/Sentry/include/SentryEnvelope+Private.h
- Sources/Sentry/include/SentryHttpStatusCodeRange+Private.h
- Sources/Sentry/include/SentryOptions+Private.h
- Sources/Sentry/include/SentrySDK+Private.h
- Sources/Sentry/include/SentrySpanContext+Private.h
- Tests/SentryTests/SentryCrash/SentryCrashTests.m
- Tests/SentryTests/SentryTests.m
Interface extensions > private categories (see https://github.com/getsentry/sentry-cocoa/pull/3236 for elaboration)
This PR collects all such changes that didn't involve any other code changes other than removing the category name to make it anonymous.
> ref: convert simple private category to interface extensions

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
- Sources/Sentry/Public/SentryDefines.h
- Sources/Sentry/SentryBaggage.m
- Sources/Sentry/SentryPropagationContext.m
- Sources/Sentry/SentryTraceContext.m
- Sources/Sentry/include/SentryBaggage.h
- Sources/Sentry/include/SentryTraceContext.h
- Tests/SentryTests/Helper/SentrySerializationTests.swift
- Tests/SentryTests/Protocol/SentryEnvelopeTests.swift
- Tests/SentryTests/Transaction/SentryBaggageTests.swift
- Tests/SentryTests/Transaction/SentryTraceStateTests.swift
Adds `sampled` flag to all trace envelope headers
closes #3201
Unit tests
> feat: Add Sampling Decision to Trace Envelope Header

- Sources/Sentry/SentryDependencyContainer.m
- Sources/SentryCrash/Recording/Tools/SentryCrashObjCApple.h
- Tests/SentryTests/SentryOptionsTest.m
Making `SentryDependencyContainer` less complex and more predictable by removing some unnecessary lazy loads.
The goal would be to have all necessary objects initialized according to SentryOptions and remove all the @syncronized locks.
> ref: Reduce complexity for SentryDependencyContainer

- Sources/Sentry/SentryMetricKitIntegration.m
Moved the duplicate timestamp setting logic to the createEvent function.
For reducing code comlexity. 
I've been using your library well. Thank you
> ref: remove setting timestamp boilderplate in SentryMetrickitIntegration

- .github/workflows/lint.yml
- CHANGELOG.md
- Sentry.podspec
Xcode 15 automatically add libc++, we dont need to add it as well.
Removes a warning in the app compilation step.
> fix: Remove duplicate C++ lib for cocoapod

- Sentry.xcodeproj/project.pbxproj
- Sources/Configuration/Sentry.xcconfig
https://github.com/getsentry/sentry-cocoa/pull/3206 didn't properly update the paths after changing the location of the info plist and modulemap. 
> fix: paths to infoplist and modulemap

- Sources/Sentry/SentryDevice.mm
Replaced macOS OS version retrieval from a deprecated API to a new one.
closes #3317
> ref: Replace deprecated function

- CHANGELOG.md
- Sentry.xcodeproj/project.pbxproj
- Sources/Configuration/SDK.xcconfig
This building settings were causing warning with Xcode 15
CI
> Fix: Remove unnecessaries build settings

- Sources/Sentry/include/SentryProfiledTracerConcurrency.h
Reported with a proposed fix in https://github.com/getsentry/sentry-cocoa/pull/3331, but that can't run all the necessary CI checks
> fix: remove relative component of import

- CHANGELOG.md
- Sentry.xcodeproj/project.pbxproj
- SentryTestUtils/ClearTestState.swift
- SentryTestUtils/SentryTestUtils-ObjC-BridgingHeader.h
- Sources/Sentry/SentryBreadcrumbTracker.m
- Sources/Sentry/SentryHttpTransport.m
- Sources/Sentry/SentryReachability.m
- Sources/Sentry/include/SentryReachability.h
- Tests/SentryTests/Integrations/Breadcrumbs/SentryBreadcrumbTrackerTests.swift
- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
- Tests/SentryTests/Networking/SentryReachabilitySwiftTests.swift
- Tests/SentryTests/Networking/SentryReachabilityTests.m
- Tests/SentryTests/Networking/TestSentryReachability.swift
- Tests/SentryTests/SentryTests-Bridging-Header.h
The tests can launch multiple threads of the ANR tracker, which call dealloc of SentryReachability simultaneously, leading to a segfault while iterating over the observers in SentryReachability. This is fixed now by using some synchronization around the observer's access. Furthermore, the bookkeeping of the observers is implemented now with weak references using an NSHashTable. Instead of relying on dealloc to be called for removing the observers, each observer must now call removeObserver after subscribing. If an observer doesn't call removeObserver no memory is leaked cause the SentryReachability uses weak references. Previously, the list of observers used a dictionary with the description method of Objective-C as the key, which is suboptimal cause the description could change between …
> fix: Multiple issues in SentryReachability

- CHANGELOG.md
- Sources/Sentry/Public/SentryOptions.h
Remove experimental note on options to make the MetricKit integration GA.
Fixes GH-2585
Nothing to test for removing code comments.
> feat: GA MetricKit integration

- Sources/Sentry/SentryReachability.m
- Tests/SentryTests/Networking/SentryReachabilityTests.m
The testMultipleReachabilityObservers sometimes times out in CI. As no threading is involved, there is no need for test expectations. So we can replace these expectations by an int keeping track of how often the connectivity changes. This speeds up the tests significantly and reduces the complexity. Furthermore, the reset of SentryReachbility can now only be achieved by calling removeAllObservers.
> test: Fix flaky Reachability test

- CHANGELOG.md
- Sources/Sentry/SentryWatchdogTerminationLogic.m
- Tests/SentryTests/Integrations/SentryCrash/SentryCrashIntegrationTests.swift
- Tests/SentryTests/Integrations/WatchdogTerminations/SentryWatchdogTerminationsTrackerTests.swift
If the host app has been terminated due to device reboot, SentrySDK assumes it as a WatchdogTermination crash. In such cases, mostly, the boot time will be mentioned as "a few seconds before this event". 
The idea behind this fix is that if the system boot time has been changed since the previous app launch, most likely the app has been terminated due to the reboot and the SentrySDK should not consider it as a WatchdogTermination crash.
This change helps reducing the amount of false WatchdogTermination events detected by the SDK.
There's a new test case added in the `SentryWatchdogTerminationsTrackerTests.swift` file, which sets the previous app-launch time to different value and expects not sending any OOM event.
> Fix: SDK detects OutOfMemory after device reboot

- CHANGELOG.md
- Sources/Sentry/SentryCoreDataTracker.m
- Sources/Sentry/SentryDependencyContainer.m
- Sources/Sentry/SentryNSDataTracker.m
- Sources/Sentry/SentrySpan.m
- Sources/Sentry/include/HybridPublic/SentryDependencyContainer.h
- Sources/Sentry/include/SentryInternalDefines.h
- Sources/Sentry/include/SentryThreadInspector.h
- Tests/SentryTests/Transaction/SentrySpanTests.swift
- Tests/SentryTests/Transaction/SentryTracerTests.swift
- Tests/SentryTests/Transaction/SentryTransactionTests.swift
Add current thread name and thread id to every span when the SDK initializes the span.
Fixes GH-3355
Unit tests and with the sample app.
> feat: Add thread id and name to span data

- CHANGELOG.md
- Sources/Sentry/SentryCrashDefaultMachineContextWrapper.m
- Sources/Sentry/SentrySpan.m
- Sources/Sentry/SentryThreadInspector.m
- Sources/Sentry/include/SentryCrashMachineContextWrapper.h
- Sources/Sentry/include/SentryThreadInspector.h
- Tests/SentryTests/Protocol/SentryThreadTests.swift
- Tests/SentryTests/SentryCrash/SentryThreadInspectorTests.swift
Set the thread name to nil when retrieving the thread name from the machine context wrapper in case it fails or the thread name is empty. This slightly reduces the payload size.
Came up here https://github.com/getsentry/sentry-cocoa/pull/3359#discussion_r1374232007.
Unit test and running the sample app on a simulator
> impr: Stop sending empty thread names

- Sources/Sentry/SentryEnvelopeRateLimit.m
- Sources/Sentry/SentryFileManager.m
- Sources/Sentry/SentryHttpTransport.m
- Sources/Sentry/SentryHub.m
- Sources/Sentry/SentryMigrateSessionInit.m
- Sources/Sentry/SentryProfiler.mm
- Sources/Sentry/include/HybridPublic/SentryEnvelope.h
This prevented Sentry from being build on an Intel mac, causing weird errors in the umbrella header until i made this change, then it built.
In general we should not import a header in another header unless we need to subclass an interface defined in it, etc.
> ref: remove header import in header, in favor of fcd already present

- CHANGELOG.md
- Sources/Sentry/SentryBacktrace.cpp
- Sources/Sentry/SentryThreadHandle.cpp
In an attempt to fix https://github.com/getsentry/sentry-cocoa/issues/3354, but unverified because we have no repro.
The crash report in the attached issue points to line 49 in SentryThreadHandle.cpp, but that is not actually the line crashing if you look at the source code, which is constructing a C++ unique pointer, the line above that is actually a macro: when it expands in place, the actual line of code crashing on line 49 is actually the call to mach_port_deallocate wrapped in the macro–see the definition for SENTRY_PROF_LOG_KERN_RETURN: https://github.com/getsentry/sentry-cocoa/blob/2124551ae0a2da085c69d3f0838e9be646fa4a70/Sources/Sentry/include/SentryMachLogging.hpp#L30-L38) 
We hope that avoiding the call to mach_port_deallocate avoids the whatever issue is occurring, and also …
> fix: avoid call to possibly crashing `mach_thread_deallocate`

- CHANGELOG.md
- Sources/Sentry/SentryUIApplication.m
- Tests/SentryTests/Helper/TestNSNotificationCenterWrapper.swift
- Tests/SentryTests/SentryUIApplicationTests.swift
Keep track of application state by notification instead of reading directly from UIApplication. This way we avoid using UIApplication in the background thread when detecting an ANR.
> fix: Reading applicationState in the background

- Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
- Samples/iOS-Swift/iOS-SwiftUITests/BaseUITest.swift
- Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift
- Samples/iOS-Swift/iOS-SwiftUITests/ProfilingUITests.swift
- Samples/iOS-Swift/iOS-SwiftUITests/UIEventBreadcrumbTests.swift
Add a base class for UITests for the iOSSwift to remove some redundant code.
This PR is based on https://github.com/getsentry/sentry-cocoa/pull/3370.
> test: Add BaseUITest class

- CHANGELOG.md
After releasing 8.14.2, other PRs were merged without first merging in `main` again, so their stale diffs didn't appear to be adding their changelog entries under 8.14.2 instead of Unreleased, but that's what wound up happening.
And also one made it in in between us updating changelog for 8.14.2 and actually merging that release branch back into main: 
I still think that craft should not be renaming `Unreleased` to whatever version is being released; instead inserting the section header for the release underneath `Unreleased`, leaving that unreleased section header always. I think the way git diffs work would avoid some of this issue: https://github.com/getsentry/craft/issues/422
> fix: changelog entries after 8.14.2

- Tests/SentryTests/Helper/SentryAppStateManagerTests.swift
- Tests/SentryTests/Helper/SentryFileManagerTests.swift
- Tests/SentryTests/Helper/SentryLogTests.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackerTests.swift
- Tests/SentryTests/Integrations/Performance/AppStartTracking/SentryAppStartTrackingIntegrationTests.swift
- Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackingIntegrationTests.swift
- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
- Tests/SentryTests/Protocol/SentryEnvelopeTests.swift
- Tests/SentryTests/SentryHubTests.swift
When looking at continued flakes of reachability tests, I noticed there are still dangling reachability observer instances when new test cases start (which I believe were coming from SentryHttpTransportTests). When I looked further I noticed that there were several tests that use SentryDependencyContainer, but never clean it up afterwards, so I added that call to each test suite's `tearDown` method.
Also changed one tearDown to tearDownWithError that did a manual XCTFail in a do/try/catch.
> test: clear test state in any test case using SentryDependencyContainer

- Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme
The test failed here https://github.com/getsentry/sentry-cocoa/actions/runs/6781674324/job/18432505182.
> test: Disable flaky testMultipleReachabilityObservers

- Sentry.xcodeproj/project.pbxproj
I was seeing this runtime error trying to run tvOS tests locally: 
```
2023-11-06 17:07:22.055807-0900 xctest[3004:27207] [general] Error loading /Users/andrewmcknight/Library/Developer/Xcode/DerivedData/Sentry-gnnqqmcfqpqmmhcjxfzwadgjajnt/Build/Products/Test-appletvsimulator/SentryProfilerTests.xctest/SentryProfilerTests (177):  dlopen(/Users/andrewmcknight/Library/Developer/Xcode/DerivedData/Sentry-gnnqqmcfqpqmmhcjxfzwadgjajnt/Build/Products/Test-appletvsimulator/SentryProfilerTests.xctest/SentryProfilerTests, 0x0109): Library not loaded: /Users/andrewmcknight/Library/Developer/Xcode/DerivedData/Sentry-gnnqqmcfqpqmmhcjxfzwadgjajnt/Build/Products/Test-appletvsimulator/libSentryTestUtils.a
Referenced from: <2D742D1E-D6A4-37DB-88B5-1F09B59C9473> …
```
> test: fix dyld error causing tvOS tests to fail to launch

- CHANGELOG.md
- Sources/Sentry/SentryProfilingLogging.mm
- Sources/Sentry/include/SentryProfilingLogging.hpp
fixes #3336 
Let's just avoid calling through to NSLog from the profiler's sampling thread until we can get a different logging solution in place, if we decide we need these logs at some point in the future.
> fix: dont call through to NSLog from profiler sampling thread

- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/SentryBuildAppStartSpans.m
- Sources/Sentry/SentryTracer.m
- Sources/Sentry/include/SentryBuildAppStartSpans.h
Move building app start spans to an extra file to shrink the code in SentryTracer. The SentryTracer previously had around 850 LOC and now about 750 LOC.
> ref: Move building app start spans

- develop-docs/DECISIONS.md
Document how we want to use DI in the SDK.
> docs: Document DI Strategy

- Sources/Sentry/Public/SentryOptions.h
`backtrace_async` is only available from Xcode 13 and from macOS 12.0, iOS 15.0, tvOS 15.0,
watchOS 8.0, see https://github.com/getsentry/sentry-cocoa/blob/de46f062cf2d18433c4d110b350dad14a67588bb/Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_SelfThread.m#L56-L59
> ref: Add availability comment for Swift Async

- .github/workflows/test.yml
- SentryTestUtils/ClearTestState.swift
Add an assert for checking clearTestState executed on the main thread. I suspected one of our tests was flaky because we weren't running clearTestState on the main thread, which was a false assumption. I added this assert to avoid any future problems caused by running clearTestState on a background thread.
> test: Assert clearTestState on main thread

- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/SentryUIEventTracker.m
- Sources/Sentry/SentryUIEventTrackerTransactionMode.m
- Sources/Sentry/SentryUIEventTrackingIntegration.m
- Sources/Sentry/include/SentryUIEventTracker.h
- Sources/Sentry/include/SentryUIEventTrackerMode.h
- Sources/Sentry/include/SentryUIEventTrackerTransactionMode.h
- Tests/SentryTests/Integrations/UIEvents/SentryUIEventTrackerTests.swift
- Tests/SentryTests/SentryTests-Bridging-Header.h
Carrier transactions are going to replace UI event transactions in the future. When users enable carrier transactions, UI event transactions must be disabled because both would interfere. Therefore, prepare the SentryUIEventTracker to be able to handle two different modes—one for the existing functionality of UI event transactions and one for adding spans to carrier transactions.
Preparation for carrier transactions https://github.com/getsentry/team-mobile/issues/157.
The unit tests are still all green—no change in functionality.
> ref: Add UIEventTracker Mode

- CHANGELOG.md
- Sources/Sentry/SentryProfilingLogging.mm
- Sources/Sentry/include/SentryProfilingLogging.hpp
#3390 attempted to compile some NSLogs out of production builds to avoid a crash, but the compilation condition was accidentally inverted, so that it was only compiled _into_ prod builds. This fixes that.
> fix: un-invert compilation condition

- Sources/Sentry/SentryTracer.m
> chore: Fix typo in SentryTracer

- Samples/iOS-Swift/iOS-Swift/ViewController.swift
Periodically read a file and perform a network request in the iOS-Swift sample app, which will help test carrier transactions.
The flaky UI test is fixed in https://github.com/getsentry/sentry-cocoa/pull/3421 and therefore this PR is also based on https://github.com/getsentry/sentry-cocoa/pull/3421.
> test: Add periodic work to sample app

- CHANGELOG.md
- SentryTestUtils/TestDisplayLinkWrapper.swift
- Sources/Sentry/SentryFramesTracker.m
- Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackerTests.swift
The SentryFramesTracker registers a callback to the CADisplayLink. While the SentryFramesTrackingIntegration keeps a reference to the SentryFramesTracker and calls SentryFramesTracker.stop on uninstall, there could be situations where the SentryFramesTracker is deallocated, but not calling invalidate on the CADisplayLink. Then the CADisplayLink still calls  and crashes with EXC_BAD_ACCESS cause the frames tracker is deallocated. To fix this problem SentryFramesTracker.dealloc now calls invalidate on the CADisplayLink.
A customer reported this crash, and we also see this in our [SDK crashes](https://sentry.sentry.io/issues/?project=4505469596663808&query=is%3Aunresolved+displaylinkcallback&referrer=issue-list&sort=user&statsPeriod=14d).
The actual crash is hard to reproduce, but I added a …
> fix: Crash in SentryFramesTracker

- Tests/SentryTests/Networking/SentryReachabilitySwiftTests.swift
Calling the methods of SCNetworkReachability in a tight loop from multiple threads is not an actual use case, and it leads to flaky test results. With this test, we want to test if the adding and removing observers are adequately synchronized and not if we call SCNetworkReachability correctly.
The reason for this PR is that testNoObservers still is flaky sometimes. See https://github.com/getsentry/sentry-cocoa/actions/runs/6888982334.
> test: Skip callbacks for Swift Reachability Tests

- Samples/iOS-Swift/iOS-SwiftUITests/ProfilingUITests.swift
Only assert frozen frames because triggering an ANR only guarantees frozen frames but not slow frames.
The test started to fail when adding some periodic work on the ViewController, which shouldn't impact the ProfilingUITest, see: https://github.com/getsentry/sentry-cocoa/pull/3420.
> test: ProfilingUITest only assert frozen frames

- CONTRIBUTING.md
- Sentry.xcodeproj/project.pbxproj
- SentryTestUtils/TestOptions.swift
- Tests/SentryTests/Integrations/Performance/IO/SentryNSDataTrackerTests.swift
- Tests/SentryTests/Integrations/Screenshot/SentryScreenshotIntegrationTests.swift
- Tests/SentryTests/Integrations/SentryCrash/SentryCrashIntegrationTests.swift
- Tests/SentryTests/Integrations/ViewHierarchy/SentryViewHierarchyIntegrationTests.swift
- Tests/SentryTests/SentryCrash/SentryCrashInstallationReporterTests.swift
- Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift
- Tests/SentryTests/SentrySDKTests.swift
- Tests/SentryTests/SentryTests-Bridging-Header.h
Specify the minimum integrations required for every test case using SentrySDK.start to minimize side effects for tests and reduce flakiness.
While investigating why `testConcurrentStacktraces_noStitching` was failing in [CI](https://github.com/getsentry/sentry-cocoa/actions/runs/6896421341/job/18762544285), I saw that the test logs print that the test is calling classes not required for the test to succeed when starting the SDK. That's how I came up with the idea for this PR.
<details><summary>Test Logs for failing testConcurrentStacktraces_noStitching</summary>
<p>
```sh
Test Case '-[SentryTests.SentryStacktraceBuilderTests testConcurrentStacktraces_noStitching]' started.
2023-11-16 21:08:28.145977+0000 xctest[6477:33127] [Sentry] [debug] [SentrySDK:145] Starting SDK...
2023-11-16 …
```
> test: Specify integrations when starting SDK

- .github/workflows/test.yml
Unit tests with Xcode 15.0.1 are more flaky compared to other Xcode versions. This could be due to a problem with GH action runners; see https://github.com/actions/runner-images/issues/8693. We will add Xcode 15 back once the next bugfix for Xcode 15.1 is released.
> ci: Remove Xcode 15.0.1 for tests

- Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
- Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme
- Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
- Samples/iOS-Swift/iOS-Swift/ExtraViewController.swift
- Samples/iOS-Swift/iOS-Swift/Tools/ANRs.swift
- Samples/iOS-Swift/iOS-Swift/ViewController.swift
- Samples/iOS-Swift/iOS-SwiftUITests/ProfilingUITests.swift
The testProfilingGPUInfo test asserts that the SDK adds a frozen frame to the last captured transaction. Previously, the test switched between UIViewControllers when triggering an ANR, which led to multiple transactions created. Now, there is a button to trigger an ANR on the same UIViewController to start and stop the transaction manually so that the frozen frame caused by the ANR ends up in the manually created transaction. This fixes the failing test.
> test: Fix failing profilingGPU test

- Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerIntegrationTests.swift
Add assert message to network tracker tests to get more insight in case they fail.
> test: Assert network errors network tracker

- CHANGELOG.md
- Sources/SentrySwiftUI/SentryTracedView.swift
GA SwiftUI support
close #2572 
> chore:  Remove "experimental" warning from SentryTracedView

- .github/workflows/test.yml
We run the iOSSwift tests on SauceLabs and also with the address sanitizer. Therefore, we can remove running them on a simulator without address sanitizer.
> ci: Stop running iOSSwift tests on simulator

- .github/workflows/saucelabs-UI-tests.yml
We once scheduled UI tests in CI to identify patterns in their duration because they often timed out. As they are currently stable, we can remove the unnecessary schedule.
> ci: Remove UI test schedule

- CHANGELOG.md
- Sources/Sentry/SentryUIApplication.m
When a UINavigationController is not initialized with initWithRootViewController, it leads to a crash.
like this: `self.window.rootViewController = [[UINavigationController alloc] init];`
> fix: Crash when UINavigationController without rootViewController

- CHANGELOG.md
- Sources/Sentry/SentryWatchdogTerminationScopeObserver.m
- Tests/SentryTests/Integrations/WatchdogTerminations/SentryWatchdogTerminationsScopeObserverTests.swift
This PR adds a check for valid JSON to prevent crashes during the breadcrumbs sync.
fixes: https://github.com/getsentry/sentry-react-native/issues/3421
integration test
> fix(breadcrumbs): Check for valid JSON in SentryWatchdogTerminationScopeObserver

- CHANGELOG.md
- Sources/Sentry/SentryBinaryImageCache.m
- Tests/SentryTests/SentryBinaryImageCacheTests.swift
Properly validate the binary image name when converting it to an NSString to avoid crashes.
I came across this when looking at https://github.com/getsentry/sentry-cocoa/pull/3468.
Unit tests.
> fix: Check for NULL in binary image cache

- CHANGELOG.md
There is some confusion over the availability of the UIKitless feature, like in https://github.com/getsentry/sentry-cocoa/issues/3460
Point out this is still an experimental feature not yet compatible with SPM.
> meta: mention experimental nature of UIKitless feature

- Sources/Sentry/PrivateSentrySDKOnly.mm
- Sources/Sentry/include/HybridPublic/PrivateSentrySDKOnly.h
When testing the native profiling integration for iOS in .NET, same way I've done it in Flutter, I've found I could use the collectProfileOutput directly without copying, which would, just if it was exposed as the NSMutableDictionary that it actually is.
See https://github.com/getsentry/sentry-dotnet/pull/2930/files#diff-1b71762e3c3bd42c9d55060467f9fcbc82b733f625ee6310ee76a6ff35a9e2d1R39
#skip-changelog - this probably doesn't make sense to mention to standard SDK consumers
> feat(internal): change collectProfilerForTrace result to mutable

- Sources/Sentry/Public/SentryCrashExceptionApplication.h
Add a comment to explain why we need SentryCrashExceptionApplication.
> ref: Add comment for CrashExceptionApplication

- CHANGELOG.md
- Sources/Sentry/SentrySpan.m
- Tests/SentryTests/Transaction/SentrySpanTests.swift
Initially, we wanted to send frame data only for spans started on the main thread, but we decided that the frame data makes sense for all spans. This PR fixes that.
> ref: Send frames for all spans

- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/SentryTime.mm
- Sources/Sentry/include/SentryTime.h
- Tests/SentryTests/Helper/SentryTimeSwiftTests.swift
SentryTime has timeIntervalToNanoseconds but not nanosecondsToTimeInterval. This PR adds nanosecondsToTimeInterval. 
Furthermore, added some tests for timeIntervalToNanoseconds  and fixed the max value check. This method is required for frame delay https://github.com/getsentry/sentry-cocoa/issues/3481.
> ref: Add nanosecondsToTimeInterval

- Sources/Sentry/Public/SentryScope.h
- Sources/Sentry/include/SentryScope+Private.h
small simple refactor of something i noticed while reading code
> ref: move fcd to where its actually used

- CHANGELOG.md
- Sources/Sentry/SentryHub.m
- Tests/SentryTests/SentryHubTests.swift
Fix marking manual sessions as crashed when capturing crash events.
Fixes GH-3498
Unit tests and with the simulator
> fix: Marking manual sessions as crashed

- CHANGELOG.md
- Sources/Sentry/SentryDelayedFramesTracker.m
- Sources/Sentry/SentryFramesTracker.m
- Sources/Sentry/SentrySpan.m
- Sources/Sentry/include/SentryDelayedFramesTracker.h
- Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackerTests.swift
- Tests/SentryTests/Transaction/SentrySpanTests.swift
Also fix a couple of edge cases when calculating the frames delay when an ongoing delayed frame is not yet recorded.
Fixes GH-3481
Unit tests and with the simulator
Update the docs once we show the feature in mobile starfish.
> feat: Add frames delay to span data

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/ViewControllers/LoremIpsumViewController.swift
- Sources/Sentry/SentryTimeToDisplayTracker.m
- Sources/Sentry/SentryUIViewControllerPerformanceTracker.m
- Sources/Sentry/include/SentryTimeToDisplayTracker.h
- Tests/SentryTests/Integrations/Performance/SentryPerformanceTrackingIntegrationTests.swift
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryTimeToDisplayTrackerTest.swift
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerPerformanceTrackerTests.swift
The SDK waits for the next drawn frame after users call reportFullyDisplayed to reflect when UI changes are visible to the user correctly.
Preparation for https://github.com/getsentry/sentry-cocoa/issues/3471.
> fix: TTFD waits for next drawn frame

- Sources/Sentry/SentryFramesTracker.m
- Tests/ThreadSanitizer.sup
The ThreadSanitizer now ignores SentryFramesTracker:getFramesDelay. 
$#skip-changelog
> ref: Ignore getFramesDelay for ThreadSanitizer

- Sources/Sentry/SentryAppStartMeasurement.m
- Sources/Sentry/include/HybridPublic/SentryAppStartMeasurement.h
SentryAppStartMeasurement is only plublic for hybrid SDKs since https://github.com/getsentry/sentry-cocoa/pull/2458. Therefore, we can remove the deprecated init method.
> ref: Remove internal init of AppStartMeasurement

- CHANGELOG.md
- Sources/Sentry/Public/SentryOptions.h
Make the option enablePreWarmedAppStartTracing stable.
Docs PR https://github.com/getsentry/sentry-docs/pull/8812.
The option has been in beta for over a year. We didn't hear any complaints about the feature. Let's make it stable and fix problems if required. The plan is to turn this feature on by default in the next major https://github.com/getsentry/sentry-cocoa/issues/3535.
No complaints.
> feat: Prewarmed App Start Tracing is stable

- .github/workflows/benchmarking.yml
- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/lint.yml
- .github/workflows/saucelabs-UI-tests.yml
- .github/workflows/test.yml
Cancel in progress workflow runs when pushing new commits to a PR to save CI computing time.
Code snippet taken from https://github.com/getsentry/getsentry/blob/a073943d465eb4616ad7c62b31a0a9d97eb443fb/.github/workflows/development-environment.yml#L11-L15.
Fixes GH-3213
> ci: Cancel in progress workflows for PRs

- CHANGELOG.md
- Sources/Sentry/SentryAppStartMeasurement.m
- Sources/Sentry/SentryAppStartTracker.m
- Sources/Sentry/SentryBuildAppStartSpans.m
- Sources/Sentry/SentrySDK.m
- Sources/Sentry/include/HybridPublic/SentryAppStartMeasurement.h
- Sources/Sentry/include/SentrySDK+Private.h
- Tests/SentryProfilerTests/SentryProfilerSwiftTests.swift
- Tests/SentryTests/Integrations/Performance/AppStartTracking/SentryAppStartTrackerTests.swift
- Tests/SentryTests/Protocol/TestData.swift
- Tests/SentryTests/SentrySDKTests.swift
- Tests/SentryTests/Transaction/SentryTracerTests.swift
Split the UIKit and Application Init span into one span for UIKit Init and another for Application Init. The UIKit Init span ends when the users start the SentrySDK. We recommend that the SentrySDK is the first to call in the UIApplication.didFinishLaunching method because otherwise, users won't receive any potential crash reports for code running before our SDK. Therefore, we pick the start time of our SDK as when the UIApplicationDelegate.didFinishLaunching is called.
Fixes GH-3345
> feat: Split up UIKit and App Init App Start Spans

- .github/workflows/test.yml
Validate that the test server runs for ThreadSanitizer tests in CI cause the tests requiring the test server failed on main: https://github.com/getsentry/sentry-cocoa/actions/runs/7409955431/job/20162751416.
> ci: ThreadSanitizer validate test server runs

- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Samples/iOS-Swift/iOS-SwiftUITests/BaseUITest.swift
Set the up-tests environment when running UI tests in CI so that we can apply filters in Sentry.
> test: Set ui-tests environment

- CHANGELOG.md
- Sources/Sentry/SentryTracer.m
- Tests/SentryTests/Transaction/SentryTracerTests.swift
Send the complete list of debug meta for app start transactions so we can calculate statistics on the number and size of libraries loaded on the backend when the app starts.
Fixes GH-3541
> feat: Send debug meta for app start transactions

- Sentry.xcodeproj/project.pbxproj
- SentryTestUtils/ClearTestState.swift
- Sources/Sentry/SentryDependencyContainer.m
- Sources/Sentry/SentryFramesTracker.m
- Tests/SentryTests/Helper/SentryDependencyContainerTests.swift
- Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackerTests.swift
The teardown of the `SentryFramesTracker` didn't work properly in tests. The `clearTestState` method continuously initialized a new frames tracker cause it accessed the property dependency container. This is fixed now by calling `SentryFramesTracker.stop` directly in `SentryDependencyContainer.reset` which is also called in `clearTestState`. Furthermore, the `SentryFramesTracker.stop` now resets all frames and removes all observers.
I identified this problem when looking at the logs of failing tests at the main branch here: https://github.com/getsentry/sentry-cocoa/actions/runs/7419191432/job/20188316830. The logs showed continuous init calls to SentryFramesTracker and also unwanted tracking of frames during tests, which could lead to failing tests.
> ref: Properly teardown frames tracker

- CHANGELOG.md
- Sources/Sentry/SentryScope.m
- Tests/SentryTests/SentryScopeSwiftTests.swift
Instead of calling the callback of useSpan within the spanLock, get a reference to the span inside the critical sector and pass this to the callback after the critical sector closes. This way, when the callback is a blocking call, useSpan doesn't block other invocations of itself and prevents potential deadlocks.
A customer reported a deadlock on macOS for which multiple threads pointed to acquiring locks to `SentryScope useSpan`.
Unit tests.
> fix: Make SentryScope.useSpan non-blocking

- CHANGELOG.md
https://github.com/getsentry/sentry-cocoa/pull/3540 was opened before the 8.18.0 release. After the release ran, the PR was not caught up to `main`, so the diff was stale and its changelog entry went in under the 8.18.0 heading.
> meta: fix changelog entry that was added to stale diff after 8.18.0 release

- Tests/SentryTests/SentryScopeSwiftTests.swift
Add two test cases for edge cases when adding breadcrumbs.
I wrote these tests while investigating https://github.com/getsentry/sentry-cocoa/issues/3341.
> test: Add Scope maxBreadcrumb edge case tests

- .github/workflows/benchmarking.yml
- .github/workflows/saucelabs-UI-tests.yml
0.107.2 was released in Sep 2022. Let's bump to the latest version.
> chore: Bump saucectl from 0.107.2 to 0.171.0

- Sources/Sentry/include/SentryFileManager.h
- Tests/SentryTests/Helper/SentryFileManagerTests.swift
SentryFileManager.allFilesInFolder is only used by the SentryFileManager and can be internal. Furthermore, we can safely remove the test testAllFilesInFolder as that functionality is covered with other tests.
> ref: Make allFilesInFolder internal

- CHANGELOG.md
- Sources/Sentry/SentryFileManager.m
- Tests/SentryTests/Helper/SentryFileManagerTests.swift
Logging an error when getting all files for a folder that doesn't exist confuses users; see GH-3577. Instead, log an info message that the SentryFileManager tried getting a list of files for a folder that doesn't exist. We chose info because it's still an edge case that shouldn't occur often, but it doesn't break any functionality. If a path was deleted manually by the user that the SDK requires, the SDK will create the path on next launch. We don't want to add checks if all the necessary paths exist every time the SDK stores an envelope cause this adds some overhead. If users manually remove the required paths, we accept that they have to wait until the next time the SDK launches.
Fixes GH-3577
Unit tests.
> fix: FileManager log info when path doesn't exist

- CHANGELOG.md
- Sources/Sentry/SentryFileManager.m
- Sources/Sentry/include/SentryFileManager.h
- Tests/SentryTests/Helper/SentryFileManagerTests.swift
Don't log a warning in SentryFileManager for .DS_Store files.
Fixes one part of GH-3577
Unit tests
> fix: Fix FileManager logs warning for .DS_Store

- Tests/SentryTests/State/SentryInstallationTests.swift
> test: Fix typo in SentryInstallationTests

- CHANGELOG.md
- Sources/Sentry/SentryClient.m
- Sources/Sentry/SentryInstallation.m
- Sources/Sentry/include/SentryInstallation.h
- Tests/SentryTests/SentryClientTests.swift
- Tests/SentryTests/State/SentryInstallationTests.swift
The SDK stores the installationID in a file. When the SDK launches, it caches the installationID async to avoid file IO on the main thread.
Fixes GH-3575
Unit tests.
> impr: Cache installationID async

- Tests/SentryTests/Integrations/Performance/SentryPerformanceTrackerTests.swift
- Tests/SentryTests/Transaction/SentrySpanTests.swift
- Tests/SentryTests/Transaction/SentryTracerTests.swift
I changed these while investigating a broken assumption that were crashing the test run instead of just failing these cases. Helps with #3576.
> test: use XCTUnwrap instead of force unwraps or unchecked array access

- .github/workflows/benchmarking.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
Use macos-13-xlarge for slow GH jobs to speed up CI.
> ci: Use macos-13-xlarge

- .github/workflows/test.yml
Address Sanitizer tests use Xcode 15.2 with iPhone 14 and iOS 17.2 instead of Xcode 14.3 with iPhone 8 and iOS 15.5.
> ci: Address Sanitizer tests use Xcode 15.2

- .github/workflows/test.yml
Add tvOS 17, iOS 17, and macOS 14. Run Catalyst on Xcode 15.2.
Fixes GH-3329
> ci: Run unit tests on macOS 14

- CHANGELOG.md
- Sources/Sentry/SentryScreenshotIntegration.m
- Sources/Sentry/SentryViewHierarchyIntegration.m
- Tests/SentryTests/Integrations/Screenshot/SentryScreenshotIntegrationTests.swift
- Tests/SentryTests/Integrations/Screenshot/TestSentryScreenShot.swift
- Tests/SentryTests/Integrations/ViewHierarchy/SentryViewHierarchyIntegrationTests.swift
We stop taking screenshot and view hierarchy during app hang events.
Main thread is blocked, and its not safe to use ui elements.
Unit tests
> fix: Dont take screenshot and view hierarchy for app hanging

- Samples/iOS-Swift/iOS-Swift/Info.plist
- Samples/iOS-Swift/iOS-Swift/ViewControllers/PermissionsViewController.swift
Add a button to trigger a biometric prompt for the iOS-Swift test app.
For investigating https://github.com/getsentry/sentry-cocoa/issues/3472.
> test: Add biometric prompt to permissions

- .github/workflows/lint.yml
When updating the CocoaPods version we should run the CocoaPods linters.
> ci: Run linters on Gemfile.lock changes.

- CHANGELOG.md
- Sources/Resources/PrivacyInfo.xcprivacy
Add C617.1 as reason to use NSPrivacyAccessedAPICategoryFileTimestamp to PrivacyInfo.xcprivacy.
Fixes GH-3597
No test required.
> impr: Add reason for NSPrivacyAccessedAPICategoryFileTimestamp

- Sources/Sentry/SentryProfileTimeseries.mm
Something I noticed while debugging for launch profiling. It's possible with concurrency that an index beyond the first may be selected. These arrays are in chronological order, so searching just for the first instance and stopping should be performant enough. Concurrency seems like overkill and overcomplicating.
> fix(profiling): don't use concurrent enumeration when slicing samples

- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Samples/iOS-Swift/iOS-Swift/Profiling/ProfilingViewController.swift
- Sources/Sentry/Profiling/SentryLaunchProfiling.m
- Sources/Sentry/include/SentryLaunchProfiling.h
- Sources/Sentry/include/SentryTraceOrigins.h
- Tests/SentryProfilerTests/SentryAppLaunchProfilingTests.m
- Tests/SentryTests/SentryLaunchProfiling+Tests.h
follows https://github.com/getsentry/sentry-cocoa/pull/3635
It was requested to make a new origin for these transactions: https://github.com/getsentry/sentry-cocoa/pull/3621#discussion_r1486012768
I wasn't sure what to do for `nameSource`, another parameter required on the init I needed to use, so I stuck with `custom` as that's the default value used in some of the other init implementations.
> fix(launch profiling): set a new trace origin for app launch profiles

- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Samples/iOS-Swift/iOS-Swift/Profiling/ProfilingViewController.swift
- Sources/Sentry/Profiling/SentryLaunchProfiling.m
- Sources/Sentry/SentryProfiler.mm
- Sources/Sentry/SentrySDK.m
- Sources/Sentry/SentryTracer.m
- Sources/Sentry/include/SentryFileManager.h
- Sources/Sentry/include/SentryLaunchProfiling.h
- Sources/Sentry/include/SentryTraceOrigins.h
- Tests/SentryProfilerTests/SentryAppLaunchProfilingTests.m
- Tests/SentryTests/SentryLaunchProfiling+Tests.h
- develop-docs/README.md
follows https://github.com/getsentry/sentry-cocoa/pull/3633 and followed by https://github.com/getsentry/sentry-cocoa/pull/3635
The dedicated trace was being created with a nil hub, so we need to inject it when it becomes available, before it is transmitted, or it will simply be lost. Also needed to inject the sampling decision in another parameter in the transaction context.
> fix(launch profiling): ensure launch profile can be uploaded

- SentryTestUtils/TestClient.swift
- Sources/Sentry/SentryClient.m
- Sources/Sentry/SentryTransportAdapter.m
- Sources/Sentry/SentryTransportFactory.m
- Sources/Sentry/include/SentryTransportAdapter.h
- Sources/Sentry/include/SentryTransportFactory.h
- Tests/SentryTests/Integrations/SentryCrash/SentryCrashIntegrationTests.swift
- Tests/SentryTests/Networking/SentryTransportAdapterTests.swift
- Tests/SentryTests/Networking/SentryTransportFactoryTests.swift
- Tests/SentryTests/Networking/SentryTransportInitializerTests.swift
- Tests/SentryTests/SentryClientTests.swift
- Tests/SentryTests/SentrySDKTests.swift
Add the possibility to add multiple transports in the TransportAdapter, which is internal. This is a preparation for adding support for Spotlight.
> ref: Add multiple transports to TransportAdapter

- SentryTestUtils/ClearTestState.swift
- SentryTestUtils/SentryTestUtils-ObjC-BridgingHeader.h
- Sources/Sentry/SentryFileManager.m
- Tests/SentryTests/Helper/SentryFileManager+TestProperties.h
Noticed there was some stale state causing test failures in #3529. I don't think we ever had something that clears disk state in between tests.
> test: reset file manager state in clearTestState()

- .github/workflows/testflight.yml
Because: Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.
> ci: Use Xcode 15.2 for TestFlight upload

- .github/workflows/test.yml
Roll back to macos-13 because macos-13-xlarge doesn't speed up CI, and is more expensive.
Other jobs show a clear trend when switching to xlarge
but not UI tests with address sanitizer:
> ci: Use non xl for UI tests with address sanitizer

- Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
- Samples/iOS-Swift/iOS-SwiftUITests/UIEventBreadcrumbTests.swift
This [SauceLabs test run](https://app.saucelabs.com/tests/db0632ba709947cc997bda7f59c74e27#15) navigated to the breadcrumb info test instead of the U event tests for the `testNoBreadcrumbForTextFieldEditingChanged`. Using an accessibility identifier should mitigate this problem.
> test: Use accessibility id for breadcrumb UI test

- .sauce/benchmarking-config.yml
- .sauce/config.yml
Our plan allows running 4 UI tests in parallel. This should speed up CI.
> ci: Increase SauceLabs Concurrency to 4

- .github/workflows/saucelabs-UI-tests.yml
SauceLabs retries aren't necessary anymore because SauceLabs isn't failing that often anymore. The retries queue many jobs in SauceLabs. Instead, we should take failing SauceLabs tests seriously and try to fix them or disable a flaky test if necessary.
> ci: Remove SauceLabs retries

- Samples/iOS-Swift/PerformanceBenchmarks/SentrySDKPerformanceBenchmarkTests.m
- Tests/SentryTests/Helper/SentryDeviceTests.mm
Some [failing benchmark tests](https://app.saucelabs.com/tests/0ed189cd1b26481eaf1d9a87581746fe#1) in SauceLabs show the devices in landscape mode. The`SentrySDKPerformanceBenchmarkTests` now use portrait mode. 
> test: Set orientation portrait for UI tests

- .sauce/benchmarking-config.yml
- .sauce/config.yml
- Sources/Sentry/SentryProfiler.mm
Downloading the jUnit artifacts fails frequently, and we don't use them. Therefore, we can remove them.
This PR is based on https://github.com/getsentry/sentry-cocoa/pull/3663.
> ci: SauceLabs remove downloading junit artifacts

- CHANGELOG.md
- Sources/Sentry/Public/SentryScope.h
- Tests/SentryTests/SentryScopeSwiftTests.swift
> Make tags of SentryScope public

- Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
- Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift
The `testCrashRecovery` failed here because it didn't find the crash the app button: https://github.com/getsentry/sentry-cocoa/actions/runs/7976509897/job/21777248607
> ci: Use accessibility id for crashTheApp button

- Samples/iOS-Swift/PerformanceBenchmarks/SentrySDKPerformanceBenchmarkTests.m
- Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
- Samples/iOS-Swift/iOS-Swift/Profiling/ProfilingViewController.swift
- Samples/iOS-Swift/iOS-SwiftUITests/ProfilingUITests.swift
GH-3665 didn't enable the app launch profiling tests because they were still disabled in Xcode. This PR fixes that and also uses more accessibility identifiers in the profiling tests.
> test: Enable App Launch Profiling UI tests

- Sources/Sentry/SentryDataCategoryMapper.m
- Sources/Sentry/include/HybridPublic/SentryEnvelopeItemType.h
- Sources/Sentry/include/SentryDataCategory.h
- Sources/Sentry/include/SentryDataCategoryMapper.h
- Tests/SentryTests/Networking/SentryDataCategoryMapperTests.swift
Add envelope item type and data category for statsd, which is required for the metrics API.
Fist step for https://github.com/getsentry/sentry-cocoa/issues/3631.
> feat: Add statsd item type

- .github/workflows/test.yml
Call create-simulator.sh for unit tests to remove some duplicated code.
> ci: Use create simulator script for unit tests

- .github/workflows/release.yml
This allows us to choose which branch the release will be merged back.
> chore: Add Target for release worflow

- .github/workflows/benchmarking.yml
- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
Stop using xlarge runners cause they eat up 20% of our GH actions quota.
> ci: Stop using xlarge runners

- CHANGELOG.md
- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor.h
- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.h
- Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_Backtrace.h
- Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_MachineContext.h
- Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_SelfThread.h
- Sources/SentryCrash/Recording/Tools/SentryCrashSymbolicator.h
If a project uses a C++ compiler, it will not compile because of some headers inside a "extern C" block referencing C++ code.
This appears to be an inheritance from KSCrash that I don't fully understand the reasoning behind. Moving these headers out of the extern block hasn't caused any crashes in our default pipeline, so I believe we're fine with it.
close #3689 
CI
> fix: Move headers out of Extern C

- CHANGELOG.md
Copy the changelog entries of 8.21.0-beta.0, so 8.21.0 contains the full summary of all changes.
> Changelog for 8.21.0

- develop-docs/README.md
We don't run UI tests on SauceLabs anymore. Only with simulators on GH actions.
> chore: Update UI test develop docs

- Sources/Sentry/Public/SentryEnvelopeItemHeader.h
- Sources/Sentry/SentryEnvelopeItemHeader.m
- Tests/SentryTests/Protocol/SentryEnvelopeTests.swift
Add an extra initializer without a filename, which is required for DDM.
> ref: EnvelopeItemHeader: Init without filename

- CHANGELOG.md
- Sources/SentryCrash/Recording/SentryCrashReport.c
- Tests/SentryTests/Integrations/SentryCrash/SentryCrashReportTests.swift
Correctly write the NSException reason when writing a crash report. When writing a crash report for NSException the crash report writer wrote the crash reason to ReferencedObject, which didn't make any sense. This is fixed now by using the reason field.
Fixes GH-3265
Unit tests.
> fix: Write NSException reason for crash report

- Sentry.xcodeproj/project.pbxproj
Setting HEADER_SEARCH_PATHS to `$(SRCROOT)/Sources/Sentry/include` recursive, so Objc compiler can use module.modulemap
> chore: Set HEADER_SEARCH_PATHS to expose _SentryPrivate to Objc

- Sources/Sentry/SentryNSURLRequest.m
- Tests/SentryTests/SentryNSURLRequestTests.swift
adds SDK version to the User-Agent reported when using SentryNSURLRequest for /envelope and /store endpoints
fixes https://github.com/getsentry/sentry-cocoa/issues/3713
manual, unit test
> chore: Add SDK version to User-Agent header

- Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme
These were left over from testing app launch profiling, and shouldn't be enabled by default.
> test: disable all launch arguments by default

- Sources/Sentry/SentryBaggage.m
- Sources/Sentry/include/SentryTraceContext.h
The SentryTraceContext doesn't need to SentrySwift import. It only needs a reference to SentryId.
> ref: Remove SentrySwift import for trace context

- Sentry.xcodeproj/project.pbxproj
- SentryTestUtils/SentryTestUtils-ObjC-BridgingHeader.h
- Sources/Sentry/PrivateSentrySDKOnly.mm
- Sources/Sentry/SentryBaggage.m
- Sources/Sentry/include/HybridPublic/PrivateSentrySDKOnly.h
- Sources/Sentry/include/SentryInternalSerializable.h
- Sources/Sentry/include/SentryPrivate.h
- Sources/Sentry/include/SentrySdkInfo.h
- Sources/Sentry/include/SentrySpan.h
- Sources/Sentry/include/SentryTraceContext.h
- Tests/SentryTests/SentryTests-Bridging-Header.h
- develop-docs/README.md
This is the first step of exposing the Client to Swift SDK code. I'm doing this in multiple steps because CI keeps failing for https://github.com/getsentry/sentry-cocoa/pull/3724, and I'm unable to track down the problem.
This PR is based on https://github.com/getsentry/sentry-cocoa/pull/3726.
> ref: Expose SDKInfo to Swift SDK Code

- Sources/Sentry/include/HybridPublic/SentryEnvelope.h
- Sources/Sentry/include/SentryEnvelope+Private.h
Having unused forward declarations in the SentryEnvelope.h doesn't make sense and makes it harder to expose that specific class to Swift. Therefore, we can remove them.
> ref: Remove forward declarations for Envelope

- Sentry.xcodeproj/project.pbxproj
- Sources/Swift/Extensions/NSLock.swift
- Tests/SentryTests/Swift/Extensions/NSLockTests.swift
Add a synchronized extension for NSLock for a convenient way to synchronize a closure call in Swift.
This is required to synchronize access to the buckets for DDM.
> chore: Add synchronized extension for NSLock

- Sources/Swift/Extensions/NSLock.swift
- Tests/SentryTests/Swift/Extensions/NSLockTests.swift
Use generics to allow a return value for NSLock synchronized.
> ref: Swift NSLock return value

- Sources/Sentry/Profiling/SentryProfilerState.mm
Debugging leftovers, but very spammy.
> meta: remove leftover noisy logging

- Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme
Failed most recently in https://github.com/getsentry/sentry-cocoa/pull/3738 (https://github.com/getsentry/sentry-cocoa/actions/runs/8274761217/job/22640682028?pr=3738#step:13:48) but I see it fail fairly regularly.
> test: disable flaky `SentryTracerTests.testDeadlineTimer_StartedAndCancelledOnMainThread`

- Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme
Failed most recently in https://github.com/getsentry/sentry-cocoa/pull/3738 (https://github.com/getsentry/sentry-cocoa/actions/runs/8274761217/job/22640682547?pr=3738#step:13:56) but I see it fail fairly regularly.
> test: disable flaky `SentrySDKTests.testStartOnTheMainThread`

- Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme
Failed most recently in https://github.com/getsentry/sentry-cocoa/pull/3738 (https://github.com/getsentry/sentry-cocoa/actions/runs/8274761217/job/22640682633?pr=3738#step:13:50) but I see it fail fairly regularly.
> test: disable flaky `SentryThreadWrapperTests.testOnMainThreadFromNonMainContext`

- SentryTestUtils/SentryTestUtils-ObjC-BridgingHeader.h
- SentryTestUtils/TestDispatchFactory.swift
- SentryTestUtils/TestSentryDispatchQueueWrapper.swift
- Sources/Sentry/include/SentryPrivate.h
- Tests/SentryProfilerTests/SentryProfilerSwiftTests.swift
- Tests/SentryTests/Integrations/Performance/AppStartTracking/SentryAppStartTrackerTests.swift
- Tests/SentryTests/Integrations/Performance/AppStartTracking/SentryAppStartTrackingIntegrationTests.swift
- Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackerTests.swift
- Tests/SentryTests/Integrations/Performance/SentrySubClassFinderTests.swift
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryTimeToDisplayTrackerTest.swift
- Tests/SentryTests/Networking/SentryDispatchQueueWrapperTests.swift
- Tests/SentryTests/Transaction/SentrySpanTests.swift
- Tests/SentryTests/Transaction/SentryTracerTests.swift
I also changed the usage of SentryDispatchQueueWrapper to TestSentryDispatchQueueWrapper in the test if possible.
This is required for DDM to send metrics on a background thread and for scheduling a repeating timer on the main thread.
> ref: Expose DispatchQueueWrapper to Swift

- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/SentryStatsdClient.m
- Sources/Sentry/include/SentryPrivate.h
- Sources/Sentry/include/SentryStatsdClient.h
- Sources/Swift/Metrics/CounterMetric.swift
- Sources/Swift/Metrics/EncodeMetrics.swift
- Sources/Swift/Metrics/Metric.swift
- Sources/Swift/Metrics/SentryMetricsClient.swift
- Tests/SentryTests/Swift/Metrics/EncodeMetricTests.swift
- Tests/SentryTests/Swift/Metrics/SentryMetricsClientTests.swift
Add the MetricsClient, which uses statsd encoding to send metrics to Sentry.
This is another PR for adding DDM to the SDK.
Unit tests
> chore(ddm): Add MetricsClient with statsd encoding

- Makefile
Make init now uses bundle install, which installs the gems specified in the gemfile, instead of bundle update, which updates the gems to the latest version specified in the gemfile.
> chore: Make init uses bundle install

- Utils/VersionBump/main.swift
We removed SentryPrivate with GH-3623, so we also have to remove it from the version bump.
The release workflow failed here https://github.com/getsentry/sentry-cocoa/actions/runs/8328632979/job/22789361830.
I tested it locally by running `make bump-version TO=9.0.0-rc.0`
> chore: Remove SentryPrivate from version bump

- CHANGELOG.md
- Package.swift
The path to the XCFramework in the package.json was incorrect before releasing the new version, so the bump tool did not properly update it.
Closes #3759
> fix: XCFramework Path

- CHANGELOG.md
- Sentry.podspec
- scripts/build-xcframework.sh
Static framework was failing Xcode validation because of minimum os version.
close #3769
> fix: Sentry.framework does not support the minimum OS Version specified in the Info.plist

- .github/workflows/ui-tests.yml
I've been trying to figure out why `ProfilingUITests` have been running in our SwiftUI sample app. Well, they weren't 😛 
> ci: fix job names for iOS-Swift UI tests

- .github/workflows/release.yml
- CHANGELOG.md
We need to update SDK version before creating the framework and saving it as artefact.
closes #3786
> fix: CFBundleShortVersionString in the Info.plist file is invalid

- Sentry.xcodeproj/project.pbxproj
- Sources/Swift/Metrics/BucketsMetricsAggregator.swift
- Sources/Swift/Metrics/CounterMetric.swift
- Sources/Swift/Metrics/DistributionMetric.swift
- Sources/Swift/Metrics/GaugeMetric.swift
- Sources/Swift/Metrics/MetricsAggregator.swift
- Sources/Swift/Metrics/SetMetric.swift
- Tests/SentryTests/Swift/Metrics/BucketMetricsAggregatorTests.swift
- Tests/SentryTests/Swift/Metrics/CounterMetricTests.swift
- Tests/SentryTests/Swift/Metrics/DistributionMetricTests.swift
- Tests/SentryTests/Swift/Metrics/EncodeMetricTests.swift
- Tests/SentryTests/Swift/Metrics/GaugeMetricTests.swift
- Tests/SentryTests/Swift/Metrics/SentryMetricsClientTests.swift
- Tests/SentryTests/Swift/Metrics/SetMetricTests.swift
This supersedes https://github.com/getsentry/sentry-cocoa/pull/3772, as this PR got messed up by merge conflicts.
Add classes for Set, Gauge, and Distribution.
This is part of adding DDM to the SDK https://github.com/getsentry/sentry-cocoa/issues/3631.
> chore(metrics): Add Set, Gauge, Distribution metric classes

- .github/workflows/build.yml
- CHANGELOG.md
- scripts/build-xcframework.sh
Removed symbol generation from Static framework.
Debug symbols will be generated by the project using our static framework.
close #3788
> fix: Redistributable static libraries should never be built with module debugging enabled

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
- Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
- Samples/iOS-Swift/iOS-Swift/ViewControllers/ReplaceContentViewController.swift
- Samples/iOS-Swift/iOS-SwiftUITests/TopViewControllerTests.swift
- Sources/Sentry/SentryUIApplication.m
When performance tracking is enabled, `loadView`'s swizzled implementation may result in a duplicate chain of events, that result in multiple `viewDidLoad` invocations, in our main app's VC/
Thanks in advance!!
Fixes #3753
I'm afraid I did not test this change. Sentry's `Package.swift` points towards a binary distribution, and because of time constraints, I've been unable to pull together a Package Description for local testing.
> fix: Avoid duplicating loadView / viewDidLoad events

- Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme
Failed here https://github.com/getsentry/sentry-cocoa/actions/runs/8520084162/job/23335548804?pr=3813. 
> Disable flaky testGetCaptureFailedRequestsEnabled

- CHANGELOG.md
- Sources/Sentry/Public/SentryOptions.h
- Sources/Sentry/SentryOptions.m
- Sources/Sentry/SentryPerformanceTrackingIntegration.m
- Sources/Sentry/SentrySubClassFinder.m
- Sources/Sentry/include/SentrySubClassFinder.h
- Tests/SentryTests/Integrations/Performance/SentrySubClassFinderTests.swift
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerSwizzlingTests.swift
- Tests/SentryTests/SentryOptionsTest.m
Add an option to exclude certain classes from swizzling.
Docs PR https://github.com/getsentry/sentry-docs/pull/9596.
Fixes GH-3798
Unit tests.
> feat: Add the option swizzleClassNameExcludes

- CHANGELOG.md
- Sources/Sentry/SentryTracer.m
- Tests/SentryTests/Transaction/SentryTracerTests.swift
Fix a crash in SentryTracer hasUnfinishedChildSpansToWaitFor by not setting the shouldIgnoreWaitForChildrenCallback to nil when finishing the tracer.
Fixes GH-3781
Unit tests.
> fix: Crash in hasUnfinishedChildSpansToWaitFor

- Sources/Sentry/SentryNSDataTracker.m
This code is a duplicate. I remove one occurence.
https://github.com/getsentry/sentry-cocoa/blob/c83ffd949311d9b6594a041d1ad32e1e61dd74f5/Sources/Sentry/SentryNSDataTracker.m#L157-L163
> ref: Remove duplicate code in NSDataTracker

- Sources/Sentry/SentryOptions.m
- Sources/Sentry/include/SentryOptions+Private.h
- Tests/SentryTests/SentryOptionsTest.m
A private (for now) feature flag that will be used to switch between implementations of legacy and continuous profiling.
For #3555 
> feat(profiling): add private option to feature flag continuous profiling mode

- Sources/Sentry/SentryClient.m
- Sources/Sentry/SentryDateUtil.m
- Sources/Sentry/SentryDefaultRateLimits.m
- Sources/Sentry/SentryRateLimitParser.m
- Sources/Sentry/SentryRetryAfterHeaderParser.m
- Sources/Sentry/SentryTransportFactory.m
- Sources/Sentry/include/SentryDateUtil.h
- Sources/Sentry/include/SentryDefaultRateLimits.h
- Sources/Sentry/include/SentryRateLimitParser.h
- Sources/Sentry/include/SentryRetryAfterHeaderParser.h
- Sources/Sentry/include/SentryTransportFactory.h
- Tests/SentryTests/Helper/SentryDateUtilTests.swift
- Tests/SentryTests/Networking/RateLimits/SentryDefaultRateLimitsTests.swift
- Tests/SentryTests/Networking/RateLimits/SentryRateLimitsParserTests.swift
- Tests/SentryTests/Networking/RateLimits/SentryRetryAfterHeaderParserTests.swift
- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
- Tests/SentryTests/Networking/SentryTransportFactoryTests.swift
- Tests/SentryTests/Networking/SentryTransportInitializerTests.swift
Replace access to the DependencyContainer in the RateLimits code by passing the current date as a dependency to reduce global state and the need to call clearTestState.
This came up when tackling https://github.com/getsentry/sentry-cocoa/issues/3805.
> ref: CurrentDate as dependency for rate limits

- Sources/Sentry/SentrySessionReplay.m
- Sources/Swift/Integrations/SessionReplay/SentryReplayOptions.swift
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayTests.swift
A session can't be longer than 60 minutes.
> feat(Session Replay): Maximum duration for a session replay

- CHANGELOG.md
- Sources/Swift/Metrics/EncodeMetrics.swift
- Tests/SentryTests/Swift/Metrics/EncodeMetricTests.swift
Update metrics data normalization to spec.
Fixes GH-3829
Unit tests
> fix(metrics): Data Normalization

- SentryTestUtils/TestTransport.swift
No ObjC code uses the TestTransport, and therefore the @objc can be removed.
> test: Remove @objc for TestTransport

- .github/workflows/codeql-analysis.yml
I keep seeing this warning on CodeQL workflows: 
> ci: update codeql actions to unpinned v3

- .github/workflows/release.yml
- CHANGELOG.md
- Makefile
The compiled framework that is not linked with UI APIs wast not being saved as asset.
> Save framework without UIKit/AppKit as Github Asset for releases

- Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
- Samples/iOS-Swift/iOS-SwiftUITests/LaunchUITests.swift
I noticed this fail locally due to a XCUIElement query timeout, but it worked when I changed `crashTheApp` from being the accessibilityIdentifier to the accessibilityLabel for the button.
I also set it up to report the test case as skipped if the OS version req is not met.
I've noticed this test flake in the past but not sure this will fix that.
> test: use correct a11y property and skip if not correct OS version

- CHANGELOG.md
- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/Profiling/SentryLaunchProfiling.m
- Sources/Sentry/Profiling/SentryLaunchProfiling.mm
- Sources/Sentry/SentryHub.m
- Sources/Sentry/SentryProfiler.mm
- Sources/Sentry/SentrySDK.m
- Sources/Sentry/SentrySampling.m
- Sources/Sentry/SentryTimeToDisplayTracker.m
- Sources/Sentry/SentryTracer.m
- Sources/Sentry/include/SentryLaunchProfiling.h
- Sources/Sentry/include/SentrySampling.h
- Tests/SentryProfilerTests/SentryAppLaunchProfilingTests.m
- Tests/SentryTests/SentryLaunchProfiling+Tests.h
We should've been prefixing any functions in the global namespace to avoid potential collisions with other apps' functions. Fixes the immediate problem reported in https://github.com/getsentry/sentry-cocoa/issues/3856, but we may need to do more here with all other functions. These generic functions names present the most likely possibility for collisions, though, so this should practically fix most of the issue.
Closes https://github.com/getsentry/sentry-cocoa/issues/3856
> fix(profiling): prefix some functions with "sentry_"

- Sources/Sentry/SentryProfileTimeseries.mm
- Sources/Sentry/SentryProfiler.mm
- Sources/Sentry/include/SentryProfileTimeseries.h
- Tests/SentryProfilerTests/SentryProfilerTests.mm
Taking some time to clean up the implementation of SentryProfiler and organize it a little better before moving forward with adding the continuous profiling implementation.
This moves the `sliceGPU` function out of SentryProfiler.mm and into SentryProfilerTimeseries.mm. Also prefix the C function names with `_sentry` as in #3862 
for #3555 #skip-changelog
> ref(profiling): move sliceGPUData to timeseries code unit; prefix C functions

- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/Profiling/SentryProfilerTestHelpers.m
- Sources/Sentry/SentryProfileTimeseries.mm
- Sources/Sentry/SentryProfiler.mm
- Sources/Sentry/include/SentryProfileTimeseries.h
- Sources/Sentry/include/SentryProfiler+Private.h
- Sources/Sentry/include/SentryProfilerTestHelpers.h
- Tests/SentryProfilerTests/SentryProfilerTests.mm
- Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackerTests.swift
- Tests/SentryTests/PrivateSentrySDKOnlyTests.swift
- Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift
- Tests/SentryTests/SentryTests-Bridging-Header.h
- Tests/SentryTests/Transaction/SentryTracerTests.swift
Following on https://github.com/getsentry/sentry-cocoa/pull/3872, for #3555, #skip-changelog
Move some functions only used for testing purposes to a separate code unit `SentryProfilerTestHelpers`
> ref(profiling): move test helpers to separate code unit; prefix with _sentry

- Tests/SentryProfilerTests/SentryProfilerSwiftTests.swift
I was investigating a seeming test flake in `-[SentryProfilerTests.SentryProfilerSwiftTests testProfileTimeoutTimer]`, which failed [here](https://github.com/getsentry/sentry-cocoa/blob/42f4107997def601a9f8782c44a51d150f2dbcbf/Tests/SentryProfilerTests/SentryProfilerSwiftTests.swift#L776) in [this run](https://github.com/getsentry/sentry-cocoa/blob/42f4107997def601a9f8782c44a51d150f2dbcbf/Tests/SentryProfilerTests/SentryProfilerSwiftTests.swift#L776) for #3876 due to there being no samples on the `main` thread. This test would've added some mock samples for a thread named `test-thread`, and, since it should've almost instantaneously simulated a timeout, wouldn't even be expected to have any actual samples from the real `main` thread. I'm guessing that due to execution speed, there usually …
> test(profiling): mock the correct expected thread name for unit tests

- SentryTestUtils/TestSentryDispatchQueueWrapper.swift
- Sources/Sentry/SentryDispatchQueueWrapper.m
- Sources/Sentry/SentryUIApplication.m
- Sources/Sentry/include/SentryDispatchQueueWrapper.h
`SentryDispatchQueueWrapper` is confusing to use with Swift. It behaves as if it were a DispatchQueue but also includes functions that interact with the main queue. When converting to Swift, the functions that manipulate its own queue overlap with those that interact with the main queue, distinguished only by the argument name, which can be omitted because it's a block.
Renaming those functions in Swift would better reflect their respective actions.
> chore: Rename SentryDispatchQueueWrapper function name for Swift

- .github/file-filters.yml
- .github/workflows/changes-in-high-risk-code.yml
We archived our fork of dorny/paths-filter. The sentry repo also uses dorny/path-filter, see https://github.com/getsentry/sentry/pull/64233.
> ci: Use replace sentry paths filter with dorny

- Sources/Sentry/SentrySessionReplay.m
- Sources/Sentry/include/SentrySessionReplay.h
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayTests.swift
This PR splits `captureReplayForEvent` into `captureReplay` and `captureReplayForEvent`, as Hybrid SDKs need to capture replay without passing their event to native.
This PR is need for the `alpha.0` of RN replay.
- https://github.com/getsentry/sentry-react-native/pull/3714
> feat(replay): add `captureReplay` without Event param for Hybrid SDKs

- CHANGELOG.md
Added the following comment in the changelog:
"To get access, it requires adding your Sentry org to our feature flag. This way data can be ingested and displayed in Sentry.
[Please let us know on the waitlist if you're interested](https://sentry.io/lp/mobile-replay-beta/)"
> Chore: Explain in the changelog that session replay is for registered users

- Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme
Failed here: https://github.com/getsentry/sentry-cocoa/actions/runs/8844626847/job/24286898382.
> test: Disable flaky testProfilerMutationDuringSlicing

- CHANGELOG.md
- Sources/Sentry/include/SentryAppState.h
- Sources/Sentry/include/SentrySysctl.h
- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitorContext.h
- Sources/SentryCrash/Recording/SentryCrashReport.c
- Sources/SentryCrash/Recording/SentryCrashReportFields.h
- Tests/SentryTests/Integrations/SentryCrash/SentryCrashReportTests.swift
Remove the boot_time from crash reports.
This is a follow up on #3912.
> fix: Remove boot_time from crash reports

- CHANGELOG.md
Duplicate changelog entries for 8.25.0, so it has a complete list of changes.
> chore: Changelog for 8.25.0

- CHANGELOG.md
- Sources/Sentry/SentryAppState.m
- Sources/Sentry/SentryWatchdogTerminationLogic.m
- Sources/Sentry/include/SentryAppState.h
- Tests/SentryTests/Helper/SentryAppStateTests.swift
- Tests/SentryTests/Integrations/WatchdogTerminations/SentryWatchdogTerminationsIntegrationTests.swift
- Tests/SentryTests/Integrations/WatchdogTerminations/SentryWatchdogTerminationsTrackerTests.swift
The release name passed to the app state from the options is nullable. The SentryAppState including the SentryWatchdogTerminationLogic couldn't handle this edge case correctly, which is fixed now.
Unit tests started to fail suddenly on the main branch https://github.com/getsentry/sentry-cocoa/actions/runs/8879401702/job/24377229574.
Unit tests
> fix: Handle no releaseName in WatchdogLogic

- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitorType.c
- Sources/SentryCrash/Recording/Tools/SentryCrashSignalInfo.c
GH actions uses a new preinstalled clang-format version which now reformarts code on several PRs. Let's merge this so it doesn't need to do that on multiple PRs and they only need to update to main to fix this.
> chore: Format code with clang-format 18.1.5

- CHANGELOG.md
- Sources/Sentry/SentrySessionReplay.m
- Sources/Sentry/SentrySessionReplayIntegration.m
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayTests.swift
Call SessionReplay.stop when uninstalling the SDK and invalidate the DisplayLinkWrapper when SessionReplay gets deallocated.
This came up when investigating a failing test on the main branch: https://github.com/getsentry/sentry-cocoa/actions/runs/8969460754/job/24630955316?pr=3940. The logs show SessionReplay running, although it shouldn't. We also have a problem with accessing UIWindow, but we'll fix this in another PR. 
```
Test Case '-[SentryTests.SentryViewHierarchyTests test_appViewHierarchy_usesMainThread]' started.
2024-05-06 13:01:44.899951+0000 xctest[4660:15933] [Sentry] [debug] [SentryThreadWrapper:26] Already on main thread.
[SentryOnDemandReplay] Could not save replay frame. Error: Error Domain=NSCocoaErrorDomain Code=4 "The file “0.png” doesn’t exist." …
```
> fix: Stop SessionReplay when closing SDK

- Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackerTests.swift
- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
- Tests/SentryTests/SentryScopeSwiftTests.swift
Performance unit tests require baseline profiles bound to an exact machine configuration, which we can't generate for CI. Thus, the performance tests run without any benefit in CI. We can remove them with this PR.
> test: Remove unit test performance tests

- CHANGELOG.md
- Sources/Sentry/SentryTracer.m
The pr https://github.com/getsentry/sentry-cocoa/pull/3929 introduced a bug that happens when Sentry is added with cocoapod, by exposing a Test file during debug, but this file is not available for cocoapod.
Sample
> fix: 'SentryFileManager+Test.h' file not found

- Tests/SentryTests/SentryViewHierarchyTests.swift
The SentryViewHierarchyTests only need to reset the SentryDependencyContainer and not reset the whole global test state.
> test: Remove clearTestState for ViewHierarchyTests

- CHANGELOG.md
- scripts/build-xcframework.sh
The hacky solution introduced in the PR https://github.com/getsentry/sentry-cocoa/pull/3774 is breaking compilation for Xcode 15.4
This solution will keep both Xcode 15 (.3 and .4) working.
I believe we can remove the version replacement after a few months after Xcode 15.4 release.
closes #3947
Samples
> fix: Clang error for Xcode 15.4

- Tests/Perf/metrics-test.yml
Our SDK got bigger because we added plenty of new features. 700 KiB is still acceptable.
> ci: Increase benchmark binary size max

- CHANGELOG.md
- Sources/Sentry/SentrySDK.m
- Tests/SentryTests/SentrySDKTests.swift
Fix a deadlock when two threads access SentrySDK.options and SentrySDK.currentHub, which used the same object in synchronized. This problem is fixed now by using two independent locks for SentrySDK.options and SentrySDK.currentHub.
Fixes GH-3956, Fixes GH-3899
Unit tests and as explained in https://github.com/getsentry/sentry-cocoa/issues/3956.
> fix: Potential deadlock when starting the SDK

- SentryTestUtils/Invocations.swift
Using the barrier flag with the concurrent attribute is similar to using a serial dispatch queue, so we can use a serial dispatch queue instead to simplify the syntax.
> test: Use serial dispatch queue for invocations

- Gemfile.lock
> chore: bump sentry-fastlane from 1.15.0 to 1.22.1

- Sources/Sentry/SentryProfileTimeseries.mm
In #3932, this line of code got accidentally removed. I'm not sure if this codepath is ever actually taken. It's not currently covered in tests; to be honest the mocking around GPU timestamps is a mess, and I haven't been able to untangle it to get this particular codepath covered. I hope to make more progress on that in #3985.
But I would like to get this merged before any release goes out, in case something would actually break.
#skip-changelog, for #3555
> fix(profiling): put back the missing insertion of initial frame rate

- Sources/Sentry/SentryFramesTrackingIntegration.m
- Sources/Sentry/include/SentryFramesTrackingIntegration.h
Remove not needed stop method.
Came up while investigating https://github.com/getsentry/sentry-cocoa/issues/3700.
> ref: FramesTrackingIntegration remove stop

- Samples/iOS-Swift/iOS-Swift-UITests/ProfilingUITests.swift
- Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
- Samples/iOS-Swift/iOS-Swift/Profiling/ProfilingViewController.swift
- Samples/iOS-Swift/iOS-Swift/Tools/iOS-Swift-Bridging-Header.h
- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/Profiling/SentryContinuousProfiler.mm
- Sources/Sentry/Profiling/SentryProfilerTestHelpers.m
- Sources/Sentry/SentryProfiler.mm
- Sources/Sentry/include/SentrySDK+Private.h
- Tests/SentryProfilerTests/SentryAppLaunchProfilingTests.swift
- Tests/SentryProfilerTests/SentryContinuousProfilerTests.swift
- Tests/SentryProfilerTests/SentryProfileTestFixture.swift
- Tests/SentryProfilerTests/SentryTraceProfilerTests.swift
Aiming to maximize code coverage of the code that's been added for continuous profiling, alongside the minimal tests added along the way.
for #3555; #skip-changelog
> test(profiling): more tests for continuous profiling

- CHANGELOG.md
- Samples/macOS-Swift/macOS-Swift/Base.lproj/Main.storyboard
- Samples/macOS-Swift/macOS-Swift/CppSample.cpp
- Samples/macOS-Swift/macOS-Swift/CppSample.hpp
- Samples/macOS-Swift/macOS-Swift/CppWrapper.h
- Samples/macOS-Swift/macOS-Swift/CppWrapper.m
- Samples/macOS-Swift/macOS-Swift/ViewController.swift
- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp
I have added custom calls that can be later used by Unity SDK for capturing C++ exceptions on iOS.
Also, when the current exception is NULL (during the std::terminate call) the sentrycrashsc_initSelfThread call is made to enrich the stack trace.
The fix is related to this [issue](https://github.com/getsentry/sentry-unity/issues/1628).
I have added the code to the Unity SDK that calls these new exposed functions using the dlsym search:
> Expose custom cxa throw and rethrow calls to Unity

- CHANGELOG.md
- Sources/Sentry/SentryClient.m
- Tests/SentryTests/SentryClientTests.swift
Replaced source of truth for app state from `SentryAppStateManager` instance to `SentryUIApplication`.
This change is required since it's sending wrong value to for all events in an UIKit application.
This PR fixes #3991 
Existing unit tests pass
> fix: Use proper application state before sending an event

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Sources/Sentry/Public/SentryDefines.h
- Sources/Sentry/Public/SentryOptions.h
- Sources/Sentry/SentryOptions.m
- Sources/Sentry/SentryScreenshotIntegration.m
- Tests/SentryTests/Integrations/Screenshot/SentryScreenshotIntegrationTests.swift
- Tests/SentryTests/SentryOptionsTest.m
Add a callback to the options to decide if the SDK should capture a screenshot or not.
PR for updating the docs: https://github.com/getsentry/sentry-docs/pull/10152.
Fixes GH-3137
> feat: Add beforeCaptureScreenshot Callback

- CHANGELOG.md
- Sources/Sentry/SentrySessionReplay.m
- Sources/Swift/Integrations/SessionReplay/SentryReplayVideoMaker.swift
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayTests.swift
Session replay used to have a hardcoded video size. Now it gets from the window size
Unit test
> Fix: Session replay video size

- CHANGELOG.md
- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/SentryBaggage.m
- Sources/Sentry/SentryNetworkTracker.m
- Sources/Sentry/SentrySerialization.m
- Sources/Sentry/include/SentrySerialization.h
- Sources/Swift/Helper/SentryBaggageSerialization.swift
- Sources/Swift/Helper/SentrySwiftSerialization.swift
- Tests/SentryTests/Helper/SentryBaggageSerializationTests.swift
- Tests/SentryTests/Helper/SentrySerializationTests.swift
The baggageEncodedDictionary method sometimes crashes with a null pointer exception in CFCharacterSetAddCharactersInString. It seems mutableCopy of NSCharacterSet.alphanumericCharacterSet or when calling stringByAddingPercentEncodingWithAllowedCharacters sometimes doesn't work. Instead of trying to fix the underlying issue of a null pointer exception, we can convert the code to Swift, which is designed for safety to avoid such mistakes. This should prevent the crash.
This is a frequent crash in our [internal SDK crash detection](https://sentry.sentry.io/issues/4688158870/?project=4505469596663808&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=6).
Unit tests.
> fix: Crash in baggageEncodedDictionary

- Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme
- SentryTestUtils/ClearTestState.swift
- Sources/Sentry/Profiling/SentryContinuousProfiler.mm
- Sources/Sentry/Profiling/SentryProfilerSerialization.mm
- Sources/Sentry/Profiling/SentryTraceProfiler.mm
- Sources/Sentry/SentryProfiler.mm
- Sources/Sentry/SentrySpan.m
- Sources/Sentry/SentrySpanContext.m
- Sources/Sentry/include/SentryContinuousProfiler.h
- Tests/SentryTests/SentryCrash/CrashReport.swift
- Tests/SentryTests/Transaction/SentrySpanTests.swift
The last piece of the puzzle is to include any continuous profiling session IDs in span serialized payloads so they can be linked in the backend.
for #3555; #skip-changelog
> feat(profiling): include continuous profile IDs in spans

- Tests/SentryTests/Integrations/Breadcrumbs/SentryBreadcrumbTrackerTests.swift
Fixing testAppLifeCycleBreadcrumbForSessionReplay and testTouchBreadcrumbForSessionReplay test
> Fix: Breadcumb converter tests

- .github/workflows/lint.yml
- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Sources/Sentry/Public/SentryOptions.h
- Sources/Sentry/SentryCrashIntegration.m
- Sources/Sentry/SentryOptions.m
- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_Signal.c
- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_Signal.h
- Sources/SentryCrash/Recording/Tools/SentryCrashSignalInfo.c
- Tests/SentryTests/SentryOptionsTest.m
We added support for SIGTERM reporting in the last release and enabled it by default. For some users, SIGTERM events were verbose and not actionable. Therefore, we disable it per default.
Fixes GH-4013
Options via unit test. The signal handling installation manually with log messages cause this code isn't testable at all at the moment, and I don't think we should change that by adding a simple boolean check.
> feat: Disable SIGTERM reporting by default

- CHANGELOG.md
- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/include/SentryLog.h
- Tests/SentryTests/Helper/SentryLogTestHelper.h
- Tests/SentryTests/Helper/SentryLogTestHelper.m
- Tests/SentryTests/Helper/SentryLogTests.swift
- Tests/SentryTests/SentryTests-Bridging-Header.h
Skip evaluating log messages the SDK doesn't log. The SDK now only evaluates log messages when it's actually logging the log message. Previously, the SDK evaluated all log messages regardless of the log level. This improves the overall SDK performance slightly.
This came up when investigating https://github.com/getsentry/sentry-cocoa/issues/3341. Some [SDK crashes](https://sentry.sentry.io/issues/4734720113/?project=4505469596663808&query=is%3Aunresolved+addbreadcrumb&referrer=issue-stream&sort=user&statsPeriod=30d&stream_index=1) are caused by allocating memory for the string for a log message when adding a breadcrumb. This specific SDK crash happens mostly on lower-end devices / older iPhones.
```
NSMallocException
Exception Type: EXC_CRASH (SIGABRT)
Thread 0 Crashed:
0   CoreFoundation …
```
> impr: Skip evaluating log messages when not logged

- CHANGELOG.md
- Sources/Sentry/SentryScope.m
- Sources/Sentry/SentrySessionReplay.m
- Sources/Sentry/include/SentryScope+Private.h
- Tests/SentryTests/SentryScopeSwiftTests.swift
- Tests/SentryTests/SentryScopeTests.m
Adding breadcrumbs was O(n) because the SDK used removeObjectAtIndex:0 when reaching the max breadcrumb amount, which requires reshifting the whole array. Now, we use a ring buffer making adding breadcrumbs O(1).
Should fix GH-3341.
Unit tests.
> impr: Speed up adding breadcrumbs

- Samples/iOS-Swift/iOS-Swift-UITests/LaunchUITests.swift
When running the testCheckTotalFrames, sometimes a few slow frames occur, which reduces the number of total frames, leading to the failure of the tests. Now, the test adds a buffer for slow frames to reduce some flakiness.
> tests: Add a slow frame buffer to totalFrames test

- Sources/Sentry/Profiling/SentryProfilerSerialization.mm
- Sources/Sentry/Profiling/SentryProfilerTestHelpers.m
- Sources/Sentry/include/SentryProfilerTestHelpers.h
Only write the test profile when the serialization succeeds. We had crashes in UI tests when trying to write empty serialized profile data, because the SENTRY_CASSERT failed. This PR avoids creating the profile paths and file when there is nothing to write.
I could reproduce the problem by running `TopViewControllerTests` locally. Now, the tests run smoothly.
The UI tests here failed because of other problems fixed with https://github.com/getsentry/sentry-cocoa/pull/4033.
> tests: Write test profile only when data exists

- CHANGELOG.md
- Sources/Sentry/SentryScope.m
- Tests/SentryTests/SentryScopeSwiftTests.swift
The SentryScopeTest.testModifyingFromMultipleThreads was failing frequently in CI, because of some threading issues introduced with #4029. This is fixed now by not swapping the array reference and other minor improvements.
`SentryScopeTest.testModifyingFromMultipleThreads` was failing frequently in CI.
Running the `SentryScopeTest.testModifyingFromMultipleThreads` locally.
> fix: Scope addCrumb threading issues

- Sources/Sentry/PrivateSentrySDKOnly.mm
- Sources/Sentry/SentryAppStartMeasurement.m
- Sources/Sentry/include/HybridPublic/PrivateSentrySDKOnly.h
- Sources/Sentry/include/HybridPublic/SentryAppStartMeasurement.h
- Tests/SentryTests/PrivateSentrySDKOnlyTests.swift
- Tests/SentryTests/Protocol/TestData.swift
- Tests/SentryTests/SentryCrash/CrashReport.swift
This PR adds a new method to the HybridSDKs interface which returns serializable app start data including span structures.
This can be used in Flutter (replacing current custom impl), React Native and other hybrid SDKs like Unity, Capacitor and others.
- https://github.com/getsentry/sentry-react-native/issues/3445
unit tests
> feat(internal): Add serialized app start measurements getter with spans for Hybrid SDKs

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Sentry.xcodeproj/project.pbxproj
- Sources/Swift/Integrations/SessionReplay/SentryReplayOptions.swift
- Tests/SentryTests/Integrations/SessionReplay/SentryReplayOptionsTests.swift
Added replay quality option.
We have 3 alternatives: low, medium, high.
- Low: 80% size scale, 20000 bps
- Medium: 100% size scale, 40000 bps
- High: 100% size scale, 60000 bps
Unit test, sample
> feat: Add Replay quality option

- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/SentrySpan.m
- Sources/Sentry/SentryTransaction.m
- Sources/Sentry/include/SentrySpan+Private.h
- Tests/SentryTests/Transaction/SentrySpanTests.swift
- Tests/SentryTests/Transaction/SentryTransactionTests.swift
Following along with #4009 , we also need the profile ID in each transaction (which just takes the id already recorded by the SentrySpan additions in that last PR when creating the transaction from the trace, which uses the span's logic as it's the superclass).
for #3555; #skip-changelog
> fix(profiling): set continuous profile id in each serialized transaction at keypath contexts.trace.data.profile_id

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Samples/iOS-Swift/iOS-Swift/Tools/MetricKitManager.swift
- Sources/Sentry/Public/SentryOptions.h
- Sources/Sentry/SentryMetricKitIntegration.m
- Sources/Sentry/SentryOptions.m
- Sources/Swift/MetricKit/SentryMXManager.swift
- Tests/SentryTests/Integrations/MetricKit/SentryMetricKitIntegrationTests.swift
- Tests/SentryTests/SentryOptionsTest.m
When enableMetricKitRawPayload is enabled, the SDK adds the raw MXDiagnosticPayloads as an attachment to the converted SentryEvent.
Docs PR https://github.com/getsentry/sentry-docs/pull/10334.
It's extremely hard to debug https://github.com/getsentry/sentry-cocoa/issues/4040 without the raw payload. Furthermore, for some users, the raw MetricKit payload could be valuable.
> feat: Add enableMetricKitRawPayload

- .github/workflows/test.yml
- .github/workflows/ui-tests.yml
- scripts/ci-select-xcode.sh
[GH will deprecate the macos-11](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal) runners by the end of June 2043. We have to remove them.
> ci: Remove macos-11 runners

- CHANGELOG.md
- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp
Update SentryCrashMonitor_CPPException.cpp to include `exception`
Why is this change required? What problem does it solve?
To support compilation with Xcode 16b1.
If it fixes an open issue, please link to the issue here.
https://github.com/getsentry/sentry-cocoa/issues/4050
Building with Xcode 15.4 and Xcode 16b1
People try the fix to make sure it doesn't break builds for existing Xcode versions.
> Update SentryCrashMonitor_CPPException.cpp to include `exception`

- .github/workflows/test.yml
- Tests/SentryTests/Helper/SentryDeviceTests.mm
Pinning tvOS tests to latest stable versions.
Github added beta simulators and those were being used as `latest`.
> chore: Pinning tvOS tests

- Sources/Sentry/SentryUIViewControllerPerformanceTracker.m
- Sources/Sentry/include/SentryDelayedFramesTracker.h
Remove two unused imports in
SentryUIViewControllerPerformanceTracker
and SentryDelayedFramesTracker.
> ref: Remove unused imports

- Sources/Sentry/Profiling/SentryProfilerSerialization.mm
- Sources/Sentry/Profiling/SentryProfilerState.mm
- Sources/Sentry/SentryFramesTracker.m
- Sources/Sentry/SentryMetricProfiler.mm
After pairing up with @phacops and @Zylphrex , we identified a few changes needed to get continuous profiling chunk envelopes accepted by the backend.
- we need to use standard unix epoch instead of apple's newer reference date
- need GPU value units to be correctly stated as nanoseconds (mistakenly changed it to "milliseconds" when changing the _timestamps_ to a non-nanosecond-integer value)
- need the envelope header ID (which is also injected as the event ID) to be the same as the chunk ID 
for #3555; #skip-changelog
> fix(profiling): various fixes needed for chunk envelopes to validate

- Sources/SentryCrash/Installations/SentryCrashInstallation.h
- Sources/SentryCrash/Installations/SentryCrashInstallation.m
Noticed while investigating something in the crash reporter. None of these appear in the static call graph or via textual search.
There is a parallel version at https://github.com/getsentry/sentry-cocoa/blob/d9280eec4f311096709ba84fc6a5d04423503c6c/Sources/SentryCrash/Recording/SentryCrash.h#L141 that is actually used.
Validated that crash reports are still sent using the iOS-Swift button to test a crash and checking the dashboard.
> fix: remove dead property/accessor/setter that seem to be duplicates of that in SentryCrash

- Samples/iOS-Swift/iOS-Swift-UITests/BaseUITest.swift
- Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Samples/iOS-Swift/iOS-Swift/ExtraViewController.swift
- Sources/Sentry/Profiling/SentryProfilerSerialization.mm
- Sources/Sentry/SentryProfiler.mm
I needed to be able to easily disable other SDK features while debugging profiling network requests, so I added more launch args and environment variables to help zero in on exactly what I needed.
Also cleaned up a few that were previously added.
> test: add more schema launch args and env vars to allow selectively enabling more sdk features

- Sources/Sentry/SentryNSURLRequest.m
Noticed this while debugging some network requests: I saw this _dsn ivar that was always nil. Turns out this prop is never used, the DSN is only a method parameter used in those method impls.
> fix: remove unused DSN property in SentryNSURLRequest

- Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
We don't use Nimble for the iOS-Swift UI tests, so we can remove the package reference.
> test: Remove Nimble from iOS-Swift sample app

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
- Samples/iOS-Swift/iOS-Swift/ExtraViewController.swift
- Sources/Sentry/Public/SentrySDK.h
- Sources/Sentry/SentryANRTrackingIntegration.m
- Sources/Sentry/SentryHub.m
- Sources/Sentry/SentrySDK.m
- Sources/Sentry/include/SentryANRTrackingIntegration.h
- Sources/Sentry/include/SentryHub+Private.h
- Tests/SentryTests/Integrations/ANR/SentryANRTrackingIntegrationTests.swift
- Tests/SentryTests/SentryHubTests.swift
- Tests/SentryTests/SentrySDKTests.swift
Add two methods pauseAppHangTracking and
resumeAppHangTracking to ignore reported AppHangs.
Docs PR https://github.com/getsentry/sentry-docs/pull/10409.
Fixes GH-3472
> feat: Pause and resume AppHangTracking API

- Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
- Samples/iOS-Swift/iOS-Swift/ViewControllers/TableViewController.swift
- Samples/iOS-Swift/iOS-Swift/ViewControllers/TableViewController.xib
TableViewController is now initialized from a Nib file with an extra view. 
This is an additional test for the changes introduced in #4071.
> chore: Changed TableViewController to have a Nib file

- Sources/Sentry/PrivateSentrySDKOnly.mm
- Sources/Sentry/Public/SentryDefines.h
- Sources/Sentry/SentryCrashWrapper.m
- Sources/Sentry/SentrySessionReplay.m
- Sources/Sentry/SentrySessionReplayIntegration.m
- Sources/Sentry/include/HybridPublic/PrivateSentrySDKOnly.h
- Sources/Sentry/include/SentrySessionReplay.h
- Sources/Sentry/include/SentrySessionReplayIntegration+Private.h
- Sources/Sentry/include/SentrySessionReplayIntegration.h
- Tests/SentryTests/PrivateSentrySDKOnlyTests.swift
This exposes a define `SENTRY_TARGET_REPLAY_SUPPORTED` (there's already `SENTRY_TARGET_PROFILING_SUPPORTED` so keeping the name format) for hybrid SDKs so they don't have to copy the specific check `SENTRY_HAS_UIKIT && !TARGET_OS_VISION` which may change in the future, e.g. when replay for macOS is made available. Also, while adding this, I've noticed that some replay functions were exported & then logged a warning if replay wasn't available, while some were not exported at all (see link below for the RN PR). I've unified this so that no functions are exported for hybrid SDKs if replay is not available.
Came up in a compilation fail for RN https://github.com/getsentry/sentry-react-native/pull/3846#issuecomment-2177952419
All the original code & tests should pass. Except for tests that …
> chore: cleanup replay exports for hybrid SDKs

- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor.c
- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_AppState.c
- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp
- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_MachException.c
- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_NSException.m
- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_Signal.c
- Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m
- Sources/SentryCrash/Recording/SentryCrash.m
- Sources/SentryCrash/Recording/SentryCrashC.c
- Sources/SentryCrash/Recording/SentryCrashCachedData.c
- Sources/SentryCrash/Recording/SentryCrashReport.c
- Sources/SentryCrash/Recording/Tools/SentryCrashCPU.c
- Sources/SentryCrash/Recording/Tools/SentryCrashCPU_arm.c
- Sources/SentryCrash/Recording/Tools/SentryCrashCPU_arm64.c
- Sources/SentryCrash/Recording/Tools/SentryCrashCPU_x86_32.c
- Sources/SentryCrash/Recording/Tools/SentryCrashCPU_x86_64.c
- Sources/SentryCrash/Recording/Tools/SentryCrashDebug.c
- Sources/SentryCrash/Recording/Tools/SentryCrashFileUtils.c
- Sources/SentryCrash/Recording/Tools/SentryCrashLogger.c
- Sources/SentryCrash/Recording/Tools/SentryCrashLogger.h
- Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.c
- Sources/SentryCrash/Recording/Tools/SentryCrashMemory.c
- Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor.c
- Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_Backtrace.c
- Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_MachineContext.c
- Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_SelfThread.m
- Sources/SentryCrash/Recording/Tools/SentryCrashSysCtl.c
- Sources/SentryCrash/Recording/Tools/SentryCrashThread.c
- Sources/SentryCrash/Reporting/Filters/SentryCrashReportFilterBasic.m
This is helpful to debug crash handling, which can't be done with the debugger attached. Reading log files is easier than getting the same info out of the system console.
I removed the file-based local level definitions, so that it's completely centralized. 
Also moved the macro def that effectively switches between console and file logging to the header so that it can be used to conditionally compile the other parts that set up file-based logging. Those pieces of code have been brought back after being removed in #2440 
> fix: reimplement crash logs written to file on disk

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Sources/Sentry/Public/SentryDefines.h
- Sources/Sentry/Public/SentryOptions.h
- Sources/Sentry/SentryClient.m
- Sources/Sentry/SentryOptions.m
- Sources/Sentry/SentryTransaction.m
- Sources/Sentry/include/SentryTransaction.h
- Tests/SentryTests/SentryClientTests.swift
- Tests/SentryTests/SentryOptionsTest.m
Add a callback to drop or change spans of a transaction.
Fixes GH-4083
> feat: Add beforeSendSpan callback

- Sources/SentryCrash/Recording/Tools/SentryCrashLogger.h
I accidentally left a change that I was using to debug in this PR: https://github.com/getsentry/sentry-cocoa/commit/1e803dcc7a1d6391e8ae84b498509fe27fe7e523#diff-242aeee1da34d09c29c968f7c11e8fc2a5cd9abe5e6cd0de3334d28cb06e8744R244
This should default to None.
> fix: put crash logger default local level back to none

- Tests/SentryTests/SentryClientTests.swift
I noticed this pattern being used in https://github.com/getsentry/sentry-cocoa/pull/4110 and found it unnecessary. we can just return the value instead of requiring a closure to pass it to.
> ref(SentryClientTests): convert closure-based functions to just return their values

- Sources/SentryCrash/Installations/SentryCrashInstallation.h
- Sources/SentryCrash/Installations/SentryCrashInstallation.m
I noticed this method was unused. As it's not customer-facing, should be safe to remove it.
> ref(crash reporting): remove unused prefilter method

- Sources/Sentry/SentryScreenshotIntegration.m
This appears to have fallen out of date.
> fix: comment regarding screenshots attached to crashes

- Sources/Sentry/SentryOptions.m
- Sources/Sentry/include/SentryTracer.h
I noticed this hanging around at some point.
> ref: remove unused constant

- Tests/SentryProfilerTests/SentryTraceProfilerTests.swift
- Tests/SentryTests/Helper/SentryFileManagerTests.swift
- Tests/SentryTests/Integrations/Performance/CoreData/SentryCoreDataTrackerTest.swift
- Tests/SentryTests/Integrations/Performance/CoreData/SentryCoreDataTrackingIntegrationTest.swift
- Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerIntegrationTests.swift
- Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerTests.swift
- Tests/SentryTests/Integrations/Performance/SentryPerformanceTrackerTests.swift
- Tests/SentryTests/Integrations/SentryCrash/SentryCrashIntegrationTests.swift
- Tests/SentryTests/Integrations/WatchdogTerminations/SentryWatchdogTerminationsScopeObserverTests.swift
- Tests/SentryTests/Networking/SentryTransportFactoryTests.swift
- Tests/SentryTests/PrivateSentrySDKOnlyTests.swift
- Tests/SentryTests/Protocol/SentryClientReportTests.swift
- Tests/SentryTests/Protocol/SentryEventTests.swift
- Tests/SentryTests/Protocol/SentryExceptionTests.swift
- Tests/SentryTests/Protocol/SentryGeoTests.swift
- Tests/SentryTests/Protocol/SentryMeasurementUnitTests.swift
- Tests/SentryTests/Protocol/SentryMechanismMetaTests.swift
- Tests/SentryTests/Protocol/SentryMechanismTests.swift
- Tests/SentryTests/Protocol/SentryThreadTests.swift
- Tests/SentryTests/Protocol/SentryUserTests.swift
- Tests/SentryTests/SentryCrash/CrashReport.swift
- Tests/SentryTests/SentryHubTests.swift
- Tests/SentryTests/SentrySDKTests.swift
- Tests/SentryTests/SentryScopeSwiftTests.swift
- Tests/SentryTests/SentrySessionTests.swift
- Tests/SentryTests/Transaction/SentrySpanTests.swift
- Tests/SentryTests/Transaction/SentryTracerTests.swift
- Tests/SentryTests/Transaction/SentryTransactionTests.swift
Helps fix #3576 
I hit one of these today so just went through and removed some easy ones. There are still almost 603 uses of the force unwrap operator and 154 unchecked array indexes in the test code after these changes.
> test: convert some test code from crashable to failable

- Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme
This test frequently hangs Xcode when I run locally, preventing the test suite from completing.
> test: disable hanging testGetCurrentThreadsWithStacktrace_WithSymbolication

- Sources/Sentry/Public/SentryOptions.h
I got a little tripped up when trying to test something related to ANRs. I didn't know it didn't work when a debugger is attached until i happened to see the console log warning. 
Figured I'd add that as well as a couple other notes for similar things.
> docs: add headerdocs notes for features we self-disable

- Sources/Sentry/SentryTransaction.m
- Tests/SentryTests/Transaction/SentryTransactionTests.swift
As part of #3555; #skip-changelog
Discovered that we were linking the profiler ID in the wrong place in the transaction payload. It should be at the location specified here: https://www.notion.so/sentry/Continuous-Profiling-SDK-design-86441dc859564a2abd9e0804f3c5deed?pvs=4#ffef96c3ab3747cc90f2db1779f5f506
Here is a transaction payload I captured after making the fix: 
[txn.json](https://github.com/user-attachments/files/16058381/txn.json)
> fix: add profiler_id to the correct contexts keypath

- .swiftlint.yml
This kept interrupting me when I was trying to create commits.
> fix: don't run swiftlint for SPM dependencies

- CHANGELOG.md
- Sources/Swift/Integrations/SessionReplay/SentrySessionReplay.swift
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayTests.swift
The frames during buffer mode were not being saved to disk.
> fix: Session replay in buffer mode not working

- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
> Chore: Use default value for `sessionTrackingIntervalMillis` in the sample

- CHANGELOG.md
- Sources/Swift/Integrations/SessionReplay/RRWeb/SentryRRWebVideoEvent.swift
Fix required for the front player.
Fixes https://github.com/getsentry/sentry/issues/74289
> fix: Session replay video duration from seconds to milliseconds

- Sources/Sentry/SentrySessionReplayIntegration.m
- Sources/Swift/Integrations/SessionReplay/SentrySessionReplay.swift
- Tests/SentryTests/Integrations/SessionReplay/SentryReplayRecordingTests.swift
Uncomment a commented code left behind for tests.
> fix: pass through captureReplay

- Sources/Swift/Integrations/SessionReplay/SentrySessionReplay.swift
The Swift 6 language module does not allow for the extraneous whitespace between the attribute name and '('.
Therefore we're removing it to adhere to the compiler.
This happens with the current Swift 6 Development Snapshot (Jul 15th) and is likely to become an issue in one of the next Xcode betas once the nightlies make it into the beta.
> Fix extraneous whitespace error in Swift 6 compiler

- CHANGELOG.md
- Sources/Swift/Integrations/SessionReplay/SentryOnDemandReplay.swift
- Tests/SentryTests/Integrations/SessionReplay/SentryOnDemandReplayTests.swift
Checks the status of the asset writer before using it.
closes #4185 
Sample and unit test
> fix: Session replay crash when writing the replay

- CHANGELOG.md
- Sources/Sentry/Profiling/SentryLaunchProfiling.m
- Sources/Sentry/Public/SentryOptions.h
- Sources/Sentry/SentryOptions.m
- Tests/SentryProfilerTests/SentryAppLaunchProfilingTests.swift
- Tests/SentryTests/SentryOptionsTest.m
Deprecating `options.enableTracing` in order to completely remove it in the next major.
Closes #4177
> chore: Deprecate options.enableTracing.

- Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
helped to try reproducing a certain customer use case
> test: add a launch flag to allow skipping the sentry initialization

- Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
> test: add env var to sample app to override default session tracking interval

- Sources/Sentry/SentryHttpTransport.m
- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
The SentryHttpTransport used a double-checked lock in flush, which isn't required because it's doubtful that somebody calls flush in a tight loop from multiple threads, and when they do, it's acceptable to block them for a bit longer.
> ref: Remove double-checked lock for flush

- .sauce/benchmarking-config.yml
- CHANGELOG.md
- Sources/Sentry/Public/SentryOptions.h
- Sources/Sentry/SentryOptions.m
- Sources/Sentry/SentryViewHierarchy.m
- Sources/Sentry/SentryViewHierarchyIntegration.m
- Sources/Sentry/include/SentryViewHierarchy.h
- Tests/SentryTests/Integrations/ViewHierarchy/SentryViewHierarchyIntegrationTests.swift
- Tests/SentryTests/SentryOptionsTest.m
- Tests/SentryTests/SentryViewHierarchyTests.swift
Added an option to choose whether to report accessibilityIdentifier with the view hierarchy.
close #4037 
Unit test
> feat: Add reportAccessibilityIdentifier option

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Sources/Sentry/Public/SentryDefines.h
- Sources/Sentry/Public/SentryOptions.h
- Sources/Sentry/SentryOptions.m
- Sources/Sentry/SentryViewHierarchyIntegration.m
- Tests/SentryTests/Integrations/ViewHierarchy/SentryViewHierarchyIntegrationTests.swift
- Tests/SentryTests/SentryOptionsTest.m
Add a callback to the options to decide if the SDK should capture a view hierarchy or not.
Related to https://github.com/getsentry/sentry-cocoa/pull/4016.
Docs PR: https://github.com/getsentry/sentry-docs/pull/10913.
Fixes GH-4004
> feat: Add BeforeCaptureViewHierarchy Callback

- Sources/Sentry/SentryFileManager.m
- Sources/Sentry/SentryMigrateSessionInit.m
- Sources/Sentry/SentryNSURLRequestBuilder.m
- Sources/Sentry/SentrySerialization.m
- Sources/Sentry/include/SentrySerialization.h
- Tests/SentryTests/Helper/SentryFileManagerTests.swift
- Tests/SentryTests/Helper/SentrySerializationTests.swift
- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
- Tests/SentryTests/Networking/SentrySpotlightTransportTests.swift
- Tests/SentryTests/Networking/SentryTransportAdapterTests.swift
Remove the error parameter for dataWithEnvelope which the method doesn't use.
> ref: Remove unused NSError in Serialization

- CHANGELOG.md
> chore: Fix typo in CHANGELOG.md

- Tests/SentryTests/Helper/SentryFileManagerTests.swift
The tests also succeed without `clearTestState`, so we can remove the extra work.
> test: Remove clearTestState in FileManagerTests

- Sources/Sentry/SentrySerialization.m
- Sources/Sentry/include/SentrySerialization.h
NS prefix belongs to Apple foundation framework.
> chore: Rename NSDataWriter to SentryDataWriter

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Sources/Sentry/SentryBaseIntegration.m
- Sources/Sentry/SentrySessionReplayIntegration.m
- Sources/Swift/Integrations/SessionReplay/SentryReplayOptions.swift
- Sources/Swift/SentryExperimentalOptions.swift
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayIntegrationTests.swift
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayTests.swift
- Tests/SentryTests/SentryOptionsTest.m
Rename session replay `errorSampleRate` property to `onErrorSampleRate`
close #4213 
> feat: Rename session replay `errorSampleRate` property to `onErrorSampleRate`

- CHANGELOG.md
- SentryTestUtils/TestDisplayLinkWrapper.swift
- SentryTestUtils/TestNSNotificationCenterWrapper.swift
- Sources/Sentry/SentryFramesTracker.m
- Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackerTests.swift
Profiling starts the frames tracker if it's not running, but the frames tracker again subscribes to the didBecomeActive and willResignActive notifications. To fix this, the start operation is a NoOp now if the frames tracker has already started. The same applies to stop.
This came up while investigating long TTID spans for a customer.
Unit tests.
> fix: Guard FramesTracker start and stop

- Sources/Sentry/SentryOptions.m
- Sources/Sentry/SentrySDK.m
- Sources/Sentry/include/SentryInternalDefines.h
- Tests/SentryTests/SentryOptionsTest.m
Disambiguated the initial value for profilesSampleRate and the default value to revert to in case of invalid configuration. Clarified the meaning of these in a few spots, including a new test.
See also https://www.notion.so/sentry/Continuous-Profiling-SDK-Options-46f8f4ce691a4fedbcc39c7f1e1e740e?pvs=4
> ref(continuous profiling): clarify initial options values

- CHANGELOG.md
- Sources/Sentry/SentryTimeToDisplayTracker.m
- Sources/Sentry/SentryUIViewControllerPerformanceTracker.m
- Sources/Sentry/include/SentryTimeToDisplayTracker.h
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryTimeToDisplayTrackerTest.swift
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerPerformanceTrackerTests.swift
Presenting a UIViewController when going to the background could lead to long-lasting TTID/TTFD spans. This is fixed now by not creating TTID/TTFD spans when the FramesTracker isn't running.
Docs PR: https://github.com/getsentry/sentry-docs/pull/10960.
A customer reported to get long lasting TTID/TTFD spans for UIViewControllers presented when the `didEnterBackgroundNotification` is posted. They do this due to privacy reasons.
Added a small sample to present an UIViewController when the `didEnterBackgroundNotification` is posted and could sometimes reproduce the problem. This PR fixes that problem. I didn't add the sample as a UITest, because it isn't reliable and this PR addresses an edge case. Furthermore, I added unit tests.
> fix: Long-lasting TTID/TTFD spans

- CHANGELOG.md
- Sources/Sentry/include/SentryInternalCDefines.h
- Tests/SentryTests/Integrations/SentryCrash/SentryCrashReportTests.swift
- Tests/SentryTests/SentryKSCrashReportConverterTests.m
The SentryInternalCDefines didn't define the SENTRY_HOST_APPLE, which led to missing mach info for crash reports, as the SentryCrashReport relies on the SENTRY_HOST_APPLE to write that info. For reference, the SentryCrashCRASH_HOST_APPLE was changed to SENTRY_HOST_APPLE in GH-4101. The problem is fixed now by defining SENTRY_HOST_APPLE in SentryInternalCDefines.
Fixes GH-4227
Unit tests and checking crash reports of a simulator.
| Before | After |
|--------|--------|
| ![CleanShot 2024-08-05 at 09 42 52@2x](https://github.com/user-attachments/assets/67be215c-49ef-4539-a66b-91203b4c4cfb) | ![CleanShot 2024-08-05 at 09 43 23@2x](https://github.com/user-attachments/assets/8eab94ac-d10c-4531-9235-9a7190ffd037) |
| ![CleanShot 2024-08-05 at 09 43 …
> fix: Missing mach info for crash reports

- CHANGELOG.md
- Sources/Sentry/include/SentryInternalCDefines.h
Fix capability checks on visionOS.
This fixes issue #4217
Crashed the visionOS sample app and verified on the console that the event was sent.
❓
> fix: Signals on visionOS

- CHANGELOG.md
- Sources/Sentry/SentryPredicateDescriptor.m
- Tests/SentryTests/SentryPredicateDescriptorTests.swift
Tenary operators can contain any type of predicate, not just comparison. Removed the force cast and called the parent method for the description.
Fixes [#3553](https://github.com/getsentry/sentry-cocoa/issues/3553)
> Don’t force cast to `NSComparisonPredicate` in TERNARY operator

- CHANGELOG.md
- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/Public/SentrySDK.h
- Sources/Sentry/SentrySDK.m
- Sources/Sentry/SentrySessionReplayIntegration.m
- Sources/Swift/Extensions/UIViewExtensions.swift
- Sources/Swift/Integrations/SessionReplay/SentryReplayOptions.swift
- Sources/Swift/Tools/SentryViewPhotographer.swift
- Sources/Swift/Tools/UIRedactBuilder.swift
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayIntegrationTests.swift
- Tests/SentryTests/UIRedactBuilderTests.swift
Added options to ReplayOptions for users to specify which classes to redact or ignore during replay. 
Also added functions to SentrySDK and a UIView extension to choose specific views to redact or ignore.
Unit tests
> feat: Add options to redact or ignore view for Replay

- Sources/Sentry/Public/SentrySDK.h
- Sources/Sentry/SentrySDK.m
#4228 broke framework building on main. I guess it was due to some merging not being taken into account.
> Fix: Build crash after merging #4228

- CHANGELOG.md
- Sources/Sentry/SentryHub.m
- Sources/Swift/Tools/UIRedactBuilder.swift
- Tests/SentryTests/SentryCrash/TestSentryCrashWrapper.h
- Tests/SentryTests/SentryCrash/TestSentryCrashWrapper.m
- Tests/SentryTests/SentryHubTests.swift
Skip enriching the scope in the hub initializer when it is nil, as enrich scope expects a non nil scope.
This came up while investigating flaky tests.
Unit tests.
> impr: Skip enriching scope when nil

- Sources/Swift/Tools/UIRedactBuilder.swift
- Tests/SentryTests/Transaction/SentryTracerTests.swift
Disable logs for SentryTracerTests
* testAddingSpansOnDifferentThread_WhileFinishing_DoesNotCrash
* testFinish_ShouldIgnoreWaitForChildrenCallback_DoesNotCrash
* testFinishAsync
because they can log around 10K log messages.
> test: Disable logs for verbose tracer tests

- CHANGELOG.md
- Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.c
Compiling `main` under Xcode 16.0 beta 5 produces the following error:
```
Missing '#include <sys/_types/_ucontext64.h>'; 'ucontext64_t' must be declared before it is used
```
This PR adds the aforementioned include.
It allows users to continue building their apps that use Sentry under Xcode 16.0 beta 5.
I compiled under Xcode 16.0 beta 5 on an arm64 Mac.
> Add include for missing ucontext64_t type

- CHANGELOG.md
- Sources/Sentry/SentryMetricProfiler.mm
- Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.c
- Sources/Swift/Tools/UIRedactBuilder.swift
Add missing synchronize block around the clear method.
I detected this problem when running the unit tests locally. We also see a couple of occurrences in our [internal SDK crash detection](https://sentry.sentry.io/issues/?project=4505469596663808&query=is%3Aunresolved+sentrymetricprofiler&referrer=issue-list&sort=user&statsPeriod=14d).
Running SentrySpanTests repeatedly. Previously the `SentrySpanTests` sometimes crashed with `EXC_BAD_ACCESS` in `SentryMetricProfiler`. Now they don't.
> fix: EXC_BAD_ACCESS in SentryMetricProfiler

- Tests/SentryTests/Integrations/Breadcrumbs/SentryBreadcrumbTrackerTests.swift
The testSkipCrumbs_WhenSenderOrTargetIsNil failed, because a connectivity crumb popped up during the test. This is fixed now by only validating that the crumbs don't contain any touch crumbs.
The test failed here https://github.com/getsentry/sentry-cocoa/actions/runs/10285151696/job/28463067103?pr=4249
```
Test Case '-[SentryTests.SentryBreadcrumbTrackerTests testSkipCrumbs_WhenSenderOrTargetIsNil]' started.
crumb: <SentryBreadcrumb: 0x60000b26a240, {
category = started;
level = info;
message = "Breadcrumb Tracking";
timestamp = "2024-08-07T13:41:11.539Z";
type = debug;
}>
[Sentry] [debug] [SentryReachability:179] Adding observer: <SentryBreadcrumbTracker: 0x6000025bd1d0>
[Sentry] [debug] [SentryReachability:181] Synchronized to add observer: <SentryBreadcrumbTracker: 0x6000025bd1d0> …
```
> test: Fix testSkipCrumbs_WhenSenderOrTargetIsNil

- Sources/Sentry/Profiling/SentryProfilerSerialization.mm
- Tests/SentryProfilerTests/SentryContinuousProfilerTests.swift
To comply with new requirements in https://github.com/getsentry/relay/pull/3882
> impr(continuous profiling): add sdk name and version to profile chunks

- CHANGELOG.md
- Sources/Sentry/SentryCrashWrapper.m
- Sources/Sentry/SentryDependencyContainer.m
- Sources/Sentry/SentrySDK.m
- Sources/Sentry/SentryUIDeviceWrapper.m
- Sources/Sentry/include/HybridPublic/SentryDependencyContainer.h
- Sources/Sentry/include/SentryUIDeviceWrapper.h
- Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.c
- Tests/SentryTests/Integrations/SentryCrash/SentryCrashIntegrationTests.swift
- Tests/SentryTests/SentrySDKTests.swift
Fix accessing UIDevice in enrich scope, which could be called on a background thread by caching the system version in the SentryUIDeviceWrapper.
Came up in https://github.com/getsentry/sentry-cocoa/issues/3836#issuecomment-2110605384 and while investigating flaky tests.
Unit tests.
> fix: Accessing UI API on bg thread in enrichScope

- .github/workflows/test.yml
- .github/workflows/ui-tests.yml
Bump Xcode 15.2 to 15.4 for jobs running on macos-14.
Xcode 15.4 is available for macos-14, see https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md.
> ci: Bump Xcode 15.2 to 15.4

- .github/workflows/test.yml
Both tvOS and macOS were using Xcode 14.3 on macos-13, which hasn't been available for a while now. So, the tests were actually running on Xcode 15.2, which uses tvOS 17.2 instead of tvOS 16 and macOS 14.2 instead of macOS 13. We never noticed this. Furthermore, I think it's not worth the computation time to run tests on these OS versions compared to the small risk of finding bugs. We run the tests on tvOS 15 and macOS 12, which should be sufficient.
> ci: Remove unit tests Xcode 14 for tvOS and macOS

- .github/workflows/ui-tests.yml
The tests keep failing in CI for no good reason. We don't act on the failures, so it's better to disable them. It's better to have a test suite that we can trust so we can take a step back when a CI job fails instead of continuing to ignore these failures.
> ci: Remove UI Address Sanitizer Tests

- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Samples/iOS-Swift/iOS-Swift/ErrorsViewController.swift
- Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.c
We plan on deprecating the existing metrics API. Therefore, we can
already remove the usages in the iOS-Swift sample app to minimize side
effects for UI tests.
> test: Remove metrics API from the iOS-Swift sample

- Sources/Sentry/Profiling/SentryProfiledTracerConcurrency.mm
- Sources/Sentry/Profiling/SentryProfilerState.mm
- Sources/Sentry/SentryFramesTracker.m
- Sources/Sentry/SentryHttpTransport.m
- Sources/Sentry/SentryNSURLRequest.m
- Sources/Sentry/SentryScreenFrames.m
Some logging I've added while debugging various things, figured I'd put them up to share, and so I don't have to rewrite them yet again in the future (some of these I've done multiple times now)
> chore: debug logging

- CHANGELOG.md
- Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m
- Sources/Swift/Integrations/SessionReplay/SentryReplayOptions.swift
Quality options was not exposed to Objc.
Sample
> feat: Add a replay quality option for Objc

- Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme
I had checked the box at some point and accidentally committed/merged it.
> chore(iOS-Swift): reenable ui tracing via scheme launch arg

- CHANGELOG.md
- Sources/Swift/Integrations/SessionReplay/SentryOnDemandReplay.swift
- Sources/Swift/Tools/UIRedactBuilder.swift
- Tests/SentryTests/UIRedactBuilderTests.swift
Subclasses of classes that should be redacted were not.
Unit tests
> fix: Session replay not redacting buttons and other non UILabel texts

- CHANGELOG.md
- Sources/Sentry/SentrySerialization.m
- Tests/SentryTests/PrivateSentrySDKOnlyTests.swift
Deserializing empty envelope with length != 0 crashes SDK during init. Unsure what the root cause (creating this kind of invalid payload) is. 
However, it seems we already had [code for that exact case](https://github.com/getsentry/sentry-cocoa/pull/4281/files?diff=split#diff-b1a03b0a05f5b53fc2dcfa9bdeebe0d6285541a37b2eb9b93733b1c2a7e5af58L199) in place but it didn't catch it because the iterator was incremented at the beginning of the loop, so the if checking for whether end of envelope is reached didn't work.
Least intrusive solution is to move incrementing to right before we use the iterator to avoid side effects.
fix GH-4280
Unit test
> fix: Crash deserializing empty envelope length>0

- CHANGELOG.md
- SentryTestUtils/TestDisplayLinkWrapper.swift
- Sources/Sentry/SentryDelayedFramesTracker.m
- Sources/Sentry/SentryFramesTracker.m
- Sources/Sentry/include/SentryDelayedFramesTracker.h
- Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackerTests.swift
Fix a race condition in the SentryFramesTracker and SentryDelayedFramesTracker that sometimes leads to frame delay durations longer than the queried interval of start and end time. This is fixed by moving the previousFrameSystemTimestamp down to the SentryDelayedFramesTracker so we can adequately synchronize it without acquiring extra locks on the main thread.
Came up while working on GH-3492.
Unit test.
> fix: Rarely reporting too long frame delays

- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/include/SentryANRTrackerV2.h
- Sources/Swift/Integrations/ANR/SentryANRTrackerV2Delegate.swift
It's always better to have more code in Swift.
> ref: Convert ANRV2Delegate to Swift

- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV2Tests.swift
Some test time out in CI. Increase the timeout a bit to avoid that.
> test: Increase timeout for ANR tests

- Sources/Sentry/SentrySerialization.m
Remove super noisy logging of serializing events.
I personally find that super noisy and I never use it. For me, it just spams the logs.
> ref: Remove logging serialized event

- Samples/iOS-Swift/iOS-Swift/Tools/TriggerAppHang.swift
- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/SentryANRTrackerV2.m
- Sources/Sentry/SentryANRTrackingIntegrationV2.m
- Sources/Sentry/include/SentryANRTrackerV2.h
- Sources/Swift/Integrations/ANR/SentryANRTrackerV2Delegate.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV2Tests.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackingIntegrationTests.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackingIntegrationV2Tests.swift
Add the logic for non-fully-blocking app hangs when the frame delay exceeds 99%. 
This PR is based on https://github.com/getsentry/sentry-cocoa/pull/4285.
This is required for GH-3492.
Running on a real device and unit tests.
> chore: Support for non-fully-blocking app hangs

- CHANGELOG.md
- Sources/Sentry/SentryFileManager.m
- Sources/Sentry/SentrySerialization.m
- Sources/Sentry/include/SentryFileManager.h
- Sources/Sentry/include/SentrySerialization.h
- Tests/SentryTests/Helper/SentryFileManagerTests.swift
- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
This reverts commit 804fd04cb28c030e74b7fbca50c995b85e8ce8ed.
Reverting #4219 to further investigation
Close #4280
> fix: Crash during SDK initialization due to corrupted envelope

- Sources/Sentry/Public/SentryOptions.h
Noticed this had been copypasta'd in https://github.com/getsentry/sentry-cocoa/pull/290
> fix(SentryOptions): correct explanation of environment

- CHANGELOG.md
- Sources/Sentry/SentrySerialization.m
- Tests/SentryTests/Helper/SentrySerializationTests.swift
Added a safe guard to prevent crashing when reading corrupted envelope
This was mentioned in #4280
Unit tests
> fix: Crash when reading corrupted envelope

- .github/file-filters.yml
Adds SentryFileManager and SentrySerialization to list of dangerous files. A recent (GH-4219) change in these files is the likely root cause of invalid envelopes that subsequently caused crashes.
n/a
> chore: Adds SentryFileManager and SentrySerialization to dangerous files

- .swiftlint.yml
I am unable to make actual use of `#colorLiteral` as it just shows a broken image (and Xcode support for them in general is very poor) 
and we don't have a need for image literals, we should just remove this rule
> fix: remove object_literal from swiftlint rules

- Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
- Samples/iOS-Swift/iOS13-Swift/Base.lproj/Main.storyboard
- Samples/iOS-Swift/iOS13-Swift/MainViewController.swift
- Samples/iOS-Swift/iOS13-Swift/SwiftUIView.swift
- Samples/iOS-Swift/iOS13-Swift/SwiftUIViewController.swift
- The files in interface builder were referencing a view controller that did not exist anymore
- Created a basic view controller with message/error/transaction calls
- Changed name of `SwiftUI` to `SwiftUIView`, so we don't clash with autogenerated `SwiftUI` prefixes
Have a working sample app which includes `SentrySwiftUI` where we can do manual tests for [#4300](https://github.com/getsentry/sentry-cocoa/issues/4300)
Run tests locally and on ci
> Fix issues with SentrySwiftUI sample app

- .github/workflows/test.yml
- .github/workflows/ui-tests.yml
- Samples/iOS-Swift/iOS-Swift-UITests/LaunchUITests.swift
- Samples/iOS-Swift/iOS-Swift-UITests/UITestHelpers.swift
`XCTAssertEqual(app.state, .runningForeground)` is flake on CI
> Fix: `testCorruptEnvelope` flakeness

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
- Sources/Swift/Tools/SentryViewPhotographer.swift
- Sources/Swift/Tools/UIRedactBuilder.swift
- Tests/SentryTests/SentryViewPhotographerTests.swift
- Tests/SentryTests/UIRedactBuilderTests.swift
A label that is outside of bounds of a view with clipBounds true is no longer being redacted.
|Screen|Before|After|
|-|-|-|
|![image](https://github.com/user-attachments/assets/d79ff780-f4c1-421e-8d7e-236446bd9ea2)|![747730062 107031 copy](https://github.com/user-attachments/assets/0fdead56-941e-4d51-9fc9-a9acae9b78f1)|![747729969 339359](https://github.com/user-attachments/assets/523969d3-eba3-4efb-9ea7-908298ff5c5e)|
Unit tests
> fix: Don't redact clipped views

- Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
- Samples/iOS-Swift/iOS-Swift/ErrorsViewController.swift
- Samples/iOS-Swift/iOS-Swift/Extensions/UIViewExtension.swift
- Samples/iOS-Swift/iOS-Swift/ExtraViewController.swift
- Samples/iOS-Swift/iOS-Swift/Profiling/ProfilingViewController.swift
- Samples/iOS-Swift/iOS-Swift/Tools/DSNDisplayViewController.swift
- Samples/iOS-Swift/iOS-Swift/Tools/DSNStorage.swift
- Samples/iOS-Swift/iOS-Swift/Tools/Toasts.swift
- Samples/iOS-Swift/iOS-Swift/TransactionsViewController.swift
- Samples/iOS-Swift/iOS13-Swift/AppDelegate.swift
I lost some time because I launched the sample app in a simulator that I'd previously changed the DSN in, and didn't realize it, wondering why I wasn't seeing data coming in for my tests.
I made it so that every main screen in the tab bar shows the current dsn, and calls out if it is overridden. I also improved the UX for changing/resetting. Including how errors are propagated and displayed.
> ref(iOS-Sample): improved DSN display/changing UX

- CHANGELOG.md
- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/SentryFileManager.m
- Sources/Sentry/include/SentryFileManager.h
- Tests/SentryTests/Helper/SentryFileManagerTests.swift
- Tests/SentryTests/Helper/SentryInvalidJSONStringTests.swift
- Tests/SentryTests/Helper/SentrySerializationNilTests.m
- Tests/SentryTests/Helper/SentrySerializationTests.swift
- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
- Tests/SentryTests/SentryTests-Bridging-Header.h
- Tests/SentryTests/TestUtils/SentryInvalidJSONString.h
- Tests/SentryTests/TestUtils/SentryInvalidJSONString.m
When the SDK tries to store an envelope and the serialization fails, it skips trying to store the envelope and handling the maximum envelope limit.
After the issue with corrupted envelope data SDK crashes https://github.com/getsentry/sentry-cocoa/issues/4280, we safeguard more edge cases when serializing and deserializing envelopes.
Unit tests.
> impr: Avoid work when storing invalid envelopes

- Tests/SentryTests/Helper/SentrySerializationTests.swift
Replace if conditions or guard statements with XCTUnwrap.
> test: Use XCTUnwrap in SerializationTests

- Samples/iOS-Swift/iOS-Swift-UITests/LaunchUITests.swift
- Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
- Samples/iOS-Swift/iOS-Swift/ErrorsViewController.swift
- Tests/SentryTests/Helper/SentrySerializationTests.swift
- Tests/SentryTests/SentrySDKTests.swift
Change the testCorruptEnvelope to a unit test instead of using a UITest. Tapping the corruptEnvelope button after v 8.33.0 doesn't even create an envelope because the writing of the envelope is atomic. The app terminates without writing an envelope. As the UITest was flaky, we instead switched to a unit test validating the underlying problem of deserializing a corrupted envelope. Furthermore, we have to ensure that the corrupted envelopes don't crash when deserializing them because we have no guarantee that our users don't modify the envelope files.
> test: Switch testCorruptEnvelope to a unit test

- Sources/SentryCrash/Recording/Tools/SentryCrashSysCtl.c
Fixing a broken link that explains a piece of code.
> chore: Fix broken link

- Sources/Sentry/SentryANRTracker.m
- Sources/Sentry/SentryANRTrackerV2.m
- Sources/Sentry/SentryANRTrackingIntegration.m
- Sources/Sentry/SentryWatchdogTerminationTrackingIntegration.m
- Sources/Sentry/include/SentryANRTracker.h
- Sources/Sentry/include/SentryANRTrackerV2.h
- Sources/Sentry/include/SentryANRTrackingIntegrationV2.h
- Sources/Swift/Integrations/ANR/SentryANRTrackerV2Delegate.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackerTests.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV2Tests.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackingIntegrationTests.swift
- Tests/SentryTests/Integrations/WatchdogTerminations/SentryWatchdogTerminationsIntegrationTests.swift
- Tests/SentryTests/SentrySDKTests.swift
Merge SentryANRTrackerDelegate and SentryANRTrackerDelegateV2 into one implementation to reduce complexity.
This is the first step in making swapping between the ANRTrackerV1 and ANRTrackerV2 easier. 
> ref: Unify ANRTrackerDelegate

- Samples/iOS-Swift/iOS13-Swift/AppDelegate.swift
Fixes an issue where DSN was not set correctly in one of the sample apps.
Looks like this was introduced with #4320.
> Fix DSN init in ios13 sample app

- CHANGELOG.md
- Sources/Resources/ThreadSanitizer.sup
- Sources/Sentry/SentryNetworkTracker.m
Speed up SentryNetworkTracker for multiple HTTP requests in parallel by removing unnecessary locks.
@brustolin, you added these locks in the past. Can you recall if there was a good reason for that, except a race condition? I just want to double-check, that we don't break anything.
This surfaced while investigating a potential slow down for a specific UIViewController when enabling the Sentry Cocoa SDK.
Running unit performance tests locally. Sadly, they don't work in CI, so adding them to the repository adds no value.
> impr: Speed up SentryNetworkTracker

- CHANGELOG.md
- Sources/Sentry/SentryInAppLogic.m
Slightly speed up the SentryInAppLogic by avoiding calls to lastPathComponent and lowercaseString in loops. Both properties require some extra work, such as iterating over the contents of the string. This is noticeable for larger apps with many images and inAppIncludes and inAppExcludes. For small apps, this doesn't make a difference.
This came up while investigating the Sentry Cocoa SDK potentially slowing down a specific UIViewController of a customer.
Unit tests still pass, and by running a performance test locally, which doesn't work in CI, so I'm not adding it.
> impr: Slightly speed up SentryInAppLogic

- Sources/Sentry/SentryInAppLogic.m
- Sources/Sentry/include/SentryInAppLogic.h
Make SentryInAppLogic.inAppExcludes internal as it's not used by any other class.
> ref: Make inAppExcludes internal

- Tests/Perf/metrics-test.yml
CI is failing because the SDK size has increased.
> Chore: Update size difference benchmark

- .github/workflows/benchmarking.yml
Remove running the benchmarks at midnight because nobody looks at the data.
> ci: Remove benchmarking schedule

- scripts/check-tooling-versions.sh
Comparing the clang versions should be != and not ==.
I got this funky error message. This PR fixes this.
```
clang-format version mismatch, expected: 19.1.1, but found: 19.1.1. Please run `make init` to update your local dev tools.
This may actually upgrade to a newer version than what is currently recorded in the lockfile; if that happens, please
commit the update to the lockfile as well.
```
> chore: Fix check tooling versions

- CHANGELOG.md
- Sources/Sentry/SentryScope.m
- Tests/SentryTests/SentryScopeSwiftTests.swift
Fix linking a crash event to an ongoing trace by skipping setting the trace context in Scope.applyToEvent for crash events.
Fixes GH-4375
I could reproduce the problem in the SwiftUI sample app with the following code in the SwiftUIApp.swift file:
```Swift
init() {
SentrySDK.start { options in
options.dsn = "https://6cc9bae94def43cab8444a99e0031c28@o447951.ingest.sentry.io/5428557"
options.debug = true
options.tracesSampleRate = 1.0
options.enableAutoPerformanceTracing = false
options.initialScope = { scope in
let user = User()
user.email = "philipp@sentry.io"
scope.setUser(user)
return scope
}
}
let t = SentrySDK.startTransaction(name: "after-crash", operation: "crash", bindToScope: true)
let child = t.startChild(operation: "hello")
DispatchQueue.global().asyncAfter(deadline: .now() + …
```
> fix: Linking ongoing trace to crash event

- .github/workflows/benchmarking.yml
Our benchmarking workflows still uses Xcode 14 that does not work with mergeable-libraries.
> chore: Bumping Xcode and SauceLab CLI for benchmarking

- .github/workflows/benchmarking.yml
- scripts/build-xcframework.sh
We broke main CI because of this.
Any change in the build script should also run benchmark workflow.
And I small improvement in performance
|before|after|
|-|-|
|![Screenshot 2024-10-03 at 17 26 25](https://github.com/user-attachments/assets/25d05365-feef-4b87-8d3c-75eff0c41cf2)|![Screenshot 2024-10-03 at 17 24 46](https://github.com/user-attachments/assets/ac5cf3d7-4d30-4cc6-86f7-0cb7e68e85c4)|
> chore: Run benchmark workflow if build script changed

- CHANGELOG.md
- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/Public/SentryOptions.h
- Sources/Sentry/SentrySubClassFinder.m
- Sources/Sentry/SentryUIViewControllerPerformanceTracker.m
- Sources/Sentry/SentryUIViewControllerSwizzling.m
- Sources/Swift/Integrations/Performance/SwizzleClassNameExclude.swift
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerPerformanceTrackerTests.swift
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerSwizzlingTests.swift
The SDK didn't exclude the RootViewController from swizzling when ignored by the option swizzleClassNameExclude. This is fixed now.
This PR is based on https://github.com/getsentry/sentry-cocoa/pull/4405.
Fixes GH-4385
Unit tests
> fix: Swizzling RootUIViewController if ignored

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/ViewControllers/SplitViewController.swift
- Sources/Sentry/SentryUIViewControllerPerformanceTracker.m
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerPerformanceTrackerTests.swift
The SDK creates a transaction when only viewDidLoad gets called for a UIViewController but doesn't create TTID/TTFD spans, leading to transactions missing TTID/TTFD data. Now, the SDK also creates TTID/TTFD spans when only viewDidLoad gets called and loadView gets skipped.
Fixes GH-4396
Unit tests and with a simulator.
| Before | Now |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/663a60ef-0df1-47ef-aa60-433dfdd7180a) [Sentry Event](https://sentry-sdks.sentry.io/performance/trace/05f1d934b0974f2aa263c0692a665247/?dataset=transactions&field=title&field=project&field=user.display&field=timestamp&field=replayId&id=18214&name=&node=txn-17530c9ea6f641dba80e4f771a6298e3&project=5428557&query=&queryDataset=transaction-like&sort=-timestamp&source=discover&statsPeriod=1h …
> fix: Add TTID/TTFD spans when loadView skipped

- scripts/build-xcframework.sh
Updated build script to only output frameworks used by our hybrid game engine SDKs
> chore: Build for Game engines

- CHANGELOG.md
- Sources/Sentry/SentryUIViewControllerPerformanceTracker.m
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerPerformanceTrackerTests.swift
According to the Apple docs, viewWillAppear should be called before the UIViewController is added to the view hierarchy. There are some edge cases, though, when this doesn't happen, and we saw customers' transactions also proofing this. Therefore, we must also report the initial display here, as the customers' transactions had spans for viewWillLayoutSubViews.
Fixes GH-4383
Unit tests
> fix: Finish TTID when viewWillAppear is skipped

- CHANGELOG.md
- Sources/Sentry/SentrySwizzle.m
- Sources/Sentry/include/HybridPublic/SentrySwizzle.h
We have a Swizzling test that was also enabled for debug, which will cause thread sanitizer to complain about data race (which probably won't happen).
Close #4432 
> fix: Data race in SentrySwizzleInfo.originalCalled

- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
When the debugger terminates an application, we receive a sigterm event in Sentry. That's way too much noise, and we can disable it.
> test: Disable sigterm reporting for iOS-Swift sample

- Sources/SentryCrash/Recording/SentryCrashC.h
The sentrycrash_reportUserException only exists in the header and isn't used anywhere. We can remove it.
> ref: Remove unused reportUserException

- CHANGELOG.md
- Sources/Sentry/SentrySerialization.m
Use unsigned integers for the indexes for accessing envelope data to eliminate the risk of negative indices.
Brought up as a nitpick by one of our customers, and it makes sense.
CI still green.
> fix: Use UInts in envelope deserialization

- CHANGELOG.md
- Sources/Sentry/SentrySessionReplayIntegration.m
- Sources/Swift/Integrations/SessionReplay/SentrySessionReplay.swift
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayTests.swift
AVFoundation video maker runs on a lower QoS than user-initiated processes, and the thread sanitizer complains about waiting for it on a higher-level thread. We are changing the QoS of our call to create video.
Reported in here: https://github.com/getsentry/sentry/discussions/74322#discussioncomment-10934816
Unit test
> Fix: Thread running at User-initiated quality-of-service for Session replay

- CHANGELOG.md
- Sources/Swift/Helper/SentryEnabledFeaturesBuilder.swift
- Tests/SentryTests/Helper/SentryEnabledFeaturesBuilderTests.swift
Add appHangTrackingV2 to the list of enabled features when the option enableAppHangTrackingV2 is enabled.
We want to know how many people use appHangTrackingV2.
Unit test.
> feat: Track usage of appHangTrackingV2

- CHANGELOG.md
The removal of the experimental API should be at the top of the release notes.
> Move API removal to the top of unreleased

- .github/workflows/ui-tests-critical.yml
iOS 18.1 is still in beta. Let's use 18.0 instead.
> ci: Run critical UI tests on iOS 18

- .github/workflows/test.yml
- .github/workflows/ui-tests-critical.yml
- .github/workflows/ui-tests.yml
- scripts/ci-select-xcode.sh
macos-12 runners will be fully unsupported by December 3rd, 2024, and are already deprecated. We have to remove them.
GH actions issue: https://github.com/actions/runner-images/issues/10721
> ci: Remove deprecated macos-12 image

- CHANGELOG.md
#4405 and #4379 are part of 8.39.0 and not 8.38.0.
> fix: Changelog for 8.38.0

- CHANGELOG.md
- Sources/Sentry/SentryHttpTransport.m
- Raise the level of an existing log statement which indicated that **all** envelope items were rate-limited, to `SENTRY_LOG_WARN`.
- Introduce a new log statement which will log a warning **each time** an envelope item has been dropped due to an exceeding rate-limit.
- ~Update `clang-formatter` to `19.1.2`~ (will be addressed in a separate PR)
- When trying to commit I've got following error:
- _`clang-format version mismatch, expected: 19.1.1, but found: 19.1.2. Please run `make init` to update your local dev tools. This may actually upgrade to a newer version than what is currently recorded in the lockfile; if that happens, please commit the update to the lockfile as well.`_
- Tried to resolve via `make init`, but then followed _`This may actually upgrade to a newer version than what …
> ref(transport): Log a warning when dropping envelopes due to rate-limiting

- Samples/iOS-Swift/iOS-Swift-UITests/LaunchUITests.swift
Removes duplicate crash recovery ui test.
After https://github.com/getsentry/sentry-cocoa/pull/4421 this test is duplicate of the crash recovery from critical ui tests.
ci
> misc(tests): Remove Crash Recovery test from non-critical UI Tests

- .github/workflows/ui-tests-critical.yml
It's flaky, as the only test from iOS 16, 17 and 18, the 17 keeps failing on XCUIServer not found.
> test(critical): Remove iOS 17

- .github/workflows/ui-tests-critical.yml
- .github/workflows/ui-tests.yml
- scripts/create-simulator.sh
- scripts/delete-simulator.sh
This PR replaces custom github action with bash scripts booting and deleting simulators. 
> test(sim): Use custom scripts to manage simulators

- CHANGELOG.md
- Sentry.xcodeproj/project.pbxproj
Expose `SentrySessionReplayIntegration-Hybrid.h` as `private`
We need this to be accessible when integrating sentry through SPM in flutter.
> Expose `SentrySessionReplayIntegration-Hybrid.h` as `private`

- CHANGELOG.md
- Sources/SentryCrash/Recording/Tools/SentryCrashFileUtils.c
Fixes [https://github.com/getsentry/sentry-cocoa/security/code-scanning/6](https://github.com/getsentry/sentry-cocoa/security/code-scanning/6)
To fix the TOCTOU race condition, we should avoid using `stat` and `open` separately. Instead, we can use the `open` function with the `O_RDONLY` flag to open the file directly and then use `fstat` to get the file status. This ensures that the file we are operating on is the same file we checked, as both operations are performed on the file descriptor.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Fix: Time-of-check time-of-use filesystem race condition

- CHANGELOG.md
- Sentry.xcodeproj/project.pbxproj
- SentryTestUtils/BreadcrumbExtension.swift
- Sources/Swift/Integrations/SessionReplay/SentrySessionReplay.swift
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayTests.swift
We create a navigation breadcrumb for every view controller that appears, but some view controllers are child view controllers and they dont represent a navigation.
Filtering out this child breadcrumbs in the session replay
Fixes https://github.com/getsentry/team-replay/issues/467
Unit tests
> fix: Too many navigation breadcrumbs for Session Replay

- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/SentrySDK.m
- Sources/Sentry/SentryUserFeedbackIntegration.m
- Sources/Sentry/include/SentryUserFeedbackIntegration.h
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackIntegrationDriver.swift
As promised regarding https://github.com/getsentry/sentry-cocoa/pull/4364#issuecomment-2370418184, move the sources to the correct location. Also taking this opportunity to rename the classes per https://github.com/getsentry/sentry-cocoa/pull/4364#discussion_r1787018390
for https://github.com/getsentry/sentry-cocoa/issues/4270
> ref(user feedback): move objc sources to correct location

- CHANGELOG.md
- Sources/Swift/Tools/UIRedactBuilder.swift
- Tests/SentryTests/UIRedactBuilderTests.swift
Labels with transparent text color get a transparent rectangle masking over. Removed the alpha component of the text color to use in the masking.
Unit tests
> fix: Masking text with transparent text color

- Sources/Sentry/SentryUIViewControllerSwizzling.m
The log messages contain the class name, so there is no need to prefix all the log messages with it.
> ref: Remove redundant log prefix in swizzling

- CHANGELOG.md
- Sources/Sentry/SentryClient.m
- Sources/Sentry/SentryDependencyContainer.m
- Sources/Sentry/SentryReachability.m
- Sources/Sentry/SentrySessionReplayIntegration.m
- Sources/Sentry/SentryTransportFactory.m
- Sources/Sentry/include/HybridPublic/SentryDependencyContainer.h
- Sources/Sentry/include/SentryTransportFactory.h
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayIntegrationTests.swift
- Tests/SentryTests/Networking/SentryTransportFactoryTests.swift
- Tests/SentryTests/Networking/SentryTransportInitializerTests.swift
Stop session replay if the app is being rate limited.
https://github.com/getsentry/team-replay/issues/496
> ref: Stops session replay if rate limiting is activated

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/ViewControllers/TableViewController.swift
- Sources/Swift/Tools/UIRedactBuilder.swift
- Tests/SentryTests/SentryViewPhotographerTests.swift
Fixed calculation of scroll view children position for masking
Unit test and sample
> fix: Session replay masking not working inside scroll view

- Sources/Sentry/Public/SentryDefines.h
- Sources/Sentry/SentrySessionReplayIntegration.m
We missed this bit in #4406.
This is based on https://github.com/getsentry/sentry-cocoa/pull/4515.
> ref: Delete unused SentryBeforeEmitMetricCallback

- CHANGELOG.md
- Sources/Sentry/SentryPropagationContext.h
- Sources/Sentry/SentryPropagationContext.m
- Sources/Sentry/SentryScope.m
- Tests/SentryTests/SentryScopeSwiftTests.swift
When cloning the scope with initWithScope, the SDK wrongly created a new propagation context instead of cloning it. This is fixe now.
I found this bug in https://github.com/getsentry/sentry-cocoa/pull/4504. This aligns with the behavior from Java: https://github.com/getsentry/sentry-java/blob/e039872d80a9a352d10e642ff630a3d905ff89d0/sentry/src/main/java/io/sentry/Scope.java#L154
Unit test.
> fix: Keep PropagationContext when cloning scope

- .github/workflows/benchmarking.yml
- Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
Fixing the certificate for the sample that we use for benchmark and TestFlight.
> Chore: Fix certificate for iOS-Swift sample

- CHANGELOG.md
- Sources/Sentry/SentryBinaryImageCache.m
- Sources/Sentry/SentrySubClassFinder.m
- Sources/Sentry/SentryUIViewControllerSwizzling.m
- Sources/Sentry/include/HybridPublic/SentryBinaryImageCache.h
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerSwizzlingTests.swift
- Tests/SentryTests/SentryBinaryImageCacheTests.swift
Xcode 16 introduces a new flag ENABLE_DEBUG_DYLIB. If this flag is enabled, debug builds of app and app extension targets on supported platforms and SDKs will be built with the main binary code in a separate “NAME.debug.dylib”. Our swizzling logic for UIViewControllers sometimes skipped swizzling the UIViewControllers in that debug.dylib binary. This is fixed now, by swizzling all matching inAppInclude binary images that the binary image cache returns and not only the first one.
A customer reported this problem.
Unit tests and sample app with Xcode 16.
> fix: Missing UIViewController traces with Xcode 16

- .github/workflows/ui-tests-critical.yml
- .github/workflows/ui-tests.yml
Xcode 16 is only available on macos-15 and not anymore on macos-14; see https://github.com/actions/runner-images/issues/10703
This fixes random can't find Xcode 16 errors, such as https://github.com/getsentry/sentry-cocoa/actions/runs/11792762676/job/32846958857
```
Run ./scripts/ci-select-xcode.sh "16.0"
xcode-select: error: invalid developer directory '/Applications/Xcode_16.0.app/Contents/Developer'
Error: Process completed with exit code 1.
```
> ci: Use macos-15 for Xcode 16

- Sources/Sentry/SentryPerformanceTracker.m
Reduce nesting in startSpanWithName by using .span instead of useSpan.
useSpan basically does the same.
https://github.com/getsentry/sentry-cocoa/blob/9854a5751cac3edac5b75aec7b68c36728269aaa/Sources/Sentry/SentryScope.m#L149-L156
This PR depends on https://github.com/getsentry/sentry-cocoa/pull/4519 cause `scope.getSpan` isn't thread-safe yet.
> ref: Reduce nesting in performance tracker

- Sources/Sentry/PrivateSentrySDKOnly.mm
- Sources/Sentry/include/HybridPublic/PrivateSentrySDKOnly.h
- Sources/Swift/Tools/SentryViewPhotographer.swift
- Sources/Swift/Tools/UIRedactBuilder.swift
- Tests/SentryTests/PrivateSentrySDKOnlyTests.swift
- Tests/SentryTests/UIRedactBuilderTests.swift
This PR adds `IgnoreWrapper` functionality to Replay Redaction logic.
Why is this needed? In RN JS we don't have access to the native view instances directly. So we create a native wrapper class which we can use from JS.
- https://github.com/getsentry/sentry-react-native/pull/4224
rn sample app, unit and integration tests
> internal(replay): Add IgnoreWrapper class for hybrid SDKs

- CHANGELOG.md
- Sources/Sentry/SentryPerformanceTracker.m
- Sources/Sentry/SentryTimeToDisplayTracker.m
- Sources/Sentry/SentryUIViewControllerPerformanceTracker.m
- Sources/Sentry/include/SentryTimeToDisplayTracker.h
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryTimeToDisplayTrackerTest.swift
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerPerformanceTrackerTests.swift
Finish the TTFD span before creating a new transaction and binding it to the scope in SentryUIViewControllerPerformanceTracker when the user doesn't call reportFullyDisplayed.
Fixes GH-4513
> fix: Finish TTFD when binding transaction to scope

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Sources/Swift/Tools/UIRedactBuilder.swift
- Tests/SentryTests/UIRedactBuilderTests.swift
Animated opacity was not being properly masked
Sample and Unit test
> Fix: Session replay opacity animation masking

- .github/workflows/build.yml
Use macos-15 for Xcode 16, cause Xcode 16 is not available on macos-14.
> ci: Fix failing macOS-SwiftUI build

- CHANGELOG.md
- Sources/Swift/Protocol/SentryId.swift
Transform SentryId into a Sendable to easily accommodate for strict concurrency
close #4545 
> ref: Make SentryId Sendable

- CHANGELOG.md
- Sources/Sentry/SentryClient.m
- Tests/SentryTests/SentryClientTests.swift
The SDK already attaches the in_foreground to events, but it didn't for transactions. This is fixed now.
Fixes GH-4559
Unit tests and [sample transaction](https://sentry-sdks.sentry.io/performance/trace/b97b7d50de1d4126bfba889ea767bfd5/?dataset=transactions&field=title&field=project&field=user.display&field=timestamp&field=replayId&id=18214&name=&node=txn-565b14d5c32c4901926d4c9948249f2a&project=5428557&query=&queryDataset=transaction-like&sort=-timestamp&source=discover&statsPeriod=1h&timestamp=1732193473&topEvents=5&yAxis=count%28%29)
> feat: Add in_foreground AppContext to transactions

- CHANGELOG.md
- Sources/Sentry/Public/SentryOptions.h
Make the performanceV2 flag stable, as it's been experimental long enough, and we didn't hear any negative feedback from customers using it.
Docs PR: https://github.com/getsentry/sentry-docs/pull/11913.
Customers frequently want to use the feature and it only confuses them when it's experimental.
It's well tested with unit tests and we didn't hear any negative feedback.
> feat: Promote performanceV2 to stable

- CONTRIBUTING.md
Explain how to promote a beta release in Contributing.md.
> chore: Explain how to promote a beta release

- Tests/SentryTests/Integrations/SessionReplay/SentryTouchTrackerTests.swift
`SentryTouchTrackerTests.testLock` is super flaky because it runs 3 long loops in parallel that use locks. For our CI with no much CPU power, this can’t finish in under a second.
I’m reducing the number of iterations. In all my tests, the reduced amount was already enough to detect the error.
> chore: Improving a flaky test.

- Brewfile.lock.json
Bump clang-format from 19.1.3 to 19.1.4,
swiftlint from 0.57.0 to 0.57.1,
pre-commit from 3.8.0 to 4.0.1,
python3 from 3.12.6 to 3.13.0_1,
maestro from 1.38.1 to 1.39.2.
> chore: Update local dev dependencies

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/ViewControllers/SRRedactSampleViewController.swift
- Sources/Swift/Tools/SentryViewPhotographer.swift
- Sources/Swift/Tools/UIRedactBuilder.swift
Speeding up mask calculation 
Samples Only
> fix: Masking for fast animations

- CHANGELOG.md
- Sources/Sentry/SentryCrashReportConverter.m
- Tests/SentryTests/SentryKSCrashReportConverterTests.m
The SDK now adds the in_foreground AppContext to crash events by retrieving this information from the application_stats of the crash report.
Fixes GH-4563
[Before](https://sentry-sdks.sentry.io/issues/6044162827/events/a1727e5be46c4bc8ab789af800942ee3/?project=5428557)
[Now](https://sentry-sdks.sentry.io/issues/4911583360/events/5a33347b088447de9cc03bf71cc3174b/?project=5428557)
> feat: Add in_foreground AppContext to crash events

- Sources/Sentry/SentrySessionReplayIntegration.m
> Chore: Session replay Log typo

- fastlane/Fastfile
Changes `sync_code_signing` in fastlane lanes to use direct branch cloning.
Workflow runs were occasionally failing due to the following error:
```
Cloning remote git repo...
If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
Checking out branch master...
fatal: a branch named 'master' already exists
```
Example: https://github.com/getsentry/sentry-cocoa/actions/runs/12154028573/job/33893118719?pr=4593#step:5:96
By directly defining the branch to clone, the branch checkout step should be skipped instead.
Created this PR to run workflows on CI.
> chore(ci): add direct branch cloning for fastlane match

- .github/workflows/release-comment-issues.yml
When a release is done the Changelog will be parsed for issue numbers. Then a comment will be added to those issues that a fix has been released.
I took this from the JS: https://github.com/getsentry/sentry-javascript/blob/develop/.github/workflows/release-comment-issues.yml 
Python also added it here https://github.com/getsentry/sentry-python/pull/3866
> chore: Comment on released issues

- Sources/Swift/Integrations/SessionReplay/SentrySessionReplay.swift
- Sources/Swift/Tools/SentryViewPhotographer.swift
- Sources/Swift/Tools/SentryViewScreenshotProvider.swift
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayTests.swift
- Tests/SentryTests/SentryViewPhotographerTests.swift
SentryViewPhotographer had an unused argument for  SentryViewPhotographer.image()
> chore: Removing unused argument

- CHANGELOG.md
- Sources/Sentry/SentrySdkInfo.m
- Tests/SentryTests/Protocol/SentrySdkInfoTests.swift
This PR fixes sdk packages which by the develop docs should be an array but was dict in cocoa.
https://develop.sentry.dev/sdk/data-model/event-payloads/sdk/
unit tests
> fix(envelope): SentrySdkInfo.packages should be an array

- Samples/iOS-Swift/iOS-Swift-UITests/UserFeedbackUITests.swift
- Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/SentryUserAccess.h
- Sources/Sentry/SentryUserAccess.m
- Sources/Sentry/include/SentryPrivate.h
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackForm.swift
also use better autocapitalization settings for the name/email fields
> feat(feedback): prefill user info in form

- Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- remove the need for most of the swiftlint toggles we had for type/function length and cyclomatic complexity
- remove a few things that just set the option to the default value
- fix some cases where the same setting was set twice
- add a launch argument to easily disable everything
- organize things with `// MARK:`: 
Food for thought: this points towards a potential enhancement to be able to configure the SDK using a plist. Wonder if customers have ever asked for it? I'm just looking at the long list of options in code and the scheme and thinking we could move that checking logic into the SDK itself.
> ref(iOS-Swift): reorganize SDK configuration

- CHANGELOG.md
- Sentry.xcodeproj/project.pbxproj
- Sources/Swift/Integrations/SessionReplay/RRWeb/SentryRRWebOptionsEvent.swift
- Sources/Swift/Integrations/SessionReplay/SentrySessionReplay.swift
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayTests.swift
Send the options used for session replay in the replay tag event.
Unit test
> feat: Show session replay options as replay tags

- CHANGELOG.md
- Sources/Swift/Tools/SentryViewPhotographer.swift
I've noticed the following crash while testing https://github.com/getsentry/sentry-react-native/pull/4328 [after upgrading to 8.42.0](https://github.com/getsentry/sentry-react-native/pull/4387) [that included the `clipPaths.removeLast()` addition](https://github.com/getsentry/sentry-cocoa/commit/114f2350b1969a0f22e2cd9b99bf8e5f99a2bb13#diff-7065ad52e9de8e634171ef82eeb8098030f9de3779b5c0afa7a006fc42847f56R85).
```
Thread 6::  Dispatch queue: io.sentry.default
...
4   libswiftCore.dylib            	       0x1930e5614 RangeReplaceableCollection<>.removeLast() + 548
5   sentryreactnativesample.debug.dylib	       0x10a1d968c closure #1 in closure #1 in SentryViewPhotographer.image(view:options:onComplete:) + 2672 (SentryViewPhotographer.swift:85)
```
Manual testing with the React Native Sample …
> Fix: Check if clipPath is empty before removing last element

- Sources/Sentry/SentryScope.m
Add a short comment to explain why we don't need to call synchronize spanLock when building the trace context in SentryScope.applyToEvent.
> ref: Add comment why no lock required in scope

- CHANGELOG.md
- Sources/Swift/Tools/SentryViewPhotographer.swift
- Sources/Swift/Tools/UIRedactBuilder.swift
- Tests/SentryTests/SentryViewPhotographerTests.swift
Fix an error where SR clipping happens in the wrong order.
Unit test
> fix: Session Redact wrong clipping order

- Sources/Sentry/SentrySessionReplayIntegration.m
- Sources/Sentry/include/HybridPublic/SentrySessionReplayIntegration-Hybrid.h
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayIntegrationTests.swift
This is a fix for hybrid SDK, where the screenshot provider and the breadcrumb converter was reverting to the default after starting a new app session, usually when the app stays too long in the background.
> Chore: Persist SR Screenshot provider and breadcrumbs converter

- CHANGELOG.md
- Sources/Sentry/SentryScope.m
Use a double checked lock for getting the span when building the trace context.
@armcknight found this.
> impr: Slightly speed up serializing scope

- Sources/Sentry/SentryUserFeedbackIntegration.m
- Sources/Sentry/include/SentryPrivate.h
- Sources/Swift/Integrations/UserFeedback/SentryFeedback.swift
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackForm.swift
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackIntegrationDriver.swift
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackWidget.swift
fixes the last build issue in #4652; #skip-changelog; for https://github.com/getsentry/sentry-cocoa/issues/4272
> fix(feedback): bubble up feedback capture to objc layer

- Samples/iOS-Swift/iOS-Swift-UITests/UserFeedbackUITests.swift
- Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
- Samples/iOS-Swift/iOS-Swift/ExtraViewController.swift
- Sources/Sentry/SentryEnvelope.m
- Sources/Sentry/SentryHttpTransport.m
- Sources/Sentry/SentryQueueableRequestManager.m
- Sources/Sentry/SentryUserFeedbackIntegration.m
- Sources/Sentry/include/SentryPrivate.h
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackForm.swift
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackIntegrationDriver.swift
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackWidget.swift
building off of #4535, tests for the new envelope we create for the feedback event; for #4272 
> test(feedback): validate envelopes

- CHANGELOG.md
- Sources/Swift/Integrations/SessionReplay/RRWeb/SentryRRWebOptionsEvent.swift
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayTests.swift
Don't add maskedViewClasses and unmaskedViewClasses when being empty.
Slightly improves the situation for https://github.com/getsentry/sentry-cocoa/issues/4666.
Unit tests.
> fix: Remove empty session replay tags

- CHANGELOG.md
Copy 8.43.0-beta.1 entries to the unreleased section for releasing 8.43.0.
> Changelog for 8.43.0

- CHANGELOG.md
With the GA of Session Replay we introduced a breaking change in the Sentry options by moving the session replay options from `experimental` to the root config. This adds a warning to the changelog.
We accepted the breaking change, as it also indicates to SDK users, that the feature is now in GA.
> docs: add breaking changes warning for session replay options to changelog

- .github/workflows/benchmarking.yml
- .github/workflows/build.yml
- .github/workflows/test.yml
- .github/workflows/ui-tests-critical.yml
- .github/workflows/ui-tests.yml
- CHANGELOG.md
Changes workflows to use Xcode 16.2 when using the macOS 15 GitHub Actions runner image.
https://github.blog/changelog/2025-01-02-actions-xcode-16-2-will-replace-xcode-16-0-in-macos-14-images/
Created the PR and waited for checks to pass.
_none_
> chore: update to Xcode 16.2 in workflows

- Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme
Flaked here: https://github.com/getsentry/sentry-cocoa/actions/runs/12748879916/job/35530125606.
> test: Disable flaky testFlush_WhenNoInternet_BlocksAndFinishes

- Sentry.xcodeproj/xcshareddata/xcschemes/Sentry.xcscheme
Flaked here: https://github.com/getsentry/sentry-cocoa/actions/runs/12748879916/job/35530125606.
> test: Disable flaky testAddFrameIsThreadSafe

- CHANGELOG.md
- Sources/Swift/Tools/SentryLog.swift
- Tests/SentryTests/Helper/SentryLogTests.swift
Introduces a new constant in `SentryLog` to configure a log level that will always be logged.
Closes #4467
I added a statement `SENTRY_LOG_FATAL(@"test")` in the SDK install code and checked if it gets printed.
_none_
> feat: add threshold to always log fatal logs

- Tests/SentryTests/Integrations/Performance/CoreData/SentryCoreDataTrackerTest.swift
- Tests/SentryTests/Integrations/Performance/CoreData/SentryCoreDataTrackingIntegrationTest.swift
- Tests/SentryTests/Integrations/Performance/CoreData/TestCoreDataStack.swift
Uses unique CoreData database names in unit tests
The current test outputs are quite noisy, mostly due to xcrun noticing issues with the test databases. See [this workflow run](https://github.com/getsentry/sentry-cocoa/actions/runs/12883706329) as an example:
- Unit iOS - Xcode 16.2 - OS 18.2 Sentry: CoreData#L1
```
(1) I/O error for database at /Users/runner/Library/Developer/CoreSimulator/Devices/2123042C-07F7-46F2-8016-FEC3B637C16C/data/Library/Caches/SingleViewCoreData.sqlite. SQLite error code:1, 'cannot rollback - no transaction is active
```
- Unit iOS - Xcode 16.2 - OS 18.2 Sentry: CoreData#L1
```
Encountered exception I/O error for database at /Users/runner/Library/Developer/CoreSimulator/Devices/2123042C-07F7-46F2-8016-FEC3B637C16C/data/Library/Caches/SingleViewCoreData.sqlite. …
```
> refactor(tests): Change database file name in CoreData tests to unique names

- Tests/Resources/fatal-error-binary-images-iphone.json
- Tests/Resources/fatal-error-binary-images-message2.json
- Tests/Resources/fatal-error-binary-images-simulator.json
- Tests/SentryTests/Integrations/Performance/IO/SentryFileIOTrackingIntegrationTests.swift
- Tests/SentryTests/SentryKSCrashReportConverterTests.m
Change the example errors `fatal error: Hello fatal\n` to `fatalX error: Hello fatal\n` to stop xcbeautify from parsing it as fatal error messages.
`xcbeautify` uses a regex to capture fatal errors in the log:
https://github.com/cpisciotta/xcbeautify/blob/87008cd2c78f7cd8735e573fa93912d4ac67f9e3/Sources/XcbeautifyLib/CaptureGroups.swift#L1543
This regex also picks up the crash converter examples:
https://github.com/getsentry/sentry-cocoa/blob/9f579537c70270d5a228bbb3bf7275161911d5eb/Tests/SentryTests/SentryKSCrashReportConverterTests.m#L309
This leads to a lot of false-positive errors logged as GitHub Action annotations:
https://github.com/getsentry/sentry-cocoa/actions/runs/12884509686
Changing the keyword `fatal` to something else, silents the logging, without changing the test case …
> refactor(tests): Change example binary message errors to silent version

- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV1Tests.swift
Increase the timeout for ANRTrackerV1 tests from 1.0 to 2.0, cause they timed out here https://github.com/getsentry/sentry-cocoa/actions/runs/12886410167/job/35926973742.
2.0 is still OK. If they still are flaky we need to disable them.
> test: Increase timeout for ANRV1 tests

- LICENSE.md
Actually, we don't need the date range, as pointed out by Michi.
In our internal [Open Source Legal Policy](https://www.notion.so/sentry/Open-Source-Legal-Policy-ac4885d265cb4d7898a01c060b061e42), we decided that licenses don't require a data range. This also has the advantage of not updating the date range yearly.
cc @gavin-zee 
> chore: Remove date range for LICENSE

- Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m
- Samples/iOS-Swift/iOS-Swift-UITests/UserFeedbackUITests.swift
- Samples/iOS-Swift/iOS-Swift.xcodeproj/xcshareddata/xcschemes/iOS-Swift.xcscheme
- Samples/iOS-Swift/iOS-Swift/SentrySDKWrapper.swift
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackFormController.swift
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackFormViewModel.swift
this has a couple simple fixes that i found i needed to make while refactoring in #4726, and wanted to keep them separate
> fix(feedback): more accessibility fixes

- CHANGELOG.md
- Samples/iOS-SwiftUI/iOS-SwiftUI/ContentView.swift
- Sources/SentrySwiftUI/SentryReplayView.swift
Adding `sentryReplayUnmask` and `sentryReplayUnmask` to a view was preventing interaction with such view.
Solved now.
Sample and UITest
> Fix: `sentryReplayUnmask` and `sentryReplayUnmask` preventing interaction

- CONTRIBUTING.md
Link to the Sentry develop docs for explaining the LOGAF scale.
> Reference LOGAF Scale from develop docs

- CHANGELOG.md
- Sources/Sentry/Public/SentryCrashExceptionApplication.h
Removed the interface for `SentryCrashExceptionApplication` when not on macOS
closes #4758 
CI
> fix: SentryCrashExceptionApplication implementation missing for non-macOS target

- Sources/Sentry/Public/SentryReplayApi.h
We already GA sentry replay and there is an API with experimental flags in it.
> chore: Removing experimental flag from SentryReplayAPI

- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV1Tests.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV2Tests.swift
The tests testClearDirectlyAfterStart,
testClearDirectlyAfterStart_FullyBlocking_NotReported sometimes failed with the started and finished invocations being greater than 1. This is fixed now by asserting the number of starts matches the number of finish invocations.
> test: Fix ANRTrackerTests.clearDirectlyAfterStart

- CHANGELOG.md
- Samples/iOS-SwiftUI/iOS-SwiftUI/ContentView.swift
- Sentry.xcodeproj/project.pbxproj
- SentrySwiftUI.podspec
- Sources/Sentry/PrivateSentrySDKOnly.mm
- Sources/Sentry/SentrySDK.m
- Sources/Sentry/SentrySessionReplayIntegration.m
- Sources/Sentry/include/HybridPublic/PrivateSentrySDKOnly.h
- Sources/SentrySwiftUI/Preview/PreviewRedactOptions.swift
- Sources/SentrySwiftUI/Preview/SentryReplayMaskPreview.swift
- Sources/SentrySwiftUI/Preview/SentryReplayMaskPreviewUIView.swift
- Sources/SentrySwiftUI/SentryInternal/SentryInternal.h
- Tests/SentryTests/SentrySDKTests.swift
Allows the user to preview how its app session replay will be masked during development.
closes #4633 
Sample
> feat: Session replay masking preview for SwiftUI

- CHANGELOG.md
- Sources/Sentry/SentryViewHierarchy.m
Add a few more logs to SentryViewHierarchy to get more insight into what the class is doing.
A customer claims that their app hangs once they enable ViewHierarchy. These debug logs can help to investigate such problems.
> impr: Add more debug logs for SentryViewHierarchy

- Sentry.xcodeproj/project.pbxproj
- Sources/Swift/Protocol/Codable/SentryRequestCodable.swift
- Tests/SentryTests/Protocol/SentryRequestTests.swift
Add Decodable/Deserializing of SentryRequest.
> feat: Deserialize SentryRequest

- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/Public/SentryBreadcrumb.h
- Sources/Sentry/SentryLevelHelper.m
- Sources/Sentry/include/HybridPublic/SentryBreadcrumb+Private.h
- Sources/Sentry/include/SentryLevelHelper.h
- Sources/Swift/Protocol/Codable/SentryBreadcrumbCodable.swift
- Tests/SentryTests/Protocol/SentryBreadcrumbTests.swift
Add Decodable/Deserializing of SentryBreadcrumb.
According to @denrase he added unknown in https://github.com/getsentry/sentry-cocoa/pull/2820 because we have this pattern also in Java and Dart. We don't have this pattern anywhere else in Cocoa. So, IMO we should either remove it for SentryBreadcrumb or also add it for all other classes. This decision shouldn't block this PR at the moment. I added an item to #4724, so we don't forget about it.
> feat: Deserialize SentryBreadcrumb

- Sentry.xcodeproj/project.pbxproj
- Sources/Swift/Protocol/Codable/SentryExceptionCodable.swift
- Tests/SentryTests/Protocol/SentryExceptionTests.swift
Add Decodable/Deserializing of SentryException.
> feat: Deserialize SentryException

- Sources/Sentry/SentryAppStateManager.m
- Sources/Sentry/SentryCrashIntegration.m
- Sources/Sentry/SentrySDK.m
- Sources/Sentry/SentrySessionCrashedHandler.m
- Sources/Sentry/SentryWatchdogTerminationLogic.m
- Sources/Sentry/SentryWatchdogTerminationTracker.m
- Sources/Sentry/include/SentryEvent+Private.h
- Sources/Sentry/include/SentrySessionCrashedHandler.h
- Sources/Sentry/include/SentryWatchdogTerminationTracker.h
Replace OOM with watchdog termination wording. We previously called the watchdog termination tracking OOM tracking, but as it turned out OOMs are just a part of watchdog terminations. There can be other reasons for watchdog terminations than OOMs.
> ref: Replace OOM wording with watchdog termination

- Sentry.xcodeproj/project.pbxproj
- Sources/Swift/Protocol/Codable/DecodeArbitraryData.swift
- Sources/Swift/Protocol/Codable/SentryCodable.swift
- Sources/Swift/Protocol/Codable/SentryEventCodable.swift
- Tests/SentryTests/Protocol/Codable/SentryDateCodableTests.swift
- Tests/SentryTests/Protocol/SentryEventTests.swift
Add a custom date encoding strategy, which supports time intervals since 1970 and ISO 8601 formatted strings.
> impr: Add date encoding strategy

- .github/workflows/ui-tests.yml
Use a large runner for one UI test job to check if the flakiness is less on large runners.
Follow up on https://github.com/getsentry/sentry-cocoa/pull/4774.
> ci: Use large runner for one UI test job

- CHANGELOG.md
- Sources/SentrySwiftUI/SentryTracedView.swift
Add a waitForFullDisplay parameter to the sentryTrace view modifier on platforms that support it, for parity with SentryTracedView.
Add a waitForFullDisplay parameter to the sentryTrace view modifier on platforms that support it
`SentryTracedView` has a `waitForFullDisplay` parameter on platforms that support it, but not the alternative `sentryTrace` view modifier. Adding this parameter gives the view modifier parity with the `View`.
Fixes https://github.com/getsentry/sentry-cocoa/issues/4787.
> feat: add waitForFullDisplay to sentryTrace view modifier

- CHANGELOG.md
Moves changes to the changelog introduced in #4761 to the correct section
> chore: moves unreleased changes to correct section

- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV2Tests.swift
Only disable the SDK logs for the specific verbose section so we still get valuable test logs for the other sections.
This will help investigate flaky ANRTracker tests.
> test: Specifically disable ANRTracker logs

- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Remove unused SentryHttpTransportTests.fixture.eventRequest property.
This came up while investigating flaky SentryHttpTransportTests tests.
> test: HttpTransport remove unused eventRequest

- .github/workflows/test.yml
- Sentry.xcodeproj/xcshareddata/xcschemes/SentrySwiftUI.xcscheme
- Sources/Sentry/include/SentryPrivate.h
- Tests/SentrySwiftUITests/SentryRedactModifierTests.swift
- Tests/SentrySwiftUITests/SentryTraceViewModelTest.swift
- scripts/xcode-test.sh
The CI is not running tests for scheme `SentrySwiftUI`.
> tests: fixed execution and compilation of SentrySwiftUI tests

- .github/workflows/build.yml
- .github/workflows/test.yml
- Makefile
- scripts/xcode-test.sh
Changes the `scripts/xcode-test.sh` to use named arguments instead of positional.
This should improve usability of the script, and reduce accidental usage errors when changing the script.
Furthermore it surfaced that the 7th argument `${{ matrix.scheme }}` is actually used as the `DERIVED_DATA` path, instead of the 8th argument
https://github.com/getsentry/sentry-cocoa/blob/bdd896e6bef9469b6d43891fed3df6d6bd019cb9/.github/workflows/test.yml#L188
https://github.com/getsentry/sentry-cocoa/blob/bdd896e6bef9469b6d43891fed3df6d6bd019cb9/scripts/xcode-test.sh#L11-L18
> chore(ci): refactor xcode-test from positional to named arguments

- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Finish the tracer and the child spans for the transaction envelope because they are usually finished when passed to the transaction, so we avoid potential side effects.
> test: HttpTransport finish spans for transaction

- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/SentryFileManager.m
- Sources/Sentry/include/SentryFileManager.h
- Sources/Swift/Protocol/Codable/SentryEventDecoder.swift
- Tests/SentryTests/Helper/SentryFileManagerTests.swift
Add storing, reading, and deleting app hang events to the SentryFileManager.
This is a prerequisite for #4261.
> internal: Store AppHang Events

- Sources/Sentry/SentryANRTrackerV1.m
- Sources/Sentry/SentryANRTrackerV2.m
- Sources/Sentry/SentryANRTrackingIntegration.m
- Sources/Sentry/SentryWatchdogTerminationTrackingIntegration.m
- Sources/Swift/Integrations/ANR/SentryANRTrackerV2Delegate.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV1Tests.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV2Tests.swift
Measure the app hang duration for ANRTrackerV2 and report it via the delegate.anrStopped, so we can set the app hang duration in the ANRTrackingIntegration in a future PR.
Required for https://github.com/getsentry/sentry-cocoa/issues/2216.
> internal: Measure app hang duration

- SentryTestUtils/SentryLogExtensions.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV2Tests.swift
- Tests/SentryTests/Integrations/Feedback/SentryFeedbackTests.swift
- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
- Tests/SentryTests/SentrySDKTests.swift
- Tests/SentryTests/Transaction/SentryTracerTests.swift
> chore(test): use correct capitalization for function "without" "logs"

- .github/workflows/release.yml
Adds the input version to the worklfow title so we can identify it in the GitHub UI:
https://github.com/getsentry/sentry-cocoa/actions/workflows/release.yml
> chore(ci): add release version to workflow title

- CHANGELOG.md
- Sources/Sentry/SentrySession.m
- Sources/Sentry/include/SentrySession.h
- Tests/SentryTests/SentrySessionTests.swift
Add abnormal mechanism to SentrySession, which is required for reporting fatal app hangs, and the app hangs rate. This PR only adds the property, which will only be used in a follow up PR via the ANRIntegration. Currently, the property is unused.
Required for https://github.com/getsentry/sentry-cocoa/issues/3319.
Unit tests.
> internal: Add abnormal mechanism to SentrySession

- Makefile
The format-clang script picked up files in a local `Pods` folder, including `Carthage/.../*.xcarchive` directories. Both are ignored, so we should also ignore them in the Makefile.
Fixes this error:
```
Check development environment tooling versions...........................Passed
check for case conflicts.................................................Passed
check for merge conflicts................................................Passed
check for broken symlinks............................(no files to check)Skipped
check xml............................................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
detect private key.......................................................Passed
fix end of …
```
> fix: Add directory Pods and *.xcarchive to ignored paths in format-clang

- Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerTests.swift
Add tests to validate that 200-399 HTTP status codes return the log level info for crumbs, as pointed out in the develop docs: https://develop.sentry.dev/sdk/expected-features/#http-client-integrations.
Follow up  on GH-4779, came up in https://github.com/getsentry/team-sdks/issues/100#issuecomment-2624916929.
> test: 200-399 HTTP status has log level info

- .github/workflows/ui-tests.yml
Our CI stats clearly show that there isn't any benefit for stability when using xlarge runners. In fact, the flakiness rate there is the highest. See [Discover](https://sentry.sentry.io/discover/results/?dataset=transactions&display=bar&field=title&field=failure_rate%28%29&name=Cocoa&project=5899451&query=branch%3Amain%20repo%3Agetsentry%2Fsentry-cocoa%20%22ui%20tests%22&queryDataset=transaction-like&sort=-title&statsPeriod=7d&yAxis=failure_rate%28%29).
Rollback of GH-4799
> ci: Rollback xlarge runner for UI test

- CHANGELOG.md
- Sources/Sentry/Public/SentrySDK.h
- Sources/Sentry/SentrySDK.m
- Tests/SentryTests/SentrySDKTests.swift
The SDK now logs a message when you call setUser before starting the SDK.
Docs PR: https://github.com/getsentry/sentry-docs/pull/12798.
Came up here: GH-4878
Unit tests
> impr: Log message when setUser before starting SDK

- CHANGELOG.md
- Sources/Sentry/SentryFileIOTracker.m
Moves the assignment of the `ioSpan` in the `NSBlock` to the outside, as it might affect memory management. 
Note: This might also not be relevant anymore as the access to Bridged-from-Swift type `SentryTraceOrigin` is not in the block anymore.
See #4887 
Effect can not be tested reliably. Method `spanForPath` is already covered by tests.
> fix: move assignment of file IO span origin outside of block

- CHANGELOG.md
Adds a warning regarding #4887 to the Changelog, which will be copied to the release notes.
> chore: add warning related to SDK crashes

- Tests/Perf/metrics-test.yml
Fix CI by allowing bit of increase for the binary size. At some point, we need to split up the SDK into multiple modules or come up with other strategies to decrease the binary size.
> ci: Increase allowed binary size

- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/SentryCrashIntegration.m
- Sources/Sentry/SentryCrashIntegrationSessionHandler.m
- Sources/Sentry/include/SentryCrashIntegrationSessionHandler.h
Rename from SentrySessionCrashedHandler to
SentryCrashIntegrationSessionHandler, as we're going to so we can add more logic to it, which isn't only related to crashed sessions.
Required for GH-4260.
> ref: Rename SentryCrashIntegrationSessionHandler

- .github/workflows/testflight.yml
I got the TestFlight emails for the iOS-Swift sample app, which contained:
> ITMS-90725: SDK version issue - This app was built with the iOS 17.2 SDK. Starting April 24, 2025, all iOS and iPadOS apps must be built with the iOS 18 SDK or later, included in Xcode 16 or later, in order to be uploaded to App Store Connect or submitted for distribution.
We use [`macos-13`](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#installed-sdks) which only supports up to iOS 17.2. Upgrading to [`macos-14`](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#installed-sdks) satisfies the requirement to support 18.
> ci: upgrade testflight workflow macos image

- .github/workflows/testflight.yml
It occurred to me that it might be nice to have a build of iOS-Swift to play with as part of the release process.
> ci: push iOS-Swift builds to testflight for release processes

- .github/workflows/release.yml
The current change from #4844 broke parsing the workflow description because you can't access `github` in the `name` property. But you can do so in [`run-name`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#run-name)
> ci: use gha workflow property that can handle expressions

- .pre-commit-config.yaml
Changes the order of pre-commit hooks to fix formatting automatically before linting in the final step.
> chore: change order of pre-commit hooks

- Gemfile.lock
> chore(deps): bump Fastlane Sentry from 1.22.1 to 1.28.0

- CHANGELOG.md
- Sources/SentryCrash/Recording/SentryCrashReport.c
- Sources/SentryCrash/Recording/SentryCrashReportFields.h
- Sources/SentryCrash/Recording/Tools/SentryCrashDynamicLinker.c
- Sources/SentryCrash/Recording/Tools/SentryCrashDynamicLinker.h
- Tests/SentryTests/SentryBinaryImageCacheTests.swift
- Tests/SentryTests/SentryCrash/SentryCrashStackEntryMapperTests.swift
- Tests/SentryTests/SentryCrash/SentryDebugImageProviderTests.swift
Remove majorVersion, minorVersion, and revisionVersion, which the SentryCrashReport writes, but the SentryCrashReportConverter doesn't pick up, so we never send them to Sentry. Also, the SentryBinaryImageInfo that the SentryBinaryImageCache uses, doesn't access these properties. This improvement slightly reduces the size of SentryCrash reports.
Came up while investigating https://github.com/getsentry/sentry-cocoa/issues/4618.
Unit tests are still green.
> impr: Slightly reduce size of SentryCrashReports

- CHANGELOG.md
- Sources/Sentry/include/SentryThreadMetadataCache.hpp
Remove the `const` qualifier for a vector member type, which is unsupported in mainstream C++, and becomes a build error in the upcoming Xcode version.
As reported in https://github.com/getsentry/sentry-cocoa/issues/4886 and demonstrated fixed in https://github.com/getsentry/sentry-cocoa/pull/4907.
> fix: dont use unsupported const vector member type

- CHANGELOG.md
- Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.c
- Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.h
- Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext_Apple.h
As pointed out in https://github.com/getsentry/sentry-cocoa/pull/4907, we have a variable-length static array being allocated, which currently breaks in the latest Xcode beta (16.3).
Instead of hiding the issue with a pragma, this PR attempts to fix the problem. I think it was just a matter of how the code was written, since at the end of the day, it's using something that _should_ be computable at compile time: the size of a struct. We just need to rewrite the code in a way that the compiler can know that. 
I originally tried using `constexpr` on the function definition, but that requires changing lots of C code to C++ which led to a bunch of other issues.
> fix: use a static const to define array size

- Sources/Sentry/SentryPerformanceTracker.m
Remove the not required __block keyword for the newSpan variable. This is a leftover from getting the current span on the scope via a block callback, and should have been removed with https://github.com/getsentry/sentry-cocoa/pull/4520.
> ref: PerformanceTracker remove not needed __block

- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV2Tests.swift
Modify the wait timeout in SentryANRTrackerV2Tests to provide more reliable test execution by extending the timeout from 1.0 to 5.0 seconds.
> test: Increase ANR tracker test wait timeout

- .github/workflows/integration-test.yml
The path to the `.xcresult` must be absolute.
> fix(ci): Add full path to xcresult for upload artifact

- CHANGELOG.md
- Sources/Sentry/SentryTimeToDisplayTracker.m
- Sources/Sentry/SentryUIViewControllerPerformanceTracker.m
Added extra debug logs for SentryTimeToDisplayTracker and SentryUIViewControllerPerformanceTracker to have more insights on whats going on.
This will help us to investigate missing spans for `viewDidLoad` and `viewWillAppear` for a customer.
> impr: More debug logs for UIViewController tracing

- CHANGELOG.md
- Sources/Sentry/SentryTimeToDisplayTracker.m
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryTimeToDisplayTrackerTest.swift
This PR fixes wrongly finishing the TTFD span as the deadline exceeded when the user calls finishSpansIfNotFinished, and the UIViewControllerPerformanceTracker calls finishSpansIfNotFinished before a new frame gets drawn. This happened for a customer using a SplashScreenUIViewController. Now, the TimeToDisplayTracker finishes the TTFD span in finishSpansIfNotFinished when the user called finishSpansIfNotFinished.
A customer reported this bug via Slack.
Unit tests.
> fix: Correctly finish TTFD span when no new frame

- CHANGELOG.md
- Sources/Sentry/SentryUIEventTrackerTransactionMode.m
- Tests/SentryTests/Integrations/UIEvents/SentryUIEventTrackerTests.swift
Skip creating user interaction transactions that would time out without any children.
Fixes GH-2407
Unit tests
> impr: Avoid creating unnecessary UI transactions

- CHANGELOG.md
- Sources/Sentry/SentryHttpTransport.m
- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Check in the HTTPTransport if the server returns a 200 HTTP status code. Only if it does delete the envelope. If not, stop sending.
Fixes GH-4458
Unit tests
> fix: Only delete envelopes when receiving HTTP 200

- CHANGELOG.md
- Sources/Sentry/SentryScope.m
- Tests/SentryTests/SentryScopeSwiftTests.swift
- Tests/SentryTests/SentryScopeTests.m
Replaces `setExtras` to `setContext` of scope observers when removing a value from scope.
Moves existing test from Objective-C to Swift.
Fixes #2588 
> fix: Fix removing value from context not updating observer context

- CHANGELOG.md
- Sources/Sentry/SentrySdkInfo.m
- Sources/Sentry/include/SentrySdkInfo.h
- Sources/Swift/Helper/SentryEnabledFeaturesBuilder.swift
- Tests/SentryTests/Helper/SentryEnabledFeaturesBuilderTests.swift
Changes the parameter `SDKInfo.initWithOptions` to be nullable.
The options can be nullable and will throw if doing something like `options.sessionReplay.enableExperimentalViewRenderer`.
This change is required for #4940.
Added a unit test
> fix: Change parameter of SDKInfo.initWithOptions to be nullable

- CHANGELOG.md
- Sources/Sentry/SentryClient.m
- Sources/Sentry/SentryScope.m
- Tests/Perf/metrics-test.yml
- Tests/SentryTests/SentryClientTests.swift
- Tests/SentryTests/SentryHubTests.swift
- Tests/SentryTests/SentryScopeSwiftTests.swift
The client wrongly applied the scope to crash events, which wasn't a problem in most cases because applying the scope only overwrites event data such as tags, user, environment, level, and context if these properties are nil. The client no longer applies the scope to crash events to avoid setting irrelevant values.
Fixes GH-4937
Unit tests, smoke test on a simulator
This feature branch
https://sentry-sdks.sentry.io/issues/5992437707/?project=5428557&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=0
Main Branch
https://sentry-sdks.sentry.io/issues/5992437707/events/543c0f451cc64233b984df68da2970b8/?project=5428557
> fix: Wrongly applying scope to crash events

- CHANGELOG.md
> Fix Important heading in CHANGELOG.md

- CHANGELOG.md
Prettier fails on the main branch. This addresses the issue.
> chore: Changelog fix prettier lint error

- Sources/Sentry/SentryClient.m
- Sources/Sentry/SentryHub.m
- Sources/Sentry/SentryScope.m
- Sources/Sentry/SentryScreenshotIntegration.m
- Sources/Sentry/SentrySessionReplayIntegration.m
- Sources/Sentry/SentryViewHierarchyIntegration.m
- Sources/Sentry/include/SentryEvent+Private.h
- Tests/SentryTests/Integrations/Screenshot/SentryScreenshotIntegrationTests.swift
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayIntegrationTests.swift
- Tests/SentryTests/Integrations/ViewHierarchy/SentryViewHierarchyIntegrationTests.swift
- Tests/SentryTests/SentryClientTests.swift
- Tests/SentryTests/SentryHubTests.swift
- Tests/SentryTests/SentryScopeSwiftTests.swift
As the SDK handles fatal app hang events similarly to crashes, it uses isCrashEvent for fatal app hangs. Therefore, it makes sense to rename the property to isFatalEvent to communicate its purpose.
Fixes GH-4935
> ref: Rename isCrashEvent to isFatalEvent

- develop-docs/DECISIONS.md
INRE recent slack conversations and https://github.com/getsentry/sentry-cocoa/issues/3846
> meta: add decision for major-4 version support

- .pre-commit-config.yaml
The  hook prevents committing directly to the main branch, but this can be annoying for developers who use a different Git workflow. If you accidentally try to commit to main, you have to create a new branch and rerun all pre-commit checks.
Since we already enforce branch protection rules for main via GitHub, this hook adds little value while reducing flexibility. Removing it allows for a more streamlined workflow without unnecessary friction.
> chore: Remove no-commit-to-branch pre-commit

- CHANGELOG.md
- Sources/Sentry/SentryScope.m
Slightly speed up adding breadcrumbs by only serializing the breadcrumb once before passing it to the scope observers.
Came up while investigating https://github.com/getsentry/sentry-cocoa/issues/4582.
Unit tests are still green.
> impr: Slightly speed up adding breadcrumbs

- Tests/SentryTests/SentryTests.m
Add a test to ensure we don't crash when passing nil to sentry_toIso8601String.
Came up while investigating https://github.com/getsentry/sentry-cocoa/issues/4582.
> test: Add testToIso8601StringNil_ReturnsNil

- Samples/iOS-Swift/iOS-Swift-UITests/ProfilingUITests.swift
- Samples/iOS-Swift/iOS-Swift/Profiling/ProfilingViewController.swift
- Samples/iOS-Swift/iOS-Swift/SentrySDKWrapper.swift
- Sources/Sentry/Profiling/SentryContinuousProfiler.mm
- Sources/Sentry/Profiling/SentryLaunchProfiling.m
- Sources/Sentry/Profiling/SentryProfilerSerialization.mm
- Sources/Sentry/Profiling/SentryProfilerTestHelpers.m
- Sources/Sentry/include/SentryProfilerTestHelpers.h
I noticed while working on #4856 that this test wasn't functioning correctly. It's a combination of things:
- first, https://github.com/getsentry/sentry-cocoa/pull/4024 changed a launch argument in iOS-Swift that switches between trace and continuous profiling, but didn't change it in the UI test. what wound up happening is that the UI test would run a trace profile, and since trace and continuous profile chunk data were both written to the same debug file, the assertions didn't know it was looking at a trace profile when they should've been checking a continuous profile. to mitigate this in the future, i've changed `SentryProfilerTestHelperssentry_writeProfileFile` so that it either writes to `trace-profiles/` or `continuous-profiles/`.
- then, we changed the behavior of calling stop on …
> test: fix continuous launch profile test

- CHANGELOG.md
- Sources/Swift/Integrations/SessionReplay/SentryReplayOptions.swift
- Tests/SentryTests/Integrations/SessionReplay/SentryReplayOptionsTests.swift
Assigns `enableExperimentalViewRenderer`, `enableFastViewRendering` in `SentryReplayOptions` `init`
I've noticed those are always false while working on https://github.com/getsentry/sentry-react-native/pull/4660 for https://github.com/getsentry/sentry-react-native/issues/4658
Manual, Unit tests
> Fix: Assigns Experimental View Renderer options in SentryReplayOptions init

- CHANGELOG.md
Merge added changelog to wrong section
> docs: move change of #4863 to unreleased section

- Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerIntegrationTests.swift
Use XCTUnwrap in
testGetRequest_SpanCreatedAndBaggageHeaderAdded
instead of ? to get better failing asserts.
Came up while investigating flaky tests.
> test: Use XCTUnwrap in NetworkTrackerTests

- Tests/SentryTests/Helper/SentryFileManagerTests.swift
Reduce the iterations from 1000 to 100 to reduce the risk of the test expectation to time out.
The test timed out here https://github.com/getsentry/sentry-cocoa/actions/runs/13856567413/job/38774995706. The test logs didn't show anything suspicious. Maybe 3000 file IO operations are to much within 10 seconds when CI is super busy.
> test: Fewer iterations in abnormal session IO test

- .github/pull_request_template.md
We hardly ever put info for next steps. Let's remove it.
> chore: Remove next steps from pull_request_template

- SentryTestUtils/TestClient.swift
- SentryTestUtils/TestHub.swift
- Sources/Sentry/SentryClient.m
- Sources/Sentry/SentryCrashReportSink.m
- Sources/Sentry/SentryHub.m
- Sources/Sentry/SentryMetricKitIntegration.m
- Sources/Sentry/SentrySDK.m
- Sources/Sentry/SentryWatchdogTerminationTracker.m
- Sources/Sentry/include/SentryClient+Private.h
- Sources/Sentry/include/SentryHub+Private.h
- Sources/Sentry/include/SentrySDK+Private.h
- Tests/SentryTests/Integrations/ANR/SentryANRTrackingIntegrationTests.swift
- Tests/SentryTests/Integrations/Session/SentrySessionGeneratorTests.swift
- Tests/SentryTests/Integrations/Session/SentrySessionTrackerTests.swift
- Tests/SentryTests/Integrations/ViewHierarchy/SentryViewHierarchyIntegrationTests.swift
- Tests/SentryTests/Integrations/WatchdogTerminations/SentryWatchdogTerminationsTrackerTests.swift
- Tests/SentryTests/SentryClientTests.swift
- Tests/SentryTests/SentryCrash/SentryCrashInstallationReporterTests.swift
- Tests/SentryTests/SentryCrash/SentryCrashReportSinkTests.swift
- Tests/SentryTests/SentryHubTests.swift
- Tests/SentryTests/SentrySDKIntegrationTestsBase.swift
- Tests/SentryTests/SentrySDKTests.swift
The captureCrashEvent is also used to capture watchdog terminations and fatal app hangs. Therefore, we rename it to captureFatalEvent to clearly communicate it's about fatal events and not only crashes.
Fixes GH-4936
> ref: Rename captureCrashEvent to captureFatalEvent

- Sources/Sentry/SentryClient.m
- Sources/Sentry/SentryScreenshotIntegration.m
- Sources/Sentry/SentryViewHierarchyIntegration.m
- Sources/Sentry/include/SentryClient+Private.h
- Tests/SentryTests/Integrations/Screenshot/SentryScreenshotIntegrationTests.swift
- Tests/SentryTests/Integrations/ViewHierarchy/SentryViewHierarchyIntegrationTests.swift
- Tests/SentryTests/SentryClientTests.swift
Specify types for NSArrays, rename attachmentsForEvent to processAttachmentsForEvent, only pass attachments to processAttachmentsForEvent, remove not required nullable for SentryClientAttachmentProcessor.
Came up while investigating GH-4936.
> ref: Improve ClientAttachmentProcessor

- CHANGELOG.md
- Sources/Sentry/Public/SentryMessage.h
- Sources/Sentry/SentryMessage.m
- Tests/SentryTests/Protocol/SentryMessageTests.swift
Let Relay truncate the max char length. The benefit is that users see that the message was truncated.
Fixes GH-5004
Unit tests
> impr: Remove char limit of 8192 for SentryMessage

- .github/workflows/ui-tests-critical.yml
Archive the crash logs for the critical UI tests, so we know what happened when the app crashes during the test run.
> ci: Archive crash logs for UI tests critical

- Tests/SentryTests/Integrations/ANR/SentryANRTrackingIntegrationTests.swift
The feature branch didn't include the refactoring of renaming assertCrashEventWithScope to
assertFatalEventWithScope. This is fixed now.
> tests: Fix broken ANRTracking tests

- .github/workflows/ui-tests-critical.yml
Stop creating simulators, which can take around 5 minutes, and use the already installed simulators on the GH action.
> ci: Use installed simulators for critical UI tests

- .github/workflows/ui-tests.yml
Stop creating simulators which can take around 5 minutes and use the already installed simulators on the GH action.
> ci: Use installed simulators for UI tests

- Tests/SentryTests/Helper/SentryFileManagerTestExtension.swift
- Tests/SentryTests/Helper/SentryFileManagerTests.swift
- Tests/SentryTests/Integrations/Performance/IO/DataSentryTracingIntegrationTests.swift
- Tests/SentryTests/Integrations/Performance/IO/FileManagerTracingIntegrationTests.swift
- Tests/SentryTests/Integrations/Performance/IO/SentryFileIOTrackerTests.swift
- Tests/SentryTests/Integrations/Performance/IO/SentryFileIOTrackingIntegrationTests.swift
- Tests/SentryTests/Integrations/Performance/Network/SentryNetworkTrackerTests.swift
- Tests/SentryTests/Integrations/SessionReplay/SentryOnDemandReplayTests.swift
- Tests/SentryTests/Integrations/ViewHierarchy/SentryViewHierarchyIntegrationTests.swift
- Tests/SentryTests/PrivateSentrySDKOnlyTests.swift
- Tests/SentryTests/Protocol/Codable/ArbitraryDataTests.swift
- Tests/SentryTests/Protocol/Codable/NSNumberDecodableWrapperTests.swift
- Tests/SentryTests/Protocol/Codable/SentryCodableTests.swift
- Tests/SentryTests/Protocol/Codable/SentryDateCodableTests.swift
- Tests/SentryTests/Protocol/SentryAttachmentTests.swift
- Tests/SentryTests/Protocol/SentryEnvelopeTests.swift
- Tests/SentryTests/Protocol/TestData.swift
- Tests/SentryTests/SentryClientTests.swift
- Tests/SentryTests/SentrySDKTests.swift
Prefer using Data(foo.utf8) over using foo.data(using: .utf8)
As discussed in https://github.com/getsentry/sentry-cocoa/pull/5019#discussion_r2012468356. 
We can enable the SwiftLint rule [non_optional_string_data_conversion](https://realm.github.io/SwiftLint/non_optional_string_data_conversion.html)  after merging https://github.com/getsentry/sentry-cocoa/pull/5019.  
> test: Use non optional data for string to data

- .github/workflows/lint.yml
- Makefile
- Sources/Sentry/SentryDsn.m
We don't need to specify the destination and analyze with Xcode 16.2.
> chore: Remove destination for analyzer

- CHANGELOG.md
- Sources/Sentry/PrivateSentrySDKOnly.mm
- Sources/Sentry/Profiling/SentryContinuousProfiler.mm
- Sources/Sentry/Profiling/SentryProfiledTracerConcurrency.mm
- Sources/Sentry/SentrySpan.m
- Sources/Sentry/SentrySpanContext.m
- Sources/Sentry/SentryTracer.m
- Sources/Sentry/include/HybridPublic/PrivateSentrySDKOnly.h
- Sources/Sentry/include/SentryProfiledTracerConcurrency.h
Fixes a couple edge cases where bookkeeping of root spans became imbalanced for trace lifecycle in UI profiling.
> fix(profiling): ui profiling trace lifecycle root span tracking

- CHANGELOG.md
- Sources/Sentry/SentryTracer.m
- Tests/SentryTests/Transaction/SentryTracerTests.swift
Calling setMeasurement on transactions ans spans could lead to crashes. This is fixed now by making it thread safe.
A customer reported this crash and we see a few occurrences in our internal [SDK crash detection](https://sentry.sentry.io/issues/4684233446/?project=4505469596663808&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20setmeasurement&referrer=issue-stream&sort=user&stream_index=0).
Unit tests.
> fix: Make setMeasurement thread safe

- develop-docs/DECISIONS.md
Add warning to Decision Log.
Closes #4897 
> docs: add discourage use of Swift strings in ObjC to decision log

- Sources/Swift/Helper/SentryEnabledFeaturesBuilder.swift
- Tests/SentryTests/Helper/SentryEnabledFeaturesBuilderTests.swift
Adds two flags for data and file manager swizzling adoption tracking
Closes #4906
Added tests
> chore(file-io): add data and file manager swizzling to enabled features

- Sources/Sentry/PrivateSentrySDKOnly.mm
- Sources/Sentry/SentryPropagationContext.h
- Sources/Sentry/SentryPropagationContext.m
- Sources/Sentry/SentryScope.m
- Sources/Sentry/include/HybridPublic/PrivateSentrySDKOnly.h
- Sources/Sentry/include/SentryScope+Private.h
- Tests/SentryTests/PrivateSentrySDKOnlyTests.swift
- Tests/SentryTests/SentryPropagationContextTests.swift
- Tests/SentryTests/SentryScopeSwiftTests.swift
This PR allows Hybrid SDKs to explicitly set the `PropagationContext` on the scope via the `PrivateSentrySDKOnly`. 
The basic idea is that the Cocoa SDK, when brought in via a Hybrid SDK, should accept a trace from the Head SDK to connect errors on all layers of the application. This PR makes use of the fact that the Hybrid SDKs rely on their own performance instrumentation right now, allowing us to leverage the propagation context to achieve this.
Originates from the Unity SDK: https://github.com/getsentry/sentry-unity/issues/1998 
Unblocks the React Native SDK: https://github.com/getsentry/sentry-react-native/issues/3918
Mirror-PR on the Java SDK: https://github.com/getsentry/sentry-java/pull/4137
> feat: Allow Hybrid SDKs to `setTrace`

- develop-docs/README.md
Clarify to set SENTRY_ASYNC_SAFE_LOG_LEVEL to
SENTRY_ASYNC_SAFE_LOG_LEVEL_TRACE
to see all logs when crashing.
> chore: Clarify how to get logs when crashing

- CHANGELOG.md
- Sentry.xcodeproj/project.pbxproj
- Sources/SentryCrash/Recording/Tools/SentryCrashStackCursor_SelfThread.m
- Tests/SentryTests/SentryCrash/SentryCrashStackCursorSelfThreadTests.swift
- Tests/SentryTests/SentryTests-Bridging-Header.h
Use async safe logging when getting the backtrace for CPP Exceptions. When an unhandled CPPExceptions occurs, the crash monitor for CPPExceptions uses SentryCrashStackCursor_SelfThread, which uses non async safe SenryLog. This is fixed now by using async safe logging in SentryCrashStackCursor_SelfThread. Only users using debug = true or setting the log level to debug were impacted by this issue.
Came up while investigating https://github.com/getsentry/sentry-cocoa/issues/4226.
Unit tests are still green.
>  fix: Async safe log for backtrace in CPPException

- .github/workflows/build.yml
- scripts/ci-select-xcode.sh
- use `macos-15` and Xcode 16.3 for sample app build jobs (they were a mixture of older ones, but this is just to make sure they compile at all, so we should be able to use the same thing for them all, and that should be what we're all presumably using on our local machines as well)
- remove the default for the xcode version parameter in ci-select-xcode.sh: it's better to see exactly what version is being used in the workflow config files. if we were to change the default in the bash script, that change is invisible in the workflow configs. also, we didn't have any naked invocations anyways
`make session-replay-camera-test-xcode` will generate the project, although in the future we might want a small script to do this that can take some parameters like platform/version/language/UI-lib …
> ci: build sample apps on latest macOS image and Xcode version

- Makefile
The nvm setup is invalid, as the `$NVM_DIR` needs to be double-escaped like `$$NVM_DIR` otherwise it will access the env var `VM_DIR` instead.
After changing it I had issues to correctly resolve the path to the `nvm` command, therefore let's just remove it because everyone manages installed node versions differently.
> chore: remove nvm setup from make init

- .github/workflows/release-comment-issues.yml
fix build fail caused by ubuntu-20.04 retirement
> chore(CI): Update release-comment-issues.yml

- Samples/iOS-Swift/iOS-Swift.xcodeproj/project.pbxproj
While refreshing code signing certificates and provisioning profiles I noticed an inconsistency in the identifiers of `iOS-Swift-UITests` and `iOS-SwiftUITests`.
As the one with two dashes is more prominent in the repository, I removed `iOS-SwiftUITests`.
> fix: change identifier iOS-SwiftUITests to iOS-Swift-UITests

- CHANGELOG.md
- Sources/Swift/Integrations/SessionReplay/SentryOnDemandReplay.swift
- Tests/SentryTests/Integrations/SessionReplay/SentryOnDemandReplayTests.swift
Optimized compatibility of video segments created by session replay on iOS.
Due to issues with video segments taken on iOS not being playable by VLC, I went through the list of video encoding settings available in AVFoundation: https://developer.apple.com/documentation/avfoundation/video-settings
After research I ruled out the ones not applicable to our use-case. The comments should give more context on why they are chosen.
- Used the sample app to create replays and viewed them in browser.
- Used `ffprobe -v` and `VLC -vvv` to investigate detailed logs.
Example Replay Video:
https://sentry-sdks.sentry.io/explore/replays/039d49b612d245a7a85352eea4b4f425/?project=5428557&query=&referrer=%2Fexplore%2Freplays%2F%3AreplaySlug%2F&statsPeriod=1h&yAxis=count%28%29&t=18
You have to check all …
> fix(session-replay): Use wider compatible video encoding options

- CHANGELOG.md
- Sources/Swift/Integrations/SessionReplay/SentryOnDemandReplay.swift
- Tests/SentryTests/Integrations/SessionReplay/SentryOnDemandReplayTests.swift
Updated the calculation of presentation time for video frames to use integer math, ensuring frame-accurate timing and avoiding floating-point rounding issues. 
This change is crucial for maintaining consistent frame spacing, especially at low frame rates like 1 FPS.
This should also fix crashes when changing the FPS to higher values, which is not possible (yet).
- Used the sample app to run locally, viewing session replay video in Sentry product.
- Used `ffprobe` to view information on file:
```
$ ffprobe -show_streams -show_format -v error /Users/philip/Library/Developer/CoreSimulator/Devices/B406E97C-4EC0-483F-82EA-32B594AB6038/data/Containers/Data/Application/424CFD83-82C0-4765-A58C-645960512C4F/Library/Caches/io.sentry/b810aaca937def33af3796f237e6793ec907f1e4/replay/A2EF1E73-C047-48E5- …
```
> fix(session-replay): improve frame presentation timing calculations

- .github/workflows/ui-tests.yml
- fastlane/Fastfile
Noticed we aren't running UI tests on the latest toolchains.
> ci: add ui test run on macos 15 / xcode 16.3

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/SentrySDKWrapper.swift
- Sources/Swift/Integrations/SessionReplay/SentryOnDemandReplay.swift
- Tests/SentryTests/Integrations/SessionReplay/SentryOnDemandReplayTests.swift
Refactors the logic to get rendered session replay info to another method.
Furthermore it also adds more debug and error logging.
This change has been a side-product of #5018 and I extracted it into another PR for easier review.
- Unit tests & manual testing using sample.
> refactor(session-replay): add separate method to get video info with more logging

- Samples/iOS-Swift/PerformanceBenchmarks/SentrySDKPerformanceBenchmarkTests.m
PR #5104 changed the benchmarking UI test to tab the tab bar overflow item "More" to the select "Benchmarking". While this is correct for iPhone, we are running benchmarking tests with iPad where the tab bar is **not** collpased, therefore the tests will fail with this error:
```
error: Failed to tap "More" Button: No matches found for Elements matching predicate '"More" IN identifiers' from input {(
Button, label: 'Errors',
Button, label: 'Transactions', Selected,
Button, label: 'Extra',
Button, label: 'Profiling',
Button, label: 'Benchmarking',
Button, label: 'Features'
)}}
```
Looking at the error, the PR actually got merged even though the workflow checks indicated [here](https://github.com/getsentry/sentry-cocoa/actions/runs/14522145712/job/40745594880#step:6:50) that the tests …
> fix(ci): add existence check for Benchmarking tab bar item

- .github/workflows/benchmarking.yml
This PR intends to make sure the step "Run Benchmarks in SauceLab" is actually showing up as failing when failing.
Reference: https://github.com/getsentry/sentry-cocoa/actions/runs/14522145712/job/40745594880#step:5:234
- [This run](https://github.com/getsentry/sentry-cocoa/actions/runs/14663965563/job/41154651595) shows how it looks like if the first attempt fails (step "Run benchmark" is marked ❌), but a retry is detected and run again.
- [This run](https://github.com/getsentry/sentry-cocoa/actions/runs/14659838641/job/41141946259) shows how it looks like when it fails without a retry.
- [This run](https://github.com/getsentry/sentry-cocoa/actions/runs/14664182495/job/41155643996?pr=5136) shows how it looks like if the checks are fine (no retry attempted).
> fix(ci): change failing saucelabs step to marked as failed

- CHANGELOG.md
- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/SentryANRTrackerV1.m
- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV1IntegrationTests.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV1Tests.swift
Use an atomic_bool to fix race conditions for accessing reported in the ANRTrackerV1.
Fixes GH-2508
With testWithActualDispatchQueueAndThreadWrapper locally having the thread sanitizer enabled.
> fix: Race condition in ANRTrackerV1

- .github/workflows/changes-in-high-risk-code.yml
Remove previous commnents to avoid this noisy iteration:
> ci: when commenting about dangerous files, remove previous comments

- CHANGELOG.md
- Sources/Sentry/Public/SentryOptions.h
Remove the experimental warning for enableAppHangTrackingV2.
> feat: Make app hangs V2 GA

- .github/workflows/benchmarking.yml
Switch to a non xl runner for benchmarking cause it's not required and xl runners are expensive.
> ci: Use non xl macos-15 for benchmarks

- .github/workflows/build.yml
Replace the xlarge runner with macos-15 and compile the XCFramework on Xcode 16.3.
If this works fine, we can also consider replacing https://github.com/getsentry/sentry-cocoa/blob/500abd8a216eb7e05a4a3383039c79a84998d71b/.github/workflows/release.yml#L19 but I think we should do that in a minor release and not a bugfix.
> ci: Build XCFramework with Xcode 15.2 on macos-14

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/SentrySDKWrapper.swift
- Sources/Swift/Integrations/SessionReplay/SentryOnDemandReplay.swift
- Tests/SentryTests/Integrations/SessionReplay/SentryOnDemandReplayTests.swift
Changes the session replay video segment keyframe interval to 1.
H.264 uses different types of frames:
- `I‑frames` are the least compressible but don't require other video frames to decode.
- `P‑frames` can use data from previous frames to decompress and are more compressible than I‑frames.
In #5134 we introduced a change in the video segment configuration to only use `I-Frame` by setting `AVVideoMaxKeyFrameIntervalKey` to increase (browser) compatibility.
Further testing surfaced now that the browser compatibility is not affected by this option, but it increases the file size of video segments:
```
$ ffprobe -select_streams v:0 -show_frames -show_entries frame=pict_type,coded_picture_number -of csv -hide_banner pre-5134.mp4
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'older.mp4':
Metadata: …
```
> fix(session-replay): revert max key-frame interval to once per video segment

- CHANGELOG.md
- Sources/Sentry/SentrySessionReplaySyncC.c
Fix a veracode security scan warning by more explicitly checking the return value of malloc for NULL.
Fixes GH-4428
> impr: Explicitly check malloc result for SRSync

- Samples/SessionReplay-CameraTest/Sources/AppDelegate.swift
- Samples/SessionReplay-CameraTest/Sources/Base.lproj/Main.storyboard
- Samples/SessionReplay-CameraTest/Sources/ViewController.swift
Adds a toggle switch to the camera sample app to disable Sentry SDK after it started.
I use this to see how well the SDK is cleaned up to fix #5069
Can also be used for #5124 
This is a side-product so it's a different PR for easy review, extracted from draft PRs
> chore: add toggle to enable/disable Sentry in sample on-demand

- CHANGELOG.md
- Samples/iOS-Swift/iOS-Swift/SentrySDKWrapper.swift
- Sources/Sentry/SentryReplayApi.m
- Sources/Sentry/SentrySessionReplayIntegration.m
- Sources/Sentry/SentrySessionReplaySyncC.c
- Sources/Swift/Integrations/SessionReplay/SentryOnDemandReplay.swift
- Sources/Swift/Integrations/SessionReplay/SentryPixelBuffer.swift
- Sources/Swift/Integrations/SessionReplay/SentryReplayType.swift
- Sources/Swift/Integrations/SessionReplay/SentrySessionReplay.swift
- Sources/Swift/Integrations/SessionReplay/SentryTouchTracker.swift
Adds debug logging to session replay integration.
It must become easier to debug issues with the integration.
I tried to add only relevant information for SDK users trying not to produce spam-like amount of logs.
Ran sample app in iOS simulator, looked at logs.
> chore(session-replay): Add detailed debug logging for session replay

- .github/file-filters.yml
- .github/workflows/changes-in-high-risk-code.yml
- Adds the `changes-in-high-risk-code.yml` to the list of risky files to make sure the action is executed when changing the workflow too
- Uses the `comments.data` instead of `comments`. See [this workflow run](https://github.com/getsentry/sentry-cocoa/actions/runs/14859106773/job/41719320930) for details on the actual value of `comments` and the error.
The bug was introduced in #5147 and we already tried to fix it in #5157.
> fix(ci): Use response data in changes-in-high-risk-code.yml

- .github/workflows/changes-in-high-risk-code.yml
After merging #5183 the removal of comments is still failing, see [this workflow run ](https://github.com/getsentry/sentry-cocoa/actions/runs/14859484969/job/41720575603?pr=5162) after updating the PR to latest main.
The reason were missing `owner` and `repo` parameters in the delete call.
To verify the changes, delete the comment "🚨 Detected changes in high risk code 🚨", then run [this job](https://github.com/getsentry/sentry-cocoa/actions/runs/14859907534/job/41722119335?pr=5185) again.
The comment will be created.
Next add any comment to this PR and run the job again. The previous comment before yours will be deleted and a new one posted to the PR.
> fix(ci): Add missing parameters to delete high-risk comments

- CHANGELOG.md
- Sources/Sentry/SentryBaseIntegration.m
- Sources/Sentry/SentryFramesTrackingIntegration.m
- Sources/Sentry/SentryOptions.m
- Sources/Sentry/SentryProfiler.mm
- Sources/Sentry/include/HybridPublic/SentryBaseIntegration.h
- Sources/Sentry/include/SentryOptions+Private.h
- Tests/SentryProfilerTests/SentryContinuousProfilerTests.swift
- Tests/SentryTests/Integrations/Performance/FramesTracking/SentryFramesTrackingIntegrationTests.swift
- Tests/SentryTests/SentryOptionsTest.m
AppHangsV2 didn't detect any app hangs when tracing was disabled. This is fixed now.
Brought up in an internal Slack discussion.
Unit tests and simulator: [sample event](https://sentry-sdks.sentry.io/issues/6588735286/events/743520cb05f54781b31e731482ad52a1/?project=5428557) when having tracing disabled
> fix: Detect AppHangsV2 when tracing not enabled

- .github/workflows/testflight.yml
- fastlane/Fastfile
didn't update the path to the generated project, and didn't generate it beforehand
> fix(testflight): generate project, and use correct path

- .github/workflows/ui-tests.yml
These tests fail with some error when showing the xcode build setting. Using a more up to date runner and Xcode version could help and anyways makes sense.
The job failed here: https://github.com/getsentry/sentry-cocoa/actions/runs/14877481283/job/41784031333.
> ci: Run UI Tests for SwiftUI with Xcode 16

- .github/workflows/version-bump-util.yml
- Utils/VersionBump/main.swift
The CameraTest doesn't contain a proper marketing version. We can ignore it. 
I also added a GH action to run the version util via the make file.
By intentionally breaking it here https://github.com/getsentry/sentry-cocoa/actions/runs/14886048089/job/41805819992?pr=5195.
> ci: Remove CameraTest xcconfig from version bump

- .github/workflows/build.yml
- Sources/Sentry/SentrySessionReplaySyncC.c
When setting the SENTRY_ASYNC_SAFE_LOG_LEVEL to
SENTRY_ASYNC_SAFE_LOG_DEBUG, the project fails to compile because SentrySessionReplaySyncC contains compiler errors for the log levels. This is fixed now, and this PR also adds a check in CI to prevent this from happening again, by setting the SENTRY_ASYNC_SAFE_LOG_LEVEL to SENTRY_ASYNC_SAFE_LOG_TRACE and compiling the project.
CI failed successfully here https://github.com/getsentry/sentry-cocoa/actions/runs/14901950471/job/41855671564?pr=5207
```
Error: expected expression
17 |     SENTRY_ASYNC_SAFE_LOG_DEBUG(@"[Session Replay] Starting session replay with path: %s", path);
|                                 ^
Error: expected expression
41 |         @"[Session Replay] Updating session info with segmentId: %u, lastSegmentEnd: %f", segmentId, …
```
> ref: Fix compiler errors for async safe logs

- .github/workflows/lint-shellcheck.yml
- .github/workflows/lint.yml
Move the shellcheck into its on workflow so it always runs when sh files change. We can also run it on ubuntu and its preinstalled.
> ci: Move shellcheck into its on workflow

- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackFormController.swift
New version of https://github.com/getsentry/sentry-cocoa/pull/5186 with correct access now
Makes it easier to iterate on the UI, could eventually use it for snapshot tests
Ran the preview locally in xcode
> test(feedback): Add Xcode previews

- Samples/macOS-Swift/macOS-Swift.entitlements
Looks like it was inadvertently added while making some changes but isn't actually used.
> test: remove unused entitlements file

- Sources/Sentry/SentryUIViewControllerPerformanceTracker.m
Adds logging statements to the UIViewController performance tracker
Derived from #5048
> chore: Add debug logging to UIViewController performance tracker

- Tests/SentrySwiftUITests/SentryTraceViewModelTest.swift
Fixes a compiler error seen locally:
fixed:
> test: fix compile error for SentrySwiftUITests

- .github/workflows/test-cross-platform.yml
This was failing my PRs because the formatter wanted to make changes but wasn't able to commit changes to workflow files: https://github.com/getsentry/sentry-cocoa/actions/runs/15049391355/job/42303272015?pr=5237
> Fix format

- Sources/Sentry/SentryANRTrackerV1.m
- Sources/Sentry/SentryANRTrackerV2.m
- Sources/Sentry/SentryANRTrackingIntegration.m
- Sources/Sentry/SentryDependencyContainer.m
- Sources/Sentry/SentryMetricKitIntegration.m
- Sources/Sentry/SentrySessionReplayIntegration.m
- Sources/Sentry/SentryWatchdogTerminationTrackingIntegration.m
- Sources/Sentry/include/SentryANRTrackerV1.h
- Sources/Sentry/include/SentryANRTrackerV2.h
- Sources/Sentry/include/SentryANRTrackingIntegration.h
- Sources/Sentry/include/SentryAppStartTracker.h
- Sources/Sentry/include/SentryAutoBreadcrumbTrackingIntegration.h
- Sources/Sentry/include/SentryMetricKitIntegration.h
- Sources/Sentry/include/SentrySessionReplayIntegration+Private.h
- Sources/Sentry/include/SentryWatchdogTerminationTrackingIntegration.h
- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV1IntegrationTests.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV1Tests.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV2Tests.swift
- Tests/SentryTests/Integrations/MetricKit/SentryMetricKitIntegrationTests.swift
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayIntegrationTests.swift
Follow up to https://github.com/getsentry/sentry-cocoa/pull/5227 this PR removes more uses of swift imports in header files and replaces them with forward declarations. In most cases the protocol conformance could be moved into a .m file, but in some cases the `asProtocol` trick had to be used for the conformance to be available outside of the .m file. You cannot use a forward declaration for a conformance, but you can use it for the return value of a function.
Helps to avoid the circular dependency issue, and is a best practice when bridging objc/swift: https://developer.apple.com/documentation/swift/importing-swift-into-objective-c#Include-Swift-Classes-in-Objective-C-Headers-Using-Forward-Declarations
Built test app
> Remove header swift imports

- Sources/Sentry/Profiling/SentryTraceProfiler.mm
- Sources/Sentry/SentryCrashReportConverter.m
- Sources/Sentry/SentryCrashScopeObserver.m
- Sources/Sentry/SentryEnvelope.m
- Sources/Sentry/SentryLogC.m
- Sources/Sentry/SentryMetricKitIntegration.m
- Sources/Sentry/SentryMigrateSessionInit.m
- Sources/Sentry/SentryNSDataSwizzling.m
- Sources/Sentry/SentryNSFileManagerSwizzling.m
- Sources/Sentry/SentryProfileTimeseries.mm
- Sources/Sentry/SentryScope.m
- Sources/Sentry/SentryUIEventTrackerTransactionMode.m
- Sources/Sentry/SentryUIViewControllerSwizzling.m
- Sources/Sentry/SentryWatchdogTerminationTracker.m
- Sources/Sentry/include/SentryLog.h
- Tests/SentryTests/TestUtils/SentryTestLogConfig.m
Remove swift import from last header file (SentryLog.h). Removing this triggered many missing imports in .m/.mm files which are now added
Same as https://github.com/getsentry/sentry-cocoa/pull/5227 and https://github.com/getsentry/sentry-cocoa/pull/5232 this is to address circular dependencies in swift/objc references and follow best practices from https://developer.apple.com/documentation/swift/importing-swift-into-objective-c#Include-Swift-Classes-in-Objective-C-Headers-Using-Forward-Declarations
Locally building
> Remove log swift header

- CHANGELOG.md
- Samples/SentrySampleShared/SentrySampleShared/SentrySDKOverrides.swift
- Samples/iOS-Swift/iOS-Swift-UITests/UserFeedbackUITests.swift
- Samples/iOS-Swift/iOS-Swift/Base.lproj/Main.storyboard
- Samples/iOS-Swift/iOS-Swift/ExtraViewController.swift
- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/Public/Sentry.h
- Sources/Sentry/Public/SentryOptions.h
- Sources/Sentry/Public/SentrySDK.h
- Sources/Sentry/SentrySDK.m
- Sources/Sentry/SentryUserFeedbackIntegration.m
- Sources/Sentry/include/SentryUserFeedbackIntegration.h
- Sources/Swift/Integrations/UserFeedback/SentryFeedbackAPI.h
- Sources/Swift/Integrations/UserFeedback/SentryFeedbackAPI.m
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackIntegrationDriver.swift
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackWidget.swift
In order to solve the SDK init and widget display ordering problem for SwiftUI access to connected scenes in https://github.com/getsentry/sentry-cocoa/pull/5223, we provide an API to manually show the widget (as well as the analogous hide method).
> feat(feedback): manual widget display

- Sources/Sentry/Profiling/SentryLaunchProfiling.m
- Sources/Sentry/SentrySysctl.m
- Sources/Sentry/SentryTime.mm
- Sources/Sentry/include/SentryTime.h
- Sources/Swift/Helper/SentryCurrentDateProvider.swift
- Tests/SentryProfilerTests/SentrySamplingProfilerTests.mm
- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
We only support > iOS 10.0 now (and same for the other platforms) so we can delete this conditional and use `clock_gettime_nsec_np` directly now to prevent the extra swift/objc interop
> Remove unnecessary version check

- Sources/Sentry/SentryCrashIntegration.m
Remove unused import for SentrySysctl in SentryCrashIntegration.m
> ref: Remove unused import for SentrySysctl

- CHANGELOG.md
- Sources/Sentry/SentryTracer.m
- Tests/SentryTests/Transaction/SentrySpanTests.swift
Added operation and description for warn log when starting child span on a finished span.
While analysing debug logs from a customer, seeing operation and description would have been helpful.
Unit tests still green and checked a printed log message.
> impr: Improve warn log in SentryTracer

- Sentry.xcodeproj/project.pbxproj
- Sources/Resources/Sentry.modulemap
- Sources/Sentry/PrivateSentrySDKOnly+Swift.m
- Sources/Sentry/PrivateSentrySDKOnly.mm
- Sources/Sentry/include/HybridPublic/PrivateSentrySDKOnly+Swift.h
- Sources/Sentry/include/HybridPublic/PrivateSentrySDKOnly.h
Objective C++ and Swift interop doesn't work with SPM, so I moved the swift code used by PrivateSentrySDKOnly.mm into a category that is in a .m file, that allowed removing the `#import "SentrySwift.h"` from PrivateSentrySDKOnly.mm
> Move swift dependant code out of objc++

- Sources/Sentry/SentrySystemWrapper.mm
Seems to be a copy-paste error from couple of lines above where the `taskThreadsStatus` was converted to an error.
Not sure if worth a changelog entry, but happy to add one.
> fix: Change status used to map Kernel error to NSError

- Sources/Sentry/SentryHttpTransport.m
> fix: change http transport flush timeout log to warning

- fastlane/Fastfile
We get a lot of UI test check run failures due to this timeout elapsing, so let's see if giving them more time helps. E.g. https://github.com/getsentry/sentry-cocoa/actions/runs/15141987547/job/42568403480#step:7:51
> ci: give fastlane more time before timing out

- fastlane/Fastfile
Looking for other ways to improve reliability of CI check runs involving fastlane.
> ci: skip SPM package resolution as we dont use SPM for sample apps

- .github/workflows/lint-prettier.yml
- .github/workflows/version-bump-util.yml
The path filters only applied to the root dir. Now they work for any files of .yml, .yaml, .json or .md in any directory.
> ci: Fix paths for prettier

- .github/workflows/test.yml
Adds all logs that are created during building and testing to the upload artifact.
Without these, the `xcbeautify` settings are too aggressive to see the actual error:
https://github.com/getsentry/sentry-cocoa/actions/runs/15160949791/job/42626770540
> fix(ci): Add all output logs to the upload artifact step

- fastlane/Fastfile
- fastlane/Matchfile
This is an intermittent failure that's plagued us for a long time. The latest fix was attempted in https://github.com/getsentry/sentry-cocoa/pull/4597 but that still didn't get it, I see a failure today in https://github.com/getsentry/sentry-cocoa/actions/runs/15146553011/job/42583551906?pr=5264#step:10:96
`clone_branch_directly` attempts to create a new branch, which seems like it should _always_ fail since master is the default branch for the repo.
specifying `git_branch` as `master` is just reiterating the default value for that parameter.
Also, centralizes these settings in Matchfile since they're copied at every invocations of `sync_code_signing`
> ci: fastlane match fixes

- Sources/Swift/Integrations/Performance/IO/SentryFileIOTracker+SwiftHelpers.swift
- Sources/Swift/Integrations/SessionReplay/RRWeb/SentryRRWebBreadcrumbEvent.swift
- Sources/Swift/Integrations/SessionReplay/RRWeb/SentryRRWebSpanEvent.swift
- Sources/Swift/Integrations/SessionReplay/RRWeb/SentryRRWebVideoEvent.swift
- Sources/Swift/Integrations/SessionReplay/SentryReplayOptions.swift
- Sources/Swift/Integrations/SessionReplay/SentryReplayRecording.swift
- Sources/Swift/Integrations/SessionReplay/SentrySessionReplayDelegate.swift
- Sources/Swift/Integrations/UserFeedback/Configuration/SentryUserFeedbackConfiguration.swift
- Sources/Swift/Integrations/UserFeedback/Configuration/SentryUserFeedbackFormConfiguration.swift
- Sources/Swift/Integrations/UserFeedback/Configuration/SentryUserFeedbackThemeConfiguration.swift
- Sources/Swift/Integrations/UserFeedback/Configuration/SentryUserFeedbackWidgetConfiguration.swift
- Sources/Swift/Integrations/UserFeedback/SentryFeedback.swift
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackFormController.swift
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackWidget.swift
- Sources/Swift/Protocol/Codable/DecodeArbitraryData.swift
- Sources/Swift/Tools/SentryLog+Configure.swift
I noticed quite a few swift files imported _SentryPrivate despite not using any objc code, this removes those unnecessary imports 
> Remove extra imports

- Sources/Sentry/Public/SentryError.h
- Sources/Sentry/Public/SentryFeedbackAPI.h
- Sources/Sentry/Public/SentryOptions.h
- Sources/Sentry/Public/SentryReplayApi.h
- Sources/Sentry/Public/SentrySpanProtocol.h
- Sources/Sentry/Public/SentryTraceHeader.h
- Sources/Sentry/Public/SentryTransactionContext.h
Continuing the changes from this PR: https://github.com/getsentry/sentry-cocoa/pull/5247 into more header files. This import format lets use use these files from targets other than Sentry and SentryWithoutUIKit
> Update imports format

- Tests/SentryTests/SentryCrash/SentryCrashJSONCodec_Tests.m
GH-4424 reports a crash when calling dataUsingEncoding, which is related to invalid memory. This PR adds two more tests to ensure we can encode Japanese characters and even an invalid JSONString, which makes dataUsingEncoding return nil.
> test: Add tests for encodeObject with NSString

- .github/workflows/version-bump-util.yml
- scripts/bump.sh
- scripts/verify-package-sha.sh
The release workflow uses `make bump` while the craft script uses `./scripts/bump.sh`.
The version bump utility was updated and tested for the Makefil, but not for the script.
This PR adds a fix and extends the test workflows to cover both.
It also adds tests for the `update-package-sha.sh` which is used by `bump.sh`.
> fix(ci): Add missing update parameter to bump.sh

- CHANGELOG.md
- Sources/Resources/ThreadSanitizer.sup
- Sources/Swift/Core/Tools/SentryLog.swift
- Tests/SentryTests/Helper/SentryLogTests.swift
Remove unnecessary lock in SentryLog.configure as it's not required because we don't call configure from multiple threads anyways. Furthermore, SentryLog isn't fully thread safe anyways when calling configure and log from multiple threads. We accept these race conditions not leading to crashes because the SentrySDK only calls configure during start and making these methods thread-safe by using locks would add a significant overhead to all log messages. This PR ignores SentryLog for the ThreadSanitizer.
The thread sanitizer is disabled in CI. This brings us one step closer for enabling it again.
Unit tests and running the thread sanitizer locally.
-  [x] I added tests to verify the changes.
> impr: Remove lock in SentryLog.configure

- CHANGELOG.md
- Sources/Swift/Core/Tools/ViewCapture/UIRedactBuilder.swift
- Tests/SentryTests/ViewCapture/UIRedactBuilderTests.swift
The cocoa SDK can be manually initialized in RN applications with or without the RN SDK. This can lead to unexpected behavior where RN text and images are not masked correctly.
This PR adds the RN text and images classes to be redacted when `maskAllText` and `maskAllImages` are used.
I have not included the RN SVG class as cocoa doesn't have `maskAllVectors`. 
fixes: https://github.com/getsentry/sentry-cocoa/issues/5301
Added unit tests.
> feat(replay): Redact React Native text and images by default

- .github/workflows/api-stability.yml
SPM has built in support for determining if a change breaks the public API of a framework using `swift package diagnose-api-breaking-changes` However I couldn't get this to work with a prebuilt binary. Internally that command uses `swift-api-digester` which is not very documented but I found a few threads on like [this one](https://forums.swift.org/t/using-swift-api-digester/22956). 
This PR runs swift-api-digester to get a report of anything that change in the API which may be a breaking change. This does not do any checking of the report to prevent any change from landing, it just generates the report so if anyone is interested they can look at it on their PRs. I think it's good to have running in main as a sanity check, and to ensure the processes used to generate the report doesn't …
> Add API stability check

- .pre-commit-config.yaml
- Makefile
Add a new Makefile script to run linter only on modified files
Running `time git commit -m "Any message"`
Previous time: 46s
Actual time: 26s
> style: Run linter only on modified swift files on pre hook

- Plans/iOS-Swift_Base.xctestplan
Failed here https://github.com/getsentry/sentry-cocoa/actions/runs/15415368588/job/43376783821
Related issue to fix https://github.com/getsentry/sentry-cocoa/issues/5345
> test: Disable flaky testProfilingGPUInfo

- Sources/Swift/Core/Helper/SentryBaggageSerialization.swift
- Sources/Swift/Core/Helper/SentryCurrentDateProvider.swift
- Sources/Swift/Core/Integrations/ANR/SentryANRTracker.swift
- Sources/Swift/Core/Integrations/ANR/SentryANRTrackerV2Delegate.swift
- Sources/Swift/Core/Integrations/ANR/SentryANRType.swift
- Sources/Swift/Core/SentryExperimentalOptions.swift
- Sources/Swift/Integrations/SessionReplay/SentryReplayRecording.swift
- Sources/Swift/Integrations/UserFeedback/SentryFeedback.swift
- Tests/SentryTests/Helper/SentryBaggageSerializationTests.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV1IntegrationTests.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTrackingIntegrationTests.swift
- Tests/SentryTests/Integrations/ANR/SentryANRTypeTests.swift
- Tests/SentryTests/Integrations/WatchdogTerminations/SentryWatchdogTerminationTrackingIntegrationTests.swift
- sdk_api.json
A follow up from https://github.com/getsentry/sentry-cocoa/pull/5307 making a few swift types that I missed `public` and adding spi where necessary (only when the enclosing class wasn't already spi)
> Add more SPI

- .github/workflows/lint-clang-formatting.yml
- .github/workflows/lint-swift-formatting.yml
- Brewfile
- Brewfile-ci-format
- Makefile
- Sentry.xcodeproj/project.pbxproj
I noticed we wanted to pin the swift format job to macOS 13 due to what is or isn't installed on the machines, but we already brew install clang-format, so figured we could do that for this too. Eventually 13 will be deprecated anyways.
Also add the format config files to the list of file triggers for the jobs, dedupe the makefile tasks that correspond to the different brewfiles we have, and add Brewfile-ci-format to the xcworkspace.
> ci: install swiftlint on more recent ci macOS images

- .github/workflows/ui-tests-critical.yml
This change should fix the Maestro Debug logs not being uploaded on failure of the UI Critical Tests.
> fix(ci): Add `--flatten-debug-output` to Maestro CLI to upload debug logs

- .github/actions/add-microphone-permissions.yml
- .github/actions/add-microphone-permissions/action.yml
- .github/actions/capture-screenshot/action.yml
- .github/workflows/ui-tests-critical.yml
- .github/workflows/ui-tests.yml
Some tests are failing due to the UI loop not being idle.
Sometimes that can happen due to the microphone permissions on macOS.
> ci: Add microphone permissions to simulator

- .github/workflows/ui-tests.yml
- Samples/iOS-Swift/iOS-Swift-UITests/BaseUITest.swift
- fastlane/Fastfile
I looked at a few of the tests that have been failing on my recent PRs and found a couple opportunities for improvements.
1 - The duplicated SDK test was running on iOS 18.0 and on that failed test the entire simulator had crashed (see screenshot) I'm trying updating it to 18.5 which has some simulator fixes that might make it not crash as much
2 - Another test was stuck with "app event loop idle notification not received". We saw things like this at Emerge sometimes that was from the app launch being prewarmed. UI tests don't know how to handle this and get stuck, we can fix it by first activating the app, and then launching it. There might be other reasons this happens, I read one is from permissions dialogs popping up on the host macOS machine, but at least this will fix one possible …
> ci: Update ios versions and handle prewarmed ui test launches

- CHANGELOG.md
- Sources/Swift/Integrations/UserFeedback/SentryUserFeedbackIntegrationDriver.swift
This used `iOSApplicationExtension` for extensions but the class definition used `@available(iOS 13.0, *)`. That works when compiling with `APPLICATION_EXTENSION_API_ONLY` but not without it. Let's just change all to `iOS` so that it works with our without the extension-only flag.
> (fix) Fix usage of app extension availability

- Sources/Sentry/Public/SentryEvent.h
- Sources/Sentry/SentryEvent.m
- Sources/Swift/Protocol/Codable/SentryEventCodable.swift
- sdk_api.json
Moves SentryEventDecodable from objc to Swift, incremental progress to making more of the API in Swift. Also solves an SPM issue which is that Swift and objc are in different modules, and you can't add a protocol conformance across module boundaries
> (ref): Move SentryEventDecodable to Swift

- .github/workflows/ui-tests-critical.yml
These are colliding because we run two types of test per Xcode version: https://github.com/getsentry/sentry-cocoa/actions/runs/15521723107/job/43695867451?pr=5377#step:12:36
> ci: fix ui-test-critical archive name collisions

- CHANGELOG.md
- Sources/SentryCrash/Recording/Tools/SentryCrashCxaThrowSwapper.c
- Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext.h
- Sources/SentryCrash/Recording/Tools/SentryCrashMachineContext_Apple.h
Fix for Xcode 26
Fixes this error in Xcode 26:
Build with xcode
> fix: Fix xcode 26

- .github/actions/capture-screenshot/action.yml
- .github/workflows/ui-tests-common.yml
- .github/workflows/ui-tests-critical.yml
- .github/workflows/ui-tests.yml
Some jobs use matrixes, so they have the same job id, adding optional suffix so we get all screenshots
> ci: avoid upload failures with unique screenshot names with optional suffixes

- fastlane/Fastfile
Use a helper function to reduce duplicated code in fastfile.
We have lots of tests in the fastfile, with pretty much the same format.
We can make the fastfile easier to read, using a helper function.
Run locally.
> ci: Use helper function to run tests in fastlane

- Sentry.xcodeproj/project.pbxproj
- SentryTestUtils/ArrayAccesses.swift
- SentryTestUtilsTests/ArrayAccessesTests.swift
The current implementation of `Array.element(at index: Int)` does not handle out of bounds indicies for negative and positive numbers.
This PR adds correct handling and tests to verify the behaviour.
> fix: Add out of bounds handling for array accessor

- .github/workflows/ui-tests.yml
- Samples/SentrySampleShared/SentrySampleShared/SentrySDKOverrides.swift
Disable everything flag was broken in the latest refactor.
Adding them back to the same flags as before.
> fix: Restore disable everything override

- SentryTestUtils/ClearTestState.swift
- Sources/Sentry/SentryClient.m
- Sources/Sentry/SentryDependencyContainer.m
- Sources/Sentry/SentryGlobalEventProcessor.m
- Sources/Sentry/SentryScope.m
- Sources/Sentry/SentrySessionReplayIntegration.m
- Sources/Sentry/include/HybridPublic/SentryDependencyContainer.h
- Sources/Sentry/include/SentryGlobalEventProcessor.h
- Tests/SentryTests/Helper/SentryDependencyContainerTests.swift
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayIntegrationTests.swift
- Tests/SentryTests/SentryClientTests.swift
Moves the singleton managed using `dispatch_once` to the dependency container, so that it gets deallocated on `SentrySDK.close()` correctly and to allow mocking in unit tests.
Related to #5393
> refactor: Move singleton of SentryGlobalEventProcessor to dependency container

- Sentry.xcodeproj/project.pbxproj
- Sources/Swift/Core/Tools/SentryLog.swift
- Sources/Swift/Core/Tools/SentryLogOutput.swift
- Tests/SentryTests/Helper/SentryLog.swift
- Tests/SentryTests/Helper/SentryLogTests.swift
- Tests/SentryTests/Integrations/SentryBaseIntegrationTests.swift
- Tests/SentryTests/SentryCrash/SentryCrashStackCursorSelfThreadTests.swift
- Tests/SentryTests/SentrySDKTests.swift
- Tests/SentryTests/TestLogOutput.swift
I noticed this was a class acting as a closure, updated it to simplify the code a bit and improve performance by avoiding objc runtime/classes.
> ref: Improve test logging

- CHANGELOG.md
- Sources/Sentry/Profiling/SentryLaunchProfiling.m
I noticed while adding more edge case tests to #5318 that these checks were copypasta'd and not checking the correct variable contents, first introduced in https://github.com/getsentry/sentry-cocoa/pull/4751
> fix: check correct variables for profiles/traces rand

- scripts/update-api.sh
- sdk_api.json
Update the API stability check to handle SPI, we use SPI to expose Swift to Objective-C and it is not part of the public API, so we can exclude it from the stability check to avoid unnecessary churn.
> Update API stability to handle SPI

- Sources/Sentry/SentryClient.m
- Sources/Sentry/SentryHttpTransport.m
- Sources/Sentry/SentryTransportFactory.m
- Sources/Sentry/include/SentryHttpTransport.h
- Sources/Sentry/include/SentryTransportFactory.h
- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
- Tests/SentryTests/Networking/SentryTransportFactoryTests.swift
- Tests/SentryTests/Networking/SentryTransportInitializerTests.swift
This PR fixes a deadlock in SentryHttpTransport by injecting a date provider instead of accessing it via the `SentryDependencyContainer.sharedInstance`.
Tests were experiencing deadlocks due to a circular dependency between `SentryDependencyContainer` and `SentryReachability`:
**Deadlock Scenario:**
- **Thread 1 (main)**: Holds `sentryDependencyContainerInstanceLock` during `reset()` → trying to acquire `sentry_reachability_observers` lock in `removeAllObservers`
- **Thread 112/132 (reachability callbacks)**: Hold `sentry_reachability_observers` lock → trying to acquire `sentryDependencyContainerInstanceLock` via `SentryDependencyContainer.sharedInstance.dateProvider`
```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00000001010e1ae0 in __ulock_wait2 ()
#1	0x0000000100c6539c in …
```
> fix: Add date provider to SentryHttpTransport constructor

- CHANGELOG.md
- Sources/Sentry/SentryANRTrackingIntegration.m
- Tests/SentryTests/Integrations/ANR/SentryANRTrackingIntegrationTests.swift
Add debug images for all app hang events directly in the ANRTrackingIntegration to ensure all app hang events have debug images attached, which is required for symbolication.
Fixes GH-5433
Unit tests and with TestFlight
Fatal app hang event before the fix from the iOS-Swift sample app via TestFlight
https://sentry-sdks.sentry.io/issues/6690874496/events/da915f043c0741959b04d9ce9ba42943/?project=5428557
With the fix
https://sentry-sdks.sentry.io/issues/6695548079/events/934bb93490554023905e9570cc78c75a/?project=5428557
> fix: Stacktrace symbolication of fatal app hangs

- Sources/Sentry/SentryAutoSessionTrackingIntegration.m
- Sources/Sentry/SentrySessionTracker.m
- Sources/Sentry/include/SentrySessionTracker.h
- Tests/SentryTests/Integrations/Session/SentrySessionTrackerTests.swift
Replace stop(gracefully) with removeObservers.
This PR is based on https://github.com/getsentry/sentry-cocoa/pull/5121#discussion_r2161035116.
> ref: SessionTracker remove observers

- Sources/Sentry/SentryDependencyContainer.m
- Sources/Sentry/SentryViewHierarchyProvider.m
- Sources/Sentry/include/SentryViewHierarchyProvider.h
- Tests/SentryTests/SentryViewHierarchyProviderTests.swift
Instead of retrieving the dependencies in the
SentryViewHierarchyProvider via the SentryDependencyContainer, clearly specify them in the initializer, which is better for testability and readability. Another benefit is that the
SentryViewHierarchyProviderTests don't need to call SentryDependencyContainer.reset.
This came up while investigating `test_appViewHierarchy_usesMainThread` being flaky on MacCatalyst. This PR minimizes potential side effects of SentryDependencyContainer.reset.
Smoke test that ViewHierarchy still works: https://sentry-sdks.sentry.io/issues/6607086585/events/1623c22620294553a448e152fac70848/?project=5428557
> ref: Inject dependencies for ViewHierarchyProvider

- Samples/iOS-Swift/iOS-Swift-UITests/BaseUITest.swift
- Samples/iOS-Swift/iOS-Swift-UITests/ProfilingUITests.swift
The profile UI tests all wind up removing launch config files before they end. But if they abnormally exited before being able to do so, then another UI test would wind up running a launch profile.
This change makes sure there is no on-disk data leakage between UI tests in any way, whether that be launch profiles, envelopes, etc.
Noticed this while investigating https://github.com/getsentry/sentry-cocoa/issues/5366, but this doesn't fix the root problem of imbalanced bookkeeping mentioned there.
> test(UI): always wipe all data on disk before starting a new UI test

- .github/workflows/release.yml
- .github/workflows/ui-tests-common.yml
Forgot to update this after making the changes in #5448 
> ci: fix artifact key name after moving to other workflow

- Sources/Sentry/include/SentryPrivate.h
I accidentally added this file here: https://github.com/getsentry/sentry-cocoa/pull/5457/files#diff-30d12b9d752ae2529667440c152936e6cbc8dbf85a84e0fd8ea08f66a7249a7aR6 but it does not need to be in this header
> fix: Remove header not needed in SentryPrivate.h

- Sources/Sentry/SentryFileManager.m
- Sources/Sentry/SentryProfiler.mm
- Sources/Sentry/include/SentryFileManager.h
I needed to be able to do this as part of running a sample app locally, but the way I'd conditionally compiled it out didn't allow that. Also compile this into debug builds.
> test: dont gate data wipe to only tests

- Samples/Shared/Config/Linking.xcconfig
Fixing running the Mac sample app from locations other than Xcode's run action
> fix: mac sample searchpaths

- .github/workflows/assemble-xcframework-variant.yml
- .github/workflows/release.yml
- CHANGELOG.md
Release 8.53.0 job used a cache instead of building from scratch: https://github.com/getsentry/sentry-cocoa/actions/runs/15873193408/job/44760111068
The cache key did not include the version
Fixes: #5492
> fix: Fix XCFramework version including commit sha on release

- SentryTestUtils/TestSentryDispatchQueueWrapper.swift
- Sources/Sentry/SentryHttpTransport.m
- Sources/Sentry/SentryTracer.m
- Sources/Sentry/_SentryDispatchQueueWrapperInternal.m
- Sources/Sentry/include/_SentryDispatchQueueWrapperInternal.h
- Sources/Swift/Helper/SentryDispatchQueueWrapper.swift
- Tests/SentryTests/Integrations/UIEvents/SentryUIEventTrackerTests.swift
- Tests/SentryTests/Transaction/SentryTracerTests.swift
This allows further work on https://github.com/getsentry/sentry-cocoa/issues/5371 by making three DispatchQueueWrapper methods `public`. These I had previously not made public because they used an internal type due to `dispatch_queue_t` not being available in Swift. This slight refactor preserves the functionality while making all the methods public.
> Make dispatch queue wrapper public

- Samples/iOS-Swift/iOS-Swift-UITests/BaseUITest.swift
A lot of the flaky UI tests I'm seeing seem to boil down to this. Basically the UI tests are asserting based on the span found in `currentHub.scope.span`. Spotlight is making network requests in the background to localhost that always fail, but are automatically tracked as spans.  When they fail they call `finishSpan` which eventually calls `finishTracer... shouldCleanup:YES` which then hits this code:
```
if (shouldCleanUp) {
id<SentrySpan> _Nullable currentSpan = [_hub.scope span];
if (currentSpan == self) {
[_hub.scope setSpan:nil];
}
}
```
So in a UI test that asserts the appearing view controller creates a valid span, the test will fail if the spotlight request finishes at just the right moment. This is what was happening in: https://github.com/getsentry/sentry-cocoa/issues/5505
I …
> tests: Disable spotlight in UI tests

- Samples/iOS-Swift/iOS-Swift/TransactionsViewController.swift
From looking at some of these flaky test logs I noticed the active span sometimes gets set by file io operations right before/during the view lifecycle of the VC being tested. That causes the span to be nil when we check it. This should fix background file io overwriting the current span in UI tests
This should fix https://github.com/getsentry/sentry-cocoa/issues/5505
> test: Fix flaky launch UI test

- .github/workflows/ui-tests-common.yml
Use vars in `ui-tests-common.yml` run commands
> Use vars in `ui-tests-common.yml` run commands

- .github/workflows/ui-tests.yml
- fastlane/Fastfile
This test flaked: https://github.com/getsentry/sentry-cocoa/actions/runs/15934135003/job/44950002764 
And I saw in the xcresult that the simulator crashed and was iOS 18.0. This PR updates it to 18.5 which we use for most other tests and we've seen to be less flaky
> test: Fix flaky Tests for SwiftUI

- Sentry.xcodeproj/project.pbxproj
- SentryTestUtils/TestDisplayLinkWrapper.swift
- Sources/Sentry/SentryDependencyContainer.m
- Sources/Sentry/SentrySessionReplayIntegration.m
- Sources/Sentry/include/SentryHub+Private.h
- Sources/Swift/Core/Integrations/FramesTracking/SentryFramesDelayResult.swift
- Sources/Swift/Core/Tools/ViewCapture/SentryViewPhotographer.swift
- Sources/Swift/Integrations/SessionReplay/RRWeb/SentryRRWebBreadcrumbEvent.swift
- Sources/Swift/Integrations/SessionReplay/RRWeb/SentryRRWebSpanEvent.swift
- Sources/Swift/Integrations/SessionReplay/SentryOnDemandReplay.swift
- Sources/Swift/Integrations/SessionReplay/SentryReplayOptions.swift
- Sources/Swift/Integrations/SessionReplay/SentryReplayVideoMaker.swift
- Sources/Swift/Integrations/SessionReplay/SentrySessionReplay.swift
- Sources/Swift/Integrations/WatchdogTerminations/Processors/SentryWatchdogTerminationContextProcessor.swift
- Sources/Swift/Persistence/SentryScopeContextPersistentStore.swift
- Sources/Swift/Protocol/SentrySessionListener.swift
- Tests/SentryProfilerTests/SentryAppLaunchProfilingTests.swift
- Tests/SentryTests/Integrations/WatchdogTerminations/SentryWatchdogTerminationTrackerTests.swift
This should be the last change necessary for https://github.com/getsentry/sentry-cocoa/issues/5371 I left removal of the actual build settings until the next PR just to isolate that change, but locally this was all the remaining SPI I needed to get it compiling.
> ref: Move last round of types to spi

- .github/workflows/ui-tests-critical.yml
The test ran for 6h in CI. If the test isn't finished after 10 minutes we can cancel the job.
The job took 6 hourse here: https://github.com/getsentry/sentry-cocoa/actions/runs/15985146703/job/45087995982
The next step is to find out why it timed out and fix it.
> ci: Add timeout for run-swiftui-crash-test

- .github/workflows/release.yml
Pulling in the latest changes from this action to unblock CI which is failing on every PR due to a bug in the latest release of "action-app-sdk-overhead-metrics"
> Fix metrics CI

- .github/workflows/ui-tests.yml
I noticed while proposing #5541 that the UI tests didn't run in CI when they should've upon changing the sample apps' xcconfig files; add this trigger to ensure that happens.
> trigger ui tests to run on sample app shared xcconfig changes

- Samples/iOS-SwiftUI/iOS-SwiftUI-UITests/LaunchUITests.swift
- Samples/iOS-SwiftUI/iOS-SwiftUI.yml
These tests flaked on me, and I noticed they didn't have our fixes for prewarmed app launches since those were in "SentrySwift" and these tests are for "SentrySwiftUI". I tried to move them to SentrySampleUITestShared, but it looks like that framework can't import XCTest so I just copied it here 
> Fix prewarmed swiftui tests

- TestSamples/SwiftUICrashTest/test-crash-and-relaunch.sh
Launch the app after crash in the background and wait for 5 seconds for it to launch. If it doesn't launch after 5 seconds exit the test as failed.
Follow up on https://github.com/getsentry/sentry-cocoa/pull/5528 cause the test timed out here https://github.com/getsentry/sentry-cocoa/actions/runs/15985146703/job/45087995982
> test: Improve critical crash test

- Sentry.xcodeproj/project.pbxproj
- SentryTestUtilsTests/InvocationsTests.swift
Add tests for the test util class Invocations. We need to ensure our test code works correctly for a deterministic test suite.
This came up while investigating https://github.com/getsentry/sentry-cocoa/issues/5421.
> test: Add InvocationTests

- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Remove a couple of DependencyContainer usages and use the date provider of the fixture instead, because we want to limit the usage of the DependencyContainer as much as we can during testing, cause it is global state.
Came up while looking at https://github.com/getsentry/sentry-cocoa/issues/5421.
> test: Remove dep container usage in HTTPTransport

- CHANGELOG.md
I didn't notice that the changelog entry #5223 wasn't scoped down for what the PR wound up actually doing: it only correctly shows the widget when manually calling the display method; automatic injection will be worked on later.
> meta: fix changelog entry for #5223

- Sources/Swift/Integrations/UserFeedback/Configuration/SentryUserFeedbackWidgetConfiguration.swift
Should've gone in with #5223. Requires https://github.com/getsentry/sentry-docs/pull/14227 to be merged first.
> docs(feedback): add a warning to autoInject property about SwiftUI

- scripts/start-test-server.sh
5 seconds don't seem to be enough, cause it timed out a few times in CI. Let's increase the value to 20s.
> ci: Increase test server timeout check to 20 s

- Makefile
Both scripts don't exist anymore.
> chore: Remove dead script references from Makefile

- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
The method givenFirstRateLimitGetsActiveWithSecondResponse only gets used at one place. Let's inline the logic so the test is easier to read.
This came up while investigating https://github.com/getsentry/sentry-cocoa/issues/5421.
> test: HTTPTransportTests inline some logic

- CHANGELOG.md
- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/SentryHub.m
- Tests/SentryTests/SentrySDKThreadTests.swift
We have a race condition in the `SentryClient` property of `SentryHub` that is causing flaky unit tests. When the tests are torn down we call `bindClient:nil` (from `[SentrySDK close]`) This sets _client to nil, but the client property can also be accessed by background threads (in particular from `[SentryHub captureReplayEvent]`). This can lead to messaging a dangling pointer. This fix makes the client property atomic, since it is accessed/read from multiple threads.
Fixes https://github.com/getsentry/sentry-cocoa/issues/5506
> fix: Race condition when closing SDK

- Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m
> fix: Remove private import from sample app

- Sentry.xcodeproj/project.pbxproj
- Sources/Sentry/Profiling/SentryProfiledTracerConcurrency.mm
- Sources/Sentry/Profiling/SentryProfilerSerialization.m
- Sources/Sentry/SentryDevice.m
- Sources/Sentry/SentryMetricProfiler.m
- Sources/Sentry/SentryProfileTimeseries.m
- Sources/Sentry/include/SentryProfileTimeseries.h
- Sources/Sentry/include/SentryProfilerSerialization.h
- Tests/SentryTests/Helper/SentryDeviceTests.m
SPM doesn't support mixing Swift and ObjectiveC++, this PR converts some ObjectiveC++ that imported SentrySwift into regular ObjectiveC
> feat(spm): Remove swift imports from objc++

- CHANGELOG.md
Just realized I should have included this in https://github.com/getsentry/sentry-cocoa/pull/5591 because I ended up adding a new deprecated attribute to a public method in that PR
> Deprecate in changelog

- Sources/Sentry/Profiling/SentryLaunchProfiling.m
- Sources/Sentry/Public/SentryOptions.h
- Sources/Sentry/SentryOptions.m
- Sources/Sentry/SentrySampling.m
- Sources/Sentry/SentrySdkInfo.m
- Sources/Swift/Helper/SentryEnabledFeaturesBuilder.swift
- Tests/SentryProfilerTests/SentryAppLaunchProfilingTests.swift
- Tests/SentryProfilerTests/SentryAppStartProfilingConfigurationTests.swift
- Tests/SentryProfilerTests/SentryContinuousProfilerTests.swift
- Tests/SentryProfilerTests/SentryProfileTestFixture.swift
- Tests/SentryProfilerTests/SentryProfilingPublicAPITests.swift
- Tests/SentryProfilerTests/SentryTraceProfilerTests.swift
- Tests/SentryTests/Helper/SentryEnabledFeaturesBuilderTests.swift
- Tests/SentryTests/SentryOptionsTest.m
- Tests/SentryTests/Transaction/SentrySpanTests.swift
- sdk_api.json
These are all deprecated but were not using the deprecated attribute
> feat(v9): Mark deprecated APIs as deprecated

- Sources/Sentry/SentrySystemEventBreadcrumbs.m
- Tests/SentryTests/Integrations/Breadcrumbs/SentrySystemEventBreadcrumbsTest.swift
Happened to notice that this was being done twice
> fix: Remove extra unregister

- CLAUDE.md
- Sentry.xcodeproj/project.pbxproj
I've started using Claude Code, and wanted to introduce a CLAUDE.md into our repo to help with it.
For future reference, we have a couple other repos at Sentry that already have a CLAUDE.md file: 
- https://github.com/getsentry/sentry-javascript/blob/develop/CLAUDE.md
- https://github.com/getsentry/getsentry/blob/master/CLAUDE.md
- https://github.com/getsentry/sentry-mcp/blob/main/CLAUDE.md
- https://github.com/getsentry/vanguard/blob/main/CLAUDE.md
And there is also a general collection of rules at https://github.com/steipete/agent-rules. 
And then there are the anthropic docs: https://www.anthropic.com/engineering/claude-code-best-practices and https://docs.anthropic.com/en/docs/claude-code/memory were two I read while going through this.
Keeping those in mind, let's iterate on this …
> meta: claude init

- README.md
Codebeat is shutting down see https://codebeat.co/. Let's remove the badge.
> chore: Remove codebeat badge

- Tests/SentryTests/TestLogOutput.swift
The test testLoggingFromMultipleThreads lead to deadlocks. This is fixed now by using a NSLock instead of a DispatchQueue. This PR also makes the logsToConsole immutable and adds more tests.
> test: Fix potential deadlock in TestLogOutput

- Sources/Sentry/include/SentryProfiledTracerConcurrency.h
This seems to be unused and unimplemented
> fix: Remove unused function declaration

- Tests/SentryTests/Networking/SentrySpotlightTransportTests.swift
- Tests/SentryTests/Networking/TestRequestManager.swift
- Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift
I saw both of these flaking due to timeouts in https://github.com/getsentry/sentry-cocoa/actions/runs/16342586541/job/46168628617
> ci: Fix flaky test timeouts

- Samples/iOS-ObjectiveC/iOS-ObjectiveC/AppDelegate.m
- Samples/iOS-ObjectiveC/iOS-ObjectiveC/ViewController.m
Noticed these were failing the objc sample app build so the ui tests couldn't run there: https://github.com/getsentry/sentry-cocoa/actions/runs/16359229447/job/46223970689?pr=5658#step:12:741
> test: fix objc sample app build errors from deprecation warnings

- Sources/Sentry/SentryDefaultObjCRuntimeWrapper.m
- Sources/Sentry/SentryDependencyContainer.m
- Sources/Sentry/SentryDependencyContainerSwiftHelper.m
- Sources/Sentry/SentryPerformanceTrackingIntegration.m
- Sources/Sentry/include/HybridPublic/SentryDependencyContainer.h
- Sources/Sentry/include/SentryDefaultObjCRuntimeWrapper.h
- Sources/Sentry/include/SentryDependencyContainerSwiftHelper.h
- Tests/SentryTests/Helper/SentryTestObjCRuntimeWrapper.m
- Tests/SentryTests/Integrations/Performance/UIViewController/SentryUIViewControllerSwizzlingTests.swift
Implementing this change here so I don't add more files changed in #5298
> ref: Remove `SentryDefaultObjCRuntimeWrapper` singleton pattern and use `SentryDependencyContainer`

- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Remove infinity response delay for the HTTPTransportTest, so we avoid having one item on the dispatch queue that would run forever. Instead, we can use the waitForResponseDispatchGroup.
> test: Remove infinity response delay

- Sources/Sentry/Public/SentryDsn.h
- Sources/Sentry/SentryDataCategoryMapper.m
- Sources/Sentry/SentryDebugImageProvider.m
- Sources/Sentry/SentryDsn.m
- sdk_api_V9.json
Fix typo in V9 check. At the time this code was added we didn't have the API stability check so this was missed, now that we have the check we can confirm the API is removed because the sdk_api_v9.json file updated
> Fix v9 typo

- Tests/SentryTests/SentryViewHierarchyProviderTests.swift
This one just flaked on me here: https://github.com/getsentry/sentry-cocoa/actions/runs/16498789244/job/46651405693?pr=5710
> ci: Fix flaky test timeout

- CHANGELOG.md
- Samples/SentrySampleShared/SentrySampleShared/SentrySDKOverrides.swift
- Samples/SentrySampleShared/SentrySampleShared/SentrySDKWrapper.swift
- Samples/Shared/feature-flags.yml
- Sources/Sentry/SentryClient.m
- Tests/SentryTests/Integrations/Feedback/SentryFeedbackTests.swift
Fixes https://github.com/getsentry/sentry-cocoa/issues/5159#issuecomment-3070392706
Added unit tests that failed before the fix and passed afterwards. Also added a new SDK override for configuring the events sample rate (and reorganized that and the preexisting override to reject events in `beforeSend` under a new `Events` override enum), and set that as a tag on the scope, and verified that with both overrides configured to reproduce the setup, the user feedback was still received: https://sentry-sdks.sentry.io/issues/feedback/?feedbackSlug=sentry-cocoa%3A6765771740&mailbox=unresolved&project=5428557&referrer=feedback_list_page&statsPeriod=1h
> fix: user feedback events should not be sampled or subject to `beforeSend`

- TestSamples/SwiftUICrashTest/test-crash-and-relaunch.sh
Increase the timeout to 20 seconds to check if the app has crashed and if it's still running. Also add more log messages.
Fixes GH-5705
> ci: SwiftUI Crash Test Increase Timeouts

- Samples/SentrySampleShared/SentrySampleShared/SentrySDKWrapper.swift
- Samples/iOS-Swift/iOS-Swift-UITests/BaseUITest.swift
- Samples/iOS-Swift/iOS-Swift-UITests/ProfilingUITests.swift
- Samples/iOS-Swift/iOS-Swift-UITests/UserFeedbackUITests.swift
- Samples/iOS-Swift/iOS-Swift/AppDelegate.swift
- Samples/macOS-Swift/macOS-Swift-UITests/MacOSSwiftUITests.swift
I don't expect any flakiness being fixed with this change but will ensure we don't use strings.
> ref: Replace hardcoded launch arguments with enums to avoid typos or values changed

- Tests/SentryTests/SentryCrash/SentryStacktraceBuilderTests.swift
The shorter timeout was still sometimes to short, to simplify let's just use one timeout. 
I saw the timeout error here: https://github.com/getsentry/sentry-cocoa/actions/runs/16528521520/job/46747914086
> ci: Increase test timeout

- SentryTestUtils/SentryFileManager+Test.h
- Sources/Sentry/Public/SentryDefines.h
- Sources/Sentry/SentryFileManager.m
- Sources/Sentry/SentryNSDataUtils.m
- Tests/SentryProfilerTests/SentryAppStartProfilingConfigurationChangeTests.swift
- Tests/SentryProfilerTests/SentryApplaunchProfilingMalformedConfigFileTests.swift
- Tests/SentryTests/Helper/SentryFileManagerTests.swift
_This PR is derived from #5572 in an effort to make the large amount of changes easier to review for #5577._
**Should be merged after #5736**
Fixes nullability handling in the `SentryFileManager`.
Most notably this PR adds a new macro `SENTRY_UNWRAP_NULLABLE` which is just a convenience macro for force-casting a nullable to non-null pointer. I introduced it, so we can easily find all locations where we force-cast.
> refactor: Add full nullability handling to SentryFileManager

- Sentry.xcodeproj/project.pbxproj
The ExceptionCatcher class had both Sentry and SentryTests as target membership. This is fixed now by removing Sentry.
This came up while looking at the raw test logs of https://github.com/getsentry/sentry-cocoa/actions/runs/16590229020
```
objc[24706]: Class ExceptionCatcher is implemented in both /Users/runner/Library/Developer/Xcode/DerivedData/Sentry-azcqyxgbmmrdtdegukmbgarszteu/Build/Products/TestCI-iphonesimulator/Sentry.framework/Sentry (0x10a2545d8) and /Users/runner/Library/Developer/Xcode/DerivedData/Sentry-azcqyxgbmmrdtdegukmbgarszteu/Build/Products/TestCI-iphonesimulator/SentryTests.xctest/SentryTests (0x10ce6ed58). One of the two will be used. Which one is undefined.
```
> test: Remove ExceptionCatcher from Sentry target

- Tests/SentryTests/Networking/SentryHttpTransportFlushIntegrationTests.swift
This test was flaky because the event could have been sent before we made the request manager blocking, leading to there not being a timeout. I just moved enabling blocking to before we send the event
> ci: Fix flush timeout test

- Sources/Sentry/Public/SentryDefines.h
- Sources/Sentry/SentryArray.m
- Sources/Sentry/SentryNSDataUtils.m
- Sources/Sentry/SentyOptionsInternal.m
- Sources/Sentry/include/SentryInternalDefines.h
Moves the utility macro introduced in #5737 from the public `SentryDefines.h` to the internal `SentryInternalDefines.h`, as it does not need to be publicly exposed.
> fix: remove internal macro SENTRY_UNWRAP_NULLABLE from public header

- .github/workflows/benchmarking.yml
- .github/workflows/ui-tests-common.yml
- scripts/xcodegen.rb
Github rate limits requests to raw.githubuser urls (see [failed run](https://github.com/getsentry/sentry-cocoa/actions/runs/16602011633/job/46963987765))
We can use a local formula to avoid this
> ci: Use versioned xcodegen file due to github 429 error

- .github/workflows/test.yml
- .github/workflows/ui-tests-common.yml
Adds a more generic flag so we can split the tests by type when looking in codecov
> ci: Add a generic flag for the test type

- Samples/iOS-Cocoapods-Swift6/fastlane/Fastfile
iOS18.2 simulators sometimes crash like here: https://github.com/getsentry/sentry-cocoa/actions/runs/16647631298/job/47112011249
This PR selects iOS18.5 to run the integration test and avoid this issues
> ci: Run Cocoapods integration test on iOS 18.5

- CHANGELOG.md
- Sources/Sentry/SentrySessionReplayIntegration.m
- Tests/SentryTests/Integrations/SessionReplay/SentrySessionReplayIntegrationTests.swift
The global event processor used a strong reference to self which lead to strong reference cycle, meaning that the ARC couldn't dealloc SentrySessionReplayIntegration. This also led to having multiple SentrySessionReplayIntegrations running in the tests after running the SentrySessionReplayIntegrationTests, making the tests flaky. This is fixed now by using a weak reference.
This came up while investigating https://github.com/getsentry/sentry-cocoa/pull/5747.
Unit test. The testSessionReplayIntegration_DoesNotLeakMemory fails without the weak ref.
> fix: Memory leak in SentrySessionReplayIntegration

- TestSamples/SwiftUICrashTest/test-crash-and-relaunch.sh
I've heard this can improve CI stability. It maybe be still setting up the shared cache while we try to screenshot it, leading to the timeout
> ci: Let simulator dyld cache update before running test

- Sources/Sentry/SentryAppStartTracker.m
- Sources/Sentry/SentryAppStateManager.m
- Sources/Sentry/SentryWatchdogTerminationLogic.m
- Sources/Sentry/include/SentryAppStateManager.h
This PR is derived from https://github.com/getsentry/sentry-cocoa/pull/5572 in an effort to make the large amount of changes easier to review for https://github.com/getsentry/sentry-cocoa/issues/5577.
Changes the `SentryAppStartTracker.previousAppState` and `SentryAppStateManager.loadPreviousAppState` to be nullable with correct null handling. 
> refactor: Add null handling for previous app state

- CHANGELOG.md
- Sources/Sentry/PrivateSentrySDKOnly.m
- Sources/Sentry/SentryScope.m
- Sources/Sentry/include/HybridPublic/PrivateSentrySDKOnly.h
- Sources/Sentry/include/SentryScopeObserver.h
This PR is derived from https://github.com/getsentry/sentry-cocoa/pull/5572 in an effort to make the large amount of changes easier to review for https://github.com/getsentry/sentry-cocoa/issues/5577.
Changes the parameter `screenName` to be nullable, as the method implementation allows it.
> refactor: Add nullability property for screenName

- Sources/Sentry/SentryClient.m
_This PR is derived from https://github.com/getsentry/sentry-cocoa/pull/5572 in an effort to make the large amount of changes easier to review for https://github.com/getsentry/sentry-cocoa/issues/5577._
Adds full type-checking of the context value and silencing of the nullability-warning
> fix: Add null-handling and type-checking to modify context in client

- Tests/SentryTests/Networking/SentryHttpTransportTests.swift
Make the test requirements less strict by removing the assert of the blocking duration and adding a test expectation timing out after 10 seconds to prevent hanging CI if the flush blocks longer.
The test failed here https://github.com/getsentry/sentry-cocoa/actions/runs/16743553141/job/47396825598
> test: Fix flaky Flush_BlocksCallingThread_TimesOut

- Sources/Sentry/SentryDependencyContainer.m
- Sources/Sentry/SentrySessionReplayIntegration.m
- Sources/Sentry/include/HybridPublic/SentryDependencyContainer.h
- Tests/SentryTests/Helper/SentryDependencyContainerTests.swift
This property was redundant, and only had one use. Updated it to the new property 
> Remove unnecessary dependency property

- .github/workflows/test.yml
- scripts/sentry-xcodebuild.sh
I noticed that sometimes unit test jobs still report failures even though no tests fail, with the script exiting nonzero. See https://github.com/getsentry/sentry-cocoa/actions/runs/16505144160/job/46673775222
I thought maybe this is actually an error coming from slather. Separate that into its own step so we can isolate potential failures.
> ci: separate slather step

- Sources/Swift/Integrations/SessionReplay/SentryVideoFrameProcessor.swift
Adds `self` in closures to fix older react native compilation issue 
See https://github.com/getsentry/sentry-react-native/pull/5038#issuecomment-3140526038
Fixes errors like the following in RN `0.65.3` that uses more strict compilation rules
```
Error: reference to property 'videoWriter' in closure requires explicit use of 'self' to make capture semantics explicit
SentrySDKLog.debug("[Session Replay] Finished video writing, status: \(videoWriter.status)")
```
This should [unblock 8.54.0 RN bump](https://github.com/getsentry/sentry-react-native/pull/5036) along with the other  changes in https://github.com/getsentry/sentry-react-native/pull/5038
CI
> fix(react-native): Fixes React Native closure compilation issue

- Sources/Sentry/SentryConcurrentRateLimitsDictionary.m
- Sources/Sentry/SentryDefaultRateLimits.m
- Sources/Sentry/include/SentryConcurrentRateLimitsDictionary.h
_This PR is derived from https://github.com/getsentry/sentry-cocoa/pull/5572 in an effort to make the large amount of changes easier to review for https://github.com/getsentry/sentry-cocoa/issues/5577._
Adds null-handling for rate limits per category.
> fix: Add null-handling for default rate limits

- Sources/Sentry/Public/SentryReplayApi.h
Added documentation to `SentryReplayApi.h` for `showMaskPreview`, `showMaskPreview:(CGFloat)opacity`, and `hideMaskPreview` methods. The documentation now explicitly states that these methods must be called from the main thread.
This change addresses an intermittent crash and masking issue reported by a user who was calling `showMaskPreview` from a background thread. Interacting with the UI hierarchy, which these methods do, must occur on the main thread. Adding this note clarifies the usage requirement and helps prevent similar threading-related issues.
Verified the documentation was correctly added to the header file by inspecting the changes.
> Document main thread requirement for replay methods

- Tests/SentryTests/SentryCrash/SentryThreadInspectorTests.swift
Change the assertion approach of
testGetCurrentThreadsWithStacktrace_WithSymbolication and testGetCurrentThreadsWithStacktrace_WithoutSymbolication to validate the percentage of threads having a stracktrace, which is more robust than the previous method which failed if more than one thread had no stacktrace frames. Especially during the test when launching multiple threads for the concurrent DispatchQueue it can occur that more than one thread have no stacktrace frames yet, because they just started.
The tests failed here https://github.com/getsentry/sentry-cocoa/actions/runs/16760984375/job/47456025143
> test: Fix flaky SentryThreadInspectorTests

- Sources/Sentry/SentryMetricKitIntegration.m
_This PR is derived from https://github.com/getsentry/sentry-cocoa/pull/5572 in an effort to make the large amount of changes easier to review for https://github.com/getsentry/sentry-cocoa/issues/5577._
Adds explicit null-handling for debug metadata. This is necessary so we do not use `nil` as a key. While this most likely will not cause issues in Objective-C, we should see it as a best practice instead.
> fix: Add null-handling for debug meta

- Tests/SentryTests/SentryCrash/SentryBinaryImageCacheTests.m
Replace the dispatch group with a XCTestExpectation to get a failure message when the wait times out.
This contributes to GH-5789  and should fix the flaky test `testRemoveImageAddAgain` because 
from the test log it seems like a bg thread adds an image while the `testRemoveImageAddAgain` 
runs. I couldn't reproduce the flaky test locally. We can reopen GH-5789 if it doesn't.
Fixes GH-5825
> test: Use XCTestExpectation in BinaryImageCache

- TestSamples/SwiftUICrashTest/test-crash-and-relaunch.sh
Some jobs fail to capture screenshots ([example](https://github.com/getsentry/sentry-cocoa/actions/runs/16675184003/job/47200028195))
Taking a screenshot should help here
> ci: Add full screen capture in addition to simulator as backup

- Tests/SentryTests/Integrations/Performance/IO/DataSentryTracingIntegrationTests.swift
- Tests/SentryTests/Integrations/Performance/IO/FileManagerTracingIntegrationTests.swift
The web request to the .gitignore file on GitHub sometimes failed in CI. We can test the same approach with a data URL to avoid flakiness.
The test `testInitContentsOfWithSentryTracing_nonFileUrl_shouldNotTraceManually` using `nonFileUrl` failed here https://github.com/getsentry/sentry-cocoa/actions/runs/16823204267/job/47654500560
```
swift:226: error: -[SentryTests.DataSentryTracingIntegrationTests testInitContentsOfWithSentryTracing_nonFileUrl_shouldNotTraceManually] : failed: caught error: "Error Domain=NSCocoaErrorDomain Code=256 "The file “.gitignore” couldn’t be opened." UserInfo={NSURL=https://raw.githubusercontent.com/getsentry/sentry-cocoa/refs/heads/main/.gitignore}"
```
I double checked the URL and it works fine. Maybe our CI hits some rate limiting or something similar. …
> test: Fix flaky non file url for data tracing

- Tests/SentryTests/Protocol/SentryUserTests.swift
Replace the dispatch group with an XCTestExpectation to get a failure message when the wait times out.
Contributes to GH-5789
> test: Use XCTestExpectation for User

- Tests/SentryTests/TestUtils/TestConncurrentModifications.swift
Replace the dispatch group with an XCTestExpectation to get a failure message when the wait times out. To make this work, this PR changes the method to an extension so it can call XCTestCase.wait. Furthermore, this PR reduces the timeout from 500s to 10s, because 500s is way too high and risks slowing down CI.
Contributes to GH-5789
> test: Use XCTestExpectation for concurrent modifications

- scripts/ci-boot-simulator.sh
After reviewing screenshots on https://github.com/getsentry/sentry-cocoa/actions/runs/16805606320/job/47597097673, I see that the simulator is launched in background.
Having it in the foreground will help the screenshots to capture relevant data.
> ci: Open Simulator GUI on CI

- .github/workflows/integration-test.yml
- Plans/iOS-Cocoapods-Swift6_Base.xctestplan
Disable test parallelization for Cocoapods Integration test since there is a single test to be ran and doing so will avoid using clone of simulators: 
```
[09:04:10]: ▸ Testing started
[09:07:37]: ▸ Test Suite UITestsLaunchTests started on 'Clone 1 of iPhone 16 - UITests-Runner (5805)'
```
> ci: Disable tests parallelization for cocoapods integration test

- CHANGELOG.md
Do a couple of wording fixes for the last changelog entry.
I did these fixes mostly to see which CI jobs will run if we're only touching the changelog to see if making unit tests required checks will block this PR.
> chore: Minor wording fixes for CHANGELOG.md

- Sources/Sentry/Public/SentryScope.h
This function wasn't doing anything because there was already an `@property ... span` defined above. Confirmed that it wasn't doing anything because the API stability check didn't trigger any changes by removing it
> fix: Remove unnecessary function

- .codecov.yml
We have some variance on what code is executed on our tests.
Because of this, the lines covered may change a little bit, with some builds changing by 0.017%.
I believe this is within as margin of error and can be safely ingored
> ci: Allow up to 0.05% decrease in coverage before marking the build as failed

- Tests/SentryTests/SentrySDKTests.swift
Add a regression test for GH-5334 by checking that captured non fatal events have debug meta attached.
Fixes GH-5575
> test: Non fatal events have debug meta

- .codecov.yml
Fixes yaml using `yes` instead of `true`
> ci: Fixes codecov config

- .codecov.yml
Apparently I misunderstood codecov docs and applied the `threshold` on the root of the settings in #5859
> ci: Update Codecov configuration to set coverage thresholds for project and patch

- .github/file-filters.yml
- .github/workflows/test.yml
- Tests/SentryTests/SentrySDKTests.swift
Use dorny path filters to have one single job failing or succeeding when the unit tests passed or were skipped so we can enable unit tests as required checks for PRs.
Fixes GH-5868
PR with only a Changelog entry let's the job unit test pass https://github.com/getsentry/sentry-cocoa/pull/5891.
When cancelling unit tests jobs fail
https://github.com/getsentry/sentry-cocoa/actions/runs/16907162839/job/47899511411
When a few unit tests fail also the main unit test job fails
> ci: Add unit tests required check

- Tests/SentryTests/TestUtils/Async.swift
- Tests/SentryTests/TestUtils/TestExtensions.swift
Ideally, we would remove the method delayNonBlocking, but that requires a few changes to a handful of tests. Instead, we remove the dispatch group wait call, which could hang tests forever in CI. Now tests using delayNonBlocking will fail with an assert instead.
I had to define the method as an extension to XCTestCase to use `XCTestCase.wait`.
Contributes to #5789
> test: Use XCTestExpectation for delay non blocking

- Sources/Sentry/Profiling/SentryProfiledTracerConcurrency.mm
- Sources/Sentry/SentryProfiler.mm
This PR is derived from https://github.com/getsentry/sentry-cocoa/pull/5572 in an effort to make the large amount of changes easier to review for https://github.com/getsentry/sentry-cocoa/issues/5577.
Resolves warnings in SentryProfiledTracerConcurrency.mm and SentryProfiler.mm
> refactor: Add null-handling to profiler

- Tests/SentryTests/Networking/SentryHttpTransportFlushIntegrationTests.swift
Replace DispatchGroup with XCTextExpectation in
SentryHttpTransportFlushIntegrationTests.
Contributes to https://github.com/getsentry/sentry-cocoa/issues/5789
> test: Use XCTestExpectation for FlushTests

- Tests/SentryTests/Transaction/SentryTracerTests.swift
Replace DispatchGroup with XCTextExpectation in SentryTracerTests.
Contributes to https://github.com/getsentry/sentry-cocoa/issues/5789
> test: Use XCTestExpectation for SentryTracer

- Tests/SentryTests/Integrations/ANR/SentryANRTrackerV1Tests.swift
A waitTimeout of 2 seconds is usually not enough. Let's increase it to 5 seconds.
Failed here on main https://github.com/getsentry/sentry-cocoa/actions/runs/16913124095/job/47921390079
> test: Increase timeout to 5 seconds for ANRV1

- CHANGELOG.md
- Sources/Swift/Integrations/UserFeedback/SentryFeedback.swift
Fixes a build error on RN SDK with Xcode 14.2: https://github.com/getsentry/sentry-react-native/actions/runs/16932149646/job/47988490015?pr=5038
Old swift version might have not liked the `@spi` inside the a precompiler flag block
Seems to only happen when building from source or with CocoaPods
> fix: Build error on Xcode 14.2

- .github/workflows/build.yml
- .github/workflows/test.yml
Releases are blocked because tests fails when iOS18.6 is not found.
> ci: Use iOS18.5 since 18.6 seems to be unavailable sometimes

- CHANGELOG-v9.md
- Sources/Sentry/Public/SentryScope.h
- Sources/Sentry/include/SentryScope+Private.h
- sdk_api_V9.json
I suggest we make this readonly in V9. I don't think we want anyone setting it to any new types that conform to the protocol. Also, I want to remove `SentrySerializable` from the public API but this property needs to have the `serialize` function defined. If we want to allow it to be set publicly we will need to keep this function public to make sure anything that it gets set to has a `serialize` function. However, I think we can just make it readonly like this, allowing us to move the `serialize` aspect to a private header.
> feat(V9): Make span read only in v9

- .github/workflows/build.yml
- .github/workflows/test-cross-platform.yml
- .github/workflows/ui-tests-critical.yml
Fixed a couple of CI tests which used an Xcode version that was too old to support the installed simulators
> ci: Fix Xcode version in CI tests

- .github/workflows/release.yml
Previously with download artifact v4 files were downloaded to:
`./Carthage/artifact_id/file.zip`
But with v5 they are stored in
`./Carthage/file.zip`
Fixes #5970
> ci: Remove move file step

- Samples/iOS-Swift/iOS-Swift/Tools/TopViewControllerInspector.swift
Moves the `Top VC Name` button 40px up so it is visible and tappable during UI Tests.
Fixes: #5972
> ci: Fix location of VC inspector being behind another button

- TestSamples/SwiftUICrashTest/SwiftUICrashTest/SwiftUICrashTestApp.swift
Adds a some more context to the code for testing crash on launch which was changed in #5855
> meta: Add comment explaining why the crash was moved to onAppear

- .github/workflows/ui-tests.yml
Bump Xcode used to 16.4 and manually set iPhone 16 and iOS 18.5 device for `ui_tests_ios_swift6`.
Fixes: #5975
> ci: Bump Xcode & set device used for `ui_tests_ios_swift6`

- CHANGELOG.md
- Sources/Swift/Protocol/SentryLogLevel.swift
- Sources/Swift/Tools/SentryLogger.swift
> If debug is set to true in SDK init, calls to the Sentry logger API should also print to the console with the appropriate log level. This will help debugging logging setups.
https://develop.sentry.dev/sdk/telemetry/logs/#other
Closes #5948
Tested with sample app.
> Structured Logging:  Log `SentrySDK.logger` calls to `SentrySDKLog` 

- Tests/SentryTests/SentryClientTests.swift
The code still compiles when removing all of these deprecation warnings.
> test: Remove not required deprecation warnings

- .github/workflows/assemble-xcframework-variant.yml
- scripts/build-xcframework-local.sh
- scripts/validate-xcframework-format.sh
Add a validation step after building the xcframework to double check the XCFramework structure.
macOS requires a very specific versioned format which is prone to breaking.
> chore(ci): Validate XCFramework structure

- Sentry.xcodeproj/project.pbxproj
- SentryTestUtilsTests/TestConstantTests.swift
- Sources/Sentry/SentryClient.m
- Sources/Sentry/SentryEnvelope.m
- Sources/Sentry/SentryTransportAdapter.m
- Sources/Sentry/include/HybridPublic/SentryEnvelope.h
- Sources/Swift/Tools/SentryEnvelopeHeader.swift
- Tests/SentryTests/Helper/SentrySerializationTests.swift
- Tests/SentryTests/Protocol/SentryEnvelopeTests.swift
- Tests/SentryTests/SentryHubTests.swift
Converts `SentryEnvelopeHeader` to Swift
> ref: SentryEnvelopeHeader to swift

- CHANGELOG.md
We merged #5800 after releasing 8.55.0. We need to move it up to the unreleased section.
> Fix Changelog: Move PR 5800 to unreleased

- .github/workflows/test.yml
Follow up on https://github.com/getsentry/sentry-cocoa/issues/6061
Closes #6176
> ci: Explain why no unit tests on macCatalyst 26

- Tests/SentryTests/SentrySDKInternalTests.swift
Ensure the anrTrackingIntegration isn't nil and add a more descriptive test failure message.
#skip-changelog 
Closes #6185
> test: Improve testResumeAndPauseAppHangTracking

- Gemfile.lock
Original PR https://github.com/getsentry/sentry-cocoa/pull/6189. Reopend it myself so we have the permissions to run the required checks.
Bumps [rexml](https://github.com/ruby/rexml) from 3.4.1 to 3.4.2.
- [Release notes](https://github.com/ruby/rexml/releases)
- [Changelog](https://github.com/ruby/rexml/blob/master/NEWS.md)
- [Commits](https://github.com/ruby/rexml/compare/v3.4.1...v3.4.2)
---
updated-dependencies:
- dependency-name: rexml dependency-version: 3.4.2 dependency-type: indirect ...
Closes #6195
> chore(deps): bump rexml from 3.4.1 to 3.4.2

- Sources/Sentry/Profiling/SentryContinuousProfiler.mm
- Sources/Sentry/Profiling/SentryProfiledTracerConcurrency.mm
- Sources/Sentry/Profiling/SentryProfilerSerialization.m
- Sources/Sentry/Profiling/SentryProfilerState.mm
- Sources/Sentry/Profiling/SentryProfilingSwiftHelpers.m
- Sources/Sentry/Profiling/SentryTraceProfiler.mm
- Sources/Sentry/SentryDevice.m
- Sources/Sentry/include/SentryDevice.h
- Sources/Sentry/include/SentryProfilingSwiftHelpers.h
- Tests/SentryProfilerTests/SentryContinuousProfilerTests.swift
- Tests/SentryProfilerTests/SentryProfilerTests.mm
- Tests/SentryProfilerTests/SentryProfilingSwiftHelpersTests.m
- Tests/SentryTests/SentryContinuousProfiler+Test.h
- Updated device model functions to return nullable types for better safety.
- Improved error handling in continuous profiler to log when no profiler is running.
- Added nullability checks in various profiling-related functions to prevent potential crashes.
- Enhanced tests to cover scenarios where profiling options or parent span IDs are nil.
Closes #6201
Closes #6202 
Closes #6203 
Closes #6204 
Closes #6205 
- Unit tests
> ref: Enhance nullability handling in profiling

- Sources/Sentry/SentryBaseIntegration.m
Watchdog tracking requires the hang tracker, and on V9 the hang tracker requires frame tracking. If you disable hang tracking on V9 but have watchdog tracking enabled, we need to make sure the frame tracker still runs
Closes #6227
Closes #6228
Closes #6229
> fix: Fix watchdog tracking on V9

- .github/workflows/benchmarking.yml
- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/integration-test.yml
- .github/workflows/lint-clang-formatting.yml
- .github/workflows/lint-cocoapods-specs.yml
- .github/workflows/lint-dprint-formatting.yml
- .github/workflows/lint-shellcheck-formatting.yml
- .github/workflows/lint-swift-formatting.yml
- .github/workflows/lint-swiftlint-formatting.yml
- .github/workflows/lint-xcode-analyze.yml
- .github/workflows/objc-conversion-analysis.yml
- .github/workflows/release.yml
- .github/workflows/test-cross-platform.yml
- .github/workflows/test.yml
- .github/workflows/testflight.yml
- .github/workflows/ui-tests-critical.yml
- .github/workflows/ui-tests.yml
- .github/workflows/version-bump-util.yml
> ci: Add v8.x branch to workflows

- .github/workflows/test.yml
The test server tests on iOS are very flaky. Let's only run these on macOS, as they didn't fail there in the last two weeks.
Perhaps that's because the simulator has difficulty communicating with a running test server in CI.
Closes #6351
> ci: Only run test server on macOS

- Sources/Sentry/Public/SentryThread.h
- Sources/Sentry/SentryBreadcrumb.m
- Sources/Sentry/SentryGeo.m
- Sources/Sentry/SentryThread.mm
- Sources/Swift/Protocol/Codable/SentryBreadcrumbCodable.swift
- Sources/Swift/Protocol/Codable/SentryEventCodable.swift
- Sources/Swift/Protocol/Codable/SentryExceptionCodable.swift
- Sources/Swift/Protocol/Codable/SentryFrameCodable.swift
- Sources/Swift/Protocol/Codable/SentryGeoCodable.swift
- Sources/Swift/Protocol/Codable/SentryMechanismCodable.swift
- Sources/Swift/Protocol/Codable/SentryMechanismMetaCodable.swift
- Sources/Swift/Protocol/Codable/SentryMessage.swift
- Sources/Swift/Protocol/Codable/SentryNSErrorCodable.swift
- Sources/Swift/Protocol/Codable/SentryRequestCodable.swift
- Sources/Swift/Protocol/Codable/SentryStacktraceCodable.swift
- Sources/Swift/Protocol/Codable/SentryThreadCodable.swift
- Tests/SentryTests/Protocol/Codable/SentryCodableTests.swift
- Tests/SentryTests/Protocol/SentryBreadcrumbTests.swift
- Tests/SentryTests/Protocol/SentryDebugMetaTests.swift
- Tests/SentryTests/Protocol/SentryExceptionTests.swift
- Tests/SentryTests/Protocol/SentryFrameTests.swift
- Tests/SentryTests/Protocol/SentryGeoTests.swift
- Tests/SentryTests/Protocol/SentryMechanismMetaTests.swift
- Tests/SentryTests/Protocol/SentryMechanismTests.swift
- Tests/SentryTests/Protocol/SentryMessageTests.swift
- Tests/SentryTests/Protocol/SentryNSErrorTests.swift
- Tests/SentryTests/Protocol/SentryRequestTests.swift
- Tests/SentryTests/Protocol/SentryStacktraceTests.swift
- Tests/SentryTests/Protocol/SentryThreadTests.swift
Removing the SDK_V9 checks here. This is already in the changelog from my previous PR
Closes #6364
> chore: Remove more codable v9 checks

- CHANGELOG.md
- Sources/SentrySwiftUI/Preview/PreviewRedactOptions.swift
- Sources/Swift/Core/Integrations/Performance/SentryProfileOptions.swift
- Sources/Swift/Core/Tools/ViewCapture/SentryRedactViewHelper.swift
- Sources/Swift/Integrations/Screenshot/SentryScreenshotOptions.swift
- Sources/Swift/Integrations/SessionReplay/SentryReplayOptions.swift
- Sources/Swift/Integrations/UserFeedback/Configuration/SentryUserFeedbackConfiguration.swift
- Sources/Swift/Integrations/UserFeedback/Configuration/SentryUserFeedbackFormConfiguration.swift
- Sources/Swift/Integrations/UserFeedback/Configuration/SentryUserFeedbackThemeConfiguration.swift
- Sources/Swift/Integrations/UserFeedback/Configuration/SentryUserFeedbackWidgetConfiguration.swift
- Sources/Swift/Integrations/UserFeedback/SentryFeedback.swift
- Sources/Swift/Protocol/Codable/SentryEventDecoder.swift
- Sources/Swift/SentryExperimentalOptions.swift
- sdk_api.json
Some v9 changes to add `final` and one case where `spi` was missing.
Closes #6366
> ref: Use final when possible
